### ISSUE TITLE
Neither onlyCompileBundledFiles or webpack config externals property work for declarations 

### ISSUE THREAD

**Issue by paulsouche** [TypeStrong/ts-loader#1002]
Hello !

### Expected Behaviour
My yarn workspace monorepo has the following structure

```
+-- packages
|   +-- lib-a
|      +-- index.ts
|   +-- lib-b
|      +-- index.ts
```

`lib-a` depends on `lib-b`.

Everything works fine when I transpile `lib-b` using `tsc`

```
+-- lib-b
|   +-- build
|      +-- index.d.ts
|      +-- index.js
|   +-- index.ts
```

But, as I use the `paths` property in my `compilerOptions` for `lib-a`

```json
{
  "compilerOptions": {
    "baseUrl": "",
    "paths": {
      "lib-b": [
        "../lib-b"
      ]
    }
  }
}
```

If I use `tsc`, it outputs the following structure

```
+-- lib-a
|   +-- build
|      +-- lib-a
|         +-- index.d.ts
|         +-- index.js
|      +-- lib-b
|         +-- index.d.ts
|         +-- index.js
|   +-- index.ts
```

This is totally normal and working as expected because I link the source of `lib-b` to transpile `lib-a`. There is no way to exclude `lib-b` of transpilation as the `tsconfig` `exclude` property has no effect on `paths`

However if I use the following webpack config

```js
module.exports = {
  externals: ['lib-b'],
  module: {
    rules: [
      { test: /\.ts$/, use: [{ loader: 'ts-loader' }] },
    ],
  },
  output: {
    filename: 'index.js',
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, 'build'),
  },
  resolve: {
    extensions: ['.js', '.ts'],
  },
};
```

I expected the following structure for `lib-a`

```
+-- lib-a
|   +-- build
|      +-- index.d.ts # lib-a declarations
|      +-- index.js # not including lib-b source
|   +-- index.ts
```

### Actual Behaviour

What I get is this structure

```
+-- lib-a
|   +-- build
|      +-- lib-a
|         +-- index.d.ts
|      +-- lib-b
|         +-- index.d.ts
|      +-- index.js # not including lib-b source
|   +-- index.ts
```

So I tried `onlyCompileBundledFiles` to exclude `lib-b` declarations (and lot of other workarounds actually :-))

I already saw #897 and I had a look at `ttypescript` but this wasn't really helpful as I don't want to dynamically change the paths at transpilation. There is also a lot of issues on TypeScript on unwanted (not excluded) transpiled source code that are closed because working as expected and I think this is fully legit as I explain before and this is a loader work to emit only `lib-a` code in my case. But now I'm wondering if there is a solution for my declarations :-).

I know I should build `lib-b` then `lib-a` sequentially but in this case, we loose all the interest of the monorepo and parallel builds. I can for sure have a look if I find a simple solution and open a PR but I wanted your opinion first and see if someone has a workaround.

Thanks anyway for the great job

### Steps to Reproduce the Problem

Clone [this repository](https://github.com/paulsouche/typescript-paths) install deps and build `lib-a`

**Comment by paulsouche** [comment]
@johnnyreilly sorry to ping you directly but I will be grateful to have an opinion on this before the bot closes it.

I can understand that it might work as expected but I can dig deeper into the issue if you are interested. 

Thank you

**Comment by johnnyreilly** [comment]
Hi @paulsouche 

I'm sorry but I don't have time to look into this in depth. On the face of it, it looks like your use case is a prime candidate for trying out project references support which ts-loader has. If might be worth a go? cc @andrewbranch

**Comment by paulsouche** [comment]
Thank you really much ! I will have a closer look on a possible solution and maybe open a PR on the problem then.
