### ISSUE TITLE
no errors TypeScript errors reported for .js when enabling checks using // @ts-check 

### ISSUE THREAD

**Issue by reinholdk** [TypeStrong/ts-loader#1004]
### Expected Behaviour
TypeScript errors shall be reported for .js files, if `"checkJS": false` in tsconfig.json but enabled for a few files selectively using `// @ts-check` .

### Actual Behaviour
no TypeScript errors are reported for such .js files

### Steps to Reproduce the Problem
Build the repo linked below, the error in [test.js](https://github.com/reinholdk/ts-loader-sample/blob/416b140e4b7f76c54c59a3174706e0820d0000f0/src/test.js#L4) is not reported.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/reinholdk/ts-loader-sample

**Comment by johnnyreilly** [comment]
I suspect this isn't ts-loader related and rather TypeScript compiler related. I don't have time to dig into this right now but I have a feeling this will be the case...

**Comment by reinholdk** [comment]
@johnnyreilly isn't the problem caused by this condition?
https://github.com/TypeStrong/ts-loader/blob/bfa48c75adc424a33bbc1f0ec3eeddb8ea1c2722/src/after-compile.ts#L186

**Comment by johnnyreilly** [comment]
You may be correct. Do you want to try it out and see if that's the case?

If it is then I'm wondering what a fix looks like. Always including js / jsx files is a possibility. I wonder if that would create any problems

**Comment by reinholdk** [comment]
Have tried the following change successfully `compilerOptions.allowJs === true` which seems to me the correct condition to include js/jsx files.

**Comment by johnnyreilly** [comment]
Want to submit a PR?
