### ISSUE TITLE
Replace usage of tsconfig-paths-webpack-plugin with your native option

### ISSUE THREAD

**Issue by akopchinskiy** [TypeStrong/ts-loader#1006]
`tsconfig-paths-webpack-plugin` contains several bugs that haven't resolved yet, and it's latest update was Sep 29, 2018.
Please do your own option for setting `tsconfig.json`, I believe it's not so hard to implement.

**Comment by johnnyreilly** [comment]
I'm afraid I'm quite busy - it might be worth you submitting a PR to that repo and seeing if you can help out.

This is open source, if people don't contribute, projects wither. Be part of the solution.
