### ISSUE TITLE
ts-loader transpiles excluded .test.ts files

### ISSUE THREAD

**Issue by pepibumur** [TypeStrong/ts-loader#1007]
### Expected Behaviour
I'm using ts-loader with Webpacker on a Rails web app that fails to deploy with Heroku with the following error:

```
remote:        ERROR in /tmp/build_ea19e160c5caf48db975cf2e4a6ce38c/frontend/components/pages/home.test.ts
remote:        ./frontend/components/pages/home.test.ts
remote:        [tsl] ERROR in /tmp/build_ea19e160c5caf48db975cf2e4a6ce38c/frontend/components/pages/home.test.ts(3,5)
remote:              TS2304: Cannot find name 'expect'.
```

The reason why it can't find those definitions is that they are defined in `devDependencies`, which are not installed when deploying the app because `NODE_ENV` is set to `production`.

The thing is that ts-loader shouldn't transpile those files because I have them excluded in my `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "frontend/*"]
    },
    "sourceMap": true,
    "target": "es6"
  },
  "compileOnSave": false,
  "exclude": ["**/*.test.ts", "node_modules", "vendor", "public"]
}
```
Which makes me think that the configuration is overridden somewhere.

### Actual Behaviour

Deployment fails.

### Steps to Reproduce the Problem

1. Clone [this repository](https://github.com/tuist/tuist)
2. Checkout the commit with sha `16a7b59dec992514adaf497777e6879eeff273c7`
3. Choose the galaxy directory `cd galaxy`.
4. Install Yarn dependencies with `NODE_ENV=production yarn install`
5. Install Bundler dependencies with `bundle install`
6. Bundle the resources with Webpacker: `RAILS_ENV=production bin/webpacker`.

### Location of a Minimal Repository that Demonstrates the Issue.
Just created [this repository](https://github.com/pepibumur/tsloader-rails) but can't reproduce it there. I can't spot what's different.

**Comment by johnnyreilly** [comment]
By the sounds of it, this is going to be a configuration issue of some kind; I'm afraid that I can't look further into it but I wish you the best of luck ♥️

**Comment by pepibumur** [comment]
> By the sounds of it, this is going to be a configuration issue of some kind; I'm afraid that I can't look further into it but I wish you the best of luck ♥️

No worries. Could you point me to some place where I can start debugging from? One of the differences between the example project that I created and the one that fails is that the app in case of the one failing is not in the roof of the repository.

**Comment by pepibumur** [comment]
Found the issue. It turns out the Webpacker added by webpacker was requiring all the files in the `components` directory, and that included the test files.
Closing the issue :)
