### ISSUE TITLE
module esnext + target es3 output incompatible code

### ISSUE THREAD

**Issue by zenxds** [TypeStrong/ts-loader#1009]
### Expected Behaviour

output code without `Object.defineProperty(__webpack_exports__, "__esModule", { value: true });`

### Actual Behaviour

main and chunk files have `Object.defineProperty(__webpack_exports__, "__esModule", { value: true });` code

### Steps to Reproduce the Problem

* webpack version: 3.x
* ts-loader version: 3.x
* typescript version: 3.x
* compilerOptions.module: "esnext"
* compilerOptions.target: "es3"
* dynamic import chunk

then build the repo

chunk file

```
webpackJsonp(["chunk-file"],[
/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony default export */ __webpack_exports__["default"] = ({
    type: 'basic'
});


/***/ })
]);
```

main file also have the `Object.defineProperty` code

**Comment by zenxds** [comment]
open issue to TypeScript

**Comment by zenxds** [comment]
every thing is ok without dynamic import。

once I add dynamic import chunk code，output code will be incompatible

**Comment by johnnyreilly** [comment]
I'm afraid ts-loader 3.0 is no longer supported. Also, I suspect this may be an issue with TypeScript rather than ts-loader
