### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'getProgram' of null

### ISSUE THREAD

**Issue by Tiramisupxl** [TypeStrong/ts-loader#1022]
my webpack's version is 4.41.0 and ts-loader's version is 6.2.0.It showed the error in my vue peoject.what i should do to deal with the probrem?

Module build failed: TypeError: Cannot read property 'getProgram' of null
    at Object.getEmitOutput (/Users/pxl/Documents/mics-ui/node_modules/ts-loader/dist/instances.js:369:41)
    at getEmit (/Users/pxl/Documents/mics-ui/node_modules/ts-loader/dist/index.js:275:37)
    at successLoader (/Users/pxl/Documents/mics-ui/node_modules/ts-loader/dist/index.js:67:15)
    at Object.loader (/Users/pxl/Documents/mics-ui/node_modules/ts-loader/dist/index.js:22:12)

 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./doc/main.ts

**Comment by marclundgren** [comment]
@ Tiramisupxl Did you end up fixing this problem?

**Comment by ashwinifly** [comment]
I am facing the same issue. Anyone knows how to fix this?

**Comment by AdamSalma** [comment]
I had this error when using ts-loader with HappyPack (this might also apply if you're using `thread-loader`)

What i did was removed ts-loader from HappyPack but kept it for everything else (e.g. babel)

```
// webpack config

new HappyPack({
    id: 'babel',
    verbose: false,
    loaders: [
      { loader: 'babel-loader' },
      { loader: 'imports-loader?define=>window.define' }
    ]
}),

... 

module: {
  rules: [
  {
    test: /\.tsx?$/,
    use: ['happypack/loader?id=babel', {
      loader: 'ts-loader',
      options: {
        configFile: require.resolve('../tsconfig.json'),
        allowTsInNodeModules: true,
      }
    }],
  },
}
```
