### ISSUE TITLE
TS-loader ignores webpack Rule.exclude

### ISSUE THREAD

**Issue by Sprit3Dan** [TypeStrong/ts-loader#1023]
### Expected Behaviour
TS-loader processes only modules passed in via webpack. Explicitly excluded files in webpack Rule.exclude do not participate in the build process and are not included at any step of build process.

### Actual Behaviour
Typescript is run against all files included in .tsconfig  during the `afterCompile` hook phase.

### Steps to Reproduce the Problem
Please, refer the Repo linked down below. After checkout, run `npm i && npm start` to retrieve the dependencies and run the webpack build process.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/Sprit3Dan/ts-loader-issue

------
This issue may feel a bit contradictory, and I've also been struggling whether I should be filing it or not, but according to webpack's described guidelines [writing-a-loader docs](https://webpack.js.org/contribute/writing-a-loader),
> Loaders should do only a single task

while running a TS against all files included in .tsconfig is clearly a side-affect, which violates this rule.

I have seen some issues rising on stackoverflow with the problem, which is pretty much the same. [[1]](https://stackoverflow.com/questions/41699244/webpack-2-ts-loader-doesnt-exclude-spec-file) [[2]](https://github.com/TypeStrong/ts-loader/issues/544). Also, I have heard several complaints from my colleagues regarding pretty much the same problem.

Also, please refer the log posted down below, where it's crystal clear that `index.ts` module is build & webpack was successful, but the after-compile hook failed

```
╭─dan@dans-arch ~/projects/ts-loader-issue ‹master*› 
╰─$ npm start

> ts-loader-issue@1.0.0 start /home/dan/projects/ts-loader-issue
> webpack --config webpack.config.js

/home/dan/projects/ts-loader-issue/src/index.ts Module excluded: false
ts-loader: Using typescript@3.6.3 and /home/dan/projects/ts-loader-issue/tsconfig.json
Hash: 1d9036f7a5fc2a959aa7
Version: webpack 4.41.0
Time: 569ms
Built at: 10/09/2019 1:35:32 PM
  Asset      Size  Chunks             Chunk Names
main.js  3.93 KiB    main  [emitted]  main
Entrypoint main = main.js
[./src/index.ts] 157 bytes {main} [built]

ERROR in /home/dan/projects/ts-loader-issue/src/other-module.ts
[tsl] ERROR in /home/dan/projects/ts-loader-issue/src/other-module.ts(7,21)
      TS2304: Cannot find name 'NotResolvedType'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ts-loader-issue@1.0.0 start: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ts-loader-issue@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dan/.npm/_logs/2019-10-09T10_35_33_021Z-debug.log
```

**Comment by Sprit3Dan** [comment]
Hello @Bnaya,

Unfortunately excluding `other-module.ts` within tsconfig is not the case, since, for instance, in our case, we have tests under `/src/__tests__` written in TS. If I exclude then in tsconfig, there is no chance typescript would work inside them.

But how comes typescript knows anything beyond modules passed in from webpack using ts-loader. `Program` you mentioned has to be an input from webpack module resolver. Otherwise, It seems to break the whole webpack idea as I mentioned above.

Do you know if there's a chance to let `tsc` build it's AST based on the input from webpack? For the sake of preserving the chain of `source files -> webpack module resolver -> loaders -> bundle`.

**Comment by Bnaya** [comment]
Because the typescript checker scans the file system by it self, to create the `Program`.
This is how TypeScript works.

Sounds like you need a separate tsconfig for tests/build will solve your issue
