### ISSUE TITLE
Custom transformers not working for referenced projects

### ISSUE THREAD

**Issue by adam-stanek** [TypeStrong/ts-loader#1025]
Hi. I am trying to build a mono-repo project consisting from webpack demo application and separately published library. The library is defined as referenced typescript project (`projectReferences: true`).
In order to build the library correctly I need custom transformer ([@zerollup/ts-transform-paths](https://www.npmjs.com/package/@zerollup/ts-transform-paths) to transform paths). It seems to be ignored when building the library.

### Expected Behaviour

Library code gets emitted while being properly transformed.

### Actual Behaviour

Library code gets emitted but no transformation is applied. It is worth mentioning that `@zerollup/ts-transform-paths` run through `ttypescript` is working fine.

### Steps to Reproduce the Problem

*ts-loader options*

```
{
  projectReferences: true,
  getCustomTransformers: require.resolve('./webpack.tsTransformers'),
}
```

*./webpack.tsTransformers.js*

```
const createTsTransformPath = require('@zerollup/ts-transform-paths')

function getCustomTransformers(program) {
  const tsTransformPath = createTsTransformPath(program)

  return {
    before: [tsTransformPath.before],
    // after: [tsTransformPath.afterDeclarations],
  }
}

module.exports = getCustomTransformers
```

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/adam-stanek/chobot/commit/8bf5dd2c69ce0437494d55ac7e9524b0f60c6469

**Comment by unstubbable** [comment]
This is also true for [typescript-plugin-styled-components](https://github.com/Igorbek/typescript-plugin-styled-components), which is mentioned in the REAMDE as an example for `getCustomTransformers `. I'd like this issue to be reopened.
