### ISSUE TITLE
TypeScript 3.7-RC doesn't work

### ISSUE THREAD

**Issue by 777PolarFox777** [TypeStrong/ts-loader#1031]
### Expected Behaviour
Transpiles optional chaining just like tsc do
```js
a?.b?.c // works in tsc, but fails in ts-loader
```
### Actual Behaviour
Getting an error "You may need an additional loader to handle the result of these loaders."
### Steps to Reproduce the Problem
1. Use optional chaining in you project
2. Start webpack

**Comment by johnnyreilly** [comment]
`ts-loader` uses whatever comes out of `tsc` - I'd be surprised if `transpileOnly` isn't supporting optional chaining....

cc @andrewbranch @sheetalkamat

**Comment by andrewbranch** [comment]
What is `target` set to in your tsconfig?

**Comment by 777PolarFox777** [comment]
> What is `target` set to in your tsconfig?

My target is `esnext`, should I change it on somthing different?

**Comment by 777PolarFox777** [comment]
Well, I've changed target to `es2018` and it works just fine! Thank you!

**Comment by inoyakaigor** [comment]
Can anybody explain what the difference between targets: `esnext` and `es2020` if at this moment it's the same?

**Comment by andrewbranch** [comment]
`esnext` is a moving target. In the year 2030, `es2020` will be old hat but `esnext` will always contain the latest and greatest features yet to make it into the ECMAScript spec, like perhaps syntax primitives for quantum computing operations, or my upcoming “incredulous chaining” operator proposal, `what‽.in‽.the‽.world‽.is‽.that`.

In other words, `esnext` is always an alias to the latest spec version, and we continue to move it forward every year.

**Comment by inoyakaigor** [comment]
@andrewbranch ok, just as I suspected. But how this affects to ts-loader? I mean why target `esnext` is causing an error 
![image](https://user-images.githubusercontent.com/1235286/69073875-4c725480-0a3f-11ea-8c46-f90ef33708fb.png)
but target es2020 not because esnext are equivalent of es2020 at current moment?

**Comment by andrewbranch** [comment]
Sorry, I actually misremembered this. `esnext` and `latest` are aliases for each other, but `es2020` is actually already a set value:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3277153/69076273-f9b97e00-09e7-11ea-8d40-8e7dfe50f3b6.png">

**Comment by johnnyreilly** [comment]
I think I've spotted the next Y2K bug in that enum 😉

"We've only got 92 years of TypeScript left!"

**Comment by andrewbranch** [comment]
Well fortunately TypeScript enums support non-integer number values, although I’m definitely going to spend the next 92 years looking forward to when we have to do safe floating point comparisons throughout the compiler whenever we look at target 😉

**Comment by inoyakaigor** [comment]
I think somebody should make an issue in Typescript repo to prevent this bug 😀

So is it possible use ts-loader with `esnext`?

**Comment by andrewbranch** [comment]
ts-loader has no problem with `esnext`. The problem you’re seeing is that Webpack itself can’t statically analyze the output JavaScript because _it_ doesn’t understand `?.` and `??` yet. This is a good thing, because _browsers_ also do not understand `?.` and `??` yet, so Webpack is saving you from shipping unsupported code to your users.

**Comment by inoyakaigor** [comment]
Oh, thank you Andrew!
