### ISSUE TITLE
Attempted import error: 'SomeObject' is not exported from file

### ISSUE THREAD

**Issue by eltonchan** [TypeStrong/ts-loader#1037]
### Expected Behaviour
build success
### Actual Behaviour

build fail 
Attempted import error: 'SomeObject' is not exported from file
### Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/12627010/70298283-1220f980-182c-11ea-83f7-5e818b35abf7.png)
![image](https://user-images.githubusercontent.com/12627010/70298300-2238d900-182c-11ea-947d-a79588c91258.png)
![image](https://user-images.githubusercontent.com/12627010/70298317-31b82200-182c-11ea-8fb9-5bf8816ab4fb.png)
![image](https://user-images.githubusercontent.com/12627010/70298324-3b418a00-182c-11ea-92c9-6cabb83df486.png)

**Comment by eltonchan** [comment]
still have this problem with the latest version ts-loader

**Comment by eltonchan** [comment]
This is not a Compile warning， is compile error, so i can't build, but when i change tsconfig module to common.js it ok

**Comment by benjamingr** [comment]
What did you end up doing @eltonchan
