### ISSUE TITLE
Stray > character results in confusing error reported on incorrect line

### ISSUE THREAD

**Issue by mcclure** [TypeStrong/ts-loader#1039]
### Steps to Reproduce the Problem / Minimal Repository:

[Here is a repo with a minimal Typescript example](https://github.com/mcclure/ts-hello-bug/tree/e6385a7c1b05ea9f8b990d1f19376037e327a050). At commit e6385a7c, if you run `npm install && npx webpack` it will use ts-loader 6.2.1 and TypeScript 3.7.3 (newest versions as of right now) to build a source file [src/index.tsx](https://github.com/mcclure/ts-hello-bug/blob/e6385a7c1b05ea9f8b990d1f19376037e327a050/src/index.tsx). This file contains a couple meaningless class definitions, followed by about ten `console.log` statements, then the following cursed line:

    function UsersBox(props: {list: State<OrderedSet<string>>>, label:string}) {

This is line 25. If you don't see the bug, there is exactly one `>` too many.

### Expected Behavior

I expect `npx webpack` to flag some sort of error on line 25 centered on the final `>` character. If you run `tsc` in the repo instead of webpack, TypeScript by itself prints:

    src/index.tsx(25,58): error TS1005: ';' expected.
    src/index.tsx(25,59): error TS1109: Expression expected.
    src/index.tsx(25,73): error TS1005: ',' expected.

I don't understand why it expects `;` exactly, but the `tsc` output seems totally reasonable to me. I'd say the `tsc` behavior is the expected behavior.

### Actual Behavior

`npx webpack` prints many errors, but the *first* two are:

```
ERROR in ./src/index.tsx 18:1
Module parse failed: Unexpected token (18:1)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| console.log("9");
| console.log("10");
>  > , label;
| string;
| {

ERROR in /Users/mcc/work/h/ts-hello/src/index.tsx
./src/index.tsx
[tsl] ERROR in /Users/mcc/work/h/ts-hello/src/index.tsx(25,58)
      TS1005: ';' expected.
```

The second error is good (it's the same as the one from `tsc`) but the first error is not just confusing but actively misleading. "Unexpected token" is a sensible thing to say, but notice the error implicates not one but **two** unrelated lines:

* The "unexpected token" is listed as being seven lines earlier, on `console.log("6")`
* The highlighted code is four lines earlier, on `console.log("9")`

### Why this is bad

I experienced this bug and got this bizarro error while writing actual code. Like I think most programmers, I focused on the first error and assumed any errors after the first are probably nonsense caused by the parser getting confused at the point of the first reported error. In retrospect, as in the example above, the *second* error flagged the correct line and problem (unexpected character on line 25) but I wasn't looking at it. Instead I wasted quite a while trying to understand what the first error meant. I think I only found the problem by commenting out random lines until I found the one with the true error.

Misbalancing `<>`s is a reasonable and I assume common mistake to make. ts-loader should not print such a misleading error in this case.

### Notes

* The test repo above has two commits containing alternate demonstrations of the bug. The [first](https://github.com/mcclure/ts-hello-bug/tree/45dda8f7cf8cc141bbc8e2cb84e8fc2f996ed288) is more or less exactly the code I originally encountered the bug with. It uses immutable.js and Preact. The [second](https://github.com/mcclure/ts-hello-bug/tree/3aa5a65a6e8983dda0226cc7008522571790325f) is again the same code but with immutable.js and preact removed and their classes mocked out. The only interesting thing about these alternate demonstrations is **the spurious error always appears to be reported roughly the same number of lines before the actual error**, regardless of what comes before it.
* With one exception: Try checking out e6385a7c and commenting out all the `console.log` lines. The error will not be reported on a comment line. **the spurious error only appears to "count back" lines with content when deciding which lines to misreport**.
* This exact same error occurs in awesome-typescript-loader. I don't know what that implies.

**Comment by mcclure** [comment]
I was also able to get this same issue (error reported with the bars and the "You may need an additional loader" and the incorrect line reporting) to occur by placing this code into my tsx:

```
return <div className="ErrorBox">
    <div className="Header">Errors</div>
    <div className="List">{errorFragment}<div>
  </div>
```

Notice the second inner div is closed with `<div>` instead of `</div>`, so this is still an error, but I expect it to report it on the correct line (or in this case reporting the error at EOF would be acceptable). I can provide a full example of this if necessary.

**Comment by johnnyreilly** [comment]
> This exact same error occurs in awesome-typescript-loader. I don't know what that implies

I think this implies that the message you are seeing comes from webpack. Not ts-loader.
