### ISSUE TITLE
Changes in DllReferences do not lead to type checks

### ISSUE THREAD

**Issue by IIIristraM** [TypeStrong/ts-loader#1046]
Let assume we have 2 projects `client` and `common` and following is true:
- `common` project build into Dll with `webpack.DllPlugin`
- `client` project has reference to `common` via both `webpack.DllReferencePlugin` and `reference` section of `tsconfig.json`

### Expected Behaviour

Changes in `common` project trigger rebuild of `client` project and type errors are emitted if any

### Actual Behaviour

Changes in `common` project trigger rebuild of `client` project, but no errors emitted

### Steps to Reproduce the Problem

1) clone repo below
2) `npm run init`
3) `npm start`
4) change [this](https://github.com/IIIristraM/lerna-ts/blob/master/packages/common/src/utils.ts#L1) function signature to something like

```ts
export function square(n: string) {
    return n + n;
}
```

so it no longer compatible with it's usage [here](https://github.com/IIIristraM/lerna-ts/blob/master/packages/client/src/pages/HomePage.tsx#L6) 

5) output in terminal shows that both projects were rebuild, and page refresh shows new results, but no typescript errors occurred

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/IIIristraM/lerna-ts

**Comment by johnnyreilly** [comment]
Do you have the `projectReferences` option set? I had a quick look at your repo but didn't notice it.

cc @andrewbranch

**Comment by IIIristraM** [comment]
https://github.com/IIIristraM/lerna-ts/blob/master/packages/client/tsconfig.json#L5

**Comment by IIIristraM** [comment]
workaround is to remove `.d.ts` files from`watchOptions.ignored`, it leads to double build:
- first is after source file changed, it displays wrong information about type's errors
- second is after new `.d.ts` emitted, id displays correct result for types check
