### ISSUE TITLE
tsLoaderDefinitionFileVersions is changing between builds

### ISSUE THREAD

**Issue by artola** [TypeStrong/ts-loader#1048]
### Expected Behaviour
tsLoaderDefinitionFileVersions should be deterministic and output always the same source.

### Actual Behaviour
tsLoaderDefinitionFileVersions is changing between builds (without any source code change), producing that webpack's hashing to get invalidated.

### Steps to Reproduce the Problem
Please see discussion on webpack issue and findings: https://github.com/webpack/webpack/issues/8419#issuecomment-543712239

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/artola/webpack-bug

Running a few times the same build it will produce different file hashes due changes in `tsLoaderDefinitionFileVersions`.
The repo contains a demo with 2 files (**foo.ts** and **bar.ts**) and what I can see is that they are "sometimes" processed in different order ("foo then bar" most of times, until happens "bar then foo") producing the mentioned problem.

**Comment by johnnyreilly** [comment]
Thanks for taking the time to raise this. I've read and re-read this but I'm afraid I'm not sure what the issue you're encountering is or what `tsLoaderDefinitionFileVersions` is? Could you clarify please?

Also, if you'd like to work on this then please do have a go; I can try and advise as you do perhaps.

**Comment by artola** [comment]
> Thanks for taking the time to raise this. I've read and re-read this but I'm afraid I'm not sure what the issue you're encountering is or what `tsLoaderDefinitionFileVersions` is? Could you clarify please?
> 
> Also, if you'd like to work on this then please do have a go; I can try and advise as you do perhaps.

@johnnyreilly Thanks. I would like also to understand better why this happens, and help to fix it if possible, I would really appreciate some hint, what could be the culprit? any guess?

As I understand `tsLoaderDefinitionFileVersions` is **metadata** and somehow it is changing between builds, what leads to having a different **hash** for the file. (when in webpack we have an output like `filename: '[name].[contenthash].js',` ... I believed that this **contenthash** was calculated from the sourcecode content, but it also is related to the metadata used in the bundling).

https://github.com/TypeStrong/ts-loader/blob/e9ef049cf2368b4b5e1f092789cf729cdc208d2c/src/index.ts#L488

It can be reproduced as this:
 - clone the [repo](https://github.com/artola/webpack-bug)
 - run `yarn`
 - manually change the file `node_modules/webpack/lib/NormalModule.js` by adding these 2 `console.log`

    ```js
			const handleParseResult = result => {
				console.log(this.resource);
				console.log(this.buildMeta);
				this._lastSuccessfulBuildMeta = this.buildMeta;
				this._initBuildHash(compilation);
				return callback();
			};
    ```
 - run the command `yarn build > log1 && yarn build > log2`
 - compare the result of `log1` and `log2` ... often they match, but sometimes they not.

When they do not match, the "hash" created is different, for example:

```
run1:
  Entrypoint trial = trial.main.f509bbd03caa2c35371b.js

run2:  
  Entrypoint trial = trial.main.91c7f7d86f11c81a2577.js
```

**Comment by johnnyreilly** [comment]
Gosh I haven't looked at that code for a long time and I can't remember too much about it!

I'd advise debugging and seeing how the values can change. Is it just ordering? Or is it a different number of entries as well?

Start answering those questions and maybe that will lead to some potential solutions

**Comment by artola** [comment]
@johnnyreilly I found that this is related somehow to the order of the entries, for example having webpack.config.js:

```js
    ...
    // sometimes foo is compiled first, otherwise it is bar and the hash will change
    entry: {
      trial: [path.resolve('src/foo.ts'), path.resolve('src/bar.ts')],
    },

    // changing to use an index file that just re-export the all from the other 2, will not fail
    entry: {
      trial: [path.resolve('src/index.ts')],
    },
```

Also it works fine, if I "force" to have a fresh instance by commenting the `if` in `getTypeScriptInstance`.

https://github.com/TypeStrong/ts-loader/blob/37a07314b0c28b72f85a3076cbb04791606d2272/src/instances.ts#L49

**Comment by johnnyreilly** [comment]
Interesting. Can the `allDefinitionFiles` sort order be enforced (order by name perhaps) to resolve the issue as well?

**Comment by artola** [comment]
> Interesting. Can the `allDefinitionFiles` sort order be enforced (order by name perhaps) to resolve the issue as well?

I tried, it is a bit better but not a full solution, because there is different number of entries when the failure happens also. :(

**Comment by johnnyreilly** [comment]
How about `instances` order?

**Comment by artola** [comment]
> How about `instances` order?

`instances` is just an object that keeps the compiler instances, by default 1 named `0_default`.

https://github.com/TypeStrong/ts-loader/blob/37a07314b0c28b72f85a3076cbb04791606d2272/src/instances.ts#L49

This instance is called and re-used to compile each file, somehow this is affecting the result when the files are compiled in different order (foo/bar or bar/foo).

The problem happens only when using `onlyCompileBundledFiles: true` (with **false** the `tsLoaderDefinitionFileVersions` always output the same content).

webpack.config.js
```
                {
                  loader: 'ts-loader',
                  options: {
                    onlyCompileBundledFiles: true,
                  },
                },
```
