### ISSUE TITLE
Sourcemaps breaks with uglify

### ISSUE THREAD

**Issue by primavera133** [TypeStrong/ts-loader#105]
I set up a simple node/express-application and tried to utilise Typescript and Webpack. Sourcemaps works fine as long as I don't add Uglify to the webpack config.

https://github.com/primavera133/tsLoader_sourcemaps

**Comment by jbrantly** [comment]
Awesome! Thanks for this, I'll take a look.

**Comment by trimeyko** [comment]
Any updates on this ?

**Comment by shaunwarman** [comment]
Seeing this as well here:

https://github.com/webpack/webpack/issues/1689

**Comment by RobertoUa** [comment]
Any updates on this ?

**Comment by johnnyreilly** [comment]
I don't believe so. But I'd generally only expect uglify to be used in production builds; is there a need to use uglify when debugging?

**Comment by RobertoUa** [comment]
is there a need for source maps in production? Yes, there is

**Comment by johnnyreilly** [comment]
That's rather surprising - source maps are expensive and you're increasing your build size by including them.  

That apart - if you'd like to submit a PR that resolves this we'd certainly take a look at it.

**Comment by onigoetz** [comment]
Hi,
I had the same issue, you have to set `{sourceMap: true}` in uglify's configuration as well.

```
new webpack.optimize.UglifyJsPlugin({sourceMap: true, compress: true})
```

This should solve your issue.
