### ISSUE TITLE
Compilation fails without the configuration file

### ISSUE THREAD

**Issue by mciesin** [TypeStrong/ts-loader#1051]
### Expected Behaviour
Sources should compile wihout having to define `tsconfig.json` file.

### Actual Behaviour
They don't.

When using ts-loader without any `tsconfig.json`, the config defaults to:
```js
{
    "compilerOptions": {},
    "files": []
}
```
which causes typescript to fail because of the empty `files` list. The error is very misleading though - it says:
```
The 'files' list in config file 'tsconfig.json' is empty.
```
yet no `tsconfig.json` file does exist at all. It is generated by ts-loader in case when no config is found.

Could the default config, generated by ts-loader, be changed, e.g. to config recommended in configuration section in readme?

Similar issues were raised in #405 and #434.

**Comment by slinkardbrandon** [comment]
I just ran into this today as well!

**Comment by sanderlissenburg** [comment]
Yep had this misleading error (TS18002: The 'files' list in config file 'tsconfig.json' is empty) too. Turned out I had a space in front of my config file. So no tsconfig.json was found, which resulted in the default empty files array as mentioned above.

**Comment by johnnyreilly** [comment]
If someone would like to raise a PR I'll take a look
