### ISSUE TITLE
Paths option not respected

### ISSUE THREAD

**Issue by thany** [TypeStrong/ts-loader#1052]
### Expected Behaviour
It should resolve modules according to `paths` in `tsconfig.json`.

### Actual Behaviour
It cannot find modules starting with `/` even though a rule in `paths` exists for them.

### Steps to Reproduce the Problem
`tsconfig.json`:
```json
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "target": "ES2019",
    "module": "commonjs",
    "lib": ["dom", "esnext", "es2017"],
    "rootDir": "./src",
    "baseUrl": "./src",
    "outDir": "./dist",
    "paths": {
      "/*": ["*"],
      "*": ["src/*", "node_modules/*"]
    }
  }
}
```
Project structure:
```
src
├── app.ts
├── config.ts
├── handlers
│   └── item.ts
└── types.ts
```
In `item.ts`:
```typescript
import { ItemParams } from '/types';
import config from '/config';
```
Error:
```
ERROR in ./src/handlers/item.ts
Module not found: Error: Can't resolve '/config' in 'D:\Projecten\Gallery\src\handlers'
 @ ./src/handlers/item.ts 7:41-59
 @ ./src/app.ts
```
On a sidenote, it would *really* help if it would print *where* it couldn't find a module. That would make it *so much* easier to diagnose a mistake in one of the many path/glob/file configuration options.

### Location of a Minimal Repository that Demonstrates the Issue.
This should do: https://github.com/thany/ts-loader-fails-to-find-import

**Comment by connorjsmith** [comment]
I'm having a similar issue with @types/react-redux
```
node_modules/react-redux/es"' has no exported member 'DispatchProp'
```
Even though I have `@types/react-redux` installed and included the following in my tsconfig.json
```
"paths": {
  "react": ["@types/react"],
  "react-redux": ["@types/react-redux"]
}
```

**Comment by johnnyreilly** [comment]
I wonder if you're in need of this plugin to create webpack aliases for you: https://github.com/dividab/tsconfig-paths-webpack-plugin

**Comment by thany** [comment]
I could give it a go, but mind you, running `tsc` works fine. So that tells me I shouldn't need additional plugins to make it work the way I intend to. I feel ts-loader should use the same mechanics as tsc, to find/resolve packages.

It seems any package on top of webpack+ts-loader to achieve the use of a feature that's already available in vanilla `tsc`, is a workaround, rather than a solution.

Having said that, the output of `tsc` only works when I set it to combine everything into a single file...
