### ISSUE TITLE
TS 3.8.x ES private fields are not taken in account

### ISSUE THREAD

**Issue by sionzeecz** [TypeStrong/ts-loader#1054]
On Jan 10 was released typescript 3.8 beta. But we are not able to compile private fields from ecmascript.

### Expected Behaviour
To compile code without issues
### Actual Behaviour

```
Module parse failed: Unexpected character '#' (17:13)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     constructor(properties) {
|         /** events */
>         this.#_onEnable = new SignalDispatcher();
|         this.#_onDisable = new SignalDispatcher();
|         this.#_onContentChange = new EventDispatcher();
```

### Steps to Reproduce the Problem
Create project with TS 3.8 beta, use tslib from git and use ts-loader with webpack.
Create a class with EcmaScript private field.

### Location of a Minimal Repository that Demonstrates the Issue.
Trivial to replicate, it is not needed.

packages:
```
"ts-loader": "^6.2.1",
"tslib": "https://github.com/microsoft/tslib",
"typescript": "^3.8.1-rc",
"webpack": "^4.41.5",
"webpack-cli": "^3.3.10",
"webpack-dev-server": "^3.10.3"
```
tsconfig:
```
{
  "compilerOptions": {
    "outDir": "../build/ts",
    "sourceMap": true,
    "strict": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "target": "ESNext",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "importHelpers": true,
    "strictPropertyInitialization": false,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
  }
}
```

**Comment by johnnyreilly** [comment]
I suspect you're either not using the 3.8 version of TypeScript or something is awry with your configuration. I'm not aware of a need for any changes required to ts-loader to facilitate this.

**Comment by sionzeecz** [comment]
`tsc` is compiling the project without issues.

**Comment by sionzeecz** [comment]
I went to: node_modules/ts-loader/dist/index.js
put debugger at funcation: 
`function loader(contents) {`

on:
`    const instanceOrError = instances_1.getTypeScriptInstance(options, this);`
instanceOrError.compiler.version === "3.8.1-rc"

**Comment by sionzeecz** [comment]
I found someone with same issue:
https://www.gitmemory.com/issue/webpack/webpack/10216/576740356

I also find out it comes from ACorn package. Where code `35` (#) is not handled and raises an error:
node_modules/acorn/dist/acorn.js, line: 4487
`pp$9.getTokenFromCode = function(code) {`

This function doesn't take in account 35. 

So it seems to be Webpack issue
