### ISSUE TITLE
Can't use nullish coalescing operator with TypeScript 3.8.2

### ISSUE THREAD

**Issue by screendriver** [TypeStrong/ts-loader#1061]
### Expected Behaviour

With TypeScript 3.8.2 I can't use the nullish coalescing operator `??` anymore.

### Actual Behaviour

I'm getting the error message

```sh
Module parse failed: Unexpected token (36:49)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
```

### Steps to Reproduce the Problem

Just use `const foo = bar ?? ''` in your codebase. With TypeScript 3.7.5 everything works fine

**Comment by ConneXNL** [comment]
Same problem here when using the nullish coalescing operator.

`fork-ts-checker-webpack-plugin` and vscode @ 3.8 things all are ok.

**Comment by screendriver** [comment]
I guess I know now why: TypeScript 3.8 changed the behaviour of the `target` version. So previously if you set it to `es2020` it gets transpiled down to older ECMAScript versions. But now it preserves the original syntax, which is not supported by any Node.js version at the moment.

A quote from the [official changelog](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-es2020-for-target-and-module):

```
TypeScript 3.8 supports es2020 as an option for module and target.
This will preserve newer ECMAScript 2020 features like optional chaining,
nullish coalescing, export * as ns, and dynamic import(...) syntax. It
also means bigint literals now have a stable target below esnext
```

@ConneXNL I'm using the latest version of `ts-loader`: `6.2.1`

**Comment by johnnyreilly** [comment]
So is a fix required to your `tsconfig.json`? Or have you identified a bug in TypeScript itself? Nothing in ts-loader has changed.

**Comment by screendriver** [comment]
No. It's not a bug. It's a breaking change in the compiler behavior. I changed the target to `es2019` and it's working now.

**Comment by dperetti** [comment]
I don't totally get it. What if I want to es2020, as I'm building solely for the latest Chromium which supports it natively?

**Comment by screendriver** [comment]
Then you need a Node.js version who is able to bundle code with nullish coalescing. At the moment this is [not supported](https://node.green) by Node.js

**Comment by lukechu10** [comment]
Why is this issue closed? I want optional chaining and nullish coalescing to appear in the outputted code because other wise, it messes up my code coverage. I am building an electron app and so it supports these latest features.

**Comment by FFdhorkin** [comment]
> Why is this issue closed? I want optional chaining and nullish coalescing to appear in the outputted code because other wise, it messes up my code coverage. I am building an electron app and so it supports these latest features.

This was the reason given:
> Then you need a Node.js version who is able to bundle code with nullish coalescing. At the moment this is [not supported](https://node.green) by Node.js

I would guess that it might come for free when Node.js catches up (soon, hopefully!), so its's not worth the effort for a temporary fix.

**Comment by mizchi** [comment]
I encountered same problem with typescript@3.8.3

`target:es2019` works but `target:es2020` is broken. Maybe `target:es2020` is something wrong.

**Comment by mizchi** [comment]
Oh, I got it. typescript 3.8 does non transform nullish syntax but webpack's acorn can not parse.
So ts-loader(and webpack) requires es2019 implicitly.

**Comment by Shuunen** [comment]
Same here with `"typescript": "^4.1.3"` still needed to downgrade my `"target": "ESNext"` to `"target": "ES2019"` in order to use nullish coalescing along with `"poi": "^12.10.3"` & `"@poi/plugin-typescript": "^12.3.1"`, poi use webpack under the hood

**Comment by MadhuvanthG** [comment]
To add info to this thread, you can use "ES2020" as your target if you are on Node 14 or higher. Node14 does support nullish coalescing and it's in Active LTS at the moment, so safe to use in Production as well.

**Comment by lucasmarinzeck** [comment]
I had to downgrade my target to ES2019  as well because ES2020 was not working for some rease

**Comment by mathieutu** [comment]
@MadhuvanthG Actually I'm currently in v15.10.0, and I still have the problem.

**Comment by MadhuvanthG** [comment]
Oops, not sure then. We've been using the operator with Node 14 and it does work fine.

**Comment by Dr-Dr3ck** [comment]
On my side, I am using typescript 4.3.5, node between >=14.16 and <15, es2020 and I also got the issue with nullish chaining operator.
ts-loader version is: 8.0.7 and I need es2020 beacuse of bigint.
Is there a solution for that config ?
