### ISSUE TITLE
Ignore config file and specify all options directly

### ISSUE THREAD

**Issue by slavafomin** [TypeStrong/ts-loader#1063]
Hello!

There should be a way to ignore `tsconfig.json` file in the project root. We are developing a tool that should embed all compilation options inside of itself and avoid loading configuration from the project's root.

Right now, `configFile` option can't be set to null.

**Comment by johnnyreilly** [comment]
Thanks but this sounds like an edge case and not something we directly want to support in ts-loader. Using a `tsconfig.json` is a very typical workflow; supported by tools and editors alike

**Comment by gregjacobs** [comment]
Actually this feature would be useful. Currently ts-loader is pulling in the `tsconfig.json` file in the root directory of my project which is actually used to compile a CLI program, and has settings that aren't meant for the webapp. 

Worse, if I set `configFile` to point to a new tsconfig.json file for the purpose of ts-loader, I get the following error:

```
TS18002: The 'files' list in config file 'tsconfig.json' is empty.
```

I don't know why I would need a `files` array when I'm using ts-loader in transpile-only mode (or even if I didn't use transpile-only mode - shouldn't webpack be providing the files to compile?)

**Comment by johnnyreilly** [comment]
Webpack does provide the files, but TypeScript still reads the `tsconfig.json`

**Comment by manast** [comment]
not sure but it seems the documentation and examples are not correct since you need to have a tsconfig.json file and that file requires a dummy files argument otherwise you get an error by the compiler... strictly speaking it is probably working but it does not look so nice to see the big red error message.
