### ISSUE TITLE
Error while using typescript 3.8 export aliases

### ISSUE THREAD

**Issue by guillaume86** [TypeStrong/ts-loader#1068]
### Expected Behaviour
Supporting typescript 3.8 export aliases. (`export * as alias from "module"`)

### Actual Behaviour
It produces an error `Module parse failed: Unexpected token (1:9)`.

### Steps to Reproduce the Problem
See same issue here: https://github.com/angular/angular/issues/36066

**Comment by Vardner** [comment]
The same

**Comment by andreybleme** [comment]
Same here. I see the additional message:
`You may need an additional loader to handle the result of these loaders.`

**Comment by webness** [comment]
The same.
```typescript
import * from '@pnotify/core';
....
export * as Pnotify from '@pnotify/core';
```

Error on export line.

**Comment by johnnyreilly** [comment]
If someone would like to take a look at this we gladly receive pull requests! 🥰

**Comment by mastrzyz** [comment]
@johnnyreilly I think this is more of a WebPack issue : https://github.com/webpack/webpack/issues/10460

**Comment by johnnyreilly** [comment]
Thanks @mastrzyz - really appreciate you sharing

**Comment by jun-sheaf** [comment]
For a workaround, see my comment on the associated Webpack issue: [webpack/webpack#10460](https://github.com/webpack/webpack/issues/10460#issuecomment-652062490)
