### ISSUE TITLE
How to skip type checks?

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-loader#1071]
I set `transpileOnly` to `true`, using ts-loader 4.5.0.\, because I'd like to limit CPU/Mem usage for certain builds.

### Expected Behaviour

I expect no type checking.

### Actual Behaviour

I see type checks every time Webpack rebuilds in watch mode, f.e.:

```
No type errors found
Version: typescript 3.8.3
Time: 25043ms
```

### Steps to Reproduce the Problem

set `transpileOnly` to true and still see type check output in console.

**Comment by guillaume86** [comment]
You're sure it actually type checks? What happens when you add a type error to your code?
