### ISSUE TITLE
Possible to insert `tsc` options outside of `tsconfig.json`?

### ISSUE THREAD

**Issue by psacawa** [TypeStrong/ts-loader#1086]
I am wondering if there is a way to insert config options outside of `tsconfig.json`.
What I am concretely trying to do is change the locale of the compiler's error messages, using the `compilerOptions.locale` attribute. As mentioned [here](https://github.com/microsoft/TypeScript/issues/34664), this option is ignored if placed in `tsconfig.json`. It only works on the comand line: `tsc --locale xx`. This is an undocumented behaviour.

I have tried to remedy this by setting `compilerOptions.locale` wherever I saw a `ts.CompilerOptions` object passed around in the `ts-loader` source, but it hasn't had the desired effect. I'm not sure why. Admittedly I don't understand the API Typescript exposes, though I do know `ts.CompilerOptions` has the `locale` attribute.

Is there a way to include options not supported from `tsconfig.json`? If not, can I get an indication of where in the source the option should be attached? Thank you.

**Comment by johnnyreilly** [comment]
I'm not sure there is; there's this: https://github.com/TypeStrong/ts-loader/blob/master/README.md#compileroptions but I'm not sure if it is what you want

**Comment by psacawa** [comment]
Unfortunately, this does not work. Actually, I think problem is not really in the purview of `ts-loader` to address. It should be available in Typescript. I think I'll just try to rebuild `tsc` to hardcode my locale.
