### ISSUE TITLE
Missing Compiler Errors when using Typescript Project References

### ISSUE THREAD

**Issue by berickson1** [TypeStrong/ts-loader#1087]
### Expected Behaviour
ts-loader warns about all typescript compiler errors on first run

### Actual Behaviour
errors for composite projects are ignored when re-running webpack

### Steps to Reproduce the Problem
1) Have a working & building typescript project that uses composite projects
2) Stop webpack
3) Introduce a compiler error into one of the composite projects
4) Run Webpack

At this point I'd expect an error, but the build reports as successful and emits without issue

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/berickson1/project-references-demo

For the above:
1) run `npm install`
2) run `npm run webpack`
3) observe successful build
4) stop webpack
5) Open `animals/dog.ts` and uncomment line 15 to introduce a compiler error
6) run `npm run webpack`
7) Observe "successful" build

Note: I turned on ts-loader logging and you can see that the error is being reported during the typescript build process, but it doesn't bubble up to webpack

**Comment by johnnyreilly** [comment]
This will hopefully be remedied by the excellent work @sheetalkamat is doing in https://github.com/TypeStrong/ts-loader/pull/1076

**Comment by berickson1** [comment]
Looks like it did! I'm happy to report that this no longer repros on ts-loader@7.0.0.
