### ISSUE TITLE
99 High Severity vulnerabilities found in Yarn Audit

### ISSUE THREAD

**Issue by plade** [TypeStrong/ts-loader#1088]
### Expected Behaviour
No vulnerabilities should be present.

### Actual Behaviour
416 vulnerabilities found, of which 99 are High Severity.

### Steps to Reproduce the Problem
run `yarn audit`

**Comment by plade** [comment]
Are there steps being taken to update the yarn dependencies? I can try making a PR to remove some, if not all of these.

**Comment by johnnyreilly** [comment]
I suspect a lot are false positives related to examples in the repo / devDependencies rather than dependencies. We're open to PRs though.
