### ISSUE TITLE
Errors are not printed on the console

### ISSUE THREAD

**Issue by niba** [TypeStrong/ts-loader#1091]
In my project I use project references. A default log level doesn't print compilation errors from referenced projects. To see the errors I need to set `logLevel: 'info'`

### Expected Behaviour

With logLevel option set to 'info' the output looks like that
```
******
some verbose log that I don't want but 'info' prints it
******
***/ManyToMany.tsx(220,5): error TS2783: 'parentItemId' is specified more than once, so this usage will be overwritten.
***/ManyToMany.tsx(241,31): error TS2769: No overload matches this call.
***/EditableCell.tsx(98,9): error TS2774: This condition will always return true since the function is always defined. Did you mean to call it instead?
Found 3 errors. Watching for file changes.
Failed to compile.
Error: TypeScript emitted no output for D:\****\CodeField.tsx. The most common cause for this is having errors when building referenced projects.
```
I expect a default log level to print the errors that we can see at the end of the output

### Actual Behaviour
This is what I see with default ts-loader config without settings logLevel option.
```
Error: TypeScript emitted no output for D:\****\CodeField.tsx. The most common cause for this is having errors when building referenced projects.
```
As you can see I don't have any information about errors.
### Steps to Reproduce the Problem
1. Have compiler errors in one of referenced projects
2. Run ts-loader@7.0.0

### Location of a Minimal Repository that Demonstrates the Issue.
Unfortunately I can't share my project

I use `typescript@next`.

**Comment by johnnyreilly** [comment]
Is this specific to project references? Please could you create a minimal repo that reproduces the behaviour?

**Comment by niba** [comment]
@johnnyreilly I edited my question to be more clear. It's related to project references. One of my 'shared' projects doesn't build and I don't see any errors when I'm trying to build it with ts-loader. I will try to create a minimal repo on the weekend

**Comment by johnnyreilly** [comment]
Thanks! cc @sheetalkamat @andrewbranch

**Comment by sheetalkamat** [comment]
Need repro to see why there are no errors reported
