### ISSUE TITLE
Enums that are not imported end up in the bundle

### ISSUE THREAD

**Issue by Njubster** [TypeStrong/ts-loader#1094]
Enums that are not being used are bundled nevertheless.

### Expected Behaviour

The bundle should know nothing about the enum that was not imported.

### Actual Behaviour

The bundle looks like this, containing enum items (ItemOne, ItemTwo):

`!function(n){var r={};function o(e){if(r[e])return r[e].exports;var t=r[e]={i:e,l:!1,exports:{}};return n[e].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=n,o.c=r,o.d=function(e,t,n){o.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},o.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},o.t=function(t,e){if(1&e&&(t=o(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)o.d(n,r,function(e){return t[e]}.bind(null,r));return n},o.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return o.d(t,"a",t),t},o.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},o.p="",o(o.s=0)}([function(e,t,n){"use strict";n.r(t);var r,o;(o=r=r||{})[o.ItemOne=0]="ItemOne",o[o.ItemTwo=1]="ItemTwo";window.addEventListener("load",function(){console.log("This variable is used")})}]);`

### Steps to Reproduce the Problem

The minimal setup is in the showcase repository. Just run `npm i` and then run the `npm run build`, and the results will be visible in output/index.js

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/Njubster/tsenumissue

**Comment by appzuka** [comment]
If you compile the file with tsc you can see what the typescript compiler outputs:
```
npx tsc ./src/index.ts
```
which produces the output in export.js:
```
var UnusedEnum;
(function (UnusedEnum) {
    UnusedEnum[UnusedEnum["ItemOne"] = 0] = "ItemOne";
    UnusedEnum[UnusedEnum["ItemTwo"] = 1] = "ItemTwo";
})(UnusedEnum = exports.UnusedEnum || (exports.UnusedEnum = {}));
```
The typescript compiler converts an enum into a function and that function is included in the bundle.  Read more about this at:

https://ncjamieson.com/dont-export-const-enums/

Despite the title of the above post, using a const enum may be what you want:
```
export const enum UnusedEnum {
  ItemOne,
  ItemTwo
}
```
If you do this, the enum will not be included in your bundle bit it will be available in your project. If you are writing a library where you want others to get access to the enum this will not work, but your goal here is to keep the enum out of the bundle.

I believe this is not an issue for ts-loader as webpack is just bundling the code is produced by typescript and you can control whether typescript inlines the enum code (const) or bundles it.
