### ISSUE TITLE
[BUG] Getting Build Failures with Multiple Entry Points

### ISSUE THREAD

**Issue by nawlbergs** [TypeStrong/ts-loader#1097]
Hello all, thanks for the cool loader.

I'm fairly new to both webpack and ts.. and am getting compile errors...

I have a js project that i have been slowly converting to ts... it outputs a couple of different directories to a js file.  I have been compiling this project for about a week now.. but today I have started using Promise.finally instead of Promise['finally'] (which we had done because of IE)... either way.... Im getting random errors now because I had to enable the lib `es2018.promise` in the tsconfig:

*basic project setup*
````
webpack.config.js
tsconfig.json
src /
  module1/index.ts  (extremely small amount of js/ts).. literally like 8 lines of ts and 100 lines of js.
  module2/index.ts  (mostly all ts and much larger)
  module3/ ... etc 
````

*tsconfig.json*
````
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "removeComments": true,
    "sourceMap": true,
    "allowJs": true,
    "lib": [
      "dom",
      "es5",
      "es6",
      "es2018.promise"
    ],
    "esModuleInterop": true,
    "typeRoots": [
      "./@types"
    ],
    "baseUrl": "./",
    "paths": {
      "@af-root/*":  ["./*"],
      "@af-module1/*": ["./src/module1/*"],
      "@af-module2/*": ["./src/module2/*"]
    }
  },
  "include": [
    "./af-globals.d.ts",
    "./**/*.ts"
  ],
  "exclude": [
    "./Gruntfile.js",
    "./GruntUtils.js",
    "./build/**/*",
    "./node_modules/**/*",
    "./grunt-config.js",
    "./**/*/grunt-config.js"
  ]
}
````

*webpack.config.js*
````
const path = require('path');
module.exports = flags => {
  return {
    mode: 'development', // production
    context: path.resolve(__dirname, './'),
    devtool: 'source-map',
    entry:{
      'module1':'./src/module1/index.ts',
      'module2':'./src/module2/index.ts',
    },
    output: {
      filename: '[name]/js/[name].js',
      path: path.resolve(__dirname, './build')
    },
    resolve: {
      extensions: ['.ts', '.js'],
      alias: {
        // see the tsconfig.js "paths" (these should match)
        "@af-root": __dirname,
        "@af-module1": __dirname + '/src/module1',
        "@af-module2": __dirname + '/src/module2',
      }
    },
    externals: {
      angular: 'angular',
      jquery: 'jquery',
      lodash : {
        commonjs: 'lodash',
        amd: 'lodash',
        root: '_' // indicates global variable
      }
    },
    //watch:true,
    optimization: {
      minimize: false,
      splitChunks: {
        cacheGroups: {
          vendors: {
            test: /[\\/]node_modules[\\/]/,
            filename: 'af-webpack-vendor.js',
            chunks: 'initial',
          },
        },
      },
    },
    module: {
      rules:
        [
          {
            test: /\.ts|.js?$/,
            use: [{
              loader: 'ts-loader',
              options:{
                configFile:'tsconfig.json'
              }
            }],
            exclude: [
              /node_modules/,
              /libs/,
              /build/
            ],
          }
        ]
    },
  }
};

````

### Expected Behaviour
Multiple entry points would load the properties of the tsconfig.json

### Actual Behaviour
It seems that it is not always loading the `es2018.promise` for all of my entryPoints:
About 80% of the time (not all the time) it throws:
````
ERROR in F:\sites\.....   TS2339: Property 'finally' does not exist on type 'Promise<void>'.
````
This does not occur if I comment out all but one entry point.
```
 entry:{
      //'module1':'./src/module1/index.ts',
      'module2':'./src/module2/index.ts',  <== now it will work
    },
```
It appears to be some type of `rat-race` issue... if i switch the order of the entry points.. putting a larger module first... it will fail far less... more like 15% of the time.. but will still randomly fail:
```
 entry:{
      'module2':'./src/module2/index.ts',  <== putting module2 first works a bit better
      'module1':'./src/module1/index.ts',
    },
```

### Steps to Reproduce the Problem
Project with multiple entryPoints and a project that uses Promise.finally.

**Comment by johnnyreilly** [comment]
Welcome to TypeScript and webpack! I suspect this is not a bug; rather a configuration issue. I've had a quick look at your code and nothing strikes me as yet - sorry

**Comment by nawlbergs** [comment]
Please close this issue..
Thanks for the response.  I feel dumb.  
After starting to setup a minimal repo to reproduce... i noticed a few of the modules actually had a .tsconfig.json file in the directory from a previous attempt at getting the project into ts:
(sorry.. the project is rather large)
````
tsconfig.json
src /
  module1/
      index.ts
      tsconfig.json <=== what?
  module2/index.ts
  module3/ ... etc 
````
apparently I did not remove them all...  and they did not include the `es2018.promise`... so I guess sometimes it use the roots tsconfig and sometimes not?  Either way... that was the problem.

**Comment by johnnyreilly** [comment]
No worries chap! Glad you got it sorted ☺️
