### ISSUE TITLE
Docs question regarding logLevel prop

### ISSUE THREAD

**Issue by rcidaleassumpo** [TypeStrong/ts-loader#1098]
>Beware of the fact that errors are written to stderr and everything else is written to stderr (or stdout if logInfoToStdOut is true).

>that errors are written to stderr and everything else is written to stderr

So is everything written to sderr ?
I don't understand here ? Is there something that I'm missing?

That's in the docs/ README.

**Comment by johnnyreilly** [comment]
Gosh I can't actually remember; feel free to discover and send us a docs PR!
