### ISSUE TITLE
[request] Emit specific files with transpileOnly flag

### ISSUE THREAD

**Issue by maxchehab** [TypeStrong/ts-loader#1100]
It would be appreciated if it was possible to specify a set of files to emit declarations with the `transpileOnly` flag. Libraries like [Typeorm](https://github.com/typeorm/typeorm) require certain declarations for type inference at runtime so this feature would let developers enjoy the speed benefits of the `transpileOnly` flag while still emitting required files.

I did a little sandboxing over the weekend and [forked ts-loader adding this feature](https://github.com/maxchehab/ts-loader), but I think it's best to introduce this with a proposal and a conversation from the community.

**Comment by jsbroks** [comment]
@maxchehab What did you set as the files that should emit? All entities' files?

I would really appreciate official support for this

**Comment by jsbroks** [comment]
@johnnyreilly Could you consider adding this option in?

**Comment by johnnyreilly** [comment]
My gut feeling is that this is a fairly niche need - as such I'm not that convinced it should be added to ts-loader.
