### ISSUE TITLE
Sourcemap sourcefile path differs from TSC

### ISSUE THREAD

**Issue by TimVosch** [TypeStrong/ts-loader#1105]
### Expected Behaviour
When TSC outputs sourcemaps it references the original file from the context of the output directory. (starts with two dots)
This allows Visual Studio Code to automatically detect the original files, since the relative path - as seen from the output file - is correct.

**dist/main.js.map**
```
source: ["../src/main.ts"]
```

### Actual Behaviour
Webpack + TS-Loader references the original files from the directory of the webpack.config.js. (Notice a single dot)

**dist/main.js.map**
```
source: ["./src/main.ts"]
```

### Steps to Reproduce the Problem
Create a project using webpack and ts-loader with the following configuration:

```js
{
  mode: "development",
  target: "node",
  entry: "./src/main.ts",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        loader: "ts-loader",
      },
    ],
  },
  resolve: {
    extensions: [".js", ".ts"],
    plugins: [new TsconfigPathsPlugin()],
  },
  devtool: false,
  plugins: [
    new webpack.SourceMapDevToolPlugin({
      filename: "[name].js.map",
      moduleFilenameTemplate: "[resource-path]",
      noSources: true,
      module: true,
    }),
  ],
}
```

### Location of a Minimal Repository that Demonstrates the Issue.
`git clone https://github.com/TimVosch/webpack-tsloader`
`cd webpack-tsloader`
`npm run build`

**Comment by appzuka** [comment]
The SourceMapDevToolPlugin plugin provides some options to control the source file path in the map file.  You could include the sourceRoot option to give a base to the files, although the filename is still given as ./src/file.ts, so you would presumably need to point sourceRoot to the folder containing src, which does not feel right.

The output filename is controlled by the moduleFilenameTemplate option.  If you set this to the string "[resource-path]" then the map will always contain file paths relative to the webpack config such as "./src/main.ts".  You could set it to:

```
      moduleFilenameTemplate: "[absolute-resource-path]",
```

This will include the absolute path, which will work.  If you want the path relative to the dist directory you can supply a function to moduleFilenameTemplate:

```
      moduleFilenameTemplate: ({resourcePath}) => '.'+resourcePath,
```
You can read about the options available at:

https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate

It would be nice if webpack automatically used a more suitable moduleFilenameTemplate if sourceRoot was supplied or one which produced a filename relative to the output directory if not. Or perhaps it is up to the developer to supply a moduleFilenameTemplate as they know best where they have located their dist folder and whether they have supplied a sourceRoot.

I believe any changes would need to be implemented in SourceMapDevToolPlugin.js and this is not an issue with ts-loader.

**Comment by TimVosch** [comment]
Thanks appzuka,

I have had a look at the SourceMapDevToolPlugin, unfortunately there is no easy solution as far as I know. Prepending a dot does not work because not all references are (relative) file paths.

For now I have decided to use absolute paths in a docker container. This way any final source-maps will already be mapped correctly.

Thanks for your help,
