### ISSUE TITLE
How to ignore all Typescript compilation errors?

### ISSUE THREAD

**Issue by vedantroy** [TypeStrong/ts-loader#1106]
Is it possible to ignore all Typescript compilation errors? I tried setting noEmitOnError` to false in my tsconfig.json, but that doesn't seem sufficient.

**Comment by johnnyreilly** [comment]
Perhaps don't use TypeScript? 😉

Quite seriously, you can use `transpileOnly` which exists so you can do type checking with something else like fork-ts-checker-webpack-plugin. Why do you want to ignore errors btw?

**Comment by liliang-cn** [comment]
Any clues?
