### ISSUE TITLE
Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by alecoder** [TypeStrong/ts-loader#1108]
I have Angular 9 application. I am using beta Webpack 5 which provides module federation feature. Just trying to play with this new tools.

I have standalone store application, which is served on localhost:9006 with module federation, it provides external remote bundle and shell(Angular 9) application can use it as imported bundle in runtime.

for example
```
import('s1').then( m => {

});
```
However the path

> s1

is not part of angular, i declared it as module to tell typescript do not throw any error

`declare module 's1'`

It's path is src and filename is decl.d.ts

but when i start my application, I get error:
```
ERROR in ./src/app/app.component.ts 78:8-20
Module not found: Error: Can't resolve 's1' in '/home/alecoder/Projects/JS/adj_integration/packages/shell/src/app'
resolve 's1' in '/home/alecoder/Projects/JS/adj_integration/packages/shell/src/app'
  Parsed request is a module
  using description file: /home/alecoder/Projects/JS/adj_integration/packages/shell/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/alecoder/Projects/JS/adj_integration/packages/shell/src/app/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/JS/adj_integration/packages/shell/src/node_modules doesn't exist or is not a directory
      looking for modules in /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules
        single file module
          using description file: /home/alecoder/Projects/JS/adj_integration/packages/shell/package.json (relative path: ./node_modules/s1)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1 doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1.js doesn't exist
        /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1 doesn't exist
      /home/alecoder/Projects/JS/adj_integration/packages/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/JS/adj_integration/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/JS/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/node_modules doesn't exist or is not a directory
      /home/alecoder/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./src/app/app.module.ts 16:0-47 63:22-34 80:16-28 87:24-36
 @ ./src/main.ts 5:0-45 9:41-50
```

Here is my webpack configuration

```
const AotPlugin = require("@ngtools/webpack").AngularCompilerPlugin;
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { resolve } = require('path');
const ProgressPlugin = require('webpack/lib/ProgressPlugin');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

module.exports = {

  devtool: 'eval-cheap-source-map',
  mode: "development",
  entry: ["./src/polyfills.ts", "./src/main.ts"],
  node: false,

  output: {
    path: resolve('./dist'),
    publicPath: '/',
    filename: '[name].bundle.js',
    chunkFilename: '[id].chunk.js'
  },

  devServer: {
    https: true,
    host: 'dev.adjarabet.com',
    port: 443,
    historyApiFallback: true,
    disableHostCheck: true,
    watchOptions: {
      ignored: /node_modules/
    },
    inline: true,
    open: true,
    hot: true,
    //quiet: true
    //stats: 'minimal'
    stats: {
      colors: true,
      chunks: false,
      hash: true,
      version: true,
      timings: true,
      assets: false,
      children: false,
      source: true,
      warnings: true,
      noInfo: true,
      contentBase: './dist',
      hot: true,
      modules: false,
      errors: true,
      reasons: true,
      errorDetails: true,
    },  
  },

  resolve: {
    extensions: ['.ts', '.js'],
    plugins: [new TsconfigPathsPlugin(
      { 
        configFile: "./src/tsconfig.app.json"
      })
    ]
  },

  performance: {
    hints: false,
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: ['ts-loader', 'angular2-template-loader'],
        exclude: /node_modules/,
        // {loader: 'ts-loader', options: {configFile: 'tsconfig.webpack.json'}  },
      }, 

      {
        test: /\.html$/,
        use: 'html-loader'
      }, 

      {
        test: /\.scss$/,
        use: ['to-string-loader', 'css-loader', 'sass-loader']
      },  

      {
        test: /\.(eot|svg|cur|ico)$/,
        loader: 'file-loader',
        options: {
          name: `[name].[ext]`,
          limit: 10000
        }
      },

      // {
      //   test: /\.(jpg|png|webp|gif|otf|ttf|woff|woff2|ani|ico)$/,
      //   loader: 'url-loader',
      //   options: {
      //     name: `[name].[ext]`,
      //     limit: 10000
      //   }
      // },

      // {
      //   test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
      //   parser: { system: true },
      // }
    ]
  },


  plugins: [

    new ModuleFederationPlugin({
      name: 'shell_app',
      library: { type: 'var', name: 'shell_app' },
      filename: 'remoteEntry.js',
      remotes: {
        s1: 's1'
      },
      exposes: {
      },
      shared: []
    }),    
    new HtmlWebpackPlugin({
      template: "./src/index.html"
    }),
    // new AotPlugin({
    //   mainPath: resolve('./src/main.ts'),
    //   sourceMap: true,
    //   nameLazyFiles: true,
    //   tsConfigPath: resolve('./src/tsconfig.app.json'),
    //   skipCodeGeneration: true
    // }),
    // new CircularDependencyPlugin(),
    new ProgressPlugin({
      activeModules: false,
    }),
  ]
};
```

Here is my tsconfig.app.json configuration

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../dist",
    // "types": ["node"]
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "node_modules"
  ],
  "angularCompilerOptions": {
    "enableIvy": false
  }  
}
```

I have Angular 9 application. I am using beta Webpack 5 which provides module federation feature. Just trying to play with this new tools.

I have standalone store application, which is served on localhost:9006 with module federation, it provides external remote bundle and shell(Angular 9) application can use it as imported bundle in runtime.

for example

import('s1').then( m => {

});
However the path

s1

is not part of angular, i declared it as module to tell typescript do not throw any error

declare module 's1'
It's path is src and filename is decl.d.ts

but when i start my application, I get error:

ERROR in ./src/app/app.component.ts 78:8-20
Module not found: Error: Can't resolve 's1' in '/home/alecoder/Projects/JS/adj_integration/packages/shell/src/app'
resolve 's1' in '/home/alecoder/Projects/JS/adj_integration/packages/shell/src/app'
  Parsed request is a module
  using description file: /home/alecoder/Projects/JS/adj_integration/packages/shell/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/alecoder/Projects/JS/adj_integration/packages/shell/src/app/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/JS/adj_integration/packages/shell/src/node_modules doesn't exist or is not a directory
      looking for modules in /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules
        single file module
          using description file: /home/alecoder/Projects/JS/adj_integration/packages/shell/package.json (relative path: ./node_modules/s1)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1 doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1.js doesn't exist
        /home/alecoder/Projects/JS/adj_integration/packages/shell/node_modules/s1 doesn't exist
      /home/alecoder/Projects/JS/adj_integration/packages/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/JS/adj_integration/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/JS/node_modules doesn't exist or is not a directory
      /home/alecoder/Projects/node_modules doesn't exist or is not a directory
      /home/alecoder/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./src/app/app.module.ts 16:0-47 63:22-34 80:16-28 87:24-36
 @ ./src/main.ts 5:0-45 9:41-50
Here is my webpack configuration

const AotPlugin = require("@ngtools/webpack").AngularCompilerPlugin;
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { resolve } = require('path');
const ProgressPlugin = require('webpack/lib/ProgressPlugin');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

module.exports = {

  devtool: 'eval-cheap-source-map',
  mode: "development",
  entry: ["./src/polyfills.ts", "./src/main.ts"],
  node: false,

  output: {
    path: resolve('./dist'),
    publicPath: '/',
    filename: '[name].bundle.js',
    chunkFilename: '[id].chunk.js'
  },

  devServer: {
    https: true,
    host: 'dev.adjarabet.com',
    port: 443,
    historyApiFallback: true,
    disableHostCheck: true,
    watchOptions: {
      ignored: /node_modules/
    },
    inline: true,
    open: true,
    hot: true,
    //quiet: true
    //stats: 'minimal'
    stats: {
      colors: true,
      chunks: false,
      hash: true,
      version: true,
      timings: true,
      assets: false,
      children: false,
      source: true,
      warnings: true,
      noInfo: true,
      contentBase: './dist',
      hot: true,
      modules: false,
      errors: true,
      reasons: true,
      errorDetails: true,
    },  
  },

  resolve: {
    extensions: ['.ts', '.js'],
    plugins: [new TsconfigPathsPlugin(
      { 
        configFile: "./src/tsconfig.app.json"
      })
    ]
  },

  performance: {
    hints: false,
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: ['ts-loader', 'angular2-template-loader'],
        exclude: /node_modules/,
        // {loader: 'ts-loader', options: {configFile: 'tsconfig.webpack.json'}  },
      }, 

      {
        test: /\.html$/,
        use: 'html-loader'
      }, 

      {
        test: /\.scss$/,
        use: ['to-string-loader', 'css-loader', 'sass-loader']
      },  

      {
        test: /\.(eot|svg|cur|ico)$/,
        loader: 'file-loader',
        options: {
          name: `[name].[ext]`,
          limit: 10000
        }
      },

      // {
      //   test: /\.(jpg|png|webp|gif|otf|ttf|woff|woff2|ani|ico)$/,
      //   loader: 'url-loader',
      //   options: {
      //     name: `[name].[ext]`,
      //     limit: 10000
      //   }
      // },

      // {
      //   test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
      //   parser: { system: true },
      // }
    ]
  },

  plugins: [

    new ModuleFederationPlugin({
      name: 'shell_app',
      library: { type: 'var', name: 'shell_app' },
      filename: 'remoteEntry.js',
      remotes: {
        s1: 's1'
      },
      exposes: {
      },
      shared: []
    }),    
    new HtmlWebpackPlugin({
      template: "./src/index.html"
    }),
    // new AotPlugin({
    //   mainPath: resolve('./src/main.ts'),
    //   sourceMap: true,
    //   nameLazyFiles: true,
    //   tsConfigPath: resolve('./src/tsconfig.app.json'),
    //   skipCodeGeneration: true
    // }),
    // new CircularDependencyPlugin(),
    new ProgressPlugin({
      activeModules: false,
    }),
  ]
};
Here is my tsconfig.app.json configuration

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../dist",
    // "types": ["node"]
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "node_modules"
  ],
  "angularCompilerOptions": {
    "enableIvy": false
  }  
}
and tsconfig.json that extends tsconfig.app.json

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@services/*": ["./app/services/*", "./app/modules/form/services/*"],
      "@typings/*": ["./app/typings/*"],
      "@app/*": ["./app/*"],
      "@env/*": ["./environments/*"]
    },
    "target": "es5",
    "module": "esnext",
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "lib": ["es2018", "dom"],
    "mapRoot": "./maps",
    "moduleResolution": "node",
    "outDir": "./dist",
    "sourceMap": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
  },
  "files": [
    "./decl.d.ts"
  ], 
}
```

It seems typescript can't see that module and tries to find it out under node_modules. I missed something in configuration but can't see where.

**Comment by appzuka** [comment]
I built a basic example using ts-loader.  It is based on the module-federation example.  You can see the code at:

https://github.com/appzuka/module-federation-ts-loader

Hopefully, this can help you understand what is going on in your code.  I did notice that it is essential to include the module name in the import statement.  For example:

```
import("app2/Button")
```
will work, but

```
import("app2")
```

will not.  This applies even if you declare 'app2' as the module name in the .d.ts file.  This may be why your import("s1") does not work.  I also needed to include the esnext module type in tsconfig.json:

```
      "module": "esnext"
```

If you are still having problems please send me a link to your code or a minimal repo with the issue and I'll try to take a look.

**Comment by alecoder** [comment]
I have tried the same. in angular environment it does not work. When i define ambient module for typescript, after rendering and loading chunks that external modules are empty like ambient modules. that remote chunk do not override local module.

Repo is private and can't provide all source codes but most configurations I have provided already...

**Comment by appzuka** [comment]
Are you sure this is an issue with ts-loader? It sounds more like something to do with webpack.  Module Federation is very new and Webpack 5 is currently at the beta release stage.  You could try using a different typescript loader and see if the issue is still present.

If you can't share your repo you could create a minimal repo which still exhibits the problem.  It is hard to debug from configuration snippets.

**Comment by alecoder** [comment]
I also tried to use awesome-ts-loader and AngularCompilerPlugin from @ngtools/webpack. 
both of them failed and the only ts-loader worked for development mode.

I have opened the bug related to AngularCompilerPlugin: https://github.com/webpack/webpack/issues/10830 it is waiting at the moment for it's turn to be fixed.

When I tried to migrate those features into my angular app, i followed this repo: https://github.com/manfredsteyer/module-federation-with-angular. here the author achieved that loading external bundle dynamically and use them.

**Comment by alecoder** [comment]
I created monorepo structure with angular and pure store apps. here you can have a look: https://github.com/alecoder/module_federation_minimal_repo_angular


Instruction:
npm run apps:install
npm run apps:build
npm run apps:serve
npm run shell:start

**Comment by appzuka** [comment]
There are no files under shell in the repo.  I assume shell is supposed to be the host application.

**Comment by alecoder** [comment]
> There are no files under shell in the repo. I assume shell is supposed to be the host application.

https://github.com/alecoder/angularmf

**Comment by appzuka** [comment]
I ran your shell and store apps and the module federation worked on my system.  There were no build errors and in the browser console I could see that the module from the store app was loaded:

```
app.component.ts?e670:9
Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}
default: (...)
Symbol(Symbol.toStringTag): "Module"
__esModule: true
get default: () => __WEBPACK_DEFAULT_EXPORT__
__proto__: Object
```

I am using WSL2 under Windows 10 and node v12.16.3 if that helps.

**Comment by alecoder** [comment]
Have you followed all instructions i provided above ?

**Comment by appzuka** [comment]
The instructions you provided are incomplete. The first repo you provided contains no files under shell so it is not possible to build and run the shell app.  When I copy the shell app from the second repo it runs fine.

Module Federation with angular is working on my system using your repos.  If you want me to look further please provide a minimal repo which contains all the files needed to demonstrate the problem and a list of the steps to show the problem.

**Comment by alecoder** [comment]
You did not have to copy anything from second repo. You had to just clone and run all commands i provided.
Thank you anyway !

**Comment by appzuka** [comment]
When I clone the first repo there are no files under packages/shell, so it is not possible to run npm run shell:start.

It looks as if packages/shell was a submodule (it has the submodule icon in github), so it is not included when you pushed the repo.

If you clone your repo to a new directory you should see the same.
