### ISSUE TITLE
Unable to override declaration for JSON modules since 7.0.3

### ISSUE THREAD

**Issue by renspoesse** [TypeStrong/ts-loader#1116]
### Expected Behaviour
Types are exracted from JSON files unless TypeScript cannot resolve the module and a custom declaration is present. Use case: loading certain JSON files with `file-loader`.

### Actual Behaviour
Types are extracted from all JSON files. ts-loader behaves differently than the TypeScript compiler run manually.

### Steps to Reproduce the Problem
- Update to https://github.com/TypeStrong/ts-loader/releases/tag/v7.0.3.
- Enable `resolveJsonModule` in `tsconfig.json`.
- Create some JSON files:

```json
// foo.json
{ "foo": "bar" }
```

```json
// my-other-files/bar.json
{ "foo": "bar" }
```

- Declare overrides for certain JSON modules:

```ts
// modules.d.ts
declare module "my-other-files/*";
```

- Import a JSON file:

```ts
import foo from "foo.json"; // Expected type: { foo: "bar" }
import bar from "my-other-files/bar"; // Expected type: any
```

At this point running the TypeScript compiler manually works as expected, but ts-loader ignores the custom declaration and recognizes the type of the contents of bar.json instead of `any`.

**Comment by johnnyreilly** [comment]
Thanks for the report. The issue is presumably related to the changes to `getScriptRegexp` here: https://github.com/TypeStrong/ts-loader/pull/1101/files

cc @berickson1

If you'd like to submit a PR then we'll take a look!

**Comment by berickson1** [comment]
It looks like this occurs due to ts-loader respecting and following webpack aliases.
The typescript compiler itself doesn't know about webpack aliases, so this explains why there's a difference in behaviour.

I put together a repro case here:
https://github.com/berickson1/ts-loader/commit/4829bcccf00d582b6dc1e5eed2b7b4a67fa4604f

The above should build cleanly when this is resolved.

I'm not sure I'm familiar enough with the internals of ts-loader to help much more than this but figured I'd share my findings nonetheless

**Comment by johnnyreilly** [comment]
> It looks like this occurs due to ts-loader respecting and following webpack aliases.

Thanks for commenting @berickson1! Could you expand on what you mean by this? I don't follow how webpack aliases affect behaviour? I think I'm missing something 🤗

**Comment by berickson1** [comment]
In the above example the 'my-other-files' modules doesn't exist in node_modules, so the only way that webpack will successfully bundle it was to build an alias.
I suspect that ts-loader used that alias as a part of modules resolution to resolve 'my-other-files/file.json' to a relative path. Given it found a file to build, I can understand why it might skip over the definition file provided.

In the case of the typescript compiler, 'my-other-files' isn't in node_modules and isn't a relative path, so the .d.ts with the ambient module declaration is used.

@renspoesse - can you try altering your tsconfig to explicitly exclude the offending json file(s) and see if that helps at all?

**Comment by renspoesse** [comment]
I tried excluding the JSON files but that has no effect.

Your explanation makes sense though. [It looks like](https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules) TypeScript tries `.ts`, `.tsx`, and `.d.ts` when resolving a module. `.json` extensions are opt-in: https://github.com/Microsoft/TypeScript/issues/24357.

So when ommitting the `.json` extension as I did in my example the TypeScript compiler won't find the file and use the ambient module declaration instead.

**Comment by berickson1** [comment]
@renspoesse - I can make typescript give you the same error as ts-loader by altering the tsconfig to include a `paths` attribute. At that point the module resolution behaves the same.

Given you need to customize webpack to use tsconfig bathUrl and paths (https://github.com/TypeStrong/ts-loader#baseurl--paths-module-resolution), my gut instinct is that it makes sense for ts-loader to use webpack's module resolution system, but I'll leave it to @johnnyreilly and friends to confirm. 

```
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "composite": true,
    "baseUrl": ".",
    "paths": {"my-other-files/*": ["my-other-files/*"]}
  },
  "include": ["**/*.ts", "**/*.json"]
}

```

**Comment by johnnyreilly** [comment]
> my gut instinct is that it makes sense for ts-loader to use webpack's module resolution system,

This is probably true. By and large, a goal for `ts-loader` is to be a drop in replacement for TypeScript.

The only real exception to that is where that goal collides with obeying webpacks behaviours.
