### ISSUE TITLE
compilerOptions.declaration - Nothing happens

### ISSUE THREAD

**Issue by hitmands** [TypeStrong/ts-loader#112]
Hi, 
I'm looking for a way to generate declaration files from my typescript project.

Unfortunately, I had no luck!
Basically nothing happens.
No `*.d.ts` file generated.

I'm using webpack with ts-loader and I set `compilerOptions.declaration = true` in my tsconfig.json

I am using: 
ts-loader@0.7.2
webpack@1.12.9
typescript@next

**Comment by jbrantly** [comment]
See #48 for a discussion about this. It's likely that generating .d.ts files for each module isn't really want you're wanting (then again, maybe it is :grin:)

**Comment by jbrantly** [comment]
Closing this in favor of #48
