### ISSUE TITLE
ES6 modules and TS modules, one webpack bundle

### ISSUE THREAD

**Issue by flahertyb** [TypeStrong/ts-loader#113]
Should it possible to directly import an es6 file into a tsx file?

Foo.ts

```
import bar from './bar';
```

Bar.es6

```
let bar = function () { console.log('bar'); };

export default bar;
```

webpack configuration

```
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts-loader'
            },
            {
                test: /\.es6$/,
                loader: 'babel'
            }
        ]
    }
```

In theory this makes a lot of sense to me - each file could be transpiled by its respective loader, and then bundled together. But what actually happens is the typescript compilation complains that it can't find `bar` as a module, because it doesn't exist in `tsconfig.json`, because you can't add non-ts files to the list of files in tsconfig.json. Which makes sense - but shouldn't there be a way to do the above? 

Maybe I am way off here in my expectations of what is supposed to happen. Or asking this question in the wrong place. Any response would be helpful.

**Comment by jbrantly** [comment]
Unfortunately it does not quite work that way. TypeScript doesn't know how to consume non-TypeScript currently (and requires certain file extensions). There are ongoing discussions about TypeScript being able to do this in the future but not there yet.

You can do this if you inform TypeScript about the file in a way that it understands. For example, you could write a bar.d.ts file that sits next to bar.es6. The bar.d.ts file would describe the shape of the module and TypeScript would be happy.

**Comment by flahertyb** [comment]
Thank you for clarifying!

**Comment by AshCoolman** [comment]
Note: It took me a few hours to work this out the other week too :)

**Comment by jbrantly** [comment]
Maybe needs some documentation then. Going to reopen to track for docs.

**Comment by flahertyb** [comment]
@jbrantly essentially said this above, but I will restate, because I had some further confusion:

With webpack using ts-loader, you absolutely can write `import bar from './bar.es6'`, as long as you define an [ambient module declaration](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#122-ambient-module-declarations), and include that declaration's file in the `files` array of the tsconfig. 

This declaration placates the TypeScript compiler (and lets you specify the correct typing for the external es6 module, if you'd like). It won't actually do any bundling or importing of course, but it can ouput compiled source with that import statement intact (if targeting es6), and webpack can then treat it like a normal import statement when constructing its bundle. 

Likewise, no problem for ES6 module to import a typescript module with ts-loader. 

One gotcha I found is that if your TypeScript file imports a module (whether a real typescript module or an ambiently declared module), but the import isn't then used anywhere, the TypeScript compiler omits it from output. Threw me for quite a while trying to test this!

**Comment by jbrantly** [comment]
The issue with ambient module declarations in this case is that they're really meant for top-level modules (ie, "jquery", "react", etc) not relative modules (ie, "./someFile", "../../lib/someOtherFile"). If you write an ambient module declaration for "./bar.es6" that will only work when importing that file from a sibling file. As soon as you tried to import it from somewhere else (like a child or parent directory) it would no longer work because the name "./bar.es6" would no longer match up with "../../bar.es6". It's much better to write a bar.d.ts file that sits next to bar.d.ts so that you can import it from anywhere (and you also don't have to include it in `files`; TS knows how to look it up).

Also, you generally do not want to include file extensions for imports, so you would just use "./bar".

**Comment by flahertyb** [comment]
Thank you for pointing that out! I didn't realize the TS magic happening there. 

If you only write module declarations with import paths relative to webpack's `root` directory, such that the path was always `bar`, not `./bar`, and the `bar` file is in webpack root dir, then this does seem to work well without a sibling definition file. Course, it relies on that webpack setting - your way is more robust.
