### ISSUE TITLE
Project reference example

### ISSUE THREAD

**Issue by IIIristraM** [TypeStrong/ts-loader#1134]
It would be really useful if repo will contain example for `projectReference` option. It's quite unclear how to make right webpack and ts configurations in real applications.

For example, I have lerna repo with some shared packages that I want to set as dependencies for others, so I made tsconfigs like

```
// packages/common/tsconfig.json

{
    "extends": "../tsconfig/tsconfig.json",
    "compilerOptions": {
        "baseUrl": ".",
        "rootDir": "src",
        "outDir": "build",
        "composite": true,
        "declaration": true,
        "declarationMap": true,
        "tsBuildInfoFile": "./node_modules/.cache/tsconfig.tsbuildinfo",
    },
    "include": [
        "src"
    ]
}
``` 

```
// packages/client/tsconfig.json

{
    "extends": "../tsconfig/tsconfig.json",
    "references": [
        {
            "path": "../common/tsconfig.json"
        }
    ],
    "compilerOptions": {
        "baseUrl": ".",
        "rootDir": "src",
        "outDir": "build",
        "paths": {
            "@project/common/*": [
                "../common/src/*"
            ]
        }
    },
    "include": [
        "src"
    ]
}
```

The main confusion for me is which folder should be aliases set to, should it be the source folder `src` or output folder `build` ? Should it be the same for tsconfig and webpack config or not ?

If I understand correctly dependencies should be resolved into `.d.ts` files instead of source `.ts` files  in `traceResolution` log. For `tsc` it could be achivied by setting aliases to output folder `build` but such webpack aliases break the build.

So the working options are
1) `build` folder for tsconfig aliases, `src` folder for webpack aliases
2) `src` folder for tsconfig aliases, `src` folder for webpack aliases

I set `traceResolution: true` and `logLevel: 'info'` for `client` package to check resolution for both cases, but found no `.d.ts` resolutions for `common` package, so I asume that dependencies always compiled from source files instead of reusing declarations, and incremental builds do not work correctly.

So me and probably a lot of other people would be very thankful for a correct example or a way to check if dependencies are really resolved into declaration files.

**Comment by johnnyreilly** [comment]
Yup - good shout. if someone would like to contribute an example I'd happily include it.

**Comment by appzuka** [comment]
I have written a guide to project references and ts-loader that includes an example repo.  You can read it at:

https://medium.com/@nickexcell/using-typescript-project-references-with-ts-loader-and-webpack-part-1-5d0c3cd7c603

**Comment by IIIristraM** [comment]
This is a good example, but I have more complex build process, where each package has it's own webpack build and the common packages are shared as webpack dll

The problem with such configuration is that while webpack build shared modules only once, Typescript still use them during typecheking, so the time of typecheck is always `share packages time + dependent package time` for each dependent package, so for N dependent packages I have N webpack builds + one build for dll, which means shared packages are processed by Typescript N + 1 time.

The idea was to reduce build time of dependent packages by configuring shared packages as project references, but It looks like ts-loader cannot leverage references builded in another webpack build

this is the example of output during webpack rebuild process
![image](https://user-images.githubusercontent.com/2033959/92242962-4c0d5200-eec9-11ea-8c47-030751cf90a3.png)

Module `components/hello/index.ts` was changed and built first in `common` package, and then the second time in the `client` package, which has reference to common package in tsconfig
