### ISSUE TITLE
error TS2300: Duplicate identifier

### ISSUE THREAD

**Issue by squarepants** [TypeStrong/ts-loader#114]
I think it's very important to tell users use "exclude" or "files" in project "tsconfig.json".

If we don't write those in "tsconfig.json", we'll get bunch of errors tells us "Duplicate identifier" in "typescript" module. and the solution to this problem is to tell "tsc" what files we want to compile.

```
    "exclude": [
        "node_modules"
    ]
```

Sometimes users just switch loader, because the solution to this problem is not easy to find.

So I think it will be nice to have some instructions in docs.

**Comment by jbrantly** [comment]
It's kind of there already:

> The files property should generally be specified even if its just an empty array. If the files property is not specified, then all TypeScript files in the directory and subdirectories will be included, possibly even ones that should not be.

**Comment by squarepants** [comment]
Alright, my bad. At least somebody like me miss this in doc has solution to search.

**Comment by szahn** [comment]
Missed this in the docs as well. For someone fairly new to the JS build chain, I missed the fact that you had to exclude the folder for node modules in the tsconfig.json, not the webpack.config.js.

**Comment by jbrantly** [comment]
Reopening to try to make docs more clear.

**Comment by Klortho** [comment]
Well, I just got bit by this, and, in fact, I still can't find the reference to "The files property ...". If it's not on the README here, where else would it be? I'm not new to node, but very new to typescript, and only using it because I'm trying to get somebody else's code to work in webpack.
