### ISSUE TITLE
`transpileOnly` does not work with `projectReferences`

### ISSUE THREAD

**Issue by chancancode** [TypeStrong/ts-loader#1158]
### Steps to Reproduce the Problem

Set up a project that uses `transpileOnly: true` and `projectReferences: true`. Something like this:

```js
// root tsconfig.json
{
  "include": ["index.ts"],
  "compilerOptions": {
    "outDir": "dist",
    "references": [
      { "path": "./packages/sub-project" },
      // ...
    ]
  }
}
```

```js
// packages/sub-project/tsconfig.json
{
  "compilerOptions": {
    "outDir": "dist",
    "composite": true,
    "declaration": true
  }
}
```

### Expected Behaviour

When a type error is introduced in either the root project or the sub-project, the build should work and emit the JS files despite the type error.

### Actual Behaviour

When a type error is introduced in either the root project, the build would work and the JS files are emitted. However, when a type error is introduced in the sub-project(s), the build fails and no JS files are emitted.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/emberjs/ember-debug/tree/d8ae4c9019f1fd673532c56575dc35898335d958 can be used to test this (by enabling `transpileOnly: true` which is not included in the repo yet)

**Comment by appzuka** [comment]
I believe this behaviour is expected.  When you define a project reference, that sub-project is built in the same way as if you typed <code>tsc --build</code> in the sub-project's directory.  If there are errors they will be reported.  Files which were not part of the sub-project will be built by webpack calling ts-loader and if you include the transpileOnly option then the file will not be checked for type errors.

There is a need for documentation for project references as this is a relatively new feature.  This behaviour could be part of the documentation.

**Comment by desmap** [comment]
just to get the terminology right, I also just tested this, check https://github.com/TypeStrong/ts-loader/pull/1173#issuecomment-681040638 and when...

#### CASE A: I have `transpileOnly: true` in `ts-loader` options + `fork-ts-checker` enabled

- No type errors if the type error is in a **non-reference file** (eg. a file that imports a reference but doesn't get imported itself)
- ✔Type errors if the type error is in a **reference file** (eg. a file that gets imported)

#### CASE B: I just have fork-ts-checker enabled:

- ✔Type errors if the type error is in a **non-reference file** (eg. a file that imports a reference but doesn't get imported itself)
- ✔Type errors if the type error is in a **reference file** (eg. a file that gets imported)

So, IDK if this reflects the same issue of OP because he uses the term subproject. But I'd expected that reference files might have problems with type checking and not non-reference files.

CC @johnnyreilly

**Comment by desmap** [comment]
just read OP's issue again and he has another problem (his build fails) and he doesn't use fork-ts-checker.

shall we still keep the discussion here for now (i closed that PR and that other multcompile issue might be also the wrong place)?

**Comment by desmap** [comment]
fwiw `fork-ts-checker`'s profiling output, is this normal that fork-ts-checker isn't doing anything? Both files have over 1,000 functions in an array each

### CASE A1
```
Parse Configuration:                0.03 s
Create Watch Compiler Host:         0.00 s
I/O Read:                           0.00 s
Parse:                              0.00 s
Program:                            0.02 s
Semantic Diagnostics:               0.00 s
Create Watch Program:               0.03 s
Poll And Invoke Created Or Deleted: 0.00 s
Queued Tasks:                       0.00 s
```
### CASE A2
```
Parse Configuration:                0.02 s
Create Watch Compiler Host:         0.00 s
I/O Read:                           0.00 s
Parse:                              0.00 s
Program:                            0.02 s
Semantic Diagnostics:               0.00 s
Create Watch Program:               0.03 s
Poll And Invoke Created Or Deleted: 0.00 s
Queued Tasks:                       0.00 s
```
### CASE B1
```
Parse Configuration:                0.01 s
Create Watch Compiler Host:         0.00 s
I/O Read:                           0.00 s
Parse:                              0.00 s
Program:                            0.01 s
Semantic Diagnostics:               0.00 s
Create Watch Program:               0.02 s
Poll And Invoke Created Or Deleted: 0.00 s
Queued Tasks:                       0.00 s
```
### CASE B2
```
Parse Configuration:                0.02 s
Create Watch Compiler Host:         0.00 s
I/O Read:                           0.00 s
Parse:                              0.00 s
Program:                            0.01 s
Semantic Diagnostics:               0.00 s
Create Watch Program:               0.02 s
Poll And Invoke Created Or Deleted: 0.00 s
Queued Tasks:                       0.00 s
```

**Comment by desmap** [comment]
fyi I found the problem: I needed to set context explicitly to the to be compile project folder within the project references structure (in this case `client`). now fork-ts shows also some activity
