### ISSUE TITLE
error: could not load typescript -> how to set compiler=global typescript instalation?

### ISSUE THREAD

**Issue by flyon** [TypeStrong/ts-loader#118]
I just upgraded after quite a while and get the error "Could not load typescript. Try in stalling with `npm install typescript`".

But I just updated my global npm typescript module, and I don't really want to install typescript for every small project.

Can I somehow point to the local typescript compiler?

npm list typescript -g
C:\Users\***\AppData\Roaming\npm
└── typescript@1.7.3

**Comment by jbrantly** [comment]
See #35 for a related discussion. The jist of it is that loading globally is [discouraged](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) and sometimes doesnt work correctly (for reasons that are unknown to me). TypeScript also recently removed the `preferGlobal` flag.

That said, ts-loader doesn't do anything special with regards to loading TypeScript locally or globally. It simply does `require('typescript')` and let's node take care of the rest. 

See [this comment](https://github.com/TypeStrong/ts-loader/issues/35#issuecomment-145792561) for a possible workaround using `npm link`.

**Comment by flyon** [comment]
sorry didnt see that issue before. `npm link typescript` works great!
