### ISSUE TITLE
ts-loader does not ignore dot files

### ISSUE THREAD

**Issue by vicpon** [TypeStrong/ts-loader#1186]
### Expected Behaviour
ts-loader should ignore dot files by default

### Actual Behaviour
It's not ignoring dot files and is processing them.

### Steps to Reproduce the Problem
I have a vue typescript project and am using the `rc` npm package for app configurations so I have a few config files for it

.myapprc
.myappstagingrc
.myappproductionrc

One of them looks like this
```json
{
  "appUrl": "http://localhost:8085",
  "auth0": {
    "domain": "some.auth0.domain",
    "clientId": "some client ID"
  },
  "apiBaseUrl": "https://localhost:7000/api",
  "embedScriptUrl": "https://some.website.com/test.js"
}
```

It tries to do load the embedScriptUrl, which results in the following error:
```
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'errors' of undefined
    at PoolWorker.fromErrorObj (D:\sandbox\vue\test\node_modules\thread-loader\dist\WorkerPool.js:262:12)
    at D:\sandbox\vue\test\node_modules\thread-loader\dist\WorkerPool.js:204:29
    at mapSeries (D:\sandbox\vue\test\node_modules\neo-async\async.js:3625:14)
    at PoolWorker.onWorkerMessage (D:\sandbox\vue\test\node_modules\thread-loader\dist\WorkerPool.js:170:35)
    at D:\sandbox\vue\test\node_modules\thread-loader\dist\WorkerPool.js:152:14
    at Socket.onChunk (D:\sandbox\vue\test\node_modules\thread-loader\dist\readBuffer.js:36:9)
    at Socket.emit (events.js:315:20)
    at Socket.Readable.read (_stream_readable.js:506:10)
    at Socket.read (net.js:624:39)
    at flow (_stream_readable.js:1006:34)
    at emitReadable_ (_stream_readable.js:570:3)
    at successfulTypeScriptInstance (D:\sandbox\vue\test\node_modules\@vue\cli-plugin-typescript\node_modules\ts-loader\dist\instances.js:119:28)
    at Object.getTypeScriptInstance (D:\sandbox\vue\test\node_modules\@vue\cli-plugin-typescript\node_modules\ts-loader\dist\instances.js:34:12)
    at Object.loader (D:\sandbox\vue\test\node_modules\@vue\cli-plugin-typescript\node_modules\ts-loader\dist\index.js:17:41)
```

**Comment by appzuka** [comment]
@vicpon, Are you sure this is an issue with ts-loader?  The error message indicates that the error is coming from thread-loader.  What happens if you take thread-loader out of your configuration?

I have not used thread-loader (the documentation suggests to only use it for expensive operations). The documentation says that it is important to use happPackMode if you are using thread-loader:

https://github.com/TypeStrong/ts-loader#happypackmode

There is an example in ts-loader

https://github.com/TypeStrong/ts-loader/blob/master/examples/thread-loader/webpack.config.js

If you are still having issues please post a minimal repository that demonstrates the issue.

**Comment by vicpon** [comment]
@appzuka thanks for the links. I did notice that the code were it threw an error is gated behind the happyPackMode flag. I'm not explicitly using thread-loader, but I do have `transpileOnly: true` and am using `ForkTsCheckerWebpackPlugin`. I will try setting the `happyPackMode` flag to true.

**Comment by vicpon** [comment]
@appzuka it does work when I use happyPackMode but I don't understand why. This is my webpack configuration. What here would tell it to use thread-loader?

```
{
  devServer: {
    disableHostCheck: true
  },
  configureWebpack: {
    devtool: 'source-map',
    plugins: [
      new VuetifyLoaderPlugin(),
      new DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify(process.env.NODE_ENV),
          appSettings: JSON.stringify(config)
        }
      }),
      new ForkTsCheckerWebpackPlugin({
        typescript: {
          diagnosticOptions: {
            semantic: true,
            syntactic: true,
          },
        },
      })
    ],
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: [/node_modules/, /^\..*rc$/],
          // include: /src/,
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
            appendTsSuffixTo: [/\.vue$/],
            happyPackMode: true,
          }
        }
      ]
    }
  },
  pages: {
    index: {
      // entry for the page
      entry: 'src/main.js',
      // the source template
      template: 'public/index.html',
      // output as dist/index.html
      filename: 'index.html'
    }
  }
}
```

**Comment by appzuka** [comment]
@vicpon, As far as I see, neither ts-loader nor ForkTsCheckerWebpackPlugin list thread-loader as a dependency (at least in the latest versions).  You could look in yarn.lock to see why it is being included or use the command:
```
yarn why thread-loader
```
When I try this with my project (which uses ts-loader and ForkTsCheckerWebpackPlugin, but not Vue) it confirms thread-loader is not installed.

**Comment by vicpon** [comment]
It looks like a few vue packages use it. It's interesting that ts-loader just picks it up if it exists though. Seems like unwanted behavior if it's not explicitly being used.

```
  Who required thread-loader:

  test > @vue/cli-plugin-babel > thread-loader@2.1.3
  test > @vue/cli-plugin-typescript > thread-loader@2.1.3
  test > @vue/cli-service > thread-loader@2.1.3
```

**Comment by appzuka** [comment]
I don't use Vue but it looks as if thread-loader is being used because it is added to the loader chain by @vue/cli-plugin-typescript:

https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript

From the docs:

> thread-loader is enabled by default when the machine has more than 1 CPU cores. This can be turned off by setting parallel: false in vue.config.js.
> 
> parallel should be set to false when using Typescript in combination with non-serializable loader options, such as regexes, dates and functions. These options would not be passed correctly to ts-loader which may lead to unexpected errors.

So I don't believe ts-loader is picking up thread-loader because it exists.  It is added because @vue/cli-plugin-typescript is used in the config.  Given that it has been added, you need <code>happyPackMode</code>, or you could disable <code>thread-loader</code> in @vue/cli-plugin-typescript.

**Comment by vicpon** [comment]
I can definitely see your point and I won't claim to know how the loader framework works. This just seems like a hidden issue because I don't have non-serializable loader options (no serialization errors) as far as I can tell and I would think one package can use thread-loader without affecting other packages.

Since it works with `happyPackMode` I'm leaving it as is. Thanks for the help.
