### ISSUE TITLE
Supported TS version error

### ISSUE THREAD

**Issue by XeniaSiskaki** [TypeStrong/ts-loader#1187]
### Expected Behaviour
When using `typescript` v3.2.4 with latest `ts-loader` it shouldn't complain about the TS version since according to the docs, it supports 

> TypeScript: 2.4.1+

### Actual Behaviour
Seeing a console error saying
```
ts-loader: Using typescript@3.2.4. This version is incompatible with ts-loader. Please upgrade to the latest version of TypeScript.
```
I'm not sure if the docs are wrong, or the error message is just wrongly displayed. The project seems to compile properly even with the above error message.

**Comment by appzuka** [comment]
I believe the minimum supported Typescript version was changed from 2.4.1 to 3.6.3 in v8.0.0 in July this year.  Thanks for spotting this.  I will submit a PR to update the docs.

I understand it is the tests which need the higher version of TypeScript so it is possible that it still works with an older version.  However, it is probably unwise to risk this for production as you are using an unsupported and untested setup.
