### ISSUE TITLE
Errors/warnings added by ts-loader do not respect webpack API

### ISSUE THREAD

**Issue by lorenzodallavecchia** [TypeStrong/ts-loader#1199]
I'm processing webpack errors/warnings in the compilation results.

### Expected Behaviour

The errors and warnings reported by ts-loader through webpack should implement the `WebpackError` interface.
Starting from webpack 5 the interface is part of webpack's official typings.

### Actual Behaviour

Instead of including the `loc` property with start/end positions of the error, the object added by ts-loader includes a `location` property with just the starting position. This is easily seen in the webpack `stats` object produced by the compilation.

```javascript
stats.compilation.errors; // each error misses the 'loc' property
stats.compilation.warnings; // each warning misses the 'loc' property
```

Probably as a consequence of this, when I transform the stats into JSON, there is no location information for the errors.

```javascript
const json = stats.toJson({ all: false, errors: true, warnings: true });
json.errors; // 'loc' missing in errors
json.warnings; // 'loc' missing in warnings
```

**Comment by lorenzodallavecchia** [comment]
The problem is still present, no reason to close this.

**Comment by johnnyreilly** [comment]
Would you like to work on this?

**Comment by lorenzodallavecchia** [comment]
Yes, I would like to. I hope to find some time to do a PR in the coming days.

**Comment by johnnyreilly** [comment]
Thanks for contributing! Should be released in the next 20 mins https://github.com/TypeStrong/ts-loader/releases/tag/v8.0.17
