### ISSUE TITLE
93% sealing after asset optimization ts-loader

### ISSUE THREAD

**Issue by flexWhale** [TypeStrong/ts-loader#1211]
Hi,
I have some strange situation with building my typescript project with webpack and ts-loader.

 `webpack --progress`

`module.exports = {
	devtool: 'eval',
	entry: './src/app.ts',
	output: {
		filename: 'main.js',
		path: path.resolve(__dirname, 'dist')
	},
	module: {
		rules: [
			{
				test: /\.tsx?$/,
				loader: 'ts-loader'
			}
		]
	},
	resolve: {
		extensions: [ '.ts', '.tsx', '.js' ]
	}
};`

some progress and message is hanging in console:

`93% sealing after asset optimization ts-loader`

and after long time:

```
99% done plugins webpack-cli[webpack-cli] Compilation finished
asset main.js 4.18 MiB [emitted] [minimized] [big] (name: main)
./src/app.ts 4.02 MiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  main.js (4.18 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (4.18 MiB)
      main.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.4.0 compiled with 3 warnings in 1218503 ms
```

Does somebody know what can be wrong? Why does my build take a too long time?

**Comment by cyzaoj** [comment]
+1

**Comment by johnnyreilly** [comment]
A minimal reproduction repo might help someone look into this

**Comment by mylastore** [comment]
+1

**Comment by grevzi** [comment]
Hi,
Are there any possible solutions how to resolve this issue?
I'm facing the same `93% sealing after asset optimization ts-loader` freezing issue on webpack 5.74.0.

Thanks.
