### ISSUE TITLE
Failed to build with project references and thread-loader

### ISSUE THREAD

**Issue by mortyccp** [TypeStrong/ts-loader#1224]
### Expected Behaviour
Build without error
### Actual Behaviour
```
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'options' of undefined
    at PoolWorker.fromErrorObj (/private/tmp/ts-loader/examples/project-references-example/node_modules/thread-loader/dist/WorkerPool.js:344:12)
    at /private/tmp/ts-loader/examples/project-references-example/node_modules/thread-loader/dist/WorkerPool.js:217:29
    at mapSeries (/private/tmp/ts-loader/examples/project-references-example/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/private/tmp/ts-loader/examples/project-references-example/node_modules/thread-loader/dist/WorkerPool.js:171:34)
    at Object.makeSolutionBuilderHost (/private/tmp/ts-loader/examples/project-references-example/node_modules/ts-loader/dist/servicesHost.js:554:66)
    at Object.buildSolutionReferences (/private/tmp/ts-loader/examples/project-references-example/node_modules/ts-loader/dist/instances.js:250:55)
    at Object.loader (/private/tmp/ts-loader/examples/project-references-example/node_modules/ts-loader/dist/index.js:23:17)
```

### Steps to Reproduce the Problem
1. Clone this repo
2. Install `thread-loader` in `project-references-demo`
3. Update webpack rule to 
```
        use: [
          {
            loader: 'thread-loader',
            options: {
              // there should be 1 cpu for the fork-ts-checker-webpack-plugin
              workers: require('os').cpus().length - 1,
              poolTimeout: Infinity, // set this to Infinity in watch mode - see https://github.com/webpack-contrib/thread-loader
            },
          },
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: false, // Set to true if you are using fork-ts-checker-webpack-plugin
              projectReferences: true,
              happyPackMode: true,
            },
          },
        ],
```
4. Run yarn build

**Comment by appzuka** [comment]
I'm not sure I would expect thread-loader to work with project references.  The documentation for thread-loader states that there are limits to what loaders running in a thread pool can do:

https://webpack.js.org/loaders/thread-loader/

ts-loader with project references emits many files so breaks these rules.  I'm not sure this is the reason for the error you are seeing but I would not recommend using thread-loader in this case.  When you use project references you avoid recompiling after the first run unless the source in the project changes so trying to run in parallel using thread-loader seems unnecessary.

**Comment by mortyccp** [comment]
>ts-loader with project references emits many files so breaks these rules. I'm not sure this is the reason for the error you are seeing but I would not recommend using thread-loader in this case. When you use project references you avoid recompiling after the first run unless the source in the project changes so trying to run in parallel using thread-loader seems unnecessary.

I think the usage of `thread-loader` is not for development time but build time and maybe in CI environment. The following the config generate by `vue-cli` for the build task.
```
/* config.module.rule('ts') */
{
    test: /\.ts$/,
    use: [
        /* config.module.rule('ts').use('cache-loader') */
        {
        loader: '/tmp/pocs/mono.ts/node_modules/cache-loader/dist/cjs.js',
        options: {
            cacheDirectory: '/tmp/pocs/mono.ts/apps/web/node_modules/.cache/ts-loader',
            cacheIdentifier: '5e1f1dc7'
        }
        },
        /* config.module.rule('ts').use('thread-loader') */
        {
        loader: '/tmp/pocs/mono.ts/node_modules/thread-loader/dist/cjs.js'
        },
        /* config.module.rule('ts').use('babel-loader') */
        {
        loader: '/tmp/pocs/mono.ts/node_modules/babel-loader/lib/index.js'
        },
        /* config.module.rule('ts').use('ts-loader') */
        {
        loader: '/tmp/pocs/mono.ts/node_modules/ts-loader/index.js',
        options: {
            transpileOnly: true,
            appendTsSuffixTo: [
            '\\.vue$'
            ],
            happyPackMode: true
        }
        }
    ]
}
```


> I'm not sure I would expect thread-loader to work with project references.

Can you share how ts-loader works with thread-loader in happyPackMode and non project reference setup?

**Comment by appzuka** [comment]
Simple webpack loaders do not read from, or write to, the filesystem.  Webpack reads the source, passes it (perhaps through other loaders) to the loader and the loader passes the result back to webpack.

If you use thread-loader, these can be run in parallel.  This should be OK as the loader processes the only the source file it gets from webpack and does not depend on the result of other files being passed through the loader.

If you use transpileOnly: true, this is how ts-loader works.  It received *.ts files from webpack, strips out the TypeScript syntax and passes plain JavaScript back.  It should be safe to do this in parallel which is probably why vue-cli generates this config.  Whether it will increase build speed is less certain; there is an overhead to creating the threads so unless the loaders are expensive it may increase build time.

With transpileOnly ts-loader does not warn about type errors, so you need to run error checking separately using fork-ts-checker-webpack-plugin.  I have not used HappyPack but I believe it is similar to thread-loader although support for HappyPack seems to have almost stopped.  I note that the instructions for HappyPack and ts-loader state that you must use transpileOnly.

If you do not use transpileOnly ts-loader does full type checking for you.  This means it must open not just the source file it is passed by webpack but all referenced files so it can check whether the types are correct.  This is why it takes longer but it also no longer behaves as a fully well-behaved loader.  Loader chaining may break and also it would be dangerous to run in parallel using thread-loader.

If you use project references, the referenced projects are built just the same as if you used tsc --build.  Specifying transpileOnly will not make any difference - errors in the referenced projects will be reported.  The output of the project references will typically be used later in the build process.  I think it is highly unlikely that this will work with thread-loader as you need to wait for the project references to finish building before you can continue with the rest of the build.

If your project is large project references are way to reduce incremental build time.  The sub-projects don't need to go through any loaders after the first build so parallelising the loaders is not an issue.

**Comment by mortyccp** [comment]
Wow. Thank you for the detailed explanation.  
So I think I can just use ts-loader with project references and without thread-loader and fork-ts-checker-webpack-plugin.
👍
