### ISSUE TITLE
TS Compile Error is logged as INFO when using Project References

### ISSUE THREAD

**Issue by m1heng** [TypeStrong/ts-loader#1238]
### Expected Behaviour
ts compile error would be log out in Error level
 
### Actual Behaviour
error info from ts complier is logged by `reportDiagnostic` regardless of error into `logInfo`

### Steps to Reproduce the Problem
NIP

### Location of a Minimal Repository that Demonstrates the Issue.
NIP

As matter of fact, when step into a new repo, and there is no build result from previous development, the circumstance that I would face is that webpack tells me `Failed to compile. Module not found:` and an useless .buildinfo in referenced package. And what's worse, ts-loader would require me to set `config.logLevel = 'info';` in order to found out ts compile error instead of a default behavior.

**Comment by m1heng** [comment]
a check of typescript.Diagnostic.category and log accordingly may be a nice way?

**Comment by johnnyreilly** [comment]
Thanks for contributing! I'm afraid I don't quite follow what you're saying here. If there's a compilation error - the build fails. You seem to be saying otherwise?

**Comment by m1heng** [comment]
> Thanks for contributing! I'm afraid I don't quite follow what you're saying here. If there's a compilation error - the build fails. You seem to be saying otherwise?

Yes, the build failed, but Error info from ts was not logged out as default.

**Comment by johnnyreilly** [comment]
Can you provide a repro that demos this please?

**Comment by m1heng** [comment]
When I was trying to reproduce the output, it turns out to be a bug of my own building tool that hidden the error log. 🥺 Sorry.
