### ISSUE TITLE
Webpack 5 watch not failing on error

### ISSUE THREAD

**Issue by aardvarkk** [TypeStrong/ts-loader#1253]
### Expected Behaviour

- Making a file invalid should cause webpack watch compilation to fail
- I realize I have named this issue exactly like [this one](https://github.com/TypeStrong/ts-loader/issues/1204), but that issue is marked as resolved as of a few versions ago and yet strange behaviour still seems to persist

### Actual Behaviour

- Webpack watch appears to succeed despite invalid input

### Steps to Reproduce the Problem

- `npm i`
- `npx webpack watch`
  - compilation succeeds
- edit `src/index.ts` to uncomment out the trailing `{` and save
- notice `npx webpack watch` runs again _and compilation still succeeds_
- stop `npx webpack watch`
- run `npx webpack watch` again and notice that an error now appears

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/aardvarkk/webpack-ts-loader-issue/tree/main

**Comment by appzuka** [comment]
@aardvarkk,  Thanks for reporting this.  I did resolve https://github.com/TypeStrong/ts-loader/issues/1204 but then broke it again fixing https://github.com/TypeStrong/ts-loader/issues/1243. Check https://github.com/TypeStrong/ts-loader/issues/1204 for my explanation.  I will raise a PR to fix this.
