### ISSUE TITLE
Can I request a new setting such as `configFileText`?

### ISSUE THREAD

**Issue by jason-grimm** [TypeStrong/ts-loader#1256]
Because the `compilerOptions.module` in the project's `tsconfig.json` is set to `amd`, and `compilerOptions.outFile` is set.

When using webpack for packaging, I can't override the `outFile` setting in the `compilerOptions`, because webpack is packaged with `commonjs` by default.

I know I can add a different `tsconfig.json` file and set the `options.configFile` at the same time to solve this problem. Or set webpack to `amd` module as well.

But I would like to have a way to reuse the original `tsconfig.json` and also use the default module settings of webpack.

**Comment by johnnyreilly** [comment]
Sorry - this doesn't seem like a common use case and so we're unlikely to take this.

**Comment by jason-grimm** [comment]
What a pity.

Because tsconfig.json extends doesn't eliminate the effect of the outFile setting, so I ask here.

But I think ts-watch in development and webpack in release is an common use case.(webpack watch mode is so slow……)

**Comment by johnnyreilly** [comment]
> Because the compilerOptions.module in the project's tsconfig.json is set to amd,

This puzzles me! Why would you have a different module definition type for development as compared to production?

Incidentally, have you considered checking out https://www.snowpack.dev/ - it's blazing fast in Dev mode and only uses webpack for releases (which is similar to what your doing anyway I think)

**Comment by jason-grimm** [comment]
Because tsc's `outFile` only supports `amd/system` mode.
I coded an `amd` module loader(a `define` function), and I can import this file via `files` in tscconfig.json. But I don't think this feature is mature enough to put in realase version.

Webpack is powerful and can package all the source code into one file with `commonjs` module, but amd's `define` function is not natively supported by webpack.

Thanks for your patient answer. I'm going to follow: https://www.snowpack.dev/
