### ISSUE TITLE
How to debug "TypeScript emitted no output for..." properly?

### ISSUE THREAD

**Issue by chbiel** [TypeStrong/ts-loader#1257]
Sorry, but I don't know were to ask, so I hope I get some help here as I don't find any other helpful resources.

We currently try to switch from "awesome-typescript-loader" to "ts-loader".
Simply switching the webpack config leads to errors like the following:

```
[...]
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for [...]
```
without any more helpful information.

`tsc` for example run without a problem.

So my question is:
How can I find out / debug deeper, what in detail is happening and maybe to get some more helpful error messages?

I expect that the error originates from typescript not being able to do some `import` statements properly but I did not find a way to debug, what is going wrong and why. 

if it helps `tsconfig.json`:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["es6", "dom", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "strict": true,
    "target": "es5"
  },
  "include": ["./frontend/**/*"]
}
```

thanks in advance!

EDIT:
So I tried to track it down and now I have the following file, that does not compile with `ts-loader` with the above error message and i am really lost^^

```
import React from 'react';

type InventoryStatsProps = {
  t: any;
  i18n: any;
  tReady: boolean;
};

export const InventoryStatsTile: React.FC<InventoryStatsProps> = () => {
  return <div>lkajskdjaksd</div>;
};

export default InventoryStatsTile;
```

**Comment by johnnyreilly** [comment]
Could be worth consulting @andrewbranch's excellent debugging guide! https://github.com/TypeStrong/ts-loader/blob/master/CONTRIBUTING.md#debugging

**Comment by andrewbranch** [comment]
@berickson1’s excellent debugging guide* 😉

**Comment by berickson1** [comment]
Try changing `noEmit` to `true` (or removing it entirely).
A contrived local example using your tsconfig.json yields the same behaviour. (I'm not sure this is a bug, but it does sound like a difference in behahaviour between ATL and ts-loader)

**Comment by chbiel** [comment]
thanks for pointing that guide out. unfortunately it did not help :)

but for some reason today removing "noEmit: true" from the config, complete solved the problem. (surprisingly i tried that yesterday and did not work, but who knows)

My learning at the moment is:
- ATL required to set `noEmit: true`, because otherwise it would write the .js files to disk
- `ts-loader` required to **not** set `noEmit: true`, as it otherwise would not emit some file (some yes, some not, don't know)

i will give up on understanding it further for the moment.

thanks for your help!

**Comment by reorx** [comment]
Hi @andrewbranch and @johnnyreilly , just read the excellent guide, but I didn't get to know how to expose the detailed error of TypeScript under the hood, can you please give some advice? The requirement is simple, just want to see the exact error of tsc compiling process.

**Comment by amanmishra1321** [comment]
Facing the same issue, didn't found any thing till now. But someone has closed this issue.
