### ISSUE TITLE
Create a wiki or document that lists examples

### ISSUE THREAD

**Issue by jbrantly** [TypeStrong/ts-loader#126]
Examples/starter kits are often asked for. Would be great to have a definitive list. See #111 for some. Also https://github.com/AngularClass/angular2-webpack-starter.

**Comment by jbrantly** [comment]
Oops, I meant #101

**Comment by jbrantly** [comment]
Another that hit HN today: https://github.com/alamgird/angular-next-starter-kit

**Comment by jbrantly** [comment]
Should also include tutorials. For example, these two popped up recently:
http://fagner.co/2016/01/01/TypeScript-+-Webpack/
http://www.thinkingincrowd.me/2016/01/02/Modulization-and-Bundling-with-TypeScript-and-Webpack-for-JS-Full-Stack-Project/

**Comment by jbrantly** [comment]
https://github.com/jaysoo/todomvc-redux-react-typescript

**Comment by johnnyreilly** [comment]
At the risk of blowing my own trumpet there's also this: https://github.com/Microsoft/TypeScriptSamples/tree/master/es6-babel-react-flux-karma

**Comment by jbrantly** [comment]
Trumpet away :+1:

**Comment by jbrantly** [comment]
Closed with https://github.com/TypeStrong/ts-loader/wiki/Tutorials-&-Examples and 25b82b9
