### ISSUE TITLE
thread-loader with ts-loader, Cannot read property 'addError' of undefined

### ISSUE THREAD

**Issue by fwt-1025** [TypeStrong/ts-loader#1268]
### Expected Behaviour
I used webpack5 to build Vue project, I used "thread loader" with "TS loader", but I got an error.

### Actual Behaviour
```cmd
  Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
  Thread Loader (Worker 0)
  Cannot read property 'addError' of undefined
      at PoolWorker.fromErrorObj (D:\workSpace\GitLeapCloud\LP_LeapCloud_Phone\nod
  e_modules\thread-loader\dist\WorkerPool.js:344:12)
      at D:\workSpace\GitLeapCloud\LP_LeapCloud_Phone\node_modules\thread-loader\d
  ist\WorkerPool.js:217:29
      at getTranspilationEmit (D:\workSpace\GitLeapCloud\LP_LeapCloud_Phone\node_m
  odules\ts-loader\dist\index.js:405:20)
      at successLoader (D:\workSpace\GitLeapCloud\LP_LeapCloud_Phone\node_modules\
  ts-loader\dist\index.js:38:11)
      at Object.loader (D:\workSpace\GitLeapCloud\LP_LeapCloud_Phone\node_modules\
  ts-loader\dist\index.js:23:5)
```

### Steps to Reproduce the Problem
```ts
// entry main.ts
const a:number = 1
console.log(a)
```
```js
  module.exports = {
      entry: {
          main: path.resolve(__dirname, 'main.ts')
      },
     module: {
        rules: [
             {
                test: /\.ts$/,
                use: [
                       'thread-loader',
                       'ts-loader'
                 ]
             }
        ]
     }
  }
```

**Comment by ComponentTY** [comment]
I'm in the source code instances.js In the "reporttranspileerrors" function“ loader.module "What you get is undefined, and then the source code doesn't make short pointer judgment, it's just judgment." loader.module.addError "
```js
function reportTranspileErrors(instance, loader) {
    if (!instance.reportTranspileErrors) {
        return;
    }
    const module = loader._module;
    instance.reportTranspileErrors = false;
    // happypack does not have _module.errors - see https://github.com/TypeStrong/ts-loader/issues/336
    if (!instance.loaderOptions.happyPackMode) {
        const solutionErrors = servicesHost_1.getSolutionErrors(instance, loader.context);
        const diagnostics = instance.program.getOptionsDiagnostics();
        const errors = utils_1.formatErrors(diagnostics, instance.loaderOptions, instance.colors, instance.compiler, { file: instance.configFilePath || 'tsconfig.json' }, loader.context);
        /**
         * Since webpack 5, the `errors` property is deprecated,
         * so we can check if some methods for reporting errors exist.
         */
        if (module.addError) {
            [...solutionErrors, ...errors].forEach(error => module.addError(error));
        }
        else {
            module.errors.push(...solutionErrors, ...errors);
        }
    }
}
```

**Comment by appzuka** [comment]
See https://github.com/TypeStrong/ts-loader/issues/1242#issuecomment-765646504 for some notes on getting ts-loader and thread-loader to work together.  This was pre-webpack5 so maybe there is a different issue with webpack5.  However, I don't believe it is a good idea to use thread-loader with ts-loader unless you are using transpileOnly mode as ts-loader breaks some of the requirements for thread-loader.

**Comment by ComponentTY** [comment]
> See [#1242 (comment)](https://github.com/TypeStrong/ts-loader/issues/1242#issuecomment-765646504) for some notes on getting ts-loader and thread-loader to work together. This was pre-webpack5 so maybe there is a different issue with webpack5. However, I don't believe it is a good idea to use thread-loader with ts-loader unless you are using transpileOnly mode as ts-loader breaks some of the requirements for thread-loader.

Thank you for your reply, I get it.

**Comment by ComponentTY** [comment]
> See [#1242 (comment)](https://github.com/TypeStrong/ts-loader/issues/1242#issuecomment-765646504) for some notes on getting ts-loader and thread-loader to work together. This was pre-webpack5 so maybe there is a different issue with webpack5. However, I don't believe it is a good idea to use thread-loader with ts-loader unless you are using transpileOnly mode as ts-loader breaks some of the requirements for thread-loader.

In real projects, I used transpileonly, but I still got this error.
Now I don't use thread-loder with ts-loader.
