### ISSUE TITLE
compilerOptions.paths breaks with v9.x

### ISSUE THREAD

**Issue by c-frater** [TypeStrong/ts-loader#1294]
### Expected Behaviour
Absolute imports using `paths` should work as it did in `v8.1.0`

### Actual Behaviour
Updating to `9.1.0` / `9.1.1`, changing nothing and compiling yields errors like the following:
```
TS2307: Cannot find module '~/static/strings' or its corresponding type declarations.
```

Either this behaviour is unintended or needs documentation in the changelog when changing from 8.x to 9.x

### Steps to Reproduce the Problem

minimum structure:
```
src
    - static
        - strings.ts (with `export default true;`)

 tsconfig.json
```

tsconfig.json
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "lib": [
      "dom",
      "es2015",
      "es2016",
      "es2017"
    ],
    "allowJs": true,
    "jsx": "react",
    "sourceMap": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "noImplicitAny": true,
    "noLib": false,
    "preserveConstEnums": false,
    "removeComments": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "target": "es6",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "declaration": true,
    "outDir": "dist",
    "types": [
      "node",
      "jest",
      "@testing-library/jest-dom"
    ],
    "baseUrl": ".",
    "paths": {
      "~/*": ["src/*"]
    }
  }
}
```

Loader config:
```js
{
  loader: 'ts-loader',
  options: {
    configFile: path.join(__dirname, 'tsconfig.json'),
  },
};
```

Webpack resolve
```
    resolve: {
      alias: {
        '~': path.resolve(__dirname, sourcePath),
      },
      extensions: ['.js', '.jsx', '.json', '.tsx', '.ts'],
    },
```

I don't believe any of the other config is relevant in this case

### Location of a Minimal Repository that Demonstrates the Issue.
N/A - Internal code.

**Comment by johnnyreilly** [comment]
If you could provide a minimal reproduction repo that may help people look into this.

**Comment by JonWallsten** [comment]
We're using paths in our monorepo, and it works fine with 9.x.x. So I guess it's not as simple as this doesn't work.
```
{
  "compilerOptions": {
    "rootDir": ".",
    "baseUrl": ".",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noEmitHelpers": true,
    "noEmitOnError": false,
    "importHelpers": true,
    "noImplicitAny": false,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "strictPropertyInitialization": false,
    "pretty": true,
    "sourceMap": true,
    "declaration": false,
    "preserveConstEnums": true,
    "downlevelIteration": true,
    "lib": [
        "dom",
        "es2015",
        "es2017.object",
        "es2016.array.include",
        "es2017.string",
        "es2018.promise",
        "es2019.string"
    ],
    "paths": {
      "@my-organisation/web-lib-core": ["./packages/web-lib-core/dist"],
      "@my-organisation/web-lib-common": ["./packages/web-lib-common/dist"],
      "@my-organisation/web-lib-angular-js": ["./packages/web-lib-angular-js/dist"],
      "@my-organisation/web-lib-angular": ["./packages/web-lib-angular/dist"],
      "@my-organisation/internal-lib-e2e": ["./packages/internal-lib-e2e/dist"]
    }
  },
  "include": [
    "./build-tools/"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Comment by c-frater** [comment]
Yeah, I tried making a minimum example and it worked perfectly fine with the exact same dependencies so it must be v9 plus _some other package_ breaking it.

I'll do some digging and update when I work out what combination is breaking this (and whether ts-loader can actually do anything about it....)

**Comment by tomachalek** [comment]
Hello, we've been experiencing a similar issue after upgrading from `8.0.18` to `9.1.2`. In our project, we use Webpack's aliases to allow custom/vendor-specific implementations of different functions. Here is a working (stripped down, with possible minor "noise") example: https://github.com/tomachalek/ts-loader-alias-issue

**Comment by Phillip-Cannon** [comment]
We also ran into this issue after the upgrade to v9. For us, the problem was caused by us setting both `baseUrl` in our `tsconfig.json` and `tsloader.options.context` in our webpack configuration. They were both set to the same path. In v8 this combination seemed to work but in v9 we found just setting `baseUrl` and removing `tsloader.options.context` got things working again.
