### ISSUE TITLE
why fix   loaderUtils.getOptions =>loaderContext.getOptions(undefined) ,it get error (loaderContext.getOptions is not a function)

### ISSUE THREAD

**Issue by wtj199101** [TypeStrong/ts-loader#1295]
### Expected Behaviour
 in 9.0.1   /**
 * either retrieves loader options from the cache
 * or creates them, adds them to the cache and returns
 */
function getLoaderOptions(loaderContext: WebpackLoaderContext) {
  const loaderOptions =
    **loaderUtils.getOptions<LoaderOptions>(loaderContext) ||
    ({} as LoaderOptions);**

  // If no instance name is given in the options, use the hash of the loader options
  // In this way, if different options are given the instances will be different
  const instanceName =
    loaderOptions.instance || 'default_' + getOptionsHash(loaderOptions);

  if (!loaderOptionsCache.hasOwnProperty(instanceName)) {
    loaderOptionsCache[instanceName] = new WeakMap();
  }
### Actual Behaviour
util 9.0.2
/**
 * either retrieves loader options from the cache
 * or creates them, adds them to the cache and returns
 */
function getLoaderOptions(loaderContext: WebpackLoaderContext) {
  **const loaderOptions = loaderContext.getOptions(undefined);**

  // If no instance name is given in the options, use the hash of the loader options
  // In this way, if different options are given the instances will be different
  const instanceName =
    loaderOptions.instance || 'default_' + getOptionsHash(loaderOptions);

  if (!loaderOptionsCache.hasOwnProperty(instanceName)) {
    loaderOptionsCache[instanceName] = new WeakMap();
  }

  const cache = loaderOptionsCache[instanceName];

  if (cache.has(loaderOptions)) {
    return cache.get(loaderOptions) as LoaderOptions;
  }

**Comment by amritk** [comment]
Hey @wtj199101 how did you end up solving the issue?

**Comment by kateetrant** [comment]
Did either of you end up solving this issue?

**Comment by amritk** [comment]
@kateetrant I just downgraded ts-loader for now

**Comment by cinderblock** [comment]
@wtj199101 Can you edit your comment to add code blocks (```) around your code? It makes it *fantastically* more readable.

@amritk What version worked for you?
