### ISSUE TITLE
Support .riot files

### ISSUE THREAD

**Issue by GianlucaGuarini** [TypeStrong/ts-loader#1298]
### Expected Behaviour
Riot.js files should be processed by the `ts-loader` after they get loaded by the `@riotjs/webpack-loader` and transformed into plain typescript files.

### Actual Behaviour
Webpack receives raw typescript syntax throwing a syntax errors.
The `ts-loader` together with the `appendTsSuffixTo: [/\.riot/$/]` option enabled doesn't process `.riot` files

### Steps to Reproduce the Problem

- Download the simple example https://github.com/riot/examples/tree/feature/update-typescript-example/typescript
- Run `npm start`

### Location of a Minimal Repository that Demonstrates the Issue.

See above

Thank you for your help

**Comment by appzuka** [comment]
I cloned the repo above.  The error thrown is below:

```
random.riot.ts
Error 2322 : Type '{ Logs: RiotComponentShell<object, object>; }' is not assignable to type '{ [key: string]: RiotComponentShell<RandomComponentProps, RandomComponentState>; }'.
  Property 'Logs' is incompatible with index signature.
    Type 'RiotComponentShell<object, object>' is not assignable to type 'RiotComponentShell<RandomComponentProps, RandomComponentState>'.
      Property 'title' is missing in type '{}' but required in type 'RandomComponentProps'.
```
I don't know Riot but it seems to me that the file is being correctly processed by ts-loader but there is a type error.  If you change:
```
export interface RiotComponentShell<Props = object, State = object> {
```
to
```
export interface RiotComponentShell<Props = any, State = any> {
```
in this file:

https://github.com/riot/riot/blob/d886da18da2a77f5dc88cb7c5947955bae6112ab/riot.d.ts#L43

Then the project compiles without error.  Obviously this turns off some type checking but it seems to show that ts-loader and webpack are correctly processing the project and it is the types that need to be fixed.

**Comment by GianlucaGuarini** [comment]
@appzuka thank you for debugging it. This is really strange because I get with `npm start`:

```
ERROR in ./app/random/random.riot 4:17
Module parse failed: Unexpected token (4:17)
File was processed with these loaders:
 * ./node_modules/@riotjs/webpack-loader/dist/riot-webpack-loader.cjs.js
You may need an additional loader to handle the result of these loaders.
| import {RandomComponent} from './types'
|
> function Random(): RandomComponent {
|   return {
|     state: {
 @ ./app/main.ts 2:0-42 4:10-16
```

Node `v12.22.1`

Is there any other side effect that might affect the compiler?

**Comment by appzuka** [comment]
I am using node v14.16.1 Mac11.3 on an M1 Mac.  I just did yarn install and yarn start from the folder. I'll try again on an Ubuntu  and/or Windows system if I get the chance.

**Comment by GianlucaGuarini** [comment]
I have tried `yarn`, `node@14.16.1`, deleted the whole project and recloned with git... I get always the same syntax error. At this point I will try with docker to understand if the issue is on my machine

**Comment by appzuka** [comment]
Hi, I used your Dockerfile and then see the same error as you.  I went back to my Mac and realised I was using the default branch (gh-pages) instead of the feature/debug branch.  When I use your debug branch I see the same as you.

I have never used the <code>appendTsSuffixTo</code> option within ts-loader.  I understand this was added to allow *.vue files to be processed with ts-loader but now vue includes TypeScript it is no longer necessary.  I don't use Vue but recent examples don't seem to use this option.

I don't think including the option in the part of the webpack config that processes *.ts files will cause *.riot files to be post-processed with ts-loader.  If you want files to be processed by the riot loader and then ts-loader you need to include this in your webpack-config:

```
  module: {
    rules: [
      {
        test: /\.riot$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              appendTsSuffixTo: [/\.riot$/]
            }
          },
          {
            loader: '@riotjs/webpack-loader',
            options: {
              hot: true
            }
          },
        ]
      },
      {
        test: /\.ts$/,
        use: [{
          loader: 'ts-loader',
        }]
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  },
```

With this config the riot output is now processed by ts-loader.  ts-loader throws a lot of errors and warnings but these would need to be fixed within the riot output.

I hope this helps.

**Comment by GianlucaGuarini** [comment]
Yes thank you that worked. BTW `appendTsSuffixTo` is still the vue.js [recommended way to compile typescript components](https://v3.vuejs.org/guide/typescript-support.html#recommended-configuration)

Thank you for your help and have a nice day
