### ISSUE TITLE
Support for latest version of ts compiler

### ISSUE THREAD

**Issue by abhishekisnot** [TypeStrong/ts-loader#131]
It seems published package version of ts compiler is 1.7.x. Can the latest version be supported?

```
$ npm info typescript version
1.7.5
```

**Comment by jbrantly** [comment]
1.7.x is supported. I think the readme is just a little out of date. TS 1.6 *and above* is supported.

**Comment by raybooysen** [comment]
Works fine for me with all the 1.7.x releases

**Comment by jbrantly** [comment]
Updated README in f682178 to explicitly show support for 1.7. Closing.
