### ISSUE TITLE
Incorrect instance hash for different compiler options

### ISSUE THREAD

**Issue by timocov** [TypeStrong/ts-loader#1316]
Let's say you have 2 packages, and one of them you want to build with target=es5, another one with target=es6. If you set up ts-loader options to override compiler options (in loader options, not in tsconfig) it wont work properly.

There is a test https://github.com/TypeStrong/ts-loader/tree/main/test/execution-tests/loaderOptions for similar situation, but it doesn't cover this case. Let's say instead of overriding the only [`getCustomTransformers`](https://github.com/TypeStrong/ts-loader/blob/94480fbdf2db2c4060706ee8bf7d51294647f4da/test/execution-tests/loaderOptions/webpack.config.js#L25-L27) option you want to override something in `compilerOptions`. In this case [this code](https://github.com/TypeStrong/ts-loader/blob/94480fbdf2db2c4060706ee8bf7d51294647f4da/src/index.ts#L165]) will return `[object Object]` for both _different_ objects (different ref and a value itself) which causes the issue (also this code doesn't cover a case when a value is `false`, thus if a value is falsy but enabled by default it will also failed).

Not too sure about the fix here. I see different approaches to solve it:
1. Use `JSON.stringify` for non-functions and `value.toString()` otherwise
2. Allow to provide a `instanceKey` or something like that so people can declare their own cache key and refer to them in different places

Maybe you have thoughts how to solve it in better way. Let me know you what do you think. I'm ready to make a fix for this.

**Comment by timocov** [comment]
I just created a PR (draft at the moment) #1317 with potential fix of the issue including tests. I'm not sure about the fix itself, probably we need to traverse the tree if there is an object in options. What do you guys think?

**Comment by johnnyreilly** [comment]
> probably we need to traverse the tree if there is an object in options.

Perhaps - what would be the impact if you did not?

**Comment by timocov** [comment]
> what would be the impact if you did not?

I guess that it might be right now as well - the hash might be different for 2 the same objects (by value) but with different order of keys:

```js
{ transpileOnly: true, compilerOptions: {} }
// vs
{ compilerOptions: {}, transpileOnly: true }
```

**Comment by johnnyreilly** [comment]
Given this is a niche use case, a simple solution is probably preferable.

**Comment by johnnyreilly** [comment]
Thanks! https://github.com/TypeStrong/ts-loader/releases/tag/v9.2.0

**Comment by timocov** [comment]
@johnnyreilly thanks for merging it! Is it possible to provide a backport for v8? We're still on webpack@4 (we're working on migrating to v5, but it's hard).

**Comment by timocov** [comment]
https://github.com/TypeStrong/ts-loader/pull/1319
