### ISSUE TITLE
TypeScript compiler option "moduleResolution" is not inferred as it is by `tsc`

### ISSUE THREAD

**Issue by chbrown** [TypeStrong/ts-loader#132]
`tsc` will infer that `moduleResolution: "node"` if I have `module: "commonjs"` in my `tsconfig.json`, even if I also have `target: "ES6"` (it won't default to node-style moduleResolution if `module` is set to "es6" and target is also set to "ES6").

However, when compiling with `ts-loader` via webpack, I have to explicitly add `moduleResolution: "node"` to my tsconfig file to avoid "Cannot find module 'whatever'" errors in the output.

Adding that line, `"moduleResolution": "node"` is trivial. Figuring out that I need to add it, to resolve errors that webpack + ts-loader was throwing at me, was frustrating. I would expect ts-loader's (default) behavior to match tsc's (default) behavior, particularly when the ts-loader log message says it's using exactly the same tsconfig file that tsc is using.

**Comment by chbrown** [comment]
The versions I'm using, FWIW:

    ├── babel-core@5.8.34
    ├── babel-loader@5.4.0
    ├── ...
    ├── ts-loader@0.7.2
    ├── typescript@1.8.0-dev.20160105
    └── webpack@1.12.9

**Comment by jbrantly** [comment]
The goal is definitely for ts-loader to work the same as `tsc`. Do you have a simple file structure/example that you could provide which shows the issue? What does your import look like and where does the module reside?

**Comment by chbrown** [comment]
Not the _simplest_ example, but [here](https://github.com/chbrown/unicode-ui)'s what I was working on when I encountered this. And the steps to recreate (I just tested this like 5 minutes ago so if you don't hit the same issue then something weird is going on with my machine):

    git clone https://github.com/chbrown/unicode-ui.git
    cd unicode-ui
    npm install                                              # sorry, lots of dependencies
    node_modules/.bin/tsc                                    # works
    node_modules/.bin/webpack --config webpack.config.js     # works
    # edit tsconfig.json, remove this line: "moduleResolution": "node",
    node_modules/.bin/tsc                                    # works
    node_modules/.bin/webpack --config webpack.config.js     # doesn't work

webpack output with error:

    ts-loader: Using typescript@1.8.0-dev.20160108 and /tmp/unicode-ui/tsconfig.json
    Hash: d7efaf08b7986c362606
    Version: webpack 1.12.10
    Time: 5961ms
         Asset     Size  Chunks             Chunk Names
     bundle.js     1 MB       0  [emitted]  app
    unidata.js  2.35 MB       1  [emitted]  unidata
       [0] multi unidata 28 bytes {1} [built]
        + 223 hidden modules

    ERROR in ./app.tsx
    (10,58): error TS2307: Cannot find module 'unidata'.

`unidata` is another package of mine, installed via npm, pretty simple, but bulky — it just reformats the Unicode 8.0 character data into plain old JavaScript objects, and exposes them via an `index.js` file using the `index.d.ts` type definitions that are automatically recognized with TypeScript >= 1.6's handy "node"-style module resolution algorithm.

The import line in question in `app.tsx` is a run-of-the-mill ES6-style import:

    import {Block, getBlocks, Character, getCharacters} from 'unidata';

**Comment by jbrantly** [comment]
Perfect, thanks!

**Comment by jbrantly** [comment]
I believe this is related to #111. Basically TypeScript's logic is if `module: "commonjs"`, then `moduleResolution: "node"` is inferred (see [here](https://github.com/Microsoft/TypeScript/blob/26d0fd0bdb2280492c91df359ffedae3dcd5c3e2/src/compiler/program.ts#L40-L42)). However, ts-loader currently does some magic where if `target: "ES6"` is set then `module: "commonjs"` is ignored and `module: "none"` is used instead. This used to be desirable because otherwise TypeScript would throw an error. However, that is no longer the case, so I believe once #111 is fixed this will be as well.

**Comment by jbrantly** [comment]
This has been fixed and published in v0.8.0.
