### ISSUE TITLE
Changes to  a nested non-bundled file are not picked up by webpack --watch

### ISSUE THREAD

**Issue by geremih** [TypeStrong/ts-loader#1322]
### Expected Behaviour
- This only affects files that are not bundled by webpack (when `onlyCompileBundledFiles = false`), and when the file is nested in a directory
- On updating the file, the changes to the file should be picked up when recompilation is triggered.
- This issue does not affect files that are not nested in a directory.

### Actual Behaviour
- Changes to non-bundled files that are nested in a directory are not picked up by webpack.

### Steps to Reproduce the Problem
File structure:
```
- src
   - index.ts
   - dir
      - file.ts  
```
Repro steps:
- Export a variable from `index.ts`.
- Add a file to a dir `dir/file.ts` that imports the variable from `index.ts`
- Start `webpack --watch`
- Rename the variable in `index.ts`. The compilation starts failing and cannot be resolved by fixing `dir/file.ts`.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/geremih/ts-loader-repro

**Comment by appzuka** [comment]
Hi @geremih,

webpack watch will watch all files that the entry point (src/index.ts) depends on.  But dir/nestedFile.ts is not a dependency of src/index.ts, rather it depends on src/index.ts. If you export a variable from dir/nestedFile.ts and import in src/index.ts then you have created a dependency and it all works fine.

This minimal example is not realistic for a real project.  If you export a variable (nestedVar1) that is not used at all in src/index.ts or any of its dependencies there is no reason for webpack or ts-loader to rebuild sources that the entry point does not depend on.

Hope this helps.

**Comment by geremih** [comment]
@appzuka Thanks for the context. I hit this issue because webpack-watch started surfacing stale errors for files in `__tests__` (they won't be exported usually). I was able to  workaround this by enabling `onlyCompileBundledFiles`, but thought it might be worth having an issue in case it was not expected.
