### ISSUE TITLE
Limit webpack version in peerDependencies

### ISSUE THREAD

**Issue by afdev82** [TypeStrong/ts-loader#1323]
I think that the `webpack` version in the `peerDependencies` section of `package.json` should be restricted to only v5, since from v9 `ts-loader` is not compatible anymore with `webpack` v4.

https://github.com/TypeStrong/ts-loader/blob/613027f1cd6d5e68088d77617ce849d6d64aa479/package.json#L102

Or am I wrong?
I tried to update `ts-loader` while still using `webpack` v4 and `yarn` didn't complain, but I got the error in the console:

```
Module build failed: TypeError: loaderUtils.getOptions is not a function
```
And found the explanation in [this issue](#595)

**Comment by johnnyreilly** [comment]
Not a bad idea - fancy raising a PR?

**Comment by afdev82** [comment]
Yes, I will do it
