### ISSUE TITLE
Allow to optionally not include typing file for lib.d.ts/lib.es6.d.ts

### ISSUE THREAD

**Issue by wesleycho** [TypeStrong/ts-loader#133]
I have an interesting situation that [this behavior](https://github.com/TypeStrong/ts-loader/blob/master/index.ts#L278-L285) adds pain in when trying to use ts-loader instead of grunt-typescript - we use the es6-shim, but are compiling the TS down to ES5. This is so we can take advantage of some ES6 features such as `Object.assign` in browsers without robust ES6 support.

However, that block of code linked above is loading an undesired additional type file for the ES5 situation, when we really want to load the ES6 type file. I would like for there to be an option for overriding this behavior that can be easily used in Webpack.

**Comment by jbrantly** [comment]
I believe (feel free to correct me) that the current behavior mimics `tsc`. I would suggest in this case to use the `noLib` tsconfig option and then specify the definition file manually using the `files` array.

**Comment by wesleycho** [comment]
I didn't realize this was an option - looks like this did the trick, thanks a lot!
