### ISSUE TITLE
ts-loader and typescript plugins?

### ISSUE THREAD

**Issue by NickDarvey** [TypeStrong/ts-loader#1341]
### Expected Behaviour

ts-loader executes [typescript plugins](https://www.typescriptlang.org/tsconfig#plugins).

### Actual Behaviour

ts-loader does not execute typescript plugins.

### Steps to Reproduce the Problem

1. Clone [this repo](https://github.com/NickDarvey/typescript-svelte-plugin-with-ts-loader) 
2. Open the folder in VS Code
3. Install the folder's [recommended extensions](https://github.com/NickDarvey/typescript-svelte-plugin-with-ts-loader/blob/master/.vscode/extensions.json)
4. Restart VS Code (probably)
5. Open main.ts and note that [importing `MyProps`](https://github.com/NickDarvey/typescript-svelte-plugin-with-ts-loader/blob/0760d3cc8b2e5a3ebc4b2ea723318a6c9ca0f919/src/main.ts#L2) is valid because of the `typescript-svelte-plugin` and [an enabled setting](https://github.com/NickDarvey/typescript-svelte-plugin-with-ts-loader/blob/0760d3cc8b2e5a3ebc4b2ea723318a6c9ca0f919/.vscode/settings.json#L2). (Mentioned in https://github.com/sveltejs/language-tools/issues/580#issuecomment-832502069)
6. Run `npm run build` and note it fails even though [the plugin is configured](https://github.com/NickDarvey/typescript-svelte-plugin-with-ts-loader/blob/326cc5a1ed72863f8c3150cbb62e9ea2034d48b1/tsconfig.json#L9):
   ```
   [tsl] ERROR in C:\Users\nickd\source\repos\typescript-svelte-plugin-with-ts-loader\src\main.ts(2,15)
        TS2614: Module '"*.svelte"' has no exported member 'MyProps'. Did you mean to use 'import MyProps from "*.svelte"' instead?
   ```

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/NickDarvey/typescript-svelte-plugin-with-ts-loader

**Comment by johnnyreilly** [comment]
If I read this link right, it seems this is more for editors than for a build tool like webpack

> List of language service plugins to run inside the editor.
> 
> Language service plugins are a way to provide additional information to a user based on existing TypeScript files. They can enhance existing messages between TypeScript and an editor, or to provide their own error messages.

**Comment by NickDarvey** [comment]
It does sound like that. Perhaps I misunderstood the intent of the plugin and there's a different fix to the [original issue](https://github.com/sveltejs/svelte/issues/5817#issue-773790759) I ran in to.

https://github.com/sveltejs/language-tools/issues/580#issuecomment-870948531

**Comment by dummdidumm** [comment]
TypeScript maintainers explicitly state somewhere that plugins are for IDE only and are not executed when running TSC from the command line.

**Comment by NickDarvey** [comment]
Closing because this is not the intended use of the plugin anyway:
https://github.com/sveltejs/svelte/issues/5817#issuecomment-871128161
