### ISSUE TITLE
Top level await fails with Module parse error.

### ISSUE THREAD

**Issue by melink14** [TypeStrong/ts-loader#1342]
### Expected Behaviour
Top level awaits are supported by typescript and shouldn't give errors.

### Actual Behaviour
`Module parse failed: Cannot use keyword 'await' outside an async function`

### Steps to Reproduce the Problem
Create a typescript file with a top level await and compile with ts-loader.

### Location of a Minimal Repository that Demonstrates the Issue.
None for now but can make one later.

**Comment by appzuka** [comment]
This looks like a message from webpack rather than ts-loader.

The link below says that in order to use top level await in webpack you need to use the topLevelAwait experiment.

https://webpack.js.org/configuration/experiments/

I suggest you try this.

**Comment by melink14** [comment]
Thanks. That's a reasonable suggestion but I did already have the experiment enabled. (My fault for not giving more context)

It turns out that there was a regression in webpack 5.41.0 which broke top level await and is now fixed in 5.42.0. I had ruled out webpack since I had it working in other contexts but that assumption was misguided.

Thanks again!
