### ISSUE TITLE
Symlinked module causes TS6059 (...is not under 'rootDir')

### ISSUE THREAD

**Issue by bspot** [TypeStrong/ts-loader#1344]
### Expected Behaviour
Both vanilla webpack as well as tsc compile a project sucessfully when a module in `node_modules` is a symlink to somewhere else. Webpack + ts-loader should do the same.

### Actual Behaviour

Webpack + ts-loader fails with `TS6059: File ... is not under 'rootDir'` for the files in the symlinked module.

### Steps to Reproduce the Problem

```
git clone https://github.com/bspot/ts-loader-symlink-reproduction.git
cd ts-loader-symlink-reproduction/main
yarn install

# This works just fine
yarn run build-with-tsc 

# This also compiles
yarn run build-without-ts-loader

# This fails with the mentioned error
yarn run build-with-ts-loader
```

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/bspot/ts-loader-symlink-reproduction

**Comment by appzuka** [comment]
@bspot, Is there a reason you need to specify <code>rootDir</code>? From the TypeScript docs <code>rootDir</code> is only needed when tsc is compiling a project to set the structure of the output directory:

https://www.typescriptlang.org/tsconfig#rootDir

When using webpack the output directory structure irrelevant as the output is passed to webpack for bundling.  If you remove <code>rootDir</code> from your ts-config the problem goes away.

**Comment by michaeltford** [comment]
This is a problem for us as well. We need to set the rootDir because we have a monoRepo with multiple tsconfig.json so we have to set the rootDir to the root of the monoRepo.

**Comment by appzuka** [comment]
@michaeltford, ts-loader uses TypeScript to process the project and this error is coming from tsc. It should be possible for you to reorganise your repo to avoid this error but without seeing your repo it is hard to suggest a fix.
