### ISSUE TITLE
`experimentalWatchApi: true` creates a different bundle in `development` mode

### ISSUE THREAD

**Issue by thasmo** [TypeStrong/ts-loader#1347]
### Expected Behaviour
When setting `experimentalWatchApi: true` and running `webpack --mode development` all bundle files including assets should be created.

```
asset main.js 4.98 KiB [compared for emit] (name: main)
asset runtime.js 5.97 KiB [compared for emit] (name: runtime)
asset fonts/poppins-v15-latin-300.woff 10.3 KiB [compared for emit] [from: assets/base/fonts/poppins/poppins-v15-latin-300.woff] (auxiliary name: main)
asset manifest.json 310 bytes [compared for emit]
Entrypoint main 11 KiB (10.3 KiB) = runtime.js 5.97 KiB main.js 4.98 KiB 1 auxiliary asset
webpack compiled successfully (3aa7a73d8f3699ee8d2b)
```

### Actual Behaviour
When setting `experimentalWatchApi: true` and running `webpack --mode development` all asset files are missing and all `ts` files get compiled, rather than `ts` files declared via `entry` option only.

```
asset main.js 5.43 KiB [emitted] (name: main)
asset manifest.json 295 bytes [emitted]
asset runtime.js 6.32 KiB [emitted] (name: runtime)
asset vendor.js 27.7 KiB [emitted] (name: vendor) (id hint: vendor)
Entrypoint main 39.5 KiB = runtime.js 6.32 KiB vendor.js 27.7 KiB main.js 5.43 KiB
webpack compiled successfully (a3da70567b2228592541)
```

### Steps to Reproduce the Problem
Setting `experimentalWatchApi: true` versus setting `experimentalWatchApi: false`.

### main.js
```ts
import './fonts/poppins-v15-latin-300.woff';
```

node: `14.17.3`
webpack: `5.46.0`
ts-loader: `9.2.4`
ts-node: `10.1.0`
typescript: `4.3.5`

**Comment by appzuka** [comment]
I spent some time looking at <code>experimentalWatchApi</code> a while ago and came to the conclusion that it does not work and should probably be removed from ts-loader.  It is not included in the ts-loader documentation but unfortunately, some other guides suggest that using it might reduce development time.

I believe the solution here is to not use <code>experimentalWatchApi</code>.  Perhaps ts-loader should emit a warning if a user has selected the option.

**Comment by johnnyreilly** [comment]
> Perhaps ts-loader should emit a warning if a user has selected the option.

That's not a bad shout - feel free to add this if you fancy it
