### ISSUE TITLE
ts-loader breaks webpack serve due to loaderContext reuse

### ISSUE THREAD

**Issue by mahkoh** [TypeStrong/ts-loader#1348]
### Expected Behaviour

`webpack serve` works.

### Actual Behaviour

`webpack serve` is broken in projects that use `.vue` files with embedded typescript and plain `.ts` files.

### Steps to Reproduce the Problem

```
git clone git@github.com:mahkoh/ts-loader-bug.git
cd ts-loader-bug
npm install
npm run start
```

Wait until `Compiled successfully` appears. Then from another shell in the same directory:

```
touch src/b.ts
```

The following error message appears in the first shell:

```
✖ ｢wdm｣: Error: The loaded module contains errors
    at /home/julian/js/ts-loader-bug/node_modules/webpack/lib/dependencies/LoaderPlugin.js:110:11
    at /home/julian/js/ts-loader-bug/node_modules/webpack/lib/Compilation.js:1674:8
    at /home/julian/js/ts-loader-bug/node_modules/webpack/lib/util/AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (/home/julian/js/ts-loader-bug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._handleResult (/home/julian/js/ts-loader-bug/node_modules/webpack/lib/util/AsyncQueue.js:322:21)
    at /home/julian/js/ts-loader-bug/node_modules/webpack/lib/util/AsyncQueue.js:305:11
    at /home/julian/js/ts-loader-bug/node_modules/webpack/lib/Compilation.js:1346:15
    at /home/julian/js/ts-loader-bug/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/julian/js/ts-loader-bug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/home/julian/js/ts-loader-bug/node_modules/webpack/lib/Cache.js:107:20)
```

After this point, the `webpack serve` process appears to be unresponsive.

I've debugged the issue:

The original webpack.config.js contains a single rule involving ts-loader. In this rule, the loader chain is

```js
["ts-loader"]
```

That is, only the ts-loader is applied. This rule applies to `.ts(x)` files.

At runtime `VueLoaderPlugin` creates a second rule involving ts-loader. This rule has the loader chain

```js
["ts-loader", "vue-loader"]
```

That is, vue-loader is applied first and passes the result to ts-loader. This rule applies to `.vue` files containing embedded typescript. E.g. `a.vue` in the repository.

When ts-loader is invoked for the first time, it [creates](https://github.com/TypeStrong/ts-loader/blob/main/src/instances.ts#L33-L40) a cached "instance". The "instance" is only initialized [once](https://github.com/TypeStrong/ts-loader/blob/main/src/instances.ts#L335-L343). At this point, it stores the `webpack.LoaderContext` that was passed to the first invocation of ts-loader.

In particular, it uses this loader context to [create](https://github.com/TypeStrong/ts-loader/blob/main/src/watch-run.ts#L9-L15) a "watch runner". Whenever a file is changed, the watch runner will use this context to [recompile](https://github.com/TypeStrong/ts-loader/blob/main/src/watch-run.ts#L88-L91) the file.

In particular, it will use this loader context to recompile `b.ts` when it is `touch`ed.

Due to the layout of the repository, the first time ts-loader is invoked is in the context of compiling `a.vue`. Therefore, the loader context is associated with the loader chain

```js
["ts-loader", "vue-loader"]
```

This loader chain can only be used to compile `.vue` files since vue-loader expects the input to be in `.vue` file format. Most `.ts` files are not in `.vue` format.

Due to the logic [documented](https://github.com/TypeStrong/ts-loader/blob/main/src/watch-run.ts#L88-L91) in the `updateFile` function, ts-loader will try to compile `b.ts` by first applying vue-loader to it.

This fails, hence breaking the process.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/mahkoh/ts-loader-bug

**Comment by mahkoh** [comment]
Fundamentally I do not understand why ts-loader concerns itself with recompiling all files. Shouldn't this be the responsibility of the core `webpack serve` process?

I see that there is value in *watching* all files since ts-loader might want to recompile a.vue even if only its dependency b.ts changes. However, it should still leave the actual act of compiling these files to webpack. Instead it should only signal to webpack which files have to be recompiled, leaving it to webpack to find the correct rule to compile the file.

I do not know if webpack has an API to signal such things.

**Comment by johnnyreilly** [comment]
I'm not sure what a solution to this would look like I'm afraid. If you come up with any ideas then please do share.

**Comment by appzuka** [comment]
I don't use Vue so it would be hard to propose a solution.  From my understanding ts-loader needs to recompile all dependencies as that is how TypeScript works.  In order to confirm that a file has no syntax errors TypeScript needs to check all of its dependencies to check that types that are defined in other files make sense.  There are also some TypeScript features, like const enums, that require other files to be checked to ensure the syntax is correct.

If you are prepared to give up syntax checking and const enums you can use transpileOnly mode.  See the link below on isolated modules to see what you are giving up in this case:

https://www.typescriptlang.org/tsconfig#isolatedModules

If you are disabling syntax checking you probably need a solution for checking syntax in a separate thread.  Many people use fork-ts-checker-webpack-plugin but I don't know how this works with Vue.

**Comment by ttencate** [comment]
Is [this problem](https://stackoverflow.com/questions/70096520/why-does-webpack-watch-invoke-my-custom-loader-on-unrelated-files) also a symptom of the issue described here?

[Repro project](https://github.com/ttencate/webpack-loader-repro)
