### ISSUE TITLE
getCustomTransformers called with different program reference for some code paths

### ISSUE THREAD

**Issue by alex-dixon** [TypeStrong/ts-loader#1349]
When `transpileOnly` is true and `projectReferences` is undefined the `program` passed to `getCustomTransformers` appears to receive no source files:
https://github.com/TypeStrong/ts-loader/blob/1cfb77c38583811bb6d5bb143266d642e092809a/src/instances.ts#L378

`before` and `after` receive source files, possibly from a different program reference.

Setting the `transpileOnly` option to false yields a `program` that returns a nonempty array for `program.getSourceFiles()` (for the `program` reference passed to `getCustomTransformers`)

**Comment by johnnyreilly** [comment]
`transpileOnly` and `projectReferences` are not compatible together I believe. I think you're not using them together but I wanted to be explicit
