### ISSUE TITLE
Cannot Uglify Angular2 imports [RangeError: Maximum call stack size exceeded]

### ISSUE THREAD

**Issue by npx** [TypeStrong/ts-loader#135]
I have a very simple Angular2 app (just 1 app component that imports and displays a hello world directive).

Without the import 
```
import {HelloDirective} from './components/hello/hello-directive'
```
and just the AppComponent loading, uglification works.

However when I import my component, build it and uglify the webpack result the app breaks with the error:
```
RangeError: Maximum call stack size exceeded
```

I've been bashing my head for too long in finding the culprit in the uglification :)

Not mangleing the code keeps it working.

Not even sure if this is the right place to report this actually :/

**Comment by jbrantly** [comment]
Hard to say without a working example. My guess is that it's not related to ts-loader, but who knows? Are you using source maps? Does it work if you turn off sourcemaps?

**Comment by npx** [comment]
I fiddled around with it. Its definitely not here :) Thanks for your time

**Comment by jvincilione** [comment]
@npx Did you figure it out?

**Comment by npx** [comment]
@jvincilione yes, the problem lies with angular beta1 which cannot be mangled at the moment. So you can either not mangle the code for now and work with beta1 or mangle it on beta0 :)

**Comment by jvincilione** [comment]
@npx I'm acutely on the beta, so I guess I'm doing something wrong. I'm using gulp-uglify, if that matters

**Comment by npx** [comment]
So am I! It really is a bug in beta1 check the angular issues. A pull request has been made, too. Feel free to check out my skinny starter. I use gulp and webpack. 

I switched from gulp minification to webpack as both use uglify but it didnt make a difference. Feel free to copy my setup if it works for you :)

Sent from mobile

**Comment by jvincilione** [comment]
Thanks, I'll look into it!
