### ISSUE TITLE
What happened to the `thread-loader` example?

### ISSUE THREAD

**Issue by elliotwaite** [TypeStrong/ts-loader#1355]
The README mentions "[our simple thread-loader example](https://github.com/TypeStrong/ts-loader/blob/main/examples/thread-loader)", but the link points to a 404 page. Was there a reason that the `thread-loader` example was removed? Is it no longer recommended to use `ts-loader` with `thread-loader`? 

I saw on the Webpack [Build Performance](https://webpack.js.org/guides/build-performance/) page that it recommends using `ts-loader` in `happyPackMode: true`. Is this recommendation outdated?

**Comment by johnnyreilly** [comment]
We should remove that reference - thread loader and happypack are not recommended anymore.

**Comment by elliotwaite** [comment]
Got it. Thanks for the quick reply.
