### ISSUE TITLE
Devtool example strategies 'cheap-module-eval-source-map' sequence of string is wrong

### ISSUE THREAD

**Issue by 1574242600** [TypeStrong/ts-loader#1362]
https://webpack.js.org/configuration/devtool/
> We expect a certain pattern when validate devtool name, pay attention and dont mix up the sequence of devtool string. The pattern is: `[inline-|hidden-|eval-][nosources-][cheap-[module-]]source-map`.

I don't know if this rule has existed before. 
But using it now makes webpack throw "Invalid configuration object".

**Comment by johnnyreilly** [comment]
PRs gratefully accepted!

**Comment by 1574242600** [comment]
thx
