### ISSUE TITLE
Cannot find module ..../ts-loader/index.js

### ISSUE THREAD

**Issue by phibersoft** [TypeStrong/ts-loader#1366]
### Story
When my project I was working on gave this error, I started researching. I thought the question was about me and started testing the official examples. In these tests, I saw that I got the same error. The problem is not on my computer because when I explained the situation for him to test, my friend showed that he got the same error.

### Expected Behaviour
Builds simple app.

### Actual Behaviour
Throws error : 
![image](https://user-images.githubusercontent.com/54160817/131238674-e2629afe-9ced-40c4-ae05-172bd520ee1e.png)

### Steps to Reproduce the Problem
 - Clone this official example: https://github.com/TypeStrong/ts-loader/blob/main/examples/vanilla/package.json
 - Install dependencies
 - Run "npm run build" // Throws error
 - Upgrade dependencies to latest versions
 - Run "npm run build" // Throws error again

**Comment by johnnyreilly** [comment]
Oh I think this got broken during the ts-loader V8 to 9 migration. Rest assured ts-loader is fine - it's just the example that isn't. I'll fix when I get a moment

**Comment by phibersoft** [comment]
Hello, thank you for your help. So, can I investigate and resolve this situation? Can you show me a way?

**Comment by johnnyreilly** [comment]
Sorry - I'm on holiday at present

**Comment by phibersoft** [comment]
### Update
Webpack build working success with this versions:
![image](https://user-images.githubusercontent.com/54160817/131258931-db278540-14be-421a-9b0c-13f150ff10e6.png)
 
### Notes
webpack-cli & typescript can be updated latest versions. Problem about "webpack" and "ts-loader" packages.

#### Updating ts-loader to latest version (Currently: 9.2.5)
Throws error "loaderContext.getOptions is not a function"

#### Updating webpack to  5+ Version
Throws error "Cannot find module .../ts-loader/index.js"

**Comment by appzuka** [comment]
@phibersoft,

I tried the example with both ts-loader@9.0.0 and ts-loader@9.2.5 and it builds fine.  Then I noticed that you have a '#' in your path. If I rename my directory to start with a '#' I see the same error as you.  If you remove the '#' from the filename it should build.

**Comment by cinderblock** [comment]
@appzuka Shouldn't having a `#` in the path be allowed?

**Comment by appzuka** [comment]
As <code>#</code> is a valid character it should be allowed, or at least noted in the documentation that it is not allowed.  It seems that it was allowed in ts-loader@8.  I don't have time today to look into this further but hopefully this information lets you proceed while this is investigated and will help somebody to understand what changed in ts-loader@9.

The ts-loader source is very readable so you could have take a look yourself although I wonder whether the issue might be in webpack or one of the other dependencies that changed when moving to webpack@5.

**Comment by johnnyreilly** [comment]
My money is on this being a webpack 5 change; though I could be wrong - I wonder if @sokra can advise?

**Comment by phibersoft** [comment]
> @phibersoft,
> 
> I tried the example with both ts-loader@9.0.0 and ts-loader@9.2.5 and it builds fine. Then I noticed that you have a '#' in your path. If I rename my directory to start with a '#' I see the same error as you. If you remove the '#' from the filename it should build.

This advice worked, thank you. I will close the issue. Should I open this issue as an issue on webpack's github?

![image](https://user-images.githubusercontent.com/54160817/131371082-3bc60891-d62e-44e9-a32a-6cf1ea10ce77.png)

**Comment by johnnyreilly** [comment]
I think so, yes

**Comment by alexander-akait** [comment]
@johnnyreilly Can be closed due https://github.com/webpack/webpack/issues/14755

**Comment by johnnyreilly** [comment]
Thanks @alexander-akait !
