### ISSUE TITLE
Dynamic imports with a dynamic list of files

### ISSUE THREAD

**Issue by DAmNRelentless** [TypeStrong/ts-loader#1373]
### Expected Behaviour
Files which are dynamically imported from a dynamic list of names should be resolved properly.

### Actual Behaviour
It can't find the files.

### Steps to Reproduce the Problem
1. Have a directory with files which should be loaded dynamically like commands for a bot
2. Get the file list with the `readdirSync()` function.
3. Dynamically import all of these files with a dynamic import.
4. Modules can't be found.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/RLNT/twitch_rlnt-bot/blob/40960348ae141fb343933af0051c439cdbecd38a/src/internals/commandhandler.ts#L44-L59

If this is a webpack thing, let me know.
As you can see in the repository, my current workaround is to hardcode the names of the commands which works fine.
The `require()` call seems to work as intended if the provided file name is already known at compile-time. Since webpack bundles the whole source to a single file, I guess all of the files which are called with `require()` are written to that single output file as well and can be resolved.
But if you use `readdirSync()`, webpack is unable to resolve the path and can't load the file any longer because the list of file names is not known yet.
Since I am compiling my project to an executable, I don't have any files in that directory anymore and a list can't be generated.
I am asking if it's possible to load my command files dynamically with this approach or if it's not possible due to the behaviour of `readdirSync()`.

**Comment by johnnyreilly** [comment]
I think "it's a webpack thing". That said, I suspect that using `require.context` may give you what you need. See this post for an example:

https://blog.johnnyreilly.com/2021/05/01/blog-archive-for-docusaurus#obtaining-the-blog-data

**Comment by DAmNRelentless** [comment]
That looks promising but is it available when you are building an app for Node?

**Comment by DAmNRelentless** [comment]
That worked flawlessly, thanks for the tip and the fast response!
