### ISSUE TITLE
[Compilation failed]: vue2.x render return jsx 

### ISSUE THREAD

**Issue by victorykong** [TypeStrong/ts-loader#1378]
### Expected Behaviour

Parse jsx normally.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/50655436/134657845-6ae668c7-b13c-41f4-9163-2edd703b43a4.png)

### Steps to Reproduce the Problem

```
// tsconfig.json
  {
      "exclude": ["node_modules"],
      "compilerOptions": {
          "rootDir": ".",
          "target": "esnext",
          "module": "esnext",
          "strict": true,
          "noImplicitAny": false,
          "moduleResolution": "node",
          "jsx": "preserve",
          "allowJs": true,
          "baseUrl": ".",
          "paths": {
              "@/*": ["./src/*"],
              "common/*": ["./src/common/*"],
              "service/*": ["./src/service/*"],
              "@@/*": ["./src-new/*"]
          },
          "jsxFactory": "h"
      }
  }

```

```
// package.json
"webpack": "^4.46.0",
"ts-loader": "^8.3.0",
"typescript": "^4.4.3",
"vue": "2.5.17",
```

### Location of a Minimal Repository that Demonstrates the Issue.
Looking forward to your reply!

**Comment by appzuka** [comment]
@victorykong,

I am not a Vue user but many people use Vue with ts-loader without issue.  There are examples of Vue+ts-loader in the Vue documentation.  I suggest that you load a simple example and check where your setup is different.

**Comment by victorykong** [comment]
@appzuka I hope to guide the relevant demo. In the document of vue2, my configuration is completely consistent.

https://cn.vuejs.org/v2/guide/typescript.html

**Comment by appzuka** [comment]
@victorykong,  I don't use Vue but I suggest you look for some recent boilerplate vue+typescript repositories.  One is below (I have not tried this myself):

https://github.com/Jamie-Yang/vue3-boilerplate

The error you pasted indicates that you do not have a webpack loader that can parse JSX in files.  Check the Vue documentation for the web pack configuration for typescript support:

https://v3.vuejs.org/guide/typescript-support.html#webpack-configuration

I suggest that you reach out to the Vue community for support.
