### ISSUE TITLE
the ts.getStart ,ts.getEnd doesnot return the right position

### ISSUE THREAD

**Issue by x3hong** [TypeStrong/ts-loader#1379]
### Expected Behaviour
i am  writing a custom typescript transform, but this getstart getend returned postion  is not right。
how can i get the right position return the right position in the code
### Actual Behaviour
not
### Steps to Reproduce the Problem
[ast](https://astexplorer.net/#/gist/7c82091002c3ea7b1c7ceda60feb0a4a/8de47cfe928feb992b1831f42871c9788dbca2a7)

**Comment by appzuka** [comment]
@x3hong, your question does not seem to be related to ts-loader.  It looks as if you are trying to understand typescript transforms. ts-loader is a webpack loader that allows you to use TypeScript in webpack.

**Comment by x3hong** [comment]
> @x3hong, your question does not seem to be related to ts-loader. It looks as if you are trying to understand typescript transforms. ts-loader is a webpack loader that allows you to use TypeScript in webpack.

ok  3q  ,so i will go to the typescript to reopen a issue
