### ISSUE TITLE
ts-loader loads the wrong file when used in conjunction with a custom loader

### ISSUE THREAD

**Issue by volkanunsal** [TypeStrong/ts-loader#1385]
### Search Terms

"ts-loader multiple loaders wrong output"

### Expected Behavior

I'm using Webpack 5. Given I have a loader like this:

```js
{
  test: /\.feature$/i,
  use: [
    { loader: 'ts-loader', options: {} },
    { loader: path.resolve(__dirname, './loaders/GherkinLoader') },
  ],
  exclude: ['/node_modules/'],
}
```

Where `GherkinLoader` is a custom loader that ingests files with `.feature` extension and outputs a Typescript file like this:

```ts
import { cucumber } from "stucumber/dist/cucumber";
import promiseFinally from 'promise.prototype.finally';
const _cucumber = cucumber.clone();

export default async function Features(obj) {

  // Feature: To search Puppeteer in google
  const feature = {"name":"To search Puppeteer in google","annotations":[],"meta":{}, "filename": "NOT_SUPPORTED"};
  await Promise.all([

  ]);
  await _cucumber.enterFeature(feature);
  await Promise.all([
    () => {
      // Puppeteer Google Search
      const world = _cucumber.createWorld();
      const scenario = {"name":"Puppeteer Google Search","annotations":[{"name":"ProtractorScenario","arguments":[]}],"meta":{}, "feature": feature, "steps": [{"name":"I am on \"Google\" search page","line":5,"keyword":"Given"},{"name":"I clear the search text","line":6,"keyword":"Then"},{"name":"I type \"puppeteer chrome\"","line":7,"keyword":"When"},{"name":"I click on search button","line":8,"keyword":"When"},{"name":"I clear the search text","line":9,"keyword":"Then"}]};

      const chain = _cucumber.enterScenario(world, scenario)
        .then(() => {
          _cucumber.rule(world, "I am on \"Google\" search page", null, "")
        })
				.then(() => {
          _cucumber.rule(world, "I clear the search text", null, "")
        })
				.then(() => {
          _cucumber.rule(world, "I type \"puppeteer chrome\"", null, "")
        })
				.then(() => {
          _cucumber.rule(world, "I click on search button", null, "")
        })
				.then(() => {
          _cucumber.rule(world, "I clear the search text", null, "")
        });

      return promiseFinally(chain, () => {
        _cucumber.exitScenario(world, scenario)
      });
  }.map(v => v())
  ]);
  await _cucumber.exitFeature(feature);
    }
}
```

I expect the output bundle to contain a compiled version of that file.

### Actual Behavior

In the bundle, I get an unrelated file that is not even imported from the output code. And I also get a bunch of import resolution errors from files I also didn't import:

```
Module not found: Error: Can't resolve '../actions/pressEnter' in '/Volumes/workplace/project/src/features'
```

### Steps to reproduce the problem

1. Check out the repo (https://github.com/volkanunsal/cuke-pup)
2. Install the dependencies
3. Type `make canaries`

### Minimal reproduction

https://github.com/volkanunsal/cuke-pup

**Comment by appzuka** [comment]
@volkanunsal,

I took a look at your repo and have a couple of comments.

You say that GherkinLoader outputs a TypeScript file but this does not seem to be TypeScript - it is plain JavaScript.  Therefore you don't need to pass it through ts-loader after GherkinLoader:

```
      {
        test: /\.feature$/i,
        use: [
          { loader: path.resolve(__dirname, './loaders/GherkinLoader') },
        ],
        exclude: ['/node_modules/'],
      },
```

The output is not quite valid JavaScript (or TypeScript).  To make it valid JavaScript you need to change:

```
  }.map(v => v())
  ]);
  await _cucumber.exitFeature(feature);
    }
}
```

to

```
  }
  ]);
  await _cucumber.exitFeature(feature);
    
}
```

With these changes your project make succeeds.  I can't say whether it still does what you intended but at least the code is valid.

Passing valid JavaScript through ts-loader should still output valid JavaScript, but the TypeScript file resolution is different from webpack file resolution and I suspect this is the cause of the errors you see. See the link below for details of how TypeScript resolves modules:

https://www.typescriptlang.org/docs/handbook/module-resolution.html

Hope this helps.

**Comment by volkanunsal** [comment]
Thanks @appzuka
