### ISSUE TITLE
Cannot create single JS file from all TS files

### ISSUE THREAD

**Issue by mofirouz** [TypeStrong/ts-loader#139]
Hi there,

I'm developing an ES6 Library with no external deps. I have multiple TS files all within one module name in one folder and I'm trying to compile all and concat into just one output JS file. This is my setup:

> webpack.config.js

```js
var webpack = require('webpack');

module.exports = [
{
  entry: './lib/lib.ts',
  output: {
    path: './dist/',
    filename: 'lib-sdk.js',
    library: '[name]',
    libraryTarget: 'var'
  },
  resolve: {
    extensions: ['', '.ts', '.tsx', '.js']
  },
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'ts-loader' }
    ]
  },
  devtool: 'source-map'
}]
```
> tsconfig.json

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
>./lib/lib.ts

```ts
/// <reference path="ping.ts" />
 module Lib {
}
```

>./lib/ping.ts

```ts
module Lib {
}
```

I would like the output `./dist/lib-sdk.js` file to contain the concat of all the files in the `./lib` folder. Is this something that I can do?

Thanks.

**Comment by jbrantly** [comment]
Yes and no. When you say `module Lib` you're trying to create what's called an internal module or namespace in TypeScript. That is the old way of writing JavaScript. The new way is creating self-contained modules, meaning each module can import other modules but a module can't be split across multiple files. However, modules can re-export their imports. For example, you could do something like.

```typescript
// lib.ts
export { ping } from './ping';

// ping.ts
export function ping() { }
```

So in the above, all of the code for the ping function is in ping.ts, but lib.ts also has a ping function (which it just reexports from the ping module).

**Comment by jbrantly** [comment]
BTW, I would highly recommend reading some resources on ES6 modules like http://www.2ality.com/2014/09/es6-modules-final.html and whatever else you can google :smile:

**Comment by mofirouz** [comment]
Thanks for the elaborate answer. I'll test it out and will reply back. Feel free to close this ticket for the time being.
