### ISSUE TITLE
Project References with different baseUrls

### ISSUE THREAD

**Issue by kberridge** [TypeStrong/ts-loader#1391]
### Issue
With project references that have tsconfig files with different baseUrls (relative to each project), `tsc --build` works, but webpack/ts-loader will fail with "module has no exported member" errors because it is looking in the wrong project for the import.

### Steps to Reproduce the Problem
- src project's tsconfig sets baseUrl to ".", which is ".\src"
- shared project's tsconfig ALSO sets baseUrl to ".", which is for example ".\packages\zoo"
- NOTE: for both of these, baseUrl is set in the tsconfig itself, not the inherited config which is in the root where "." means ".\" not ".\src" for example.
- src and zoo both have a module with the same name like "Components\ex" and they import that with a non-relative path like `import { whatever } from "Components\ex";` 

In this state, tsc respects the baseUrl and successfully resolves those non-relative paths in each project.  But in webpack/ts-loader, that doesn't work, so zoo ends up looking in src for that import!

I don't know if this is a bug or unsupported feature, or if there is some way to configure webpack to support this, or if this is just not possible?  If I understand it correctly, paths like this are usually configured in webpack via `{ resolve: modules: [] }`, but in this case that list needs to be different depending on what project is being compiled.

In researching this I've come across the https://github.com/Heniker/webpack-file-alias plugin, and I did also have an issue with conflicting "paths" in different projects, but since that plugin is about managing aliases I don't think it can handle this.  That project does mention using "@" as an alias for root, but we're not doing that in our code base ;)  

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/kberridge/ts-loader/tree/baseurl-issue-example
This is a fork of ts-loader with the project-references-example modified to mimic my setup and demonstrate the issue.

If you run `npx tsc --build` in the root (or in src) it will compile.  If you run `npm run build` is will fail with this error:
```
ERROR in C:\projects\ts-loader\examples\project-references-example\packages\zoo\zoo.tsx
./packages/zoo/zoo.tsx
[tsl] ERROR in C:\projects\ts-loader\examples\project-references-example\packages\zoo\zoo.tsx(3,10)
      TS2305: Module '"../../src/Components/ex"' has no exported member 'zooExample'.

ERROR in C:\projects\ts-loader\examples\project-references-example\packages\zoo\zoo.tsx
./packages/zoo/zoo.tsx
```
There are other errors too, but I think the other errors are a consequence of this error.

I would appreciate any guidance on if it is possible to support this, and if not if there are any project/import setup conventions or approaches that I should be looking into instead.

**Comment by appzuka** [comment]
@kberridge,

Webpack and TypeScript use different module resolution strategies so it is possible that there can be a difference between tsc and ts-loader.

Is there a reason you can't use a relative import?  You are importing a file from within the same project so a relative import feels right.

**Comment by kberridge** [comment]
A reason why I can't?  Hehe, well no, I suppose not.  It was just the convention we've been using in this rather large project to NOT use relative imports except for basically child or sibling modules.  We found it much easier to read rooted imports than ../../.. etc.  And since we now have LOTS of those, converting them would be a pretty significant project.  Enough that it would probably be a blocker to using project references.

Thanks for the reply though!
