### ISSUE TITLE
just use ts-loader to emit .d.ts file without type checking in webpack

### ISSUE THREAD

**Issue by SilentSword69** [TypeStrong/ts-loader#1392]
same problem with https://stackoverflow.com/questions/66589942/using-ts-loader-to-run-emitdeclarationonly

my webpack config

if i set transpile to false, then not emitting declaration files.
if i set emitDeclarationOnly to true, babel-loader will emit error.

`{
  target: ['node'],
  entry: {
    main: {
      import: './src/index',
      filename: 'index.js',
      library: {
        type: 'commonjs',
      },
    },
  },
  output: {
    path: resolve('dist'),
  },
  resolve: {
    modules: ['node_modules'],
    extensions: ['.ts', '.js', '.cjs', '.mjs'],
    alias: {},
  },
  optimization: {
    minimize: false,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          parse: {
            // 解析最新的代码
            ecma: 2020,
          },
          compress: {
            ecma: 5,
            comparisons: false,
            inline: 2,
            drop_console: true,
          },
          mangle: {
            safari10: true,
          },
          // TODO lyw
          // Added for profiling in devtools
          // keep_classnames: isProductionProfile,
          // keep_fnames: isProductionProfile,
          format: {
            ecma: 5,
            comments: /(@preserve|@license|webpackIgnore|^!)/,
            ascii_only: true,
          },
          sourceMap: false,
        },
        // 不生成 LICENSE.TXT 文件
        extractComments: false,
      }),
    ],
  },
  module: {
    parser: {
      javascript: {
        commonjsMagicComments: true,
      },
    },
    rules: [
      {
        oneOf: [
          {
            test: /\.ts/,
            include: [resolve('src')],
            use: [
              {
                loader: 'babel-loader',
                options: {
                  babelrc: false,
                  configFile: false,
                  compact: false,
                  presets: ['@babel/preset-env'],
                  cacheDirectory: true,
                  cacheCompression: false,
                  shouldPrintComment: (val) =>
                    /@license|@preserve|webpackIgnore/.test(val),
                },
              },
              {
                loader: 'ts-loader',
                options: {
                  compilerOptions: {
                    noEmit: false,
                    outDir: 'dist',
                    declaration: true,
                    removeComments: false,
                  },
                },
              },
            ],
          },
          {
            test: /\.(js|cjs|mjs)/,
            exclude: [resolve('src')],
            use: [
              {
                loader: 'babel-loader',
                options: {
                  babelrc: false,
                  configFile: false,
                  compact: false,
                  presets: ['@babel/preset-env'],
                  cacheDirectory: true,
                  cacheCompression: false,
                  shouldPrintComment: (val) =>
                    /@license|@preserve|webpackIgnore/.test(val),
                },
              },
            ],
          },
        ],
      },
    ],
  },
  externals: [
    NodeExternals(),
    NodeExternals({ modulesDir: resolve('../../node_modules') }),
  ],
}`

### Expected Behaviour

only emit .d.ts files without type checking

### Actual Behaviour

emit .d.ts files with type checking

**Comment by appzuka** [comment]
@SilentSword69, I'm not sure why you would want to use babel-loader to transpire Typescript into JavaScript.  Why don't you just use ts-loader?

I don't think any webpack loader can function the way you expect.  Webpack expects the loader to output the transpiled code so if you tell it not to then webpack will complain.

**Comment by zyf0330** [comment]
Because I use swc-loader to compile code, and swc doesn't support emit .d.ts, so I need use ts-loader to emit and utilize ts-loader custom transformer feature.
