### ISSUE TITLE
treeshake not work with re-export

### ISSUE THREAD

**Issue by keyiis** [TypeStrong/ts-loader#1394]
I used webpack with ts-load to package my app to a file,I used `mode: 'production'` to enable tree shake,although I didn't use the `function b()` in server.ts, the bundle still contains `function b()`
My directory structure
```
src
    tool
           a.ts
           b.ts
           index.ts
    server.ts
```
**a.ts**
```
function a(){
....
}
export {a};
```
**b.ts**
```
function b(){
....
}
export {b};
```
**index.ts**
```
export * from './a';
export * from './b';
```
**server.ts**
```
import {a} from './tool';
a();
```
**webpack**
```
mode: 'production',
module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    use: require.resolve('ts-loader'),
                    exclude: /node_modules/,
                },
            ],
}
```

**Comment by appzuka** [comment]
@keyiis, Is this an issue with webpack or ts-loader?  If you create a minimal example with JavaScript files does it do the same?

**Comment by keyiis** [comment]
@appzuka At present, I'm not sure what caused it,But after I did the following operations, the bundle file only contains `function a()`.
step 1: delete index.ts
step 2: change server.ts
```
//import {a} from './tool';
import {a} from './tool/a';
a();
```
my envirment
```
webpack@4.46.0
ts-loader@8.3.0
typescript@4.2.4
```
