### ISSUE TITLE
Usage outside Webpack?

### ISSUE THREAD

**Issue by hydrotik** [TypeStrong/ts-loader#144]
Might be a dumb question... but I'm contemplating creating something to load react views for express/hapi in Typescript. Similar to this:

https://github.com/duereg/express-coffee-react-views/blob/master/index.js

Wondering if you have any thoughts on using something like a loader to transpile as a solution for this? I ran into some issues trying this with the basic transpile() command, but it might be around the export throwing off the dom render server which I plan to look into again.

**Comment by jbrantly** [comment]
This seems like it's outside of the scope of this project.

I would maybe check out https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function
