### ISSUE TITLE
Error when using TSC plugin that adds a custom property `hooks` to tsconfig. `hooks` not present in `validLoaderOptions`

### ISSUE THREAD

**Issue by flyon** [TypeStrong/ts-loader#1456]
I would love to use [this tsc-hooks plugin](https://github.com/swimauger/tsc-hooks) to copy over json files to my output (lib) folder.

However I get this error when running webpack
```
Please take a look at the options you are supplying; the following are valid options: ...
```
and I see that `hooks` is not in the fixed list of `validLoaderOptions` in index.js

My tsconfig:
```
{
	"compilerOptions": {
            //...
	},
	"files": ["./src/index.tsx"],
       "hooks": ["copy-files"]
}
```

Is it possible to use this plugin with the current ts-loader? Would a pull request to add 'hooks' to validLoaderOptions be reasonable?

**Comment by johnnyreilly** [comment]
It's probably a better idea to use webpack loaders / plugins to achieve your goal - I'm not sure tsc-hooks would fit with ts-loader well given the architecture

**Comment by flyon** [comment]
thanks, fair point. will do.
