### ISSUE TITLE
Module not found for TypeScript 4.7

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-loader#1463]
### Expected Behaviour

Able to bundle.

### Actual Behaviour

errors such as:

```sh
Module not found: Error: Can't resolve './tersible.js'
```

### Steps to Reproduce the Problem

In TypeScript 4.7, the `NodeNext` module resolution requires the source code to specify the extension as `.js`.
e.g.:

```ts
// index.ts
export * from './tersible.js' // for `tersible.ts`
```

For `ts-jest` on the `jest` side,
it solves that by doing a transformation:

```js
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
```

Maybe something similar is needed?
Would be great to add a section in the readme specifically for that.

### Location of a Minimal Repository that Demonstrates the Issue.

Not a minimal repo, but here is an example: https://github.com/unional/tersify.
Run `yarn bundle` in the repo

🌷

**Comment by johnnyreilly** [comment]
It's possible that ts-loader doesn't support ECMAScript modules for importing with extensions as you are attempting. Certainly no work has been done to actively support this.

We're open to this support being added, though it's not clear at the moment where work would be required. Some questions:

- are changes required to webpack? If so is anyone looking at this?
- are changes required to ts-loader? If so, what's the nature of the required change? I wonder if @cspotcode might have some insight on this given his work on ts-node. See also: 
https://github.com/TypeStrong/ts-node/pull/1727
https://github.com/TypeStrong/ts-node/pull/1694
https://github.com/TypeStrong/ts-node/pull/1757
https://github.com/TypeStrong/ts-node/issues/1778

If someone would like to start work on this, we'll happily take a look and collaborate on PRs ❤️🌻

**Comment by unional** [comment]
> are changes required to ts-loader? If so, what's the nature of the required change?
Although the workaround is done at the webpack config's `plugins`, I think it should be handled by `ts-loader`, as it would be very cumbersome to instruct user to use `ts-loader` AND do that workaround.

**Comment by unional** [comment]
Just in case I have tested older code of that repo. It does look like the `exports not defined` issue is related to the new stuff.

**Comment by cspotcode** [comment]
Roughly the three major bits of NodeNext / mts / cts support in ts-node were:

---

Replace node's resolver with one that checks what I call "alternative file extensions."  Every time node's resolver would check for `foo.js`, also check for the alternatives: `foo.ts`, `foo.tsx`, `foo.jsx`

---

Teach transpiler codepaths to emit Typescript's 2x new flavors of module:
- nodenext-flavored CommonJs, like commonjs emit except that now dynamic imports are preserved
- nodenext-flavored ESM, like EsNext emit except that now `import foo = require('foo')` statements automatically use `createRequire` to gin up a `require` function

`ts.transpileModule` does not expose this functionality; cannot be used

---

Teach transpiler codepaths to classify files as either CJS or ESM using the same rules as NodeNext
- So, use file extension and contextual package.json to decide which of the 2x flavors to emit
- TypeScript relies on its own resolver to do this classification; transpile-only codepaths need to reimplement it

**Comment by unional** [comment]
FYI here is one issue that I found related to source map:
https://github.com/microsoft/TypeScript/issues/49335

**Comment by unional** [comment]
```js
new NormalModuleReplacementPlugin(/.js$/, (resource) => {
      if (/node_modules/.test(resource.context)) return
      resource.request = resource.request.replace(/.js$/, '')
    })
```

I found that the workaround needs to be adjust to this so that it will not remove the `.js` in external deps.
Of course, the `node_modules` is really a work around and doesn't work in other cases (e.g. yarn 2)

**Comment by unional** [comment]
@johnnyreilly I notice running `yarn test` causes the `yarn.lock` updated.
Is there a particular version of `yarn` this repo is using? I have 1.22.15.

Maybe first have a PR to pin the yarn version by using `packageManager` (`corepack`)?

**Comment by unional** [comment]
https://github.com/microsoft/TypeScript/issues/49340

Related issue. Maybe when that is available, `ts-loader` can use it to resolve the module name instead of coming up with a custom implementation.

**Comment by johnnyreilly** [comment]
The pnpm test is very out of date - I wouldn't worry particularly about it; it needs refreshing anyway. It's surfaced misleading results in the past as well. It's on my list to do something about.

The error message is familiar - I think it came up recently but I can't remember the details. 

> loading or preprocessing
TypeError: Cannot read properties of undefined (reading 'split')

As to the yarn version; we use v1 but not a specific version. Not a problem if it's updated.

Apologies if I only reply occasionally - I'm on holiday

**Comment by unional** [comment]
> Apologies if I only reply occasionally - I'm on holiday
NP. That explains all those nice pics. 🌷

**Comment by unional** [comment]
https://github.com/microsoft/TypeScript/issues/49083

Cross ref

**Comment by johnnyreilly** [comment]
I'm back home now @unional - is everything going okay on this? Are you blocked on anything?

**Comment by unional** [comment]
Hi there. I was trying to do a clean run of tests but there is a test failure. Wanted to have a clean start. At the moment I was making some changes to one of my projects as my office work needs it. Was planning to get on this after that. 

As for the approach, I saw 4.7.3 have the resolve function exposed for `ts-node`. My guess is if `ts-loader` can use the same function, that would the the way to go.

**Comment by johnnyreilly** [comment]
Sounds good - when you get to it, feel free to stick up a work in progress PR with broken tests if needs be. Will be happy to pair on this

**Comment by unional** [comment]
Have a question about the test system. Is there any reason why it is so slow? Is it because of using karma? (Haven't use karma for ages. 😛 ).

If there are things can be done to improve on that (e.g. migrate to `jest` or use some other tools), I might able to help too. :)

This is obvious off-topic to this OP. So if you are interested, we can kick off a discussion about it. 🌷

**Comment by unional** [comment]
When running the tests in Windows environment, I got this error:

```sh
START:
Webpack bundling...
Error: EINVAL: invalid argument, mkdir 'C:\Users\homa\AppData\Local\Temp\_karma_webpack_583487\D:\code\others\ts-loader\test\execution-tests\3.6.0_projectReferencesToBeBuilt\lib'
```

Seems like the test setup doesn't work in Windows.

**Comment by johnnyreilly** [comment]
So there's two test systems; both quite old. The execution tests which run TypeScript tests using Karma and validate if transplantation is working successfully. And comparison tests which are effectively equivalent to Jest snapshot tests. @g-plane tried to do this but we couldn't get it to work on windows - see discussion here:

https://github.com/TypeStrong/ts-loader/pull/1161

**Comment by unional** [comment]
I see. I can take a look at it. :)

**Comment by johnnyreilly** [comment]
> Seems like the test setup doesn't work in Windows.

They should work on Windows: https://github.com/TypeStrong/ts-loader/runs/6682852223?check_suite_focus=true

See the above GitHub Action from 10 days ago running on Windows

**Comment by johnnyreilly** [comment]
There's a chore piece of work to do with the comparison tests every time there's a major release of TypeScript. I don't think I've done it yet for 4.7. will probably do it on Sunday night

**Comment by unional** [comment]
```sh
$ git clean -xfd test/comparison-tests && npm link ./test/comparison-tests/testLib && node test/comparison-tests/run-tests.js
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: babel-loader@7.1.2
npm ERR! Found: webpack@5.37.1
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"^5.0.0" from karma-webpack@5.0.0
npm ERR!   node_modules/karma-webpack
npm ERR!     dev karma-webpack@"^5.0.0" from the root project
npm ERR!   peer webpack@"^5.1.0" from terser-webpack-plugin@5.1.2
npm ERR!   node_modules/terser-webpack-plugin
npm ERR!     terser-webpack-plugin@"^5.1.1" from webpack@5.37.1
npm ERR!   3 more (webpack-cli, @webpack-cli/configtest, the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"2 || 3" from babel-loader@7.1.2
npm ERR! node_modules/babel-loader
npm ERR!   dev babel-loader@"^7.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: webpack@3.12.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"2 || 3" from babel-loader@7.1.2
npm ERR!   node_modules/babel-loader
npm ERR!     dev babel-loader@"^7.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/homa/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homa/.npm/_logs/2022-06-11T06_10_04_151Z-debug-0.log
error Command failed with exit code 1.
```

When trying to run on WSL.  🤣  looks fun.

**Comment by unional** [comment]
> See the above GitHub Action from 10 days ago running on Windows

I see. Likely because my WIndows env is using Node 18. Let me downgrade

**Comment by johnnyreilly** [comment]
Gosh what would cause that 😂 I use Ubuntu for the most part - which should behave the same but I've not encountered that

**Comment by johnnyreilly** [comment]
Inside the devcontainer it looks like we use node 16: https://github.com/TypeStrong/ts-loader/blob/3f8e3a4688100152d6afc0e37b186f7f732be49a/.devcontainer/Dockerfile#L6

**Comment by johnnyreilly** [comment]
And node 14 and 16 in our execution test pack: https://github.com/TypeStrong/ts-loader/blob/3f8e3a4688100152d6afc0e37b186f7f732be49a/.github/workflows/push.yml#L78

**Comment by unional** [comment]
Running with Node 16 now. btw, running with Node 16 in WSL still fail the save way as above. Just FYI. 🌷

**Comment by johnnyreilly** [comment]
Strange. Just out of curiosity, why don't you fork ts-loader, submit a PR that just changes whitespace or something and see if the tests run successfully there? It'll validate if tests are fundamentally broken. I don't think they are but you never know

**Comment by johnnyreilly** [comment]
> Running the tests with Node 16 now. btw

Oh they run - cool

**Comment by johnnyreilly** [comment]
I wonder if this was the issue: https://stackoverflow.com/a/64615583/761388

**Comment by unional** [comment]
> Oh they run - cool

Ar, I mean "running". 🤣 . It failed. Yeah, trying to figure out what's wrong.

Right now I'm suspecting `nushell`, but not very likely. :)

**Comment by unional** [comment]
> Strange. Just out of curiosity, why don't you fork ts-loader, submit a PR that just changes whitespace or something and see if the tests run successfully there? It'll validate if tests are fundamentally broken. I don't think they are but you never know

Will do.

**Comment by unional** [comment]
![image](https://user-images.githubusercontent.com/3254987/173176754-0bf2231e-d239-47ae-9619-df8daafde6a1.png)

🤣  that's why. Only running comparison tests on Windows. I was running `yarn test`, i.e. also running `execution-tests`

**Comment by johnnyreilly** [comment]
https://github.com/TypeStrong/ts-loader/issues/1464

It looks like the npm that ships with node 18 had some breaking changes. We use yarn 1 for ts-loader anyway, so I'd advise sticking with that

**Comment by unional** [comment]
Do you use `Prettier` + `ESLint`:
![image](https://user-images.githubusercontent.com/3254987/173177229-0c8f0b82-97f0-4bf5-b085-50b0664df595.png)
![image](https://user-images.githubusercontent.com/3254987/173177246-67356a54-b884-48c6-9a29-8700dc13dd58.png)


or `Prettier ESLint`:
![image](https://user-images.githubusercontent.com/3254987/173177236-f415255e-8fcf-4372-a64a-d631b4855810.png)


My personal coding style is not compatible with the coding style in the repo.

I can add a vscode setting to the repo so that it is easier for contributors to create consistent code following the style of the repo.

Let me know which one do you use or do you have any other extensions preferences.

**Comment by johnnyreilly** [comment]
Prettier + ESLint I think

> My personal coding style is not compatible with the coding style in the repo.

Not sure I understand? Come what may, I think we have a precommit hook set up to format consistently.  Generally we use the prettier defaults.

**Comment by johnnyreilly** [comment]
I can see you've upgraded to TS 4.7.3 - the comparison tests won't work now until I do some fiddling. Execution tests will be fine though

**Comment by unional** [comment]
> Prettier + ESLint I think

👌 

The issue is when using VSCode and doing format document will mess up the styling. I do that through muscle memory so always need to `[ctrl+z]` afterwards. So it's much better if the environment is setup already so that it doesn't mess up the code.

> the comparison tests won't work now until I do some fiddling. 

Ok. The all the tests "passes" in Windows.
Please go ahead to make any changes needed. I updated it so that I can add the `NodeNext` test cases for this issue.

**Comment by johnnyreilly** [comment]
> The issue is when using VSCode and doing format document will mess up the styling. I do that through muscle memory so always need to [ctrl+z] afterwards. So it's much better if the environment is setup already so that it doesn't mess up the code.

I'm open to adjusting this - I mostly care that code is formatted consistently. If there's DX tweaks you have in mind we can look at it.

> Please go ahead to make any changes needed. I updated it so that I can add the NodeNext test cases for this issue.

I'll try and do this tomorrow night. Will pop a message on here when done

**Comment by unional** [comment]
> I'm open to adjusting this - I mostly care that code is formatted consistently. If there's DX tweaks you have in mind we can look at it.

#1477 is the PR for that.

**Comment by johnnyreilly** [comment]
upgrade to 4.7.3 (including test pack) complete

**Comment by unional** [comment]
I have published `color-map` with a few variations to test this:

- 2.0.0: ESM only, build with module: `esnext` and module resolution `node` (https://github.com/unional/color-map/blob/v2.0.0/tsconfig.esm.json)
- 2.0.1: ESM only using NodeNext (https://github.com/unional/color-map/blob/v2.0.1/tsconfig.esm.json)
- 2.0.2: export with `exports.require` (https://github.com/unional/color-map/blob/v2.0.2/package.json)
- 2.0.3: export with ESM and main (https://github.com/unional/color-map/blob/v2.0.3/package.json)

**Comment by unional** [comment]
https://github.com/justland/just-web/pull/58

One update. After I add the `cjs/package.json` workaround, at least the CommonJS side resolution is working fine.
It's not directly related to this issue,
but it shows that having due-export (CJS + ESM/NodeNext) able to work at the end application.

**Comment by unional** [comment]
This is an additional plugin that seems to solve the same problem:

https://github.com/softwareventures/resolve-typescript-plugin

**Comment by johnnyreilly** [comment]
Yeah I'm aware of this. I have an idea that we used to link to this somewhere

**Comment by Hujianboo** [comment]
hi, does this problem has been solved by ts-loader?

**Comment by unional** [comment]
Right now you can workaround it using the workaround mentioned above or using the plugin mentioned above.

I don't know what should the general direction for this at the moment, as I just learn that `ts-loader` is not using `tsc` for resolution.

What do you think @johnnyreilly ?

**Comment by johnnyreilly** [comment]
I'm not sure to be honest. @djcsdy's plugin implies webpack itself didn't support ESM. My guess is that might have changed by now but I don't know. If it has, maybe there's less of a workaround way forward?

I'd appreciate anyone who's up to date with where webpack is with this advising? cc @sokra / @alexander-akait

**Comment by alexander-akait** [comment]
hm, why don't use https://webpack.js.org/configuration/resolve/#resolveextensionalias? I think it will work

**Comment by slhck** [comment]
>  This is an additional plugin that seems to solve the same problem:
>
> https://github.com/softwareventures/resolve-typescript-plugin

This in conjunction with `ts-loader` actually did the job for me just fine.

Sorry for the +1 without contributing much. Really just coming in here as a user who wanted to convert their project to ESM and is still quite confused about how the different standards work and tools interact.

**Comment by IronGeek** [comment]
> hm, why don't use https://webpack.js.org/configuration/resolve/#resolveextensionalias? I think it will work

Yes, it works! 
Upgrading webpack to [v5.74.0](https://github.com/webpack/webpack/releases/tag/v5.74.0) and adding the [resolve.extensionAlias](https://webpack.js.org/configuration/resolve/#resolveextensionalias) settings, fix this issue for me :tada:

**Comment by unional** [comment]
https://github.com/microsoft/TypeScript/issues/49083#issuecomment-1200999574

🎉
