### ISSUE TITLE
Clarify Documentation on Emitting Declarations (.d.ts) Files

### ISSUE THREAD

**Issue by phil-lgr** [TypeStrong/ts-loader#1494]
### Expected Behaviour

Have an option to output declarations files in webpack output folder

### Actual Behaviour

ts-loader does not support it?

The official documentation points to a 7 years old plugin (https://github.com/TypeStrong/ts-loader#declarations-dts)

### Steps to Reproduce the Problem

>Declarations (.d.ts)
To output a built .d.ts file, you can set "declaration": true in your tsconfig, and use the [DeclarationBundlerPlugin](https://www.npmjs.com/package/declaration-bundler-webpack-plugin) in your webpack config.

Did I miss something? I'd be happy to PR an update to the docs if it's out of date.

Thank you

**Comment by johnnyreilly** [comment]
Does the suggested approach in the documentation work?

**Comment by phil-lgr** [comment]
When I was looking on how to produce .d.ts files, I was very confused by this paragraph. 

IMO, this section should answer the following questions:

- How can I configure ts-loader to output .d.ts files?
- How do I emit .d.ts. files when using ts-loader with transpileOnly = true and fork-ts-checker-webpack-plugin? (very common scenario?)
- How can I output a single bundled declaration file?

Here is a rough draft:

---

## Declarations (.d.ts)

To output declaration files (.d.ts), you can set "declaration": true in your tsconfig and set "transpileOnly" to false.

If you use ts-loader with  "transpileOnly": true along with [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin), refer to the plugins' modes to output .d.ts files: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#typescript-options

To output a built .d.ts file, you can use the [DeclarationBundlerPlugin](https://www.npmjs.com/package/declaration-bundler-webpack-plugin) in your webpack config.


---

Does that make sense to you? I've used ts-loader for years, and I am not even sure if it can output .d.ts files on its own, I always use it with fork-ts-checker-webpack-plugin, so please correct me.

**Comment by johnnyreilly** [comment]
Thanks for the draft, I didn't quite follow the meaning of this sentence:

> refer to the plugin's modes to output .d.ts files

Otherwise looks great!

> I've used ts-loader for years, and I am not even sure if it can output .d.ts files on its own

I have written and used ts-loader for years and I can't even remember 😅

**Comment by phil-lgr** [comment]
Ok what about:

---

## Declarations (.d.ts)

To output declaration files (.d.ts), you can set "declaration": true in your tsconfig and set "transpileOnly" to false.

If you use ts-loader with  "transpileOnly": true along with [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin), you will need to configure fork-ts-checker-webpack-plugin to output definition files, you can learn more on the plugin's documentation page: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#typescript-options

To output a built .d.ts file, you can use the [DeclarationBundlerPlugin](https://www.npmjs.com/package/declaration-bundler-webpack-plugin) in your webpack config.

---

**Comment by johnnyreilly** [comment]
Looks great!

**Comment by phil-lgr** [comment]
You want a PR for that, or you can just copy and paste and update the README? lmk
