### ISSUE TITLE
v9.4.0 cannot resolve .d.ts files

### ISSUE THREAD

**Issue by falsandtru** [TypeStrong/ts-loader#1504]
ts-loader was able to resolve `index.d.ts` from `index.ts` until v9.3.1, but cannot do it since v9.4.0. The errors occurs on Ubuntu 20.04 but doesn't on Windows 10.

### Expected Behaviour

no error

### Actual Behaviour

```console
ERROR in /home/runner/work/pjax-api/pjax-api/index.ts
./index.ts 1:9-15
[tsl] ERROR in /home/runner/work/pjax-api/pjax-api/index.ts(1,10)
      TS2303: Circular definition of import alias 'Config'.
 @ ./test/integration/index.test.ts 7:16-38
```

https://github.com/falsandtru/pjax-api/actions/runs/3081442336/jobs/4980275627

### Steps to Reproduce the Problem

Check out https://github.com/falsandtru/pjax-api/commit/76ad3769e23497a15817914a92787089c5dfa8cc on Ubuntu.
Run `npm i && npm run dist`.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/falsandtru/pjax-api/commit/76ad3769e23497a15817914a92787089c5dfa8cc

**Comment by johnnyreilly** [comment]
This was likely caused by https://github.com/TypeStrong/ts-loader/pull/1503

@manuth would you be able to take a look please?  If we can resolve this quickly that'd be great - if we can't then we'll likely have to revert 9.4.0 for now.

For others bumping on this, please pin to 9.3.1 for now.  We'll look to either revert or fix in the near future. @falsandtru thanks for the repro.

**Comment by manuth** [comment]
> This was likely caused by https://github.com/TypeStrong/ts-loader/pull/1503
> 
> @manuth would you be able to take a look please?  If we can resolve this quickly that'd be great - if we can't then we'll likely have to revert 9.4.0 for now.
> 
> For others bumping on this, please pin to 9.3.1 for now.  We'll look to either revert or fix in the near future. @falsandtru thanks for the repro.

We could go forward and disable `enhanced-resolver` as it used to be.

I will try to work it out using your repository, @falsandtru.

**Comment by manuth** [comment]
@falsandtru Sadly I could not find myself able to reproduce the issue. For me, the command `webpack --env mode=test` is working properly using your most recent commit `418756d009a14b300f00a7f75831030ff0a6496a`.

Could you please tell me how to reproduce the issue? Is there any other repository or code example causing this error?

**Comment by manuth** [comment]
@xemlock could you please tell me on which repository and what branch you're facing this issue?

**Comment by falsandtru** [comment]
@manuth I already fixed the issue on master branch. Please use the commit written in https://github.com/TypeStrong/ts-loader/issues/1504#issue-1377755555.
