### ISSUE TITLE
v9.4.0 cannot import the members

### ISSUE THREAD

**Issue by falsandtru** [TypeStrong/ts-loader#1505]
The errors occurs on Windows 10 since v9.4.0.
cc @manuth @johnnyreilly 

### Expected Behaviour

no error

### Actual Behaviour

```console
TS2305: Module '"spica/global"' has no exported member 'setTimeout'.
```

### Steps to Reproduce the Problem

Check out https://github.com/falsandtru/clientchannel.
Run `npm i && npm run dist`.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/falsandtru/clientchannel

**Comment by johnnyreilly** [comment]
Thanks for reporting - see discussion on linked PR
