### ISSUE TITLE
Problem with html-webpack-plugin 

### ISSUE THREAD

**Issue by AndreyUtka** [TypeStrong/ts-loader#152]
> I'm trying to use version 2.1.0 in my typscript project. When I add an error Typescript will report the appropriate error ("error TS2304: Cannot find name 'consol'"). After fixing it I'm getting this:

> HtmlWebpackPlugin Error: Child compilation failed:
(2,1): error TS2304: Cannot find name 'consol'.
After restarting webpack-dev-server it works again. This bug is not present in 1.7.0 so I'll simply continue to use this version.

> Unfortunately the ts loader does a lot of stuff.. maybe the maintainer of the ts-loader can help to fix this issue. So please open a ticket there.

So more details [here](https://github.com/ampedandwired/html-webpack-plugin/issues/151)

**Comment by smolyakoff** [comment]
+1 have the same issue

**Comment by thaiat** [comment]
same for me

**Comment by endway** [comment]
+1 same

**Comment by aka-toxa** [comment]
I've the same

**Comment by jbrantly** [comment]
In an effort to be responsive to this, I have published a fix for this in v0.8.1. However, I'm not confident the fix is the best one and may be changing in the future.
