### ISSUE TITLE
Exported Class not included in the bundle if not used directly

### ISSUE THREAD

**Issue by bbottema** [TypeStrong/ts-loader#158]
Maybe I'm going about it the wrong way, but I'm trying to convert a javascript project with Angular 1.x to WebPack and TypeScript. I got it mostly working, but I'm running into trouble when ts-loader seems to be optimizing my scripts out of the bundle when the exports are not directly used.

Here's a sample project demonstrating the issue (npm install, webpack, then load index.html). The logging from ClassA is showing up, but angular is reporting ClassB missing (provider). If you look in bundle.js you'll notice ClassB missing entirely.

https://github.com/bbottema/webpack-typescript

The difference is ClassA begin use directly after importing, and ClassB is only referenced by type for compilation.

Is there a way to force ClassB to be included? Or am I going about it wrong? Angular 2 would probably solve this issue, but that's a step too large right now.

**Comment by jbrantly** [comment]
See [this discussion and my answer on StackOverflow](http://stackoverflow.com/questions/34657652/webpack-with-typescript-external-commonjs-module/34658780).

TypeScript elides unused modules by design. There are various discussions like [here](https://github.com/Microsoft/TypeScript/issues/2812) and [here](https://github.com/Microsoft/TypeScript/issues/4717).

**Comment by bbottema** [comment]
Thanks, I have a work around now. But it's not a pretty one (duplicate imports essentially).

I might use the preprocessor-loader to add an extra require for every typescript import it encounters. I'll give it a play and if it works, I'll report back.

**Comment by bbottema** [comment]
I got it working using preprocessor that automatically insert require statements for import statements. My bundle is now produced properly with directly editing the source file.

The regex needs a lot of work though to make it robust, but in concept it works.

https://github.com/Microsoft/TypeScript/issues/4717#issuecomment-186304734
