### ISSUE TITLE
How does ts-loader find typings/ambient ts files?

### ISSUE THREAD

**Issue by btraut** [TypeStrong/ts-loader#159]
My project loads a ton of external modules from npm, many of which require us to use type definitions to use. We use TSD for some of these and write some of our own. We also have several of our own interfaces/enums/etc defined in a ts file that has no exports. None of these files are explicitly required()'ed, yet ts-loader (or at least tsc internally) seems to find them just fine. How does this work!?

Part of why I'm asking is because I have a .d.ts file off in some directory that I'd love to include, but I don't know how. With gulp-typescript, I was actually responsible for passing all these files into the compiler.

**Comment by nitintutlani** [comment]
[https://github.com/Microsoft/TypeScript/wiki/tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json), reads

> If no "files" property is present in a tsconfig.json, the compiler defaults to including all TypeScript (*.ts or *.tsx) files in the containing directory and subdirectories. When a "files" property is present, only the specified files are included.

> If the "exclude" property is specified, the compiler includes all TypeScript (*.ts or *.tsx) files in the containing directory and subdirectories except for those files or folders that are excluded.

> The "files" property cannot be used in conjunction with the "exclude" property. If both are specified then the "files" property takes precedence.

**Comment by jbrantly** [comment]
What @nitintutlani said is accurate and is likely the way those definitions you mentioned are being loaded automatically. If you want to manually include some file you can either use a triple-slash reference or use `files` in tsconfig, but note that if you use `files` it changes the behavior of automatically finding files.
