### ISSUE TITLE
Compatibility with Typescript 1.8.2

### ISSUE THREAD

**Issue by nitintutlani** [TypeStrong/ts-loader#160]
The boilerplate app: https://github.com/keokilee/react-typescript-boilerplate does not work anymore with the newly released typescript 1.8.2.

```
ERROR in ./app/index.tsx
Module build failed: Error: Typescript emitted no output for /home/nitin/MyProjects/references/react-typescript-boilerplate/app/index.tsx
    at Object.loader (/home/nitin/MyProjects/references/react-typescript-boilerplate/node_modules/ts-loader/index.js:437:15)
```
is this something ts-loader can fix from within?

**Comment by nitintutlani** [comment]
Although it works with typescript 1.7.5.

**Comment by johnnyreilly** [comment]
For what it's worth I've been using ts-loader with 1.8.2 happily (though not doing any TSX)

**Comment by nitintutlani** [comment]
My bad, #147 I got rid of noEmit from tsconfig.json and back to business.
