### ISSUE TITLE
Webpack re-compile the final bundle JS when watching

### ISSUE THREAD

**Issue by s-eiermann** [TypeStrong/ts-loader#1603]
### Expected Behaviour
Webpack re-compiles the bundle app.js file

### Actual Behaviour
Webpack does only recompile the individual js files, but not the final bundle app.js file.

### Steps to Reproduce the Problem
In the referenced reprex you can run the watcher via: `npm run client:watch`, then edit the ts file in `client/src/ts/index.tx` and see that it updates the `client/src/js/index.js` respectively, but it does not compile the final bundle in `client/dist/app.js`.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/s-eiermann/webpack-example

**Comment by johnnyreilly** [comment]
Is this new with TS 5.0?
