### ISSUE TITLE
ts-loader does work when ts-config noEmit is set to true in typescript 1.8.2

### ISSUE THREAD

**Issue by afaayerhan** [TypeStrong/ts-loader#161]
{
  "compilerOptions": {
    "target": "ES6",
    "jsx": "preserve",
    "noEmit": true,
    "watch": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ]
}
 this is the current tsconfig I am using with 1.8.2 that is working. but after changing noEmit to false it works. but as you know I don't want to emit anything as I use IDE like webstorm .... that does compilation to correctly understand errors in typescript.

**Comment by jbrantly** [comment]
You can override the options just for ts-loader. In your webpack config, put something like:

```
  ts: {
    compilerOptions: {
      noEmit: false
    }
  }
```

**Comment by afaayerhan** [comment]
@jbrantly  thanks already did that and solved my problems. would be closing this issue. but maybe noEmit: false should be coded in by default.

**Comment by LinusU** [comment]
Opened an issue for changing the default: #719
