### ISSUE TITLE
Overriding `skipLibCheck` compiler option does not work

### ISSUE THREAD

**Issue by haakonflatval-cognite** [TypeStrong/ts-loader#1613]
Duplicates https://github.com/TypeStrong/ts-loader/issues/1247

### Expected Behaviour

Compiler options specified in `tsconfig.json` (or `options.compiler` field in the Webpack config object) should override the defaults specified in `ts-loader`. In particular, the user should be able to set the `skipLibCheck` field to be `false`, although it is given the default value `true` in `compilerSetup.ts`. 

### Actual Behaviour

Setting `skipLibCheck` to `false` in either `tsconfig.json` or options in the Webpack config does not override the default value.

### Steps to Reproduce the Problem

- In a Webpack+ts-loader project, use a dependency which will create an error if the Lib Check is not skipped. One example of such a dependency is `@cognite/reveal@4.3.1` (note the exact patch version).
- Make sure `skipLibCheck` is `false` in `tsconfig.json`.
- Compile. If the lib check was performed, the build should fail, complaining about some missing type. With current behavior, build succeeds. 
- Modify `node_modules/ts-loader/dist/compilerSetup.js` so that `skipLibCheck` is `false`. Compile again
- The build fails, as expected

### Location of a Minimal Repository that Demonstrates the Issue.

Can provide upon request

**Comment by haakonflatval-cognite** [comment]
@johnnyreilly Do you have time to address this?

**Comment by johnnyreilly** [comment]
Would you like to submit a PR and I'll take a look?

**Comment by haakonflatval-cognite** [comment]
@johnnyreilly Sure, I've submitted a PR now: https://github.com/TypeStrong/ts-loader/pull/1617

**Comment by haakonflatval-cognite** [comment]
Fixed in https://github.com/TypeStrong/ts-loader/pull/1617
