### ISSUE TITLE
Is there a pass-through options?

### ISSUE THREAD

**Issue by dumconstantin** [TypeStrong/ts-loader#164]
Hi,

I'm using the following webpack setup:
```javascript
     { test: /\.js|\.tag|\.ts$/, exclude: exclude, loader: 'babel',
          query: {
            presets: ['es2015'],
            plugins: ['transform-flow-strip-types']
          }
        },
        { test: /\.ts$/, loader: 'ts-loader', 
          query: {
            configFileName: './../tsconfig.json'
          }
        },
```
I want ``` ts-loader ``` to only do a type check on the ts files without making any compilation. Is this possible?

What I'm looking for is having a ``` pass-through ``` option that leaves the files intact for babel to take over.

I tried to pinpoint where the compiled files overwrite the source files in the ts-loader source but haven't managed yet (if there isn't a more elegant solution than this, can you please point me to those lines so that I can fork and comment them out?)

Thanks!

**Comment by johnnyreilly** [comment]
Hey @dumconstantin,

Check this out: https://github.com/Microsoft/TypeScriptSamples/tree/master/es6-babel-react-flux-karma

The example is for React / JSX but the principal that you're looking for of using TypeScript to do it's static compilation thing and pass it on to Babel is implemented.  It's my personal preference for working with TypeScript and I :heart: it.

**Comment by jbrantly** [comment]
The closest thing to a "passthrough" would be to set your target to `es2015` in tsconfig.json.

**Comment by johnnyreilly** [comment]
That reminds me; must switch over the sample from `"target": "es6"` to ` "target": "2015"`. Both the same but one's out of fashion

**Comment by dumconstantin** [comment]
Hi all, thank you for much for the replies. I'll test doing something like https://github.com/Microsoft/TypeScriptSamples/tree/master/es6-babel-react-flux-karma and let you know. Thanks!

**Comment by dumconstantin** [comment]
The ``` "target": "es2015" ``` saved the day! Thank you very much!
