### ISSUE TITLE
[QUESTION] No experimentalWatchApi in latest v9.5.1

### ISSUE THREAD

**Issue by rahulranjan-blitz** [TypeStrong/ts-loader#1649]
### Expected Behaviour
I am currently in the process of migrating ts-loader from version 8.0.4 to 9.5.1
However, i am unable to find experimentalWatchApi in the latest documentation. Has this been removed or replaced with other field? Please point out the source for this in either case.

Thank you!

**Comment by johnnyreilly** [comment]
If memory serves we removed the experimentalWatchApi
