### ISSUE TITLE
NPM packages which has type definition in package.json is not working

### ISSUE THREAD

**Issue by Ciantic** [TypeStrong/ts-loader#170]
I think one can reproduce this using Immutable js:

`npm install immutable --save`

The typescript definitions work immediately in VSCode because it has [typescript defined in the package.json](https://github.com/facebook/immutable-js/blob/master/package.json#L18) but ts-loader using webpack gives me error in webpack:

error TS2307: Cannot find module 'immutable'.

**Comment by Ciantic** [comment]
I found a workaround, by explicitely listing immutable.d.ts in the files section of webpack specific tsconfig:

**tsconfig.webpack.json**
```
{
    "compilerOptions": {
        "target": "es6",
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "jsx": "react"
    },
    "exclude": [
        "typings/main.d.ts",
        "typings/main"
    ],
    "files": [
        "node_modules/immutable/dist/immutable.d.ts"
    ]
}
```

Another odd thing is if I remove "files" from there completly it will seek all d.ts files from all node_modules directories and gives a bunch of duplicate errors.

So it must be `"files" : []` for ts-loader to work at all.

**Comment by blakeembrey** [comment]
@Ciantic Actually, that's wrong. That is not the correct way to use the definitions and it's probably an accident that it's working for you in VSCode. The field in `package.json` should be `typings`. The field you allude to is non-standard and not used by TypeScript. See https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages.

**Comment by elboman** [comment]
I'm having the same problem. I'm using a module that has `typings` definition in its [`package.json`](https://npmcdn.com/ui-router-core@1.0.0-alpha.5/package.json), however `ts-loader` can't seem to resolve them, and I get:
```
TS2307: Cannot find module 'ui-router-core'.
```

**Comment by bipinpoudyal** [comment]
I am facing the same issue. ts-loader is loading the typings if the *main* field points to a js file but if it points to a ts file, it doesnot load the typings folder. I have created a sample [project] (https://github.com/bipinpoudyal/tsloader-issue) with the recreation steps.

I tried compiling the same using tsc and it compiles properly without any issues.

**Comment by blakeembrey** [comment]
@elboman Are you using node module resolution or CommonJS?

**Comment by blakeembrey** [comment]
@bipinpoudyal I don't understand, what do you mean by "the typings folder".

**Comment by blakeembrey** [comment]
By the way, all these three issues are separate - they aren't the same issue. Advice on one of them does not apply to the others.

**Comment by bipinpoudyal** [comment]
@blakeembrey This is not a production setup but a development time setup where I want to develop a library which will be consumed by another module. I have a workaround where I can export the same definitions from the *main* ts file, but since TSC compiles fine with the same setup I thought I will bring it to your notice.

Btw, should I raise a separate issue for this?

**Comment by blakeembrey** [comment]
@bipinpoudyal Thanks for bringing it up. I'd create a separate issue, just want to note it would likely happen with Webpack anyway since it'd start resolving via `package.json` `main` - so even if the cause is patched, I'd guess might still run into issues as it starts compiling node modules. Still, I can try to take a look - feel free to separate out the issue 😄

**Comment by aryzing** [comment]
Are we still seeing this issue, or can we close this @Ciantic ?

**Comment by Ciantic** [comment]
I'm quiet sure this can be closed.
