### ISSUE TITLE
Import is always undefined

### ISSUE THREAD

**Issue by DerekStrickland** [TypeStrong/ts-loader#177]
Hi,

I am having an issue sharing code across two ts files. I am using react/redux tool chain and the reducer file can't see imported actions.  

Here is my actions.ts
`
const BROWSE:string = 'BROWSE';
const SET_CATEGORY:string = 'SET_CATEGORY';

export { BROWSE , SET_CATEGORY }
`

And here is my reducer.ts.

`
import { Action } from '../Action.ts';
import Actions = require('./Actions.ts');
import objectAssign = require('object-assign');

interface IDashboardState {
    Category?:string;
    Hints?:string[]
}

const _initialState:IDashboardState = {
    Category: '',
    Hints: []
};

const _supportedActionTypes:string[] = [
    Actions.BROWSE,
    Actions.SET_CATEGORY
]; 

export default function DashboardReducer(state:any, action:Action) {
    if(!state)
        return _initialState; 

    if(_supportedActionTypes.indexOf(action.Type) === -1)
        return state;

    let newState = objectAssign({}, state, action.Payload);
        return newState;
};
`

the attempt to initialize the _supportedActionTypes array fails saying "Cannot read property 'BROWSE' of undefined" and manual debugging shows that Actions is in fact undefined.  The emitted webpack code looks like this.

`
!(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__, exports], __WEBPACK_LOCAL_MODULE_3__ = (function (require, exports) {
    "use strict";
    var BROWSE = 'BROWSE';
    exports.BROWSE = BROWSE;
    var SET_CATEGORY = 'SET_CATEGORY';
    exports.SET_CATEGORY = SET_CATEGORY;
}.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)));
!(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__, exports, __WEBPACK_LOCAL_MODULE_3__, __webpack_require__(256)], __WEBPACK_LOCAL_MODULE_4__ = (function (require, exports, Actions, objectAssign) {
    "use strict";
    var _initialState = {
        Category: '',
        Hints: []
    };
    var _supportedActionTypes = [
        Actions.BROWSE,
        Actions.SET_CATEGORY
    ];
    function DashboardReducer(state, action) {
        if (!state)
            return _initialState;
        if (_supportedActionTypes.indexOf(action.Type) === -1)
            return state;
        var newState = objectAssign({}, state, action.Payload);
        return newState;
    }
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = DashboardReducer;
    ;
}.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)));
`

and what I find very odd is that the exports arg has my Actions defined on it.  Somehow they have been merged onto this exports instance, but the Action arg remains undefined.  Of course, pre-compilation, I have no access (that I am aware of) to the exports variable.  

For what it's worth, I have also used the import * as Actions from './Actions.ts' syntax, and that failed in exactly the same way.  What am I doing wrong?

**Comment by DerekStrickland** [comment]
Also, here's my webpack.config.js

`var webpack = require('webpack');
var path = require('path');

var config = {  
  entry: [
      'webpack-dev-server/client?http://localhost:8000',
      'webpack/hot/only-dev-server',
      'bootstrap-loader',
      path.join(__dirname, 'src/ts/Main.tsx')
  ],
  output: {
        path: path.resolve(__dirname, 'build/www'),
        filename: 'clear.js',
  },
  resolve: {
    extensions: ['', '.Webpack.js', '.web.js', '.ts', '.js', '.tsx']
  },
  plugins: [
    new webpack.ProvidePlugin({
        'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
    })
  ],
  module: {
    loaders: [{ 
            test: /\.tsx?$/, 
            loaders: ['react-hot', 'ts-loader'],
            include: path.join(__dirname, 'src', 'ts')
        }, {
            test: /\.css$/,
            loaders: [ 'style', 'css', 'postcss' ]
        }, {
            test: /\.scss$/,
            loader: 'style!css!sass?includePaths[]=' + (path.resolve(__dirname, "./node_modules"))
        }, {
            test: /\.(png|jpg)$/,
            loader: 'url?limit=25000'
        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: 'url-loader?limit=10000&mimetype=application/font-woff'
        }, {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: 'file-loader'
        }
    ]
  }
};

module.exports = config;`

**Comment by DerekStrickland** [comment]
I actually created a pared down version of the whole project to illustrate the issue.  You can check it out here.

https://github.com/DerekStrickland/TSLoaderDemo

**Comment by DerekStrickland** [comment]
I solved the issue.  The error was entirely in my code.  The working example can be found at the repo above, but the tl;dr is that the following syntax for exporting a module is like mandatory and stuff. 

`module LoginActions {
    export const LOGIN:string = 'LOGIN';
    export const LOGOUT:string = 'LOGOUT';
}

export = LoginActions;`

**Comment by QuantumInformation** [comment]
So what was the issue in the end?
