### ISSUE TITLE
Watch only watches first .ts file and sourcemaps are mapping to javascript files instead of typescript files.

### ISSUE THREAD

**Issue by B3nCr** [TypeStrong/ts-loader#179]
I'm working on a large angularjs project using typescript, and webpack. I'm developing in Visual Studio so VS is compiling my typescript every time I save a file. I'm not sure if that has any bearing on what's happening.

ts-loader is building all my typescript files and I can see that by introducing compilation errors but when I use the debugger in Chrome dev tools and add a break point in the bundle it's mapping to the compiled js file.

What's strange is that the file which is defined as the app entry point maps to the ts file. Every other file maps to the compiled javascript.

Another issue is that `webpack --watch` only watches the app entry point file. Changes to any of the other files don't trigger webpack to run again.

**Comment by xaclincoln** [comment]
In my case, webpack --watch watches all the file in directory, but after compiling, the webpack dev server do not trigger a live reloading. 
I tried a hello-world sample app (without using ts-loader), the webpack dev server did trigger live reloading when any jsx file changed.
Is this a ts-loader bug or ts-loader do not cooperate with webpack dev server?

**Comment by B3nCr** [comment]
Anyone got any idea why this is happening?

**Comment by B3nCr** [comment]
I was importing the modules incorrectly. 

`require("./ModuleName")` instead of `import "./ModuleName.ts"`
