### ISSUE TITLE
Error output format can not be navigated in vscode

### ISSUE THREAD

**Issue by drywolf** [TypeStrong/ts-loader#188]
Hi,

I think at one point it was possible with either ts-loader or awesome-typescript-loader to navigate to an error that was produced during TypeScript compilation by clicking on the generated error line in the vscode output panel.

Vscode seems to need a certain formatting for output-messages to automatically provide navigable links to the file + line-number + column-number that the message points to.

IIRC the format was of the form: `{relative_file_path}:{line-nr}:{column-nr} {message}`

Is there currently any way to configure the ts-loader or vscode to achieve this functionality ? It is a really invaluable dev-experience feature.

**Comment by johnnyreilly** [comment]
I don't know anything about this I'm afraid.  Closing as nothing to do....
