### ISSUE TITLE
 Cannot resolve export class Instance

### ISSUE THREAD

**Issue by twoeo** [TypeStrong/ts-loader#191]
**tsconfigFolder/../Test.ts**
export default class Test{
}

**tsconfigFolder/../Demo.ts**
import Test from './Test';
const Demo = new Test();
export default Demo;

**tsconfigFolder/test.ts**
import Demo from '../Demo'
console.log(Demo)

webpack config entry is test.ts
tsconfig at tsconfigFolder
webpack.config.js at tsconfgFolder

**It will show error**
ERROR in ../Demo.ts
Module not found: Error: Cannot resolve module 'ts-loader'

**Comment by s-panferov** [comment]
@twoeo do you have `ts-loader` installed?

**Comment by twoeo** [comment]
Yes!
There is no problem if Demo.ts and Test.ts in tsconfigFolder.
There is no problem if define of class Test in Demo.ts
Problem only appear when test.ts import Demo.ts, and Demo.ts import Test.ts, and Demo.ts&Test.ts is at the parent folder of tsconfigFolder

**Comment by s-panferov** [comment]
@twoeo and where is your `node_modules` folder is located relatively to `tsconfigFolder`?

**Comment by twoeo** [comment]
Yes,  tsconfigFolder/node_modules,
and webpack & typescript link global.

**Comment by twoeo** [comment]
Could be reproduced by this 3 simple files.

**Comment by twoeo** [comment]
tsc -p .  works well

**Comment by s-panferov** [comment]
I think that probleb is that `webpack` resolves all loaders relatively to required files. Please try to add resolveLoader section to your `webpack.config.json` https://webpack.github.io/docs/configuration.html#resolveloader

**Comment by s-panferov** [comment]
Something like 

```
resolveLoader: {
           root: [
            	path.join(__dirname, "node_modules")
           ],
           fallback: path.join(__dirname, "node_modules")
},
```

**Comment by twoeo** [comment]
**Cool !!**
**resolveLoader solved this !**

_I think that problem is that webpack resolves all loaders relatively to required files. _

That's right. It works if I "npm install ts-loader" at ../tsconfigFolder

**Thank you so much !**
