### ISSUE TITLE
ts-loader and webpack 2.0

### ISSUE THREAD

**Issue by olegstepura** [TypeStrong/ts-loader#195]
Hi!

Just want to know if `ts-loader` is ready for `webpack 2.0`? I tried to switch my app, which correctly works with latest webpack 1.x, to webpack 2.0 and got bunch of typescript module resolve errors.

I'm using paths relative from root for imports. Like this:
(4ex: file `container\Home\HomePage.tsx`)

``` javascript
import Logger from 'common/util/logger'
```

folder structure for this:

```
+ root
|
+- container / Home / HomePage.tsx 
+- common / util / logger.tsx
```

my tsconfig:

``` json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "moduleResolution": "node",
    "allowJs": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "removeComments": false,
    "noImplicitAny": false,
    "inlineSourceMap": true,
    "jsx": "react",
    "rootDir": "src/main",
    "outDir": "target/typescript"
  },
  "exclude": [
    "node_modules",
    "typings",
  ]
}
```

webpack was reconfigured according to changes noted here: https://gist.github.com/sokra/27b24881210b56bbaff7

**Comment by aaalsubaie** [comment]
it works for me but too slow!

**Comment by QuantumInformation** [comment]
@aaalsubaie doesn't work for me:

└── UNMET PEER DEPENDENCY webpack@2.1.0-beta.21

npm WARN webpack-dev-server@1.14.1 requires a peer of webpack@>=1.3.0 <3 but none was installed.

**Comment by blakeembrey** [comment]
@QuantumInformation This issue is unrelated. It actually says right there that the warning is coming from `webpack-dev-server` and is not related to this issue.

**Comment by rasentry** [comment]
ts_loader does not add webpack's options.resolve.modules to module resolver

**Comment by oojacoboo** [comment]
@rasentry that actually helped some for me, thanks.

I'm still wondering about this.  There doesn't seem to be much talk about webpack 2 support here.  I realize it's still beta, but it's been in beta for a while too.  Documentation is VERY sparse.  I can't even locate any docs on the webpack 2 config format and details.  I've seen some bits and pieces, but that's about it.

I'm getting all kinds of module resolving issues here.  At first I was having issues with the webpack entry file and had to directly pass it to `ts-loader!index.tsx`.  This at least gets my entry loading, but now it's having issues resolving modules that are imported into the entry file.

Any direction/help would be greatly appreciated here.  If anyone has this working, a little write-up would be huge.  At the least, a working webpack config and tsconfig.  Thanks.

**Comment by johnnyreilly** [comment]
@oojacoboo you might want to take a look at https://github.com/TypeStrong/ts-loader/issues/283 - this may help

**Comment by wpitallo** [comment]
I have tried to use this with webpack 2 but it is very very very slow :(
