### ISSUE TITLE
Child couldn't see it's parent, if the internal module is spilt across multiple files.

### ISSUE THREAD

**Issue by yssource** [TypeStrong/ts-loader#200]
a.ts
```
module A {
        export class Base {}
}
```

b.ts
```
/// <reference path="./a.ts" />
module A {
         export class Child extends A.Base {}
}
```

c.ts
```
/// <reference path="./a.ts" />
module A {
       export class Another {
            constructor(protected base: A.Base)
       }
}
```

The final out.js is reporting error message "`TypeError: Super expression must either be null or a function, not undefined`".

The problem is
`A.Another can see A.Base, However, Child can not see A.Base.`

I think 'ts-loader' is able to deal with internal module, which is spilt across multiple files.
But,  It seems to be 'ts-loader' unable to deal with child class extending it's parent's class, if they are not in the same file.

**Comment by johnnyreilly** [comment]
If you're using ts-loader then I think I'm right in saying you shouldn't be using modules/namespaces. It's the difference between working with internal modules and external modules..

**Comment by yssource** [comment]
Thanks for your information.

But, I don't think the internal modules is the old styles for Typescript.
And I try to reproduce my problem by
`tsc ./a.ts ./b.ts ./c.ts --outFile ./out.js`
as a result, the out.js works well.

I also agree with you actually it is not an issue, if I am not using modules/namespaces. 

If some others happen such a problem like me,  and insist on using the modules/namespaces, it is helpful if merging the base and sub class into one file.

**Comment by johnnyreilly** [comment]
Hi @yssource,

> If some others happen such a problem like me, and insist on using the modules/namespaces, it is helpful if merging the base and sub class into one file.

Sure, but if you're using webpack the idea is that it takes responsibility for bundling instead of tsc.  

Closing for now as there is no action to take.
