### ISSUE TITLE
Could not pass the compilation randomly occurring on different machines

### ISSUE THREAD

**Issue by kirillonufreinko** [TypeStrong/ts-loader#201]
I'm experiencing following issue when trying to build application with webpack->ts-loader->typescript

ts-loader: Using typescript@1.8.7 and C:\[...]\tsconfig.json
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at exports._errnoException (util.js:890:11)
    at WriteWrap.afterWrite (net.js:769:14)_

It might happen on one machine and does not reproduce on other. Please investigate

**Comment by johnnyreilly** [comment]
Insufficient information to go on I'm afraid. Our CI runs on Linux and Windows - I suspect this may be a problem with your machine
