### ISSUE TITLE
how to specifies the path of a directory containing a tsconfig.json file.

### ISSUE THREAD

**Issue by geminiyellow** [TypeStrong/ts-loader#222]
tsc can use `-p`/`--project` to specific the `tsconfig.json` file path,
how to use it in `ts-loader`

> Using tsconfig.json
> 
> ...
> By invoking tsc with no input files and a --project (or just -p) command line option that specifies the path of a directory containing a tsconfig.json file.

**Comment by geminiyellow** [comment]
i can see the log: 
```
ts-loader: Using typescript@1.8.10 and /Users/my/Documents/Sources/myproject/configs/tsc/tsconfig.json
```
but the loader cannot found the d.ts files

**Comment by TheLarkInn** [comment]
You can do this using the `ts` property in the webpack config. 

Example: 
```
  ts: {
    configFileName: ngAppResolve('./src/tsconfig.json'),
    silent: true
  },
```

**Comment by geminiyellow** [comment]
Hi @TheLarkInn , thank you.
yes, i do it before https://github.com/TypeStrong/ts-loader/issues/222#issuecomment-223936083 , but got the error.
