### ISSUE TITLE
Enhancement: Implement Tsickle for Google Closure Compiler

### ISSUE THREAD

**Issue by TheLarkInn** [TypeStrong/ts-loader#224]
Currently there is an angular project which I think could benefit all Typescript users.

As we all know, Google closure compiler is still the most efficient minifier, however requires annotations for it to be used in ADVANCED mode.

https://github.com/angular/tsickle

This project is using a baked tsc that automagically converts decorators and types to annotations that allow for GCC to understand.

Since Webpack2 is implementing LoaderOptionsPlugin which hands the responsibilities of minifying to the loader, it would be perfect timing to add a minify feature into the loader.

Thoughts?

Cross reference post to both ts loaders. 
https://github.com/s-panferov/awesome-typescript-loader/issues/153

**Comment by AnimaMundi** [comment]
Would love to see this! Need any help?

**Comment by johnnyreilly** [comment]
If you'd like to have a crack at implementation then go for it! We gratefully accept PRs

**Comment by AnimaMundi** [comment]
Did you have any preferences on the configuration for this? Like just a boolean flag to turn tsickle on or off from the user's point of view?

**Comment by johnnyreilly** [comment]
That sounds like a good starting point. Essentially anything can be refined at any point though - have a play and see what you come up with would be my advice.

**Comment by AnimaMundi** [comment]
Sounds good, I'll post back when I come up with something.
