### ISSUE TITLE
How to pass in global type definitions?

### ISSUE THREAD

**Issue by pizza2code** [TypeStrong/ts-loader#234]
Greetings,

Is there any way to pass global type definitions into ts-loader?  Including triple-slash path references at the top of every single Typescript file seems overkill, and I'd prefer to avoid the debugging headaches that "comments as code" introduces.

I've tried placing them in the "files" property of tsconfig.json:
```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "jsx": "react"
  },
  "files": [
        "node_modules/typescript/lib/lib.es6.d.ts",
        "typings/index.d.ts"
  ]
}
```
But that just results in tons of multiple-inclusion errors like:
```
ERROR in /[snip]/extender-example/node_modules/typescript/lib/lib.es6.d.ts
(13961,5): error TS2300: Duplicate identifier 'baseVal'.
```
I'm intentionally targeting ES5 while using some ES6 features, since we have tight control over the browsers used (which have a lot of ES6 support) but ES6 module loading still seems to be an unsolved problem.

Is there a global .d.ts file option I'm missing?  Would it be possible to add such an option?

**Comment by blakeembrey** [comment]
It should work already. A duplicate identifier error implies that you'e got the same definition in two places. Is there any other errors?

**Comment by pizza2code** [comment]
Sorry, yes there are additional errors.  I'm trying to load Typescript from a couple external directories, which Webpack supports via resolve/resolveLoader.root and .fallback

However I'm receiving 'error TS2307: Cannot find module' on those external Typescript files, and an odd non-Typescript error `Module not found: Error: Cannot resolve module 'ts-loader' in /external/file.ts`.  

Even a custom Typescript 1.8.10 (modified to support NODE_PATH) is throwing a file not found error.

This may warrant a separate issue.  Doesn't seem related to what I first posed about.

**Comment by pizza2code** [comment]
Even when I symlink the external Typescript files into the local node project, I get the same errors.

webpack.config.js:
```js
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');

var outDir      = 'built';
var NODE_PATH   = process.env.NODE_PATH;

var entries = ['./app/index.tsx'];
var assets = [
    { from: 'node_modules/bootstrap-sass/assets/fonts/**/*', 
        to: 'fonts' 
    }
];

// Webpack and plugin configuration
var htmlPlugin = new HtmlWebpackPlugin({
    title: 'Test',
    template: 'index.html.ejs'
});

var copyPlugin = new CopyWebpackPlugin(assets);

var sourceMapLoader = {
    loader: 'source-map',
    test: /\.tsx?$/,
    exclude: /(node_modules)/
};

var webpackConfig = {
    entry: entries,
    output: {
        path: path.resolve(__dirname, outDir),
        publicPath: '/',
        filename: 'bundle.js'
    },
    devServer: {
        contentBase: outDir
    },
    module: {
        preLoaders: [],
        loaders: [
            {
                loader: 'ts-loader',
                test: /\.tsx?$/,
                exclude: /(node_modules)/
            }
        ]
    },
    plugins: [
        htmlPlugin,
        copyPlugin
    ],
    resolve: {
        fallback: NODE_PATH.split(':').map(function(dir) {
           return path.resolve(dir); 
        }),
        extensions: ["", ".webpack.js", ".web.js", ".js", ".ts", ".tsx"]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      path: true,
      tls: 'empty'
    },
    //devtool: 'eval',
};

if (process.env.NODE_ENV !== 'production') { 
    webpackConfig.module.preLoaders.push(sourceMapLoader);
    //only want hot reloading when in dev.
    webpackConfig.entry.push('webpack/hot/only-dev-server');
    webpackConfig.entry.push('webpack-dev-server/client?http://0.0.0.0:8080');
}

module.exports = webpackConfig;
```

**Comment by blakeembrey** [comment]
@pizza2code I'm not going to debug the project for you. You're welcome to create a reproduction someone can run, or can you post the list of errors. As I mentioned, it's complaining about a duplicate so there should be a second error that mirrors that duplicate. 

The "Cannot find module" error is a TypeScript error - it means the module you're trying to load has no definition that can be found.

**Comment by blakeembrey** [comment]
Continuing from above, don't look at the whole error list - can you find the two files where there's duplicates?

**Comment by blakeembrey** [comment]
Oh, you know what it'd be. If you read the errors, it should confirm. You've combined `lib.es6.d.ts` with `lib.d.ts` which results in a ton of conflicts. Please specify `noLib` in your `tsconfig.json`.
