### ISSUE TITLE
compilerOptions.declaration=true in tsconfig.json with output.path in webpack.config.js incorrectly nests *.d.ts file

### ISSUE THREAD

**Issue by autochthe** [TypeStrong/ts-loader#238]
Setting `compilerOptions.declaration=true` in `tsconfig.json` with `output.path` defined in `webpack.config.js` incorrectly nests resulting *.d.ts file within output path.

**Minimal example**
[ts-loader-declarations-bug.zip](https://github.com/TypeStrong/ts-loader/files/353589/ts-loader-declarations-bug.zip)

package.json
```json
{
  "name": "ts-loader-declarations-bug",
  "version": "1.0.0",
  "description": "Minimal example of ts-loader declarations bug",
  "main": "dist/output.js",
  "scripts": {
    "prepublish": "webpack",
    "test": "webpack"
  },
  "author": "Mara Kim",
  "license": "ISC",
  "devDependencies": {
    "ts-loader": "^0.8.2",
    "typescript": "^1.8.10",
    "webpack": "^1.13.1"
  }
}
```

tsconfig.json
```json
{
    "compilerOptions": {
        "declaration": true
    }
}
```

webpack.config.js
```javascript
module.exports = {
    entry: './input.ts',
    output: {
        path: __dirname + '/dist',
        filename: 'output.js',
    },
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: "ts-loader",
            },
        ],
    },
};
```

input.ts
```javascript
export default class {
    foo():number {
        return 42;
    }
}
```

To build:

    npm install

**Current output**

Try `ls -R dist` to view the output directory.  The output files are `output.js` and a weirdly nested *.d.ts file whose location can be described as follows:

If the global location of the `ts-loader-declarations-bug` directory is `$PACKAGE`, the *.d.ts file is located at `$PACKAGE/dist/$PACKAGE/input.d.ts`.

**Expected output**

The *.d.ts file should be located at `$PACKAGE/dist/input.d.ts`.

**Miscellaneous**

There is also currently no way to change the name of the resulting *.d.ts file.

**Environment**
* ts-loader: 0.8.2
* typescript: 1.8.10
* webpack: 1.13.1
* node: 6.2.2
* Operating System: Mac OSX 10.11.5

**Comment by johnnyreilly** [comment]
Think this is resolved with 0.9.1
