### ISSUE TITLE
consider webpack alias prop for typescript npm modules 

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/ts-loader#239]
webpack allow to define alias for node_modules.
We can write 

```
  alias: {
      'any-ts-npm-package': path.resolve(__dirname, 'node_modules/any-ts-npm-package')
  } 
```

For example, packages p1,p2 uses different versions of  'any-ts-npm-package' with different api;

in this case compiler don't know about webpack alias and do typechecking for p1 (dependent 'any-ts-npm-package' of version 0.1) and for p2 (dependent on  'any-ts-npm-package' of version 0.1).

**Comment by johnnyreilly** [comment]
Does `"moduleResolution": "node"` in`tsconfig.json` resolve this issue?

**Comment by samuelmaddock** [comment]
I've run into the same problem using webpack's `resolve.alias` configuration option and ES6 module imports. However, using the commonjs `require('module')` method seems to work.

**Comment by michaelwoods** [comment]
It appears as though this is supported as there's [tests](https://github.com/TypeStrong/ts-loader/tree/master/test/aliasResolution) to validate this functionality.

I came here by the way of [modernizr-loader](https://github.com/peerigon/modernizr-loader) and I cannot get the modernizr module to be recognized by the TypeScript compiler.

```js
import Modernizr from 'modernizr';
```

```
error TS2307: Cannot find module 'modernizr'.

**Comment by finico** [comment]
@stepancar @samuelmaddock @michaelwoods 

It's can be solved by using `paths` in tsconfig

webpack.config.js
```js
resolve: {
    alias: {
        'any-ts-npm-package': path.resolve(__dirname, 'node_modules/any-ts-npm-package'),
        config: path.resolve(__dirname, 'config')
    }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "any-ts-npm-package": ["node_modules/any-ts-npm-package"],
      "config": ["config"]
    }
  }
}
```

read more [ts/handbook/module-resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html)

**Comment by scamden** [comment]
@finico any idea how this might work if you wanted to then generate declaration files for this project and publish them? i can't seem to get the paths to be honored in a package that consumes the declaration files
