### ISSUE TITLE
Ignoring node_modules for compiling server-side TypeScript

### ISSUE THREAD

**Issue by mohsen1** [TypeStrong/ts-loader#242]
#### My Setup
I am working on this universal application that [is open source](https://github.com/rah-foundation/website). Check it out at [b699116](https://github.com/rah-foundation/website/tree/b699116d5b8594ef65c43b8211225ec4b16a33a3) where I have this issue

Here is my `tsconfig.json`: 

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noResolve": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "removeComments": true,
    "experimentalDecorators": true,
    "jsx": "react"
  },
  "exclude": [
    "node_modules"
  ]
}
```

And here is the webpack config: [`webpack.config.server.ts`](https://github.com/rah-foundation/website/blob/b699116d5b8594ef65c43b8211225ec4b16a33a3/webpack.config.server.ts)

#### Problem 
JavaScript files in `node_modules` are included as part of dependency graph and some of them are throwing error despite my `tsconfig.exclude` and ts-loader exclude options. 

```
ERROR in ./~/fsevents/~/node-pre-gyp/lib/node-pre-gyp.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in /Users/mazimi/Projects/rah-foundation/website/node_modules/fsevents/node_modules/node-pre-gyp/lib
 @ ./~/fsevents/~/node-pre-gyp/lib/node-pre-gyp.js 60:16-37
# and many more like this
```

How can I tell webpack and ts-loader not to include any module from node_modules and just use a `require` call instead?

**Comment by blakeembrey** [comment]
I don't believe this has anything to do with `ts-loader`. Is there something that makes you think it is? `ts-loader` is not actually invoked at all for JavaScript files. Can you provide more details about the errors? It sounds like you have a corrupt `node_modules` folder and I'd recommend removing it and re-installing.

**Comment by mohsen1** [comment]
I'll take a look at it tonight and let you know. I'm expecting webpack not to look at my node_modules at all

**Comment by blakeembrey** [comment]
Why? Any module require will definitely go into the node modules folder?

**Comment by mohsen1** [comment]
Because I'm compiling a Node.js program and node will require my modules in `node_modules`. I don't want to bundle all those modules...

**Comment by blakeembrey** [comment]
Then you should read the documentation of Webpack. It's not something `ts-loader` does itself. `tsconfig.json` is a configuration file for TypeScript, not Webpack, so you'd need to specify settings there. 

That said, you probably shouldn't be using Webpack to build node applications.

**Comment by blakeembrey** [comment]
Here's an example found by quickly searching google, https://stackoverflow.com/questions/33001237/webpack-not-excluding-node-modules, it's the first result if you search for "webpack exclude node_modules" and looks like what you want to do. For reference, loaders have nothing to do with Webpack exclusions (or many other Webpack settings). Loaders are there to transform files that you require.

**Comment by mohsen1** [comment]
Ah! I used `webpack-node-externals` before! I totally forgot about that! Thank you for pointing that out. 

This is my first Node.js app that uses TypeScript so I tend to blame everything on TypeScript and ts-node!  😄

**Comment by blakeembrey** [comment]
No worries, I'll close this issue if it's resolved.
