### ISSUE TITLE
Cannot find typings with typescript@beta and @types

### ISSUE THREAD

**Issue by SebastianStehle** [TypeStrong/ts-loader#243]
Hi,

I am testing the new beta version of ts 2.0. In Visual Studio Code everything looks fine, but when I run my webpack build I get a lot of erros like 

"Cannot find name Promise"
"Cannot find name Require"

I have added the same typings than before using the @types/... npm modules.

**Comment by blakeembrey** [comment]
Have you tried debugging anything or running it with `tsc`. I know for a fact it's not looked up automatically, so those errors make sense and probably are issues with `tsc` unless you've configured it. Please make sure this is a `ts-loader` and not a configuration issue by running `tsc` and providing a minimal reproduction.

**Comment by SebastianStehle** [comment]
Yeah, sure. When I run tsc standalone it works well (I get one error in angular2, but this is another problem ;))

**Comment by blakeembrey** [comment]
And is that a global version or a local version?

**Comment by SebastianStehle** [comment]
tsc? it is a global version, but the same version

**Comment by blakeembrey** [comment]
Can you provide a reproduction for someone to look over?

**Comment by SebastianStehle** [comment]
Sorry to waste your time. I was just too lazy to read the documentation carefully. I just have to add the typings to the types folder.

**Comment by seanchas116** [comment]
Hi, I reproduced this problem.

https://github.com/seanchas116/ts-loader-global-types

In this project, `tsc` just works but `webpack` (with ts-loader) fails with 
`Cannot find module 'path'.` and `Cannot find name 'process'.`

**Comment by SebastianStehle** [comment]
I realized that I have to add the 3 typings packages to the types config: types: ['core-js', 'node', 'jasmine']

Dont know why it works with tsc, but it works fine now.

**Comment by seanchas116** [comment]
Specifying `types: ['node']` in `compilerOptions` in tsconfig also fixed my project. (thanks @SebastianStehle !)

**Comment by gxsjtu** [comment]
i do not know why close the issue?
'can-use' and 'good-to-use' is different, it is redundant to declare types in tsconfig.json.

**Comment by blakeembrey** [comment]
@gxsjtu make a PR. There's duplicate issues for this which you have already commented on.
