### ISSUE TITLE
Module build failed: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by svdoever** [TypeStrong/ts-loader#246]
This error is given if no tsconfig.json is available... took me hours until I found the blogpost https://www.garysieling.com/blog/fixing-webpack-error-path-must-string-received-undefined

**Comment by pigcan** [comment]
+ 1

**Comment by chuwik** [comment]
Plus 1.
This was not happening when using Node 5.x, it only started happening for us when we upgraded to Node 6.x.

**Comment by johnnyreilly** [comment]
Fixed with 0.9.0
