### ISSUE TITLE
ESLINTstandard js output with this loader

### ISSUE THREAD

**Issue by istiti** [TypeStrong/ts-loader#248]
How can I config this ts-loader to output "eslint standard" javascript file

because I have in my webpack eslint activated to check my outputed js files and after passing in ts-loader all my js files are not js standard valid 

is there option to es-lint or feature will come, or other typescript compiler whose eslint compatible ? thanks

**Comment by blakeembrey** [comment]
@istiti The output is from TypeScript. It's designed to be readable, but it's not designed to be output according to specified JavaScript rules. In that case, it won't ever output an "ESLint standard" file. I'd recommend you don't lint generated code.
