### ISSUE TITLE
Writes a log message to stderr even when everything is OK

### ISSUE THREAD

**Issue by SteveSandersonMS** [TypeStrong/ts-loader#249]
When `ts-loader` starts up, it logs messages like this to stderr:

    ts-loader: Using typescript@1.8.10 and /some/path/tsconfig.json

This is because the `log` function calls `console.log.apply(console, message)`, and the `console` variable is overridden as follows:

    var console = new Console(process.stderr);

I know most of the log values outputted by `ts-loader` are errors, but the `Using typescript@...` message isn't an error. Logging it to stderr isn't great, because many apps are configured to treat stderr output as actual errors (and write it to a DB, email an administrator, etc.)

I am aware this can be suppressed by setting `silent` to `true`, but then this suppresses other potentially useful error information.

Would it be possible not to log the `Using typescript@...` to stderr, but still log other messages to stderror?

**Comment by jbrantly** [comment]
See #95 for a discussion on this.

**Comment by johnnyreilly** [comment]
Hi @stevesandersonms,

Is this still a problem for you? If so I think we're open to PRs (the discussion in #95 may be useful)

**Comment by SteveSandersonMS** [comment]
> Is this still a problem for you?

Thanks for getting back to me. No, it's not still a problem: we set `silent` to true by default in the project templates, and nobody has complained :)

**Comment by johnnyreilly** [comment]
Awesome 😄  As it happens we're likely to merge this [PR](https://github.com/TypeStrong/ts-loader/pull/313) which should provide an option to control this.  Not that you seem to need it but it should be there soon!

**Comment by johnnyreilly** [comment]
Released with 0.9.4
