### ISSUE TITLE
ts-loader doesnot pick up definitions from the typings field in package.json if the main field points to a .ts file

### ISSUE THREAD

**Issue by bipinpoudyal** [TypeStrong/ts-loader#250]
ts-loader is loading the typings if the main field points to a js file but if it points to a ts file, it doesnot load the typings folder. I have created a sample [project](https://github.com/bipinpoudyal/tsloader-issue) with the recreation steps.

I tried compiling the same using tsc and it compiles properly without any issues.

Refer to #170 for a discussion on the same issue.

**Comment by bipinpoudyal** [comment]
@blakeembrey I understand what you mean by the [comment](https://github.com/TypeStrong/ts-loader/issues/170#issuecomment-233420659) that we maynot need a typings field if the main is a .ts file. 

Like I said earlier, I was able to workaround this issue by exporting the definitions from the main .ts file which you can check in this [branch](https://github.com/bipinpoudyal/tsloader-issue/tree/workaround).

However TSC and IDE(Visual Studio) is able to resolve the definitions by just looking at the typings field in package.json whereas tsloader is not able to do the same.

**Comment by blakeembrey** [comment]
@bipinpoudyal Correct. Webpack will be resolving both type definition time (`typings`) and runtime (`main`) which will result in a lot of broken code in this example. I'd still love to see if it makes sense to fix it, I'm just trying to say it will probably still break after this is fixed. In my opinion, it seems reasonable to resolve `main.ts` even over the `typings` field since that's what would be used in runtime.

**Comment by xogeny** [comment]
@blakeembrey I came across this issue when trying to resolve a "related" issue.  I can open a separate issue if you want, but I at least wanted to make some kind of report about this.  I had a case where `main` pointed to an incorrect file in one of my dependencies.  Running `tsc` was no problem and didn't complain.  But when running `ts-loader` (via `webpack`), it came back with a:

```
Module not found: Error: Can't resolve '...'
```

I could not understand what was going on.  I mean `tsc` didn't report an error.  It would, of course, be nice if the error message said something more along the lines of "The 'main' entry for dependency '...' points to a non-existent file".

I'm not even sure if this is actually related to `ts-loader` or more to `webpack`.  In any case, as I said, I'm happy to open a separate issue if you want.

**Comment by aryzing** [comment]
Was having this issue with version 2.x.x, it seems that it's gone in version 3.x.x. Perhaps we could close this issue?

Could anyone else confirm that it's working with v3 for them as well? Thanks!
