### ISSUE TITLE
Source map merging problem when using tslint-loader

### ISSUE THREAD

**Issue by sinedied** [TypeStrong/ts-loader#253]
Hello,

I'm trying to build a upgrade basic angular workflow based on gulp to webpack, and I'm having sourcemap issues: I end up having the base *.ts sources referenced 2 times and it seems to be due to the `tslint-loader` preloader (I have no issues when I remove it).

I tried many config changes, but so far no luck.

Any ideas?

Here is my config:

``` js
'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('../gulpfile.config');
var webpack = require('webpack-stream');
var browserSync = require('browser-sync');

var $ = require('gulp-load-plugins')();

function buildScripts(watch, test, done) {
  var options = {
    resolve: {
      root: conf.src,
      modulesDirectories: [
        '.',
        'main',
        'modules',
        'libraries'
      ],
      extensions: ['', '.ts']
    },
    watch: watch,
    devtool: watch || test ? 'inline-source-map' : undefined,
    module: {
      preLoaders: [{
        test: /\.ts$/,
        exclude: /node_modules/,
        loader: 'tslint-loader'
      }],
      loaders: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          loaders: ['ng-annotate', 'awesome-typescript-loader']
        },
        {
          test: /\.html$/,
          loader: 'raw!html-minify'
        },
        {
          test: /\.po$/,
          loader: 'angular-gettext?module=translations'
        }
      ]
    },
    output: {
      filename: 'app.ts.js',
      devtoolModuleFilenameTemplate: '[resource-path]',
      devtoolFallbackModuleFilenameTemplate: '[resource-path]?[hash]'
    },
    'html-minify-loader': {
      empty: true,
      cdata: true,
      comments: true,
      conditionals: true,
      quotes: true,
      dom: {
        lowerCaseAttributeNames: false,
        lowerCaseTags: false
      }
    },
    tslint: {
      emitErrors: true
    }
  };

  var changeHandler = function(err, stats) {
    if (err) {
      conf.errorHandler('Webpack')(err);
    }

    $.util.log(stats.toString({
      colors: $.util.colors.supportsColor,
      chunks: false,
      hash: false,
      version: false
    }));

    browserSync.reload();

    if (watch) {
      console.log('yeah!');
      watch = false;
      done();
    }
  };

  var sources = [
    path.join(conf.paths.src, '**/*.ts'),
    path.join(conf.paths.src, 'translations/*.po'),
    path.join('!' + conf.paths.bower, '/**/*.ts')
  ];

  if (!test) {
    sources.push(path.join('!' + conf.paths.src, '/**/*.spec.ts'));
    sources.push(path.join('!' + conf.paths.src, '/**/*.mock.ts'));
  }

  return gulp.src(sources)
    .pipe(webpack(options, null, changeHandler))
    .pipe(gulp.dest(path.join(conf.paths.tmp)));
}

gulp.task('scripts', function() {
  return buildScripts(false, false);
});

gulp.task('scripts:watch', function(done) {
  return buildScripts(true, false, done);
});

gulp.task('scripts:test', function() {
  return buildScripts(false, true);
});

gulp.task('scripts:test-watch', function(done) {
  return buildScripts(true, true, done);
});
```

Here is the version of the packages I'm using:

```
"awesome-typescript-loader": "^0.17.0-rc.1",
"ng-annotate-loader": "^0.1.0",
"raw-loader": "^0.5.1",
"tslint": "^3.6.0",
"tslint-loader": "^2.1.3",
"typescript": "^1.8.9",
 "webpack-stream": "^3.1.0",
```

The generated sourcemaps by tslint have this suffix:

```
[code]

/** WEBPACK FOOTER **
 ** ./~/tslint-loader!./sources/main/main.config.ts
 **/
```

Whereas the "good" sourcemaps have this suffix:

```
[code]

/** WEBPACK FOOTER **
 ** ./sources/main/main.config.ts
 **/
```

I opened an issue on the `tslint-loader` repo (https://github.com/wbuchwalter/tslint-loader/issues/27) but after investigation it seems more related to `ts-loader` as it does not seems to use at all the input sourcemaps, which seems to cause the issue.

Any ideas?

**Comment by johnnyreilly** [comment]
I'm afraid not; closing as doesn't appear to be a specific problem with ts-loader

**Comment by sinedied** [comment]
@johnnyreilly in what way is it not specific to `ts-loader`?

As it appears `ts-loader` is not loading the sourcemaps passed in from the previous loader, causing an issue in the webpack sourcemap chain and resulting in having 2 copies of the files in the sourcemaps, making it really annoying when debugging.

Webpack plugins should properly load input sourcemaps in respect to the webpack chain, otherwise issues like this occurs, so I definitely think this is a ts-loader issue? What do you propose if not?

**Comment by johnnyreilly** [comment]
> As it appears ts-loader is not loading the sourcemaps passed in from the previous loader,

If this is true that's a shame. (I haven't checked.)  If you'd like to submit a PR to resolve the issue we'd be interested.  At present it's not something I have time to look at.

**Comment by sinedied** [comment]
I have tried looking into it, but the thing I'm unsure of is basically how to make the typescript compiler accepts input sourcemaps.

**Comment by johnnyreilly** [comment]
Sure - reopening for visibility

**Comment by jbrantly** [comment]
This was never done because it was Hard®. Or at least I didn't understand enough about source map internals to make it not hard for me. From my recollection into researching this issue, there are essentially two ways to "combine" source maps and there is not a clear consensus on which way is better. Assume you have a transformation from A -> B -> C (where B -> C would be ts-loader, in this case). Should the resulting source map contain the transformation directly from A -> C and exclude B. Or should it also contain the intermediary source B. (or something like that, I may have gotten that all wrong). 

In any case, I think it's theoretically possible to take the source map given by TypeScript and a source map given by webpack from a previous loader and combine them using [source-map](https://github.com/mozilla/source-map), but I don't know how exactly. I don't think it's possible to pass a source map into TypeScript, but it was quite a while ago that I looked and that may have changed by now.

**Comment by johnnyreilly** [comment]
Thanks for the background @jbrantly - very helpful!

**Comment by sinedied** [comment]
@jbrantly sure it doesn't look easy to do, I'll try to make quick test see if tools like https://www.npmjs.com/package/source-map-merger could help simplify the problem.
