### ISSUE TITLE
How to use global typescript compiler?

### ISSUE THREAD

**Issue by llyys** [TypeStrong/ts-loader#261]
I have the latest typescript next version in my machine
$ tsc --version
Version 2.1.0-dev.20160806

but when I run command from webpack I see that it still uses typescript version 1.8.10

$ webpack --config webpack-server.js
ts-loader: Using typescript@1.8.10 

How can I use the global typescript compiler or at least typescript version 2.0

**Comment by raybooysen** [comment]
Do you have typescript installed in your node_modules? If so, can you
uninstall and try again?

**Comment by llyys** [comment]
Hi, I figured it out.
to have a global typescript there you must to remove local typescript from project node_modules folder.
and then execute the command to link to the global typescript.
$ npm link typescript

now when I run the webpack command I see
ts-loader: Using typescript@2.1.0-dev.20160806

**Comment by johnnyreilly** [comment]
Hi @iv-mexx,

Just make typescript a devDependency of your project and you should be good to go...
