### ISSUE TITLE
error TS2307: Cannot find module when importing with inline loader

### ISSUE THREAD

**Issue by autochthe** [TypeStrong/ts-loader#264]
Typescript is unable to find the module if it is imported using an inline loader.

For example:

```
import Foo from 'exports!./foo.ts';
```

`exports` in this case is the [webpack exports-loader](https://webpack.github.io/docs/shimming-modules.html#exporting), which serves as a simple passthrough in this example.  The compilation is still successful, but we lose type checking within the module.

**Minimal example**
[ts-loader-module-resolution-bug.zip](https://github.com/TypeStrong/ts-loader/files/419122/ts-loader-module-resolution-bug.zip)

**Current behavior**
There are two test scripts:
`test.ts` uses the exports loader, and generates TS2307, compiles successfully but misses the type error on line 14.
`test2.ts` (identical except does not use exports-loader) properly finds the type error on line 14 (TS2345) when the function is passed a bad argument.

**Expected behavior**
`test.ts` should compile successfully and catch the type error on line 14.

The use case for the exports-loader in a real example would be to expose internal unexported functions in a module for unit testing.

**Environment**
- ts-loader: 0.8.2
- typescript: 1.8.10
- webpack: 1.13.1
- node: 6.2.2
- Operating System: Mac OSX 10.11.5

**Comment by davidspiess** [comment]
Same problem here. Any news on this?

**Comment by JuneAndGreen** [comment]
Same problem I met, how to solve it?

**Comment by carloscarvallo** [comment]
Same problem here
