### ISSUE TITLE
Possibility to support vue-loader?

### ISSUE THREAD

**Issue by HerringtonDarkholme** [TypeStrong/ts-loader#270]
Thanks for building ts-loader for webpack! I wonder whether ts-loader can support vue.js' single file component.

Related issue in vue-loader
https://github.com/vuejs/vue-loader/issues/109

The current problem is ts-loader cannot resolve files with extension name `.vue`. However, TypeScript compiler supports [customizing module resolution](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#customizing-module-resolution).

Since ts-loader has already implemented a custom `resolveModuleNames` function, supporting it is feasible.

 I tried locally and it works. However I'm a newbie to webpack and I think my try is dirty and hacky...

Do you have any good ideas? I'm happy to implement them.

**Comment by HerringtonDarkholme** [comment]
I forked ts-loader for this. But it seems ts-loader changes quite fast. Any possibility to support vue natively in ts-loader?

**Comment by johnnyreilly** [comment]
Quite possibly. I'm just doing a bit of a refactor on the code to get it to a more maintainable place. I'd be interested in getting vue support in once that's done. (I'm currently guessing I'll be done with the refactor inside a week or 2). 

Does adding `vue` to your webpack.config not resolve the issue?:

```
 resolve: {
    extensions: ['', '.ts', '.tsx', '.js', 'vue']
```

Forgive me if that's a naïve question; I have 0 vue experience....

**Comment by HerringtonDarkholme** [comment]
It still need some special handling in loader, but rather small modification.

https://github.com/HerringtonDarkholme/vue-ts-loader/commit/d581d4635776429ccf8090c11a1163710ad0a398

The core modification is appending `.ts` suffix to `*.vue` file, then every thing is fine. My concern is its hard coding nature.

**Comment by johnnyreilly** [comment]
I'm on my phone and so can't really look at this properly. But I think we can avoid hard coding and just add another option. As I see it

```
function appendSuffixToVue(fileName: string) {
    if (/\.vue$/.test(fileName)) {
        return fileName + '.ts';
    }
    return fileName;
}
```
Is something that tests a file path ends with `vue` and if so suffixes `.ts` on the end. So what say we introduce a ts-loader option called `appendTsSuffixTo` that, when supplied, is used to suffix `.ts` in the manner your fork does. Sound good?

**Comment by HerringtonDarkholme** [comment]
That's great. More generic. :+1:

**Comment by johnnyreilly** [comment]
Great - we'll need an integration test to cover this. You may already have one we can use. We've recently introduced "execution tests" as well as the pre-existing "comparison tests". Either will do. The comparison tests only run against the latest released version of TypeScript. The execution tests against all versions back to 1.6.

**Comment by HerringtonDarkholme** [comment]
I will submit a pull request once refactor is done. Looking forward to your refactor :)

**Comment by johnnyreilly** [comment]
Cool! The refactor is basically done. Just waiting on some feedback. Will let you know when I merge :smile:

**Comment by johnnyreilly** [comment]
https://github.com/TypeStrong/ts-loader/pull/343

**Comment by johnnyreilly** [comment]
Over to you... 1.0.0 has 🚢 😄

**Comment by HerringtonDarkholme** [comment]
Thanks! I need some time to understand what ts-loader does now, so please be patient.

**Comment by johnnyreilly** [comment]
No worries - I need that too!

**Comment by HerringtonDarkholme** [comment]
Is there any flaky test? vue-loader's output is indeed very flaky...

**Comment by johnnyreilly** [comment]
There are flaky tests in the comparison test pack.  Look out for a `_FLAKY_` file in the root of test directories.  This denotes a flaky test and a failure of this will not fail the build.  I think there's about 3 flaky tests; mainly down to platform issues.
