### ISSUE TITLE
Issue with transpiling ts files to js

### ISSUE THREAD

**Issue by kodali2446** [TypeStrong/ts-loader#273]
Hi
I am totally new to web pack. I'm trying to implement a task: “bundle and minify all the files with its dependencies in webpack-for reducing the number of http requests".
My project source code files are huge and I need to transpile typescript files to java script files and also manage their dependencies(which are js files that are in other folder named assets)and bundle all of them to a single file (along with dependencies) and put it in index.html.
So, I tried doing by integrating typescript and webpack.

AND IM GETTING THIS KIND OF ERRORS:tHE ERRORS SHOWN BELOW ARE IN MY PROJECT SRC FILES
 error TS2304: Cannot find name 'show_loading_bar'.
error TS2339: Property 'alert' does not exist on type 'JQueryStatic'
 error TS2304: Cannot find name 'neonRegister'.
error TS2339: Property 'select2' does not exist on type 'JQuery'.
 error TS2304: Cannot find name 'FB'.
error TS2339: Property 'modal' does not exist on type 'JQuery'.
error TS2339: Property 'confirm' does not exist on type 'JQueryStatic'.
error TS2339: Property 'modal' does not exist on type 'JQuery'.
 error TS2304: Cannot find name 'attrDefault'.
 error TS2339: Property 'niceScroll' does not exist on type 'JQuery'.
 error TS2339: Property 'val' does not exist on type 'JQueryEventObject'.
error TS2304: Cannot find name 'toggle_sidebar_menu'.
error TS2339: Property 'select2' does not exist on type 'JQuery'.
error TS2304: Cannot find name 'setup_sidebar_menu'.
error TS2304: Cannot find name 'setup_horizontal_menu'.
error TS2403: Subsequent variable declarations must have the same type.  Variable 'months' must be of type 'number', but here has type 'string'.

Can anyone please help me in doing this. Can you tell me the steps what I exactly need to do.

**Comment by Alexisvt** [comment]
Can you please provide your webpack config file and your tsconfig file, also will be good if you provide a repo where we can see your code

**Comment by johnnyreilly** [comment]
Closing as not an issue with ts-loader
