### ISSUE TITLE
webpack 1.13.2 + ts-loader 0.8.2 = masked errors

### ISSUE THREAD

**Issue by garthk** [TypeStrong/ts-loader#289]
TypeScript errors that should fail the build are being masked, with `webpack` indicating success.

Reproduction:

* `git clone https://github.com/garthk/webpack-and-ts-loader-mask-build-failures-demo.git`
* `cd webpack-and-ts-loader-mask-build-failures-demo`
* `npm install`
* `npm pack` or `node_modules/.bin/webpack`
* `echo $?`
* Observe `webpack` exiting with zero status, indicating success
* Observe tar-ball produced because `npm` acted on that "success"

I'd expect `webpack` to behave like `tsc` and, well, everything else we trust in our build chains:

* `node_modules/.bin/tsc`
* `echo $?`
* Observe `tsc` exiting with non-zero status, indicating failure

**Comment by johnnyreilly** [comment]
See the readme: https://github.com/TypeStrong/ts-loader/blob/master/README.md

**Comment by johnnyreilly** [comment]
(it can be made to fail following the instructions there)
