### ISSUE TITLE
Doesn't emit interfaces.d.ts

### ISSUE THREAD

**Issue by dizel3d** [TypeStrong/ts-loader#292]
I have 3 files:
- `interfaces.ts` with an interface,
- `classes.ts` with a class that implements the interface,
- and `main.ts` that exports all from them.

*webpack* builds `main.ts`. It emits `main.js`, `main.d.ts` and `classes.d.ts`, but doesn't emit `interfaces.d.ts`. However, `main.d.ts` and `classes.d.ts` refer to missing `interfaces.d.ts`.

Here's a [test-case](https://gist.github.com/dizel3d/fb85c8aab039629034f4825fe7c0aa8e)

**Comment by dizel3d** [comment]
I found 2 workarounds:
- Add `import './interfaces'` in `main.ts`. But `dts-bundle` (if you use it) produces invalid result.
- Add `export const __ts_loader_bug_fix__ = undefined;` to `interfaces.ts`.

**Comment by johnnyreilly** [comment]
I think / hope this will be resolved by https://github.com/TypeStrong/ts-loader/commit/3bb0fec73a2fab47953b51d256f0f5378f236ad1

**Comment by johnnyreilly** [comment]
Should be resolved with the 0.9 release
