### ISSUE TITLE
Can't prevent Linting via postLoaders if compile fails

### ISSUE THREAD

**Issue by fcntl** [TypeStrong/ts-loader#299]
Yes, it seems that using webpack-fail-plugin, one can cause webpack to return non-zero at the very end of the build...however that does not stop tslint running as a postLoader from reporting more issues (and crashing the build itself if "failOnHint" is true).

This module clearly needs a "failOnCompileError" option to halt the build if the ts->js compilation fails. No-one wants to see linting errors if the compile fails. Running linting before compilation is not recommended as it can spit chow.

**Comment by johnnyreilly** [comment]
Since linting is usually external to webpack generally (it certainly is in every project I've seen) then I don't think this is actually an issue for ts-loader.  Closing for now.  If you can provide an example of how linting plugs into webpack I'd be interested to see it.

**Comment by fcntl** [comment]
@johnnyreilly tslint-loader does it.
