### ISSUE TITLE
Is ts-loader compatible with TypeScript 2.1?

### ISSUE THREAD

**Issue by IRus** [TypeStrong/ts-loader#312]
From this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11864

Error:

```
ERROR in ./app/containers/position/Position.tsx
(13,20): error TS2307: Cannot find module 'moment'.
```

I used 
```
webpack: 2.1.0-beta.25
typescript: 2.0.3 (downgrade from 2.1.0)
ts-loader: 0.9.1
```

My tsconfig:
```
{
  "compilerOptions": {
    "sourceMap": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "noImplicitReturns": false,
    "strictNullChecks": false,
    "module": "es2015",
    "target": "es2015",
    "jsx": "react"
  }
}
```

**Comment by johnnyreilly** [comment]
Have you tried `allowSyntheticDefaultImports`?

```
 "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "module": "es2015",
    "moduleResolution": "node",
    "noEmitOnError": false,
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es2015"
  },
```

**Comment by johnnyreilly** [comment]
Oh and not forgetting `"moduleResolution": "node"`

**Comment by IRus** [comment]
Yep, this helps. Sorry for buzz and thanks for great work!

**Comment by IRus** [comment]
What you think if i create sample project using ts-loader with latest webpack to show how properly setup ts-loader? Does it make sense for ts-loader?

**Comment by johnnyreilly** [comment]
Could do yes - I haven't looked at the docs for a while but it could be worth having some samples if we don't already.

**Comment by lionelB** [comment]
@IRus  would be interested too. Do you have plan to create a gist ?

**Comment by IRus** [comment]
@lionelB yea, for sure. I think try to create PR for this repository, because then it would be coupled, and can be so sort of test.

**Comment by lionelB** [comment]
Oki cool..  can't wait to see it :)

**Comment by Paden** [comment]
Hey @IRus  did moduleResolution and allowSyntheticDefaultImports resolve your issue with tsloader? I can't seem to resolve it on my end.

**Comment by IRus** [comment]
@Paden yep. my config which works with 2.1:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "strictNullChecks": false,
    "module": "es6",
    "skipLibCheck": true,
    "target": "es5",
    "jsx": "react",
    "lib": [
      "dom",
      "es5",
      "es2015",
      "es2016",
      "es2017"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by Paden** [comment]
Ahh, I think I found my problem. I was referring to "moment.Moment" in a module without importing moment. I'm accustomed to the definitions being separate from the asset. Thanks for the quick response and help, @IRus.
