### ISSUE TITLE
[Compiler Options] Account for `allowJs` compiler option

### ISSUE THREAD

**Issue by dschnare** [TypeStrong/ts-loader#316]
Currently, even though the `allowJs` compiler option has been defined in a `tsconfig.json` or via the `ts.compilerOptions` config, JavaScript modules will not be found. I have resolved this issue, at least for my needs, by changing line 95 in `index.ts`.

Original: `const scriptRegex = /\.tsx?$/i;`
Changed: `const scriptRegex = /\.[jt]sx?$/i;`

I haven't ran into any issues yet. If anyone has time to fully test this use case out. I would greatly appreciate your efforts. I currently don't have time to dig into this for a few weeks. There may other cases in the source code where the file extension match needs to take into account the `allowJs` option as well.

**Comment by johnnyreilly** [comment]
Thanks for raising this issue @dschnare - if it's as simple as that (and it may well be) then I'd like to include this in a future release.  If you get the chance to dig into this we'd greatly appreciate a PR.

**Comment by johnnyreilly** [comment]
Actually I may look at this myself- fixing this way well resolve https://github.com/TypeStrong/ts-loader/issues/278

**Comment by johnnyreilly** [comment]
Hi @dschnare,

I'm planning to release a version of ts-loader that includes your suggested fix.  Would you be able to supply me with a repo that demostrates the problem when this is not available?  Try as I might I've struggled to reproduce the problem myself.  js seems to be resolved no matter what and I'd like to ensure that I have a test to cover this in terms of preventing regressions.

**Comment by dschnare** [comment]
Hey John,

It seems to occur when the entry point module is a JS file. It also
occurred when a TS entry point imports a JS module. I'll put up a repo for
you though in the next 24 hours.

**Comment by johnnyreilly** [comment]
Thanks chap!  Just readying the 0.9.3 release now which adds `allowJs` support - should ship in an hour or so.

I will look forward to the repo 👍

**Comment by dschnare** [comment]
@johnnyreilly version 0.9.3 resolved the issue I was having. I have pushed up a [repo](https://github.com/dschnare/xyfocus) that still uses 0.9.2 and can demonstrate the issue.

Steps to reproduce:
1. run `npm install`
2. run `npm run build:web`

The `build:web` npm-script uses Webpack to build out a browser-ready version of this module.

**Comment by johnnyreilly** [comment]
Excellent - thanks!

**Comment by johnnyreilly** [comment]
Great - I've used your repo to make a some better allowJs tests: https://github.com/TypeStrong/ts-loader/pull/325

**Comment by dschnare** [comment]
This issue has been re-introduced in version 1.3.3.

**Comment by johnnyreilly** [comment]
See discussion in https://github.com/TypeStrong/ts-loader/issues/388 @dschnare - this was intentional due to the implications of introducing that behaviour as a default (caused problems in certain scenarios). The behaviour you are after is still available but behind the `entryFileIsJs` ts-loader option. See the readme for details
