### ISSUE TITLE
local file with private class properties symlinked multiple times erroneously fails compilation

### ISSUE THREAD

**Issue by seansfkelley** [TypeStrong/ts-loader#324]
The title is a mouthful, but basically, I'm seeing https://github.com/Microsoft/TypeScript/issues/6496 on Typescript 2.0.3, but only when run through Webpack. I'm not 100% which of the many moving parts is at fault here, so I've cross-posted an issue here and as a comment on https://github.com/Microsoft/TypeScript/issues/6496.

The repro is sort of involved, so I made a repo to demonstrate: https://github.com/seansfkelley/typescript-lerna-webpack-sadness

**Comment by blakeembrey** [comment]
@seansfkelley Not a bug in `ts-loader`, as you already found 😄 It's an issue with TypeScript, see also https://github.com/Microsoft/TypeScript/issues/11436 and https://github.com/Microsoft/TypeScript/issues/7755. It's a bit of a PITA.

**Comment by seansfkelley** [comment]
What's strange about the repro I provided above is that it only seems to happen when running through Webpack. `tsc` behaves just fine (in line with https://github.com/Microsoft/TypeScript/issues/6496#issuecomment-254336000), but something about Webpack specifically seems to be causing issues. I wasn't able to nail down anything more precise than that repro though.

**Comment by blakeembrey** [comment]
Perhaps one is getting the realpath internally. No sure, hopefully there's some insights here for others 😄

**Comment by andy-ms** [comment]
This is working with `tsc` and with https://github.com/s-panferov/awesome-typescript-loader.
It looks like ts-loader's [ModuleResolutionHost](https://github.com/TypeStrong/ts-loader/blob/cc95c0bad454c7db455ca39456e90228594aced8/src/interfaces.ts#L197) only implements 2 methods.
Try implementing the optional methods in [ModuleResolutionHost](https://github.com/Microsoft/TypeScript/blob/2fc634f46048bb00f1cf27a798761fd70f269ec1/src/compiler/types.ts#L3550), particularly `realpath`.

**Comment by johnnyreilly** [comment]
Thanks for commenting @andy-ms. If you could submit a PR that would be greatly appreciated. John

**Comment by johnnyreilly** [comment]
Looking at the atl implementation it may be as simple as replacing `moduleResolutionHost` with `compiler.sys`

**Comment by johnnyreilly** [comment]
In the `compiler.resolveModuleName` call

**Comment by veeramarni** [comment]
Would there be a permanent fix or need to use the workaround? I think it was working with `awesome-typescript-loader`
