### ISSUE TITLE
@types/ts-loader

### ISSUE THREAD

**Issue by dizel3d** [TypeStrong/ts-loader#338]
It would be comfortable to install declaration below through `npm install @types/ts-loader`.
```ts
declare var require: {
    <T>(path: string): T;
    (paths: string[], callback: (...modules: any[]) => void): void;
    ensure: (paths: string[], callback: (require: <T>(path: string) => T) => void) => void;
};
```

**Comment by blakeembrey** [comment]
I don't think it should be `@types/ts-loader`. Also issues for `@types` declarations be logged in the owners repo, they have no control over it. All definitions for `@types` are from https://github.com/DefinitelyTyped/DefinitelyTyped. I would suggest a `@types/webpack` as a starting point, it doesn't really make sense to tie the definition to `ts-loader` as it's not related to it.

**Comment by blakeembrey** [comment]
In fact, there's already a `webpack-env` file - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/webpack/webpack-env.d.ts.

**Comment by johnnyreilly** [comment]
Ha! That could be useful to me.... 😄
