### ISSUE TITLE
file-loader with default export 

### ISSUE THREAD

**Issue by mohsen1** [TypeStrong/ts-loader#344]
I'm using TypeScript 2.0 wildcard module name matching to allow importing files like images:

```ts
declare module '*.png' {
    const fileName: string;
    export = fileName;
}
```

And now I can import images with ` * as ` syntax: 

```ts
import * as myImage from './my-image.png'
```

This works but I love to ditch the ` * as ` syntax and simply do `import myImage from './my-image.png'`. For that I can change the module declaration to:

```ts
declare module '*.png' {
    const fileName: string;
    export default fileName;
}
```
```ts
import myImage from './my-image.png'
```
Problem is, when I do this, the transpiled code becomes: 

```js
var myImage = require(42).default;
```

My `tsconfig`:
```
    "target": "es5",
    "module": "commonjs"
```

Do you have a recommendation for fixing this?

**Comment by johnnyreilly** [comment]
You could give this a go: (no guarantees)

```
"allowSyntheticDefaultImports": true
```

**Comment by johnnyreilly** [comment]
cc @mohsen1 - I'm sure you're past this now but see @andrewMuntyan in case you're not!
