### ISSUE TITLE
ts-loader loaded twice and webpack compilation 10x slower

### ISSUE THREAD

**Issue by Strato** [TypeStrong/ts-loader#345]
Hello,

I just upgraded my project to TypeScript 2.0.6, with ts-loader 0.9.5. My webpack compilation is now 10x slower.

I don't know where it comes from, but now I see in my console two lines for ts-loader instead of one in the past.

![image](https://cloud.githubusercontent.com/assets/662430/19775192/e62e0006-9c6f-11e6-8bfb-06cac6c960f9.png)

Actually webpack seems to be doing the whole job twice, since I'm seeing two reports back-to-back in the end.

While upgrading to TypeScript 2.0 I made a couple of changes to tsconfig.json.

```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "es5",
        "module":  "commonjs",
        "jsx": "react",
        "lib": [ "dom", "es2015", "scripthost" ],
        "experimentalDecorators": true,
        "noImplicitAny": false,
        "strictNullChecks": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true
    },
    "compileOnSave": false,
    "exclude": [
        "node_modules"
    ]
}
```

Also I used to use _typings_ which is no longer the case. I switched to the new @types system from npm.

webpack.config.js has not changed at all. It's a bit long so I'm not putting it here for the moment.

I can't say if it comes from the TypeScript compiler, ts-loader, webpack. I tried a lot of combinations, turning source maps generation off, going back to ts-loader 0.8.2, to no avail.

Do you have any idea what could be wrong, and in the first place, why I see two ts-loader lines?

**Comment by johnnyreilly** [comment]
I haven't used ts 2.0.6 but I've got no issues with ts 2.0.3 (and I'm running with a similar setup to you, just using Babel to handle transpilation).  I also don't have duplicate "using TypeScript..." messages. I suspect this is something to do with your setup.  I'll close for now as this doesn't seem to be a specific problem with ts-loader. Please reopen if you can confirm what there is a problem. In the meantime you might want to look at my (similar) setup here: https://www.github.com/johnnyreilly/proverb-signalr-react

**Comment by wpitallo** [comment]
I am having the exact same issue when i upgraded to ts 2.0.6 is a big project and has just become horribly slow :(
