### ISSUE TITLE
Error when using unions

### ISSUE THREAD

**Issue by MaklaCof** [TypeStrong/ts-loader#346]
I am not sure to whom I should address this  issue. Hope this is the right place.
When I try webpack typescript I get this error:

> ERROR in ./scripts/htmlforms/firms.ts
> (126,16): error TS2322: Type 'Promise<{}>' is not assignable to type 'Promise<IResult | null>'.
>   Type '{}' is not assignable to type 'IResult | null'.
>     Type '{}' is not assignable to type 'IResult'.
>       Property 'name' is missing in type '{}'.
> 
> ERROR in ./scripts/htmlforms/firms.ts
> Module build failed: Error: Typescript emitted no output for D:\WebClient\trunk\OpPISWebClient\scripts\htmlforms\firms.ts
>     at Object.loader (D:\WebClient\trunk\node_modules\ts-loader\index.js:456:15)

My code is:
```
awaitConfirm(): Promise<IResult | null>
    {
        return new Promise((resolve, reject) =>
        {
            this.callback = resolve;
        });
    }
```
webpack.config.js is:
```
module: {
        loaders: [
          { test: /\.ts$/, loader: 'ts-loader' }
        ]
    },
```
and tsconfig:
```
{
  "compilerOptions": {
    "module": "amd",
    "noEmitOnError": true,
    "noImplicitAny": true,
    "removeComments": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es6",
    "experimentalDecorators": true
  },
    "exclude": [
        "node_modules",
        "wwwroot"
    ]
}
```
I hope this is enought information to fix this issue.

**Comment by johnnyreilly** [comment]
Closing as not an issue with ts-loader as far as I can see. I advise looking at examples to see how to use ts-loader/WebPack
