### ISSUE TITLE
Webpack 2 and typescript 2.0.6 results in TS1192

### ISSUE THREAD

**Issue by Aleksion** [TypeStrong/ts-loader#349]
It's a rather specific scenario, but with Webpack 2 and typescript 2.0.6 (might be happening on other versions as well), I get the following error when trying to use the library react-toolbox in my code (it's not happening for my own ts files or the other d.ts file i've loaded)

```
error TS1192: Module '".../node_modules/react-toolbox/lib/index"' has no default export.
```

Adding ``allowSyntheticDefaultImports`` to tsconfig.json results in other random errors: (TS2305 among others.)

While this could seem like a typescript error, everything works as expected in both visual studio code (it can read the typings properly), and it compiles correctly when running tsc.

part of my webpack.config.json:

```
module: {
    rules: [
      {
        test: /\.tsx?$/, 
        use: ['babel', 'ts-loader'],
        exclude: /node_modules/
      },
    {
        test: /(\.js|\.jsx)$/,
        include: [/src/, /node_modules\/react-toolbox/],
        use: 'babel',
        query: { presets: ['es2015', 'stage-0', 'react'] }
      },
      {
        test: /(\.scss|\.css)$/,
        use: [
            "style",
            "css?sourceMap&modules&importLoaders=2&localIdentName=[name]__[local]___[hash:base64:5]",
            "sass?sourceMap&sourceMapContents&outputStyle=expanded"]
      }
    ]
  },
```

and my tsconfig.json:

```
{
    "compilerOptions": {
        "module": "es2015",
        "target": "es6",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "outDir": "./dist",
        "sourceMap": true,
        "allowJs": true,
        "jsx": "react",
        "allowSyntheticDefaultImports": true
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "**/*.test.ts",
        "**/*.spec.ts",
        "node_modules"
    ],
    "compileOnSave": false,
    "buildOnSave": false
}
```

It's probably an error on my behalf, but I've been hitting the wall on this all day, so I was hoping a kind soul might know the way past it :)

**Comment by johnnyreilly** [comment]
I've never used WebPack 2.0 but I do notice that whilst your supplying presets to Babel for your JSX/JS, you're not when using TypeScript. I'm assuming you're emitting es2015 from TypeScript and having babel-loader do the transpilation?

**Comment by johnnyreilly** [comment]
See https://github.com/johnnyreilly/proverb-signalr-react/blob/master/webpack.config.js

**Comment by johnnyreilly** [comment]
Closing as probably not a ts-loader specific problem
