### ISSUE TITLE
Does ts-loader support HMR?

### ISSUE THREAD

**Issue by tobico** [TypeStrong/ts-loader#352]
I'm trying to get hot reloading working in my TypeScript project, following this example here: https://github.com/krausest/ts-webpack-hmr

The example code README states that ts-loader does not support HMR, but there also appears to be issues here that suggest it does. I can't switch to awesome-typescript-loader right now, as it appears to be incompatible with the "pixi.js" library that I'm using.

I've tried following the example, and while I'm able to call the `module.hot.accept` method, webpack doesn't seem to pick it up when I change my module, and reloads the entire page.

Does ts-loader support HMR, and if so, would anyone have a working example I can refer to?

**Comment by johnnyreilly** [comment]
Based on what I've read in the source code and the docs: 
- https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack
- https://webpack.github.io/docs/hot-module-replacement.html

Then I don't think ts-loader is directly supporting HMR no.  I wasn't aware of this API until you mentioned `module.hot.accept`.  That said; having a quick look at the atl code I can't see where they are hooking in to support this either.

If there's something we're missing (sounds like it) we're open to PRs!

**Comment by johnnyreilly** [comment]
https://github.com/TypeStrong/ts-loader/pull/322

That said others seem to be using hmr successfully. Maybe @dopare could share his setup?

**Comment by dopare** [comment]
I am using [this template](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa).
Using angular2 with dotnet core.

**Comment by kirillgroshkov** [comment]
It works for me if I set `transpileOnly: true` and `isolatedModules: true`!

**Comment by johnnyreilly** [comment]
In short - yes.  Use `transpileOnly: true` and use the `fork-ts-checker-webpack-plugin` for typechecking.

**Comment by johnnyreilly** [comment]
I'll try and add an example at some point

**Comment by johnnyreilly** [comment]
See our [hot example](https://github.com/TypeStrong/ts-loader/tree/master/examples/hot)

**Comment by rbonomo** [comment]
> See our [hot example](https://github.com/TypeStrong/ts-loader/tree/master/examples/hot)

404

**Comment by Pong420** [comment]
https://github.com/TypeStrong/ts-loader#hot-module-replacement

create an other entry ( `hot.ts` ) and  re-require the main entry ( `main.ts` ) inside the HMR  callback function

```ts
require('./main');

if (module.hot) {
  module.hot.accept(['./main'], function () {
    require('./main');
  });
}
```

webpack.dev.js
```js
module.exports = {
  mode: 'development',
  entry: ['./src/hot.ts'],
  // ....
}
```


webpack.prod.js
```js
module.exports = {
  mode: 'production',
  entry: ['./src/main.ts'],
  // ....
}
```
