### ISSUE TITLE
Visual Studio compatible error output

### ISSUE THREAD

**Issue by gamli** [TypeStrong/ts-loader#355]
The error format in the case of TypeScript compilation errors is not recognized by Visual Studio if Webpack with TS-Loader is used in a Build Event (i.e. errors are not shown with the correct file name in the Error List).

I implemented the feature for myself by replacing line 29 of utils.js

`message: "" + '('.white + (lineChar.line + 1).toString().cyan + "," + (lineChar.character + 1).toString().cyan + "): " + messageText.red,`

by

`message: path.normalize(diagnostic.file.fileName).red + '('.white + (lineChar.line + 1).toString().cyan + "," + (lineChar.character + 1).toString().cyan + "): " + messageText.red,`

So i wonder if this is something that could go into TS-Loader.

Kind Regards
   Markus

**Comment by johnnyreilly** [comment]
PRs are welcome!

**Comment by gamli** [comment]
Thx for the fast response :)
I created a PR (#356) for it.
The change itself is simple, but I had to change 63 files that contain the expected output.

**Comment by johnnyreilly** [comment]
Merged.
