### ISSUE TITLE
Crash when adding/removing files in watch-mode since 0.9.5

### ISSUE THREAD

**Issue by jbbr** [TypeStrong/ts-loader#358]
Since version 0.9.5 ts-loader crashes for me when adding new ts-files, deleting  and maybe other cases.
I can say for sure that switching from 0.9.5/1.0.0 back to 0.9.4 fixes this issue.

Steps:
- Run webpack in development configuration (webpack-dev-server, watch mode...)
- Add a new *.ts file
- Crash:

```js
/myproject/node_modules/ts-loader/dist/after-compile.js:50
            Object.keys(instance.modifiedFiles).forEach(function (modifiedFileName) {
                   ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Compiler.<anonymous> (/myproject/node_modules/ts-loader/dist/after-compile.js:50:20)
    at next (/myproject/node_modules/meteor/webpack_webpack/node_modules/tapable/lib/Tapable.js:83:14)
....
```

Workaround/Fix:
Change the line https://github.com/TypeStrong/ts-loader/blob/master/src/after-compile.ts#L63 makes this error go away.

from `Object.keys(instance.modifiedFiles).forEach ...`
to `Object.keys(instance.modifiedFiles || {}).forEach ...`

I'm not sure if this is a good fix or if this might cause other troubles - so I did not create a pull request.

Environment:
> Webpack 2.1.0-beta.25
> Typescript 2.0.7
> ts-loader 1.0.0
> Webpack within Meteor (meteor-webpack)

I know that the configuration (Webpack 2.x, Webpack integrated into Meteor...) is not really supported. But as I can definitely say that this was introduced with 0.9.5 and a fix is probably as easy as the undefined check, this might still be worth reporting.

**Comment by jbbr** [comment]
@johnnyreilly Sorry for accidentally posting before writing my issue. I added a description now. Maybe you could reopen it now?

Unfortunately I was not yet able to reproduce this behavior in a simple demo-repository outside of a meteor project but I was able to circumvent/fix this issue with a little undefined check.

Thanks in advance.

**Comment by johnnyreilly** [comment]
Thanks for the report!

**Comment by johnnyreilly** [comment]
(and suggestion :smile: )

**Comment by johnnyreilly** [comment]
Do you fancy submitting a PR with your suggested fix in? I think it's an improvement and so I say we should include it.

**Comment by jbbr** [comment]
Thank you very much for fixing this.
I would have submitted a PR now but I see you made a lot more adjustments as I would have with my small workaround.

I'm using v1.2.0 now and didn't had any crashes since.

**Comment by johnnyreilly** [comment]
No problem - to be honest the other changes are just refactoring. The actual solution is down to you - I just implemented it differently. Thanks for suggesting!
