### ISSUE TITLE
ts vue file extension 

### ISSUE THREAD

**Issue by druppy** [TypeStrong/ts-loader#366]
Hi ... 

Now that `ts-loader` are more and more the main plugin for webpack I then tried to build up a workflow using this. And VueJS has since v2 been very attractive.

I have tried to make a setup where I can mix vue files containing typescript, and normal typescript files, and i hope one day for real tsx files to have react like coding style (we are so close).

The new `appendTsSuffixTo` is nice for Webpack, it will read the vue file, append a ts ext in it inside webpack (as far as I understand it) and make a nice component output.

But, when I use my editor (vscode in this case), tsc complains that the `*.vue` file is not know to it, as it can't really read these, and therefore complains. 

The fun part is that webpack understand the vue `import` as it resolve differently inside webpack than plain simple tsc. This means that the editor will mark the `import` as invalid, but webpack is cool about it.

Has anyone solved this, or are we waiting for a more flexible tsc loader, or need we to have a preloader `vue -> d.ts` step of a kind ?

**Comment by druppy** [comment]
I was thinking of adding this kind of definition to one of my global definition files.

``` typescript
declare module "*.vue" {
    const content: any; // The Vue class would be a better choice
    export default content;
}
```

This is a start as long as I just add these components to my views and don't intent to make any interactions with its static interface on the Vue component.

I can't import 'Vue' into the definition file, so `any` must be it then for now.

Any better idea's ?

**Comment by johnnyreilly** [comment]
@HerringtonDarkholme do you have any advice?

**Comment by HerringtonDarkholme** [comment]
Hi, let me explain it separately.
1. vscode complains about unknown extension: this is basically the limitation of compiler core. Sorry we cannot do much here. The workaround is exactly adding an wildcard ambient declaration.

2. import Vue into definition file: actually I have done that before. 

```ts
import Vue = require('vue')
declare module "*.vue" {
  const content: Vue
  export default content
}
```

This should work. If not, please specify the compiler version. A similar but different example is here

https://github.com/HerringtonDarkholme/vue-loader-test/blob/master/src/components/nani.vue.d.ts

**Comment by druppy** [comment]
@HerringtonDarkholme Thanks for the input, this was my idea too, but a `import Vue = require( 'vue' )` in the d.ts files, makes all other parts of the `d.ts` definition file break.

Normally import is not possible in a definition files only `/// <reference path='...` and Vue types have no interfaces for Vue anymore only a class :-)

**Comment by HerringtonDarkholme** [comment]
Hmmm, this is also typescript's feature. Once an `import` is added, all ambient declaration will not work.
But you can separate vue module declaration from normal ambient declaration. Or use a third party library like. https://github.com/locoslab/vue-typescript-import-dts

**Comment by druppy** [comment]
Ok, it is fine to have vue files import as `any` for now, as I only bind them to my components and use them in the template's. We don't get any typing help there, anyway.

Now that TypeScript has gotten the `--jsxFactory` option merged, we may soon have a bit more focus on using `.tsx` files more natively, and if this include more type checking in the templates I am really happy. 

I have been considering React many times, just because of the maturity of its TS integration, but the reactive and minimalistic nature of Vue always get me back :-)

**Comment by HerringtonDarkholme** [comment]
I'm not familiar with tsx. But given the [doc](https://www.typescriptlang.org/docs/handbook/jsx.html), I'm quite worried about the current approach in Vue+TS. At least no one library provides a `prop` field or so.

Any way, jsxFactory option should be well supported by ts-loader. And ts-loader can play well with babel plugin. Building shouldn't be the bottleneck of a new approach.

**Comment by druppy** [comment]
@HerringtonDarkholme are you thinking about static analysing of props ?, that would be a really nice feature, at the moment most of that is done runtime.

Chaining tsx via jsx and then babel seems fine, but it also seems a bit heavy on the building system, subjectively I really love to see a more 'pure' approach.

**Comment by HerringtonDarkholme** [comment]
That will be an interesting idea. But ts-loader's issue isn't a good place for discussing vue-specific topic.

You can go to [here](https://github.com/HerringtonDarkholme/av-ts), a repo where I also want to support vue by code transformation. Or typescript's source repo for feature request.
