### ISSUE TITLE
Config query param instead of config file 

### ISSUE THREAD

**Issue by mohsen1** [TypeStrong/ts-loader#370]
We have a different tsconfig for webpack and currently it's a separate file that we refer to from webpack config with the `configFileName` option. Our webpack specific config file is a little different than our original `tsconfig.json` file.

If there was an option to pass tsconfig as an object to ts-loader we can remove the secondary file and instead require our tsconfig and make our modifications before passing it to ts-loader.

Please add a `tsconfig` option that accepts contents of `tsconfig.json` file.

**Comment by HerringtonDarkholme** [comment]
Hi, I think we already have it. https://github.com/TypeStrong/ts-loader#compileroptions-object-default

**Comment by mohsen1** [comment]
That is limited to compiler option but it's not possible to add configuration options outside of that

**Comment by HerringtonDarkholme** [comment]
What more do you want? CompileOnSave? files/include/exclude? I think none of these is useful in ts-loader.

**Comment by mohsen1** [comment]
`files` specifically but now I solved that problem with `types` in compiler option so I think you're right.

**Comment by abirmingham** [comment]
I ran into a need for this where I want to exclude test files during the normal build, and include them when running karma. I could have two tsconfig files but I'd prefer to have one with separate parameters.

**Comment by m1neral** [comment]
`files` would be very useful!!!!
