### ISSUE TITLE
Re-exported const enums break emit in watch mode

### ISSUE THREAD

**Issue by smphhh** [TypeStrong/ts-loader#376]
Given

bar.ts:
```typescript
export const enum BarEnum {
    Bar = 1
};
```
foo.ts:
```typescript
export { BarEnum } from './bar';
```
app.ts:
```typescript
import { BarEnum } from './foo';
console.log(BarEnum.Bar);
```
the emit for app.ts in the initial build looks like the following:
```javascript
"use strict";
console.log(1 /* Bar */);
```
After changing bar.ts to
```typescript
export const enum BarEnum {
    Bar = 2
};
```
no modules will be rebuild. The expected output after the change would be
```javascript
"use strict";
console.log(2 /* Bar */);
```

This is because ts-loader currently only adds the direct dependencies of modules as dependencies to webpack. Because bar.ts is not a direct dependency of app.ts, app.ts will not be rebuild when bar.ts changes.

For semantic errors the deeper dependencies are handled in the after-compile hook, but this doesn't help in cases like const enums where the actual emit can depend on deeper dependencies.

I believe awesome-typescript-loader does add all actual dependencies of a module as webpack dependencies recursively, which I think is the only way to handle these (relatively rare) cases correctly.

I'll post a pull-request with a test showcasing this error.

**Comment by johnnyreilly** [comment]
Thanks for the issue and the PR illustrating the issue. I think you're right - it's a problem. If you get the time to take a look at this that'd be awesome. I'm not sure when I'd get time to look myself.

**Comment by smphhh** [comment]
I can probably at least play around with this.

**Comment by johnnyreilly** [comment]
Awesome - every little helps :wink:

**Comment by johnnyreilly** [comment]
Fixed with https://github.com/TypeStrong/ts-loader/pull/377 - thanks @smphhh!
