### ISSUE TITLE
Improve architecture of the loader.

### ISSUE THREAD

**Issue by Strate** [TypeStrong/ts-loader#382]
Hey all. I want to suggest you some improvements, please tell me what do you think about it.

I think that typescript loader should not be loader at all :) I think it should be plugin + loader, where plugin startup tsserver, and loader communicate with it (as vscode do). This improvement could significant improve performance of the build, because typescript compilation process would not break webpack process, as tssserver would start in separate process.

**Comment by johnnyreilly** [comment]
Sounds interesting - I'm guessing this would significantly increase the complexity though?  I'm not familiar with VSCode's codebase and so can't say I understand the implications of the proposed change.

**Comment by Strate** [comment]
Of coulrse this would increase complexity, we should interop with tsserver, this could be tricky.

**Comment by johnnyreilly** [comment]
Feel free to have a go implementing this in a fork.  I'd be really interested to see what the results look like.  We could take a view then as to whether any added complexity "earns it keep" in terms of performance / stability.  Could be interesting!

**Comment by HerringtonDarkholme** [comment]
Why? tsserver is based on typescript service. Using tsserver means you will lose a lot of customization available only in service.

**Comment by s-panferov** [comment]
@HerringtonDarkholme

**Comment by s-panferov** [comment]
I've already tried this approach in awesome-typescript-loader, I can share the code with you. In fact, it significantly *slower* (2-3 times) in webpack cases and also right now tsserver don't have commands to emit files with response back to client:

https://github.com/Microsoft/TypeScript/issues/11468

**Comment by johnnyreilly** [comment]
Thanks for sharing that link @s-panferov.
