### ISSUE TITLE
Why are the `tsconfig.json`'s compilerOptions overriden by the options defined in the loader ?

### ISSUE THREAD

**Issue by onigoetz** [TypeStrong/ts-loader#384]
Hi

First, thanks for your work! We use ts-loader all the time in our projects, the work you do to constantly improve it is really appreciated.

In the company I work for we have a tool similar to Facebook's `create-react-app`, a package that gives you all default configuration (webpack, postcss, eslint ...) for your project that you can then override to match your needs.

I'm curious why, if you set a value in `compilerOptions` passed to the loader configuration it overrides what is set in `tsconfig.json` ?

(Here in the code: https://github.com/TypeStrong/ts-loader/blob/master/src/config.ts#L55-L57)

Shouldn't it be the other way around ? You define your defaults in the ts-loader and if needed you override in `tsconfig.json` ? 

Thanks in advance for your answer.

**Comment by johnnyreilly** [comment]
I'm afraid I don't know anything about this flag; it was implemented prior to my involvement.  @jbrantly may be able to advise?

**Comment by jbrantly** [comment]
I idea is that it's a lot harder to customize external tooling than it is webpack. So you set up your tsconfig.json to work with things like Visual Studio Code, etc and then if you need any special customizations in the webpack build you can place those in the webpack config.

**Comment by jbrantly** [comment]
I should say, in the ideal (and usual) scenario you just have a tsconfig.json and no customizations in the webpack config. I think it's rare that you need to override anything and so the defaults should go in tsconfig.json so that it's usable by all TypeScript aware tooling.

**Comment by HerringtonDarkholme** [comment]
IMHO @jbrantly 's decision is very sensible. We can execute javascript in webpack configuration which can be arbitrarily flexible. In my own experience webpack customization is very helpful when developing environment and deploying environment are different.
