### ISSUE TITLE
Escaped octal literals cause problems?

### ISSUE THREAD

**Issue by xogeny** [TypeStrong/ts-loader#394]
If I include the following code in a `.ts` file:

```
import { cssRaw } from 'typestyle';

export function injectCSS() {
    cssRaw(`.glyphicon-pencil:before{content:"\270f"}`)
}
```

...that is loaded with `ts-loader`, I get the following error:

```
ERROR in ./src/style/bootstrap.ts
Module parse failed: /Users/mtiller/Source/Simran/simran/node_modules/ts-loader/index.js!/Users/mtiller/Source/Simran
/simran/src/style/bootstrap.ts Octal literal in strict mode (4:58)
You may need an appropriate loader to handle this file type.
| const typestyle_1 = require("typestyle");
| function injectCSS() {
|     typestyle_1.cssRaw(`.glyphicon-pencil:before{content:"\270f"}`);
| }
| exports.injectCSS = injectCSS;
```

This is with `ts-loader` version `1.2.2` (running webpack 2).  To be clear, the string in question **is quoted with backticks**.  The TypeScript compiler itself has no issue with this and the error seems to be coming from the `ts-loader/index.js` script.

Of course, it is possible that this is actually a `webpack` issue and I'm barking up the wrong tree.  Just let me know if that is the case.

**Comment by johnnyreilly** [comment]
@basarat - possibly you can advise?

**Comment by blakeembrey** [comment]
You can't use octal literals with TypeScript modules, they aren't allowed in strict mode according to the ES spec.

**Comment by xogeny** [comment]
FYI, if I change my code to:

```
import { cssRaw } from 'typestyle';

export function injectCSS() {
    cssRaw(`.glyphicon-pencil:before{content:"\\270f"}`)
}
```

All is fine. I'd be surprised if I have to actually escape octal sequences *inside* a template string...but who knows.  I got the compilation to work.  I thought that perhaps my CSS would be messed up and all these octal sequences would be unnecessarily escaped.  But it doesn't look like it.  When I look at the `<script>` tag that gets injected by `typestyle`, it looks OK to me.

What I have not yet been able to determine is what the semantics of `\` is in a template string.  I know that you can escape a '`' with `\`' but I'm not aware of any other escaping that is taken into account.  I suspect, but cannot prove, that I should not have to add these extra `\` characters.  The fact that it "works itself out" makes me nervous...I don't want to rely on that.  But I'm not sure where in this whole chain something is being mishandled.

So at least there is a workaround.

**Comment by blakeembrey** [comment]
You should be using two backticks anyway, as one backtick means you're writing an octal literal. It's not allowed according to the ES spec and it's probably Webpack trying to warn you here (it's a bummer TypeScript didn't catch it actually).

![image](https://cloud.githubusercontent.com/assets/1088987/20774071/86be346a-b709-11e6-96b3-6bce087f2cf9.png)

**Comment by blakeembrey** [comment]
You can review how the backslashes work, but it is _always_ an escape character in strings. If you literally want a backslash, you need to escape the backslash with a backslash (hence using two backslashes). One backslash is an escape code (e.g. octal literals, `\n`, `\t`, `\r`, etc). See https://en.wikipedia.org/wiki/Escape_character.

**Comment by xogeny** [comment]
I'm familiar with escape characters (I've used them in many languages).  What surprised me here is that they aren't allowed in *template strings*.  Since template strings are frequently used to build strings *in other languages* and the main purpose of the is to *avoid* having to escape all kinds of stuff, it seems odd that they should apply Javascript semantics to octal literals inside the template string.  The underlying language may not even be Javascript (as in this case), so it seems rather arbitrary.

Fortunately, it seems like there is an effort to change this:

https://tc39.github.io/proposal-template-literal-revision/

Thanks for the help!

**Comment by blakeembrey** [comment]
Even if changed, I'm sure they still won't be allowed in strict mode (the original error). Your file is implicitly in strict mode if you're using ES6 modules.

**Comment by blakeembrey** [comment]
Ah, that's an interesting proposal:

> This loosening of the escape sequence restriction only applies to tagged template literals; untagged templates still throw an early error for invalid escape sequences
