### ISSUE TITLE
Extracts string messages from React components that use React Intl

### ISSUE THREAD

**Issue by bang88** [TypeStrong/ts-loader#395]
Hi all:

We plan use TypeScript in our new project with React instead of Babel,we use react-intl manage our locales,we use this plugin https://github.com/yahoo/babel-plugin-react-intl for messages extracts before, But now we don't use Babel and how can we do the same thing with `ts-loader` like tools.or does `ts-loader` has any options when transform TypeScript files we can use.

Thanks you.

**Comment by johnnyreilly** [comment]
Sorry this isn't an issue - please try stackoverflow
