### ISSUE TITLE
"allowJs": true leads to error in decorators "error TS1240: Unable to resolve signature of property decorator when called as an expression."

### ISSUE THREAD

**Issue by pqr** [TypeStrong/ts-loader#401]
TypeScript 2.0.10
ts-loader 1.2.2
Webpack 1.13.2

When using decorators from https://github.com/mobxjs/serializr library I see error "error TS1240: Unable to resolve signature of property decorator when called as an expression."

manual run ``tsc`` also works fine.

Regression introduced in [v0.9.3](https://github.com/TypeStrong/ts-loader/releases/tag/v0.9.3)
0.9.2 works fine!

I created minial repository to show the error: https://github.com/pqr/ts-loader-issue-401

**Comment by johnnyreilly** [comment]
Possibly related to https://github.com/TypeStrong/ts-loader/issues/388

Could you try the amend suggested there and see if that resolves your issue as well?

**Comment by pqr** [comment]
@johnnyreilly I changed that line to ``const scriptRegex = /\.tsx?$/i;`` and now it compiles without the error!

**Comment by johnnyreilly** [comment]
Thanks! - I'll be doing something about this. Just need to work out a plan of action. Watch this space

**Comment by johnnyreilly** [comment]
Should be resolved with 1.3.0
