### ISSUE TITLE
Error message newlines are confusing

### ISSUE THREAD

**Issue by nfriend** [TypeStrong/ts-loader#402]
When I listen for errors from `webpack-stream` using `.on('error')` and print the results to the console, the newlines in the error messages make the output hard to read.  Here's an example:

![image](https://cloud.githubusercontent.com/assets/1638631/20903110/7bbe7128-bb10-11e6-808e-8dd00d7a1c08.png)

In the screenshot above, the first two errors are occurring in `./app/index.ts` while the last is occurring in `./app/main-layout/main-layout.controller.ts`.  I'm assuming the newline that's after the file path should actually be appearing after the error message itself, so that you'd instead get something like:

```bash
./app/index.ts (26,3): error TS1005: ';' expected.
./app/index.ts (26,3): error TS2304: Cannot find name 'wes'.
./app/main-layout/main-layout.controller.ts (9,9): error TS2304: Cannot find name 'asdf3'.
```

This is how I'm getting the error message and logging the message to the console in my `gulpfile.js`:

```javascript
return gulp.src('./app/**/*.ts')
    .pipe(webpackStream(webpackConfig, null, onBuildFinished)
        .on('error', function handleError(err) {
            gutil.log(gutil.colors.bgRed('Webpack bundle error'));
            gutil.log(err.message);
            this.emit('end');
        }))
    .pipe(rename(outputFilename))
    .pipe(gulp.dest(outputDirectory));
```

I'm using Webpack 1.13.3, ts-loader 1.2.2, node 6.7.0, gulp 3.9.1, and `cmd` on Windows 10.

**Comment by johnnyreilly** [comment]
Feel free to submit a PR to improve things.  I can't guarantee we'll take it but we'll certainly consider it seriously.
