### ISSUE TITLE
Not working with @types migration

### ISSUE THREAD

**Issue by aaronbeall** [TypeStrong/ts-loader#403]
I posted my issue on StackOverlfow: http://stackoverflow.com/questions/40984172/moving-from-typings-to-types-with-webpack-ts-loader

In summary: I have a TypeScript project that uses `ts-loader` and previously `typings` with a bunch of installed type definitions. I migrated to TS 2.0.10 and converted all typings from `typings.json` to `@types` dependencies. It works fine with `tsc` but when I run through webpack with `ts-loader` I get a lot of errors that seem as though it cannot resolve the typing definitions.

My `tsconfig.json` looks like this:

```json
{
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "./compiled",
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "noImplicitAny": true,
    "sourceMap": true,
    "skipLibCheck": true
  },
  "exclude": [
    "node_modules",
    "compiled",
    "dist"
  ]
}
```

My `ts-loader` config looks like this:

```js
{
  test: /\.tsx?$/,
  loader: 'ts',
  exclude: /node_modules/
}
```

My `package.json` has typings installed like this:

```json
 "devDependencies": {
    "@types/core-js": "^0.9.35",
    "@types/enzyme": "^2.5.39",
    "@types/greensock": "^1.15.32",
    "@types/isomorphic-fetch": "0.0.31",
    "@types/jasmine": "^2.5.38",
    "@types/jquery": "^2.0.34",
    "@types/mixpanel": "0.0.28",
    "@types/node": "0.0.2",
    "@types/react": "^0.14.52",
    "@types/react-addons-css-transition-group": "^0.14.18",
    "@types/react-addons-perf": "^0.14.17",
    "@types/react-addons-shallow-compare": "0.0.0",
    "@types/react-addons-test-utils": "^0.14.15",
    "@types/react-addons-transition-group": "^0.14.17",
    "@types/react-bootstrap": "0.0.37",
    "@types/react-dnd": "^2.0.31",
    "@types/react-dnd-html5-backend": "^2.1.6",
    "@types/react-dom": "^0.14.19",
    "@types/react-dropzone": "0.0.28",
    "@types/react-intl": "^2.1.0",
    "@types/react-modal": "^1.3.6",
    "@types/react-overlays": "^0.6.0",
    "@types/react-redux": "^4.4.35",
    "@types/react-router": "^2.0.41",
    "@types/react-router-redux": "^4.0.35",
    "@types/react-scroll": "0.0.30",
    "@types/redux-thunk": "^2.1.32",

```

This worked fine with `typings`. Again, this works fine running `tsc` directly, as well as through the IDE compiler (IntelliJ 2016.3).

**Comment by aaronbeall** [comment]
It seems that *automatic type inclusion* as [described in TS documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) does not work like `tsc` when using `ts-loader`. This explains why the errors coming out of `ts-loader` were that it couldn't find certain global type definitions, like jasmine `describe()` or core-js shims. I added all missing types explicitly to `tsconfig.json` as `"types"`:

```json
"types" : ["jasmine", "mixpanel", "greensock", "core-js", "node"]
```

And this made all errors go way; now both `tsc` and webpack build with `ts-loader` run without errors.

Is this expected behavior? I would prefer if `ts-loader` was able to just include all `@types` like `tsc` does by default.

**Comment by johnnyreilly** [comment]
No - in my own projects it seems to work as expected: https://github.com/johnnyreilly/proverb-signalr-react

**Comment by aaronbeall** [comment]
Does that project refer to any global definitions in TS code? I don't see any...

**Comment by johnnyreilly** [comment]
> global definitions in TS code

Sorry I don't know what you mean by this?

**Comment by aaronbeall** [comment]
Mean not this:
```ts
import {foo} from "foo";
foo();
```

But something like this:
```ts
foo(); // never imported, assumes it exists in global scope
```

The problem seems to be failure to pull in global declarations like this:

```ts
declare function require();
```

Because in those cases your source code never imports it, it just assumes it's there. This works in `tsc` because it pulls in all definition files found in `@types` but I'm finding that I have to explicitly include them in the `"types"` config for them to be included in my webpack build.

**Comment by aaronbeall** [comment]
Looking at your project I see that it does refer to global jasmine APIs like `describe()` in your test files, so that works for you. In fact jasmine was one of the ones I had to add to make a bunch of errors go away like "cannot find describe()`. So I guess *something* in my webpack configuration is making this not work.

I'm using `webpack-dev-server` if that matters.

**Comment by johnnyreilly** [comment]
Ah I see. Yes there are examples of that in terms of the jasmine typings: https://github.com/johnnyreilly/proverb-signalr-react/blob/master/test/stores/GreetingStore.tests.ts

`describe` and `it` etc are not explicitly imported but seem to work just fine

**Comment by johnnyreilly** [comment]
I'd compare the setup in my project with yours and go from there.

**Comment by johnnyreilly** [comment]
Closing this as it all seems to work. If you realise what the problem with your setup was please do share details here.

**Comment by aaronbeall** [comment]
@johnnyreilly The problem was I was using an old version of `ts-loader`. Updating made the errors go away. I actually checked for updates using `ncu` before logging the issue but I guess I misread the output, sorry!

**Comment by johnnyreilly** [comment]
No worries - thanks for confirming!
