### ISSUE TITLE
Cannot import jsx files even with `allowJs: true`

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-loader#414]
Here is a simple reproduction that illustrates the bug:
https://gist.github.com/cspotcode/217f364daed15cb7aa06568313b0c933

I have `allowJs: true` and *all* files are passing through `ts-loader`.  The entry point is a `.ts` file and it imports two `.jsx` files and two `.js` files.  tsc handles this situation correctly and compiles as you'd expect.  webpack & ts-loader, however, say they can't find the .jsx files but can find the .js files.

Adding `entryFileIsJs: true` makes the errors go away, but it shouldn't be necessary, right?  The entry file isn't JS; it's TS.

**Comment by cspotcode** [comment]
Actually, I just figured out it's also fixed by adding `jsx: "react"` to the tsconfig.  That's interesting, because tsc doesn't throw errors with or without the `jsx` option set.

Without `jsx`, tsc emits the JSX syntax unmodified.  With `jsx: "react"`, tsc transpiles the JSX syntax.

So, with that new information, I'm not sure if this is a bug or not.

**Comment by johnnyreilly** [comment]
Very strange... Not sure either. Will close as there's a workaround
