### ISSUE TITLE
Memory leak on watcher dispose

### ISSUE THREAD

**Issue by Llorx** [TypeStrong/ts-loader#417]
When I run this code:
```js
var i = 0;
var webpack = require("webpack");
function c() {
    var compiler = webpack({
        context: __dirname,
        entry: "./main3.ts",
        output: {
            filename: 'bundle.js',
            path: '/'
        },
        resolve: {
            extensions: ["", ".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
        },
        module: {
            loaders: [{
                test: /\.tsx?$/,
                loader: "ts-loader"
            }],
        }
    });
    compiler.plugin("compile", () => {
        console.log("cmp", i++);
    });
    return compiler.watch({
        aggregateTimeout: 333
    }, (err, stats) => {
        setTimeout(() => {
            oldc.close();
            oldc = c();
        }, 33);
    });
}
oldc = c();
```

Having as `main3.ts` contents simply a bunch of `console.log` (about 10k, for testing), without any dependencies of anything, after some time I get a "process out of memory" error.

Don't happens if I change the `main3.ts` extension to `js` (so the loader is not used) and also don't happens with `awesome-typescript-loader` (you see the memory going up and down, instead of all the way up), so I guess is a `ts-loader` problem.

**Comment by johnnyreilly** [comment]
Which version are you using? Does this apply to the latest version? If you could spend some time on this it would be greatly appreciated!

**Comment by Llorx** [comment]
Of, forgot to say... silly me xD webpack 1.14.0 and ts-loader 1.3.3

I guess they are the latest. Just made `npm install webpack` and `ts-loader`

**Comment by johnnyreilly** [comment]
If someone else can take a look at this (btw not totally sure this is an issue or not yet) that'd be awesome. If not I'll probably close this issue; I don't have time to look into it myself and I'm not experiencing the issue described

**Comment by johnnyreilly** [comment]
Perhaps related to #421

**Comment by johnnyreilly** [comment]
If you add in the loader options plugin as suggested in #421 does this resolve the issue?

**Comment by Llorx** [comment]
As far as I can remember, I had one plugin defining a production environment variable, but I removed it from the script above. This evening I'll check/try it.

**Comment by johnnyreilly** [comment]
thanks

**Comment by Llorx** [comment]
Ok, I was not using `LoaderOptionsPlugin`.

Upgraded to `webpack 2.2.0-rc.1` (I was on 1) and tested exactly with this script:
```js
var i = 0;
var path = require("path");
var webpack = require("webpack");
    function c() {
        var compiler = webpack({
        context: path.join(__dirname),
        entry: "./main3.ts",
        output: {
            filename: 'bundle.js',
            path: '/'
        },
        resolve: {
            extensions: [".ts", ".tsx", ".js"]
        },
        module: {
            loaders: [
                {
                    test: /\.tsx?$/,
                    loader: "ts-loader"
                }
            ]
        },
        plugins: [
            new webpack.LoaderOptionsPlugin({ options: {} })
        ]
    });
    compiler.plugin("compile", function () {
        console.log("cmp", i++);
    });
    return compiler.watch({
        aggregateTimeout: 333
    }, (err, stats) => {
        setTimeout(() => {
            oldc.close();
            oldc = c();
        }, 33);
    });
}
oldc = c();
```

The `main3.ts` is a 10 Kb file containing nothing more than `console.log("test");console.log("test");cons...`.

Received the same error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

In short, these are my versions:
 - `ts-loader 1.3.3`
 - `webpack 2.2.0-rc.1`
 - `node v4.4.7`

**Comment by johnnyreilly** [comment]
And if you add the loader options plugin does it resolve the issue?

**Comment by johnnyreilly** [comment]
Like this:

```
new LoaderOptionsPlugin({      
   options: {       
     resolve: {
       extensions: ['.ts', '.tsx', '.js', 'jsx']
     }  
   }        
 })     
```

**Comment by Llorx** [comment]
I'm not sure where to add it. In the code above it is added inside the `plugins:` array.

Now I changed it to
```js
plugins: [
    new webpack.LoaderOptionsPlugin({
        options: {
            resolve: {
                extensions: ['.ts', '.tsx', '.js', 'jsx']
            }
        }
    })
]
```
And still having the problem.

**Comment by johnnyreilly** [comment]
Very strange. Thanks for trying. Could you try using ts-loader 1.3.1 and see if it's still an issue?

**Comment by Llorx** [comment]
```
`-- ts-loader@1.3.1
  `-- enhanced-resolve@0.9.1
    +-- memory-fs@0.2.0
    `-- tapable@0.1.10
```
And still receiving the problem at `cmp 23`.

**Comment by johnnyreilly** [comment]
I haven't used your script. I've been running ts-loader in watch mode for days at a time and watching the memory. It stays pretty static. In normal usage there's no sign that I've picked up on of a memory leak. Which is good. But confusing

**Comment by Llorx** [comment]
Oh, the thing is that I'm closing the watcher and opening it again on each loop. Watcher could be fine. The problem can be when disposing it.

**Comment by johnnyreilly** [comment]
That's interesting. Since watch mode only typically ends when the process terminated and all resources seem to be released then that means I'm a little less concerned. Still like to get to the bottom of this though

**Comment by Llorx** [comment]
Let's see if someone (or me when I get forced to use `ts-loader` instead of `awesome-typescript-loader`) finds something
