### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by prasanthkarukkuvel** [TypeStrong/ts-loader#421]
ts-loader runs out of memory while building. Its seems related to use of **enhanced-resolve**

`==== JS stack trace =========================================

Security context: 000002F1F9DC9E51 <JS Object>
    1: forEachBail [D:\Production\fsm-ui-analytics\node_modules\ts-loader\node_modules\enhanced-resolve\lib\forEachBail.js:~5] [pc=000003F65D84C023] (this=000002F1F9DE0D29 <JS Global Object>,array=0000038750240011 <JS Array[7]>,iterator=0000038750240079 <JS Function (SharedFunctionInfo 0000006216543CD1)>,callback=00000387502400C1 <JS Function (SharedFunctionInfo 0000006216543D91)>)
    2: /* ...`

But adding **LoaderOptionsPlugin** with options to webpack resolves this issue

`new LoaderOptionsPlugin({  options: {} })`

Might be because 

`function makeResolver(options: { resolve: interfaces.Resolve }): interfaces.ResolveSync {
    return node.create.sync(options.resolve);
}`

**Comment by johnnyreilly** [comment]
Thanks for sharing that. I'm wondering if this is related to #420 - seems likely.

**Comment by johnnyreilly** [comment]
I'm pondering whether adding loader options to when constructing the resolver might be a good idea.

**Comment by johnnyreilly** [comment]
BTW - which version of WebPack are you using? And can you confirm if the issue occurs when using ts-loader 1.3.1? We used an older version of enhanced-resolve then

**Comment by prasanthkarukkuvel** [comment]
@johnnyreilly  I am on webpack@2.1.0-beta.28 rite now. With 1.3.1 its failing with ` TypeError: Cannot read property 'unsafeCache' of undefined` without **options** in **LoaderOptionsPlugin**

**Comment by johnnyreilly** [comment]
Thanks @prasanthkarukkuvel - I'm not totally certain but I think having `LoaderOptionsPlugin` in play is pretty much mandatory for webpack 2.  I'm asking for some guidance on this.

**Comment by shepmaster** [comment]
I am experiencing something similar when trying to upgrade ts-loader from 2.3.7 to 3.0.5. I'm using Webpack 3.8.1. If it's useful, you can [grab the code](https://github.com/integer32llc/rust-playground/tree/ts-loader) and execute `yarn build` in the `ui/frontend` directory. I am using macOS (10.12.6) and Node v8.7.0. My computer has 16GB of RAM, and watching the memory usage of the node process, I only see it get to about 1.4GB. What's interesting is that I'm seeing [the same behavior trying to upgrade TypeScript from version 2.4.x](https://github.com/Microsoft/TypeScript/issues/18411#issuecomment-339449274), but this is without that upgrade.

**Comment by shepmaster** [comment]
Perhaps there is a difference in how ts-loader 3.x decides which files to compile? It turns out that I have ~50 MB of files in my build directory and my build directory was **not** in the `tsconfig.json`'s `exclude` key. That was causing these files to be compiled even though they aren't referenced from my entrypoint. Perhaps this is what #267 is intended to fix?

**Comment by johnnyreilly** [comment]
Don't know why anything we'd have done between 2.x and 3.x would make a difference. Curious..
