### ISSUE TITLE
ts-loader message is outputted when webpack is run with '--json'

### ISSUE THREAD

**Issue by jumpinjackie** [TypeStrong/ts-loader#428]
When I run `webpack --json` and redirect its output to a json file, the following string is on the first line of the file, rendering it an invalid json file.

`ts-loader: Using typescript@x.y.z and /path/to/tsconfig.json`

**Comment by johnnyreilly** [comment]
You can turn it off with silent / log levels I believe

**Comment by jumpinjackie** [comment]
I have never had any `ts-loader` settings applied and circa `v0.8.3` at least (this was the version I upgraded `ts-loader` from) that message never snuck to stdout when I ran `webpack --json`

**Comment by johnnyreilly** [comment]
You may also want to check out: logInfoToStdOut

**Comment by joerick** [comment]
Just ran across this as well. More normal in the UNIX world would be to log this kind of message to stderr. On my system (macOS) that message was on stdout, even without the `logInfoToStdOut` option. Would it be possible to change the default to stderr?

**Comment by johnnyreilly** [comment]
Hi @joerick - the details of how we landed where we are can be found here: https://github.com/TypeStrong/ts-loader/pull/313

I'm open to change subject to the concerns raised in the linked issue still being addressed

**Comment by joerick** [comment]
Hm... so the default _is_ for 'info' logs to go to stderr.  Not sure why I was having that problem then. I've combed through the ts-loader code and I can't see any obvious reason why that would be. I'll let you know if I find anything definitive, otherwise, sorry for the noise!

**Comment by johnnyreilly** [comment]
No bother!
