### ISSUE TITLE
Hot module reload does not work if transpileOnly is false

### ISSUE THREAD

**Issue by HerringtonDarkholme** [TypeStrong/ts-loader#433]
I finally find a reliable reproduction. 

Repo: https://github.com/HerringtonDarkholme/ts-loader-hmr

TS file

```ts
// app.ts
import {test} from './import'
console.log(test)
// import.ts
export var test = '3333333'
if (module.hot) {
  module.hot.accept()
}
```

tsconfig.json

```js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    },
    "exclude": [
        "node_modules", "dist"
    ]
}
```

webpack config

```ts
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './app.ts',
  output: {
    path: path.join(__dirname, 'dist'),
    publicPath: 'dist/',
    filename: 'build.js'
  },
  resolve: {
      extensions: ['.ts', '.js'],
  },

  module: {
      rules: [
          { test: /\.ts$/, use: {loader: 'ts-loader'} },
          // toggle these lines to see HMR difference
          // { test: /\.ts$/, use: {loader: 'ts-loader', options: {transpileOnly: true}} },
      ],
  },
  devServer: {
    port: 8080,
    host: 'localhost',
    watchOptions: { aggregateTimeout: 300, poll: 1000 }
  },
}
```

package.json
```
  "devDependencies": {
    "@types/webpack-env": "^1.12.1",
    "ts-loader": "^1.3.3",
    "typescript": "^2.1.4",
    "webpack": "^2.2.0-rc.3",
    "webpack-dev-server": "^2.2.0-rc.0"
  },
```

I have also compared full-compiled and transpile files. They only differs in hotCurrentHash which I don't think is a relevant point here.

**Comment by HerringtonDarkholme** [comment]
The problem seems to be `addDependencies`. ts-loader will push app.ts to webpack and causes unintentional reload.

**Comment by johnnyreilly** [comment]
Good work on the repro.  Can you think of a nice approach to deal with this?

**Comment by HerringtonDarkholme** [comment]
Hmmm, I don't have idea about what `addDependency` does. The doc says it adds file to watch list. But  how can it impact hot module reload? ~~Maybe because we flush dependency by `clearDependencies` so webpack have to refresh all the file~~

**Comment by johnnyreilly** [comment]
So the prpblem is experienced when you amend app.ts or import.ts?

**Comment by HerringtonDarkholme** [comment]
The problem is, when editing import.ts where HMR is correctly set up, the whole page is refreshed.
If I add HMR in app.ts, then HMR is universally available. 

However, since import.ts accepts itself in HMR, the whole page should not refreshed. app.ts is refreshed, probably because ts-loader rebuilds the dependency graph in webpack internal (I guess, newbie in webpack)

**Comment by johnnyreilly** [comment]
> newbie in webpack

Likewise my friend! :smile:

**Comment by HerringtonDarkholme** [comment]
In index.ts, `emitFile` will call `clearDependencies` and `addDependency`, which seem to be the culprit. I don't know what's the purpose of these two calls, but if I comment out these two calls, hot module reload works with type checking.

@johnnyreilly any idea?

**Comment by johnnyreilly** [comment]
My understanding (limited) is that `addDependency` is used to create a dependency graph which will trigger the emit of dependent files if that file is changed.  I'm not too sure why this breaks hot module reloading; it may be worth asking for more information in the webpack repo....

**Comment by HerringtonDarkholme** [comment]
I'm quite sure the culprit should be `clearDependencies` and `addDependency` after reading webpack source code.

HMR is done by pushing/polling changed module to web browser, and `webpackHotUpdate` will check whether those module is reloadable and recompute the dependencies, to dispatch reload command to related modules. All those happened in `HotModuleReload.runtime.js`.

After clearDependencies and addDependencies, webpack server will have to send all modules to browser to recompute deps because the original deps have been discarded. 

However, not all modules are reloadable. For example, in the above minimal repro, `app.ts` does not have hot module reload code so it will force browsers reload.

**Comment by HerringtonDarkholme** [comment]
Interestingly, ATL has `clearDependencies` in its interface declaration but it is not used at all. https://github.com/s-panferov/awesome-typescript-loader/blob/e06f436656302335a0cc94f6de055ffdb6267004/src/instance.ts#L42

ATL is originally a fork of TL, so I wonder if @jbrantly know something about `clearDependencies` call? 
I cannot find the original author after the great refactor...

**Comment by jbrantly** [comment]
Working off memory here, but I believe the idea there was that dependencies could change between runs in watch mode, but webpack's `addDependency` was additive only. So if a dependency was removed in the TS source, that dependency remained according to webpack. The `clearDependencies` call was done on each run to get a fresh start and then re-add all actual dependencies.

**Comment by jbrantly** [comment]
Also, FWIW, I have HMR working in a project using ts-loader. Not something I can share, but just to say that it might be something specific to the way you're using HMR.

Just talking out my ass here, but since you're accepting inside the imported file, wouldn't that necessarily cause a full reload since the parent has no way to see the imported file's changes? What if you accept in `app.ts` instead?

Also [see here](https://webpack.github.io/docs/hot-module-replacement.html):

> `accept([errHandler]) => void`
> Accept code updates for this module without notification of parents. This should only be used if the module doesn’t export anything. The errHandler can be used to handle errors that occur while loading the updated module.

That said, I'm by no means an HMR expert and I've often had many difficulties in setting up HMR.

**Comment by HerringtonDarkholme** [comment]
Hmmm, maybe webpack did not handle dependency back then.

But it seems webpack do support analyzing dependency now.  (a minimal example https://github.com/ktsn/ts-loader-test, you can add and remove dependency). Removed dependency in JS will not trigger reload. The same in transpiled TS.

So I think there is no need for ts-loader to rebuild dependency graph.

>  What if you accept in app.ts instead?

This is a good advice. However, not every entry module is side effect free, which means root level HMR isn't available. And current ts-loader's behavior is different from the default js loader. Usually it is a bad sign. 

More importantly, HMR is often hidden behind other loaders. (vue-loader, react-loader, https://github.com/ktsn/vue-template-loader), ordinary users will not have enough knowledge to fix the problem. Also, other loader's authors will also have better integration with ts-loader if we can keep compatible with plain js-loader.
