### ISSUE TITLE
Optimizing Typescript + Webpack

### ISSUE THREAD

**Issue by wotsyula** [TypeStrong/ts-loader#436]
I'm working on a big project that uses Typescript 2 and has over 100 classes that are coded in Typescript and are split over around 4-5 repositories. The final build uses Webpack (NPM version). Unfortunately Typescript generates a lot of bloated code (functions like `__assign()` and `__extend()` are added to virtually all files. The final build has over 100 KB of this code and its my job to make it all go away. I thought I could hack `ts-loader` to add `__assign()` / `__extend()` etc as Webpack modules so they would only appear once in the final `.js` file and then finally import the `.ts` version of files instead of compiled `.js` files. My directory structure looks something like this.

```
|
+dist
|    + index.js
|    +index.map
|
+source
|    +index.ts
|    
+node_modules
|    +core (git repository)
|        +index.js
|        +index.d.ts
|        +index.ts
|        +index.map 
|
|    +other (git repository)
|        +index.js
|        +index.d.ts
|        +index.ts
|        +index.map 
```

I had tried making a custom version of ts-loader but that failed because after a certain version it stopped loading `.ts` files in `node_modules` directory.

Any advice would be greatly appreciated. It does not have to be limited to ts-loader. If I could stop Typescript from generating this code and make sure that the relevant functions are defined globally could also work for me.

I'm asking this here 1st because you guys have a strong record of answering tickets. I'm counting on you.

**Comment by johnnyreilly** [comment]
You could try getting TypeScript to emit es2016 and drop Babel into the mix with uglify. Howe

**Comment by johnnyreilly** [comment]
However, I can't guarantee anything. Good luck!

**Comment by aindlq** [comment]
See https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-external-helpers-library-tslib

I'm adding tslib to my Webpack's DLL and use `importHelpers: true` with ts-loader this way __assign and __extend bundled only once.

**Comment by johnnyreilly** [comment]
That's brilliant @aindlq - I did not know about that!

**Comment by wotsyula** [comment]
Sorry for long delay in reply.

@johnnyreilly  I was hoping to help make this a feature of ts-loader but if it can be fixed in configuration then there is no need I suppose.

@aindlq Thanks man. I'll try it out right now.

**Comment by wotsyula** [comment]
@aindlq Works perfectly. Thanks man!!!
