### ISSUE TITLE
unrecognized keyword keyof

### ISSUE THREAD

**Issue by staeke** [TypeStrong/ts-loader#438]
This is the same issue as with 
https://github.com/s-panferov/awesome-typescript-loader/issues/345

Basically, object spread and keyof doesn't work, e.g.
```typescript
let a:keyof string = 'length';
let a:{};
let b = {...a};
```

Neither `transpileOnly = false`, nor `transpileOnly = true` works, which surprises me a little. I thought the problem was acorn parsing, but when `transpileOnly = false` I thought it used the typescript original parser. However, getting errors like this

```
error TS1005: '=' expected.
error TS1136: Property assignment expected.
error TS1005: ',' expected.
error TS1128: Declaration or statement expected
...
```

Also tried ntypescript with no success.

I'm using:
ts-loader@1.3.3
typescript@2.1.4 (tried 2.1.1 too)

**Comment by johnnyreilly** [comment]
I think this must be something to do with your setup; it works in my own projects.

**Comment by staeke** [comment]
@johnnyreilly Ok, that's interesting! I will try to reproduce with a very basic setup

**Comment by staeke** [comment]
Seems this was due to too low webpack version
