### ISSUE TITLE
Watcher gets an instance of IgnoringWatchFileSystem and errors

### ISSUE THREAD

**Issue by herschel666** [TypeStrong/ts-loader#441]
In my Webpack-setup I'm ignoring some `.d.ts`-files by adding Webpack's `WatchIgnorePlugin`-plugin. These ignored files lead to the `watchFileSystem` of the webpack-compiler not being an instance of `NodeWatchFileSystem`, but of `IgnoringWatchFileSystem`.

This again makes `src/watch-run.ts` throw an error, because it expects the `watcher`-property to be on `watching.compiler.watchFileSystem`. But instances of the `IgnoringWatchFileSystem` have their instance of `NodeWatchFileSystem` on the `wfs`-property.

```bash
node_modules/ts-loader/dist/watch-run.js:10
        var mtimes = watching.compiler.watchFileSystem.watcher.mtimes;
                                                              ^
TypeError: Cannot read property 'mtimes' of undefined
```

This can easily be fixed by doing:

```typescript
function makeWatchRun(
    instance: interfaces.TSInstance
) {
    return (watching: interfaces.WebpackWatching, cb: () => void) => {
        const watcher = watching.compiler.watchFileSystem.watcher ||
            watching.compiler.watchFileSystem.wfs.watcher;
        …
```

However I'm not sure if this is actually a problem of the `ts-loader`. Maybe `.ts`-files handled by the `WatchIgnorePlugin`-plugin must not run through the `ts-loader` at all?!?

Can someone with more knowledge of the internals of Webpack provide an oppinion? This would be great! :-)

**Comment by scriby** [comment]
I ran into the exact same issue.

**Comment by johnnyreilly** [comment]
Could a minimal repro be supplied please? We can use this as a basis for a comparison test which is necessary for this PR to remedy the issue:  https://github.com/TypeStrong/ts-loader/pull/444

**Comment by herschel666** [comment]
I'm currently setting up the comparison test. Still wrangling with the webpack output though …

**Comment by johnnyreilly** [comment]
Believe me I know that feeling... Do take a look at the existing tests - due to webpack 2 they've all changed in some way. Oh and ignore test output for pre TypeScript 2.1. it's for historic Interest only

**Comment by johnnyreilly** [comment]
Details of changes here: https://github.com/TypeStrong/ts-loader/pull/445/files
