### ISSUE TITLE
strictNullChecks can cause failures

### ISSUE THREAD

**Issue by nevir** [TypeStrong/ts-loader#442]
It appears like `ts-loader` causes the TS compiler to parse `.d.ts` files in a different mode than what the compiler normally does?

From a working ts-loader based project (occurs on both webpack 1 & 2), on typescript 2.1:

1. Set `"strictNullChecks": true"`
2. Import a module that has a function that is declared with an _optional_ options argument that is also destructured.  In my case, that's [`apollo-client`'s constructor](https://github.com/apollostack/apollo-client/blob/22c68f5b4b27829ed530a5c6d5024e4159013921/src/ApolloClient.ts#L135-L165).
  
Running `./node_modules/.bin/tsc` directly compiles without complaint.  Running `ts-loader` results in:

```
ERROR in /node_modules/apollo-client/lib/src/ApolloClient.d.ts
(28,18): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'networkInterface' and no string index signature.
…
```

Here's the complete `tsconfig.json` being used, as well:

```
{
  "compilerOptions": {
    "charset": "utf-8",
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "jsx": "react",
    "module": "commonjs",
    "newLine": "LF",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "outDir": "./dist/",
    "pretty": true,
    "strictNullChecks": true,
    "target": "es5",
    "lib": [
      "dom",
      "es2016",
      "es2017.object"
    ],
    "sourceMap": true
  },
  "exclude": [
    "dist",
    "build",
    "node_modules"
  ]
}
```

Possibly related to https://github.com/Microsoft/TypeScript/issues/8681

**Comment by johnnyreilly** [comment]
Thanks for the detailed report; that's always appreciated. If you have ideas on how to remedy this we always welcome PRs.
