### ISSUE TITLE
Move section ts -> tsconfig.json worsened performance

### ISSUE THREAD

**Issue by m1neral** [TypeStrong/ts-loader#446]
Use webpack 1.x, ts-loader: 1.2.1, typescript: 2.0.9.

Then I updated TypeScript to 2.1.x I got error:
`"error TS18002: The 'files' list in config file 'tsconfig.json' is empty.`

So I moved 'ts' webpack section in `tsconfig.json` and performance slow down, because, I consider, `ts-loader` began to check all ts files in project folder, and I can't ignore this by `exclude`. Why is this happening? Why it doesn't check the files from the webpack entry point as it was before? Thanks!

Was(good performance):

```
module: {
        loaders: [{
            test: /\.ts$/,
            loader: 'ts-loader'
        }]
    },
    devtool: "eval",
    ts: {
        configFileName: '',
        compilerOptions: {
            target: "es5",
            module: "commonjs",
            rootDir: "./src/ts/",
            noImplicitUseStrict: true,
            preserveConstEnums: true
        },
        exclude: [
            "node_modules"
        ]
    }
```
Now (bad performance):
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "rootDir": "./src/ts/",
    "noImplicitUseStrict": true,
    "preserveConstEnums": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by johnnyreilly** [comment]
Thanks for raising an issue. The problem with `error TS18002: The 'files' list in config file 'tsconfig.json' is empty` is down to a change in TypeScript 2.1; not ts-loader related. 

I'm afraid I don't have time to look into the issue you raised but I would encourage you to do so. We welcome contributions and PRs.

**Comment by johnnyreilly** [comment]
FWIW I don't think you need the `exclude` - I advise using `"skipLibCheck": true` though 

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by m1neral** [comment]
Thank you, I understand.
The problem is that, when I didn't have `tsconfig.json` `files` value computed by webpack entry point, and it was cool. But the only way out - create several `tsconfig.json`, because I can't change it dynamically. :(

**Comment by m1neral** [comment]
`files` would be very useful!!!!

**Comment by stepancar** [comment]
@m1neral, try to use atom and atom-typescript plugin. This plugin can rewrite tsconfig and update files section automatically.

**Comment by m1neral** [comment]
Resolved. Move your `ts` property in the `tsconfig.json` file. Do not forget add rule that typechecker scan only the files you want (bundled files): enough add your webpack entry point (or one of them) to `includes` or `files` or use the hack `exclude: '*'`. Good luck.
