### ISSUE TITLE
Replace vue test with appendTsSuffixTo test

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#447]
At some point the [vue test](https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/vue) should be replaced with a test specifically for `appendTsSuffixTo`.  This is what the vue test originally covered and this functionality is what vue relies upon and so we want to maintain.  (Given how often vue changes having a directly vue specific test turns out to be a bad idea)

cc @HerringtonDarkholme

**Comment by HerringtonDarkholme** [comment]
Good idea!
