### ISSUE TITLE
Differences with awesome-typescript-loader

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-loader#449]
There's some difference listed here: https://github.com/s-panferov/awesome-typescript-loader#differences-between-ts-loader

Can you guys expand on that and or add some other differences here? Thanks a ton!

**Comment by johnnyreilly** [comment]
Hi @trusktr,

The long term plan is that ts-loader and awesome-typescript-loader hope to merge together into a single loader. At that point there should no longer be any differences :smile:  

cc @s-panferov
