### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-loader#453]
Hi, does this work with Webpack 2's tree shaking feature?

**Comment by johnnyreilly** [comment]
I'm not totally sure if it's covered already when you're emitting ES2016 and having babel transpile.  It may be; see this for what I mean:

```js
var babelOptions = {
  "presets": [
    "react",
    [
      "es2015",
      {
        "modules": false // I think this is necessary for tree shaking
      }
    ],
    "es2016"
  ]
};
```

https://github.com/TypeStrong/ts-loader/blob/master/examples/webpack2-gulp-react-flux-babel-karma/webpack.config.js

If not then I believe there needs to be a change to webpack to support this.  Check this:

https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.7d47infog

You can vote for this to be the thing they pick up next I believe.

**Comment by OliverJAsh** [comment]
Ah, interesting. That should work! I will add Babel to my workflow

Ideally we could just use TS to downlevel to an older ECMAScript version whilst still having Webpack perform tree shaking. I imagine TS would have to downlevel everything to the specified target *except* modules, which webpack will handle.

**Comment by ariutta** [comment]
Setting your `tsconfig.json` file to use these options might work:

```json
{
	"compilerOptions": {
		"module": "es2015",
		"target": "es5"
	}
}
```

**Comment by doxiaodong** [comment]
@ariutta , it's not work
I use
```
import {extend} from 'lodash-es'
```
with your config

**Comment by doxiaodong** [comment]
I see the normal way is to set target to es2015 and add babel to do tree-shaking, How about ts-loader?

**Comment by johnnyreilly** [comment]
Pipe ts-loader output to Babel-loader and you should be able to do the same.

**Comment by dolsem** [comment]
@johnnyreilly 
> Pipe ts-loader output to Babel-loader and you should be able to do the same.

How do I do that? I tried setting module and target both to "es6" in tsconfig, but something is still going wrong. I'm using babel-plugin-lodash to transform and then tree shake lodash imports. This plugin only works with ES6-style imports, and it works in my JS files. It looks like piping ts-loader output into babel-loader is what I need, it also seems to be what's already happening behind the scenes, but tree shaking doesn't happen.

**Comment by johnnyreilly** [comment]
`rules: [{
      test: /\.ts(x?)$/,
      exclude: /node_modules/,
      use: [
        babelLoader,
        {
          loader: 'ts-loader'
        }
      ]
    }]`

Here's what piping looks like; I haven't tested tree shaking in a while

**Comment by nyngwang** [comment]
I still don't know the advantage(s) of using `ts-loader` if I just want to do tree-shaking. Babel v7 can also transpile typescript, which means `babel-loader` should be enough.
