### ISSUE TITLE
HMR on .vue files

### ISSUE THREAD

**Issue by pedrodbsa** [TypeStrong/ts-loader#459]
Hi,

I'm not sure if this is the right forum for this particular problem that involves Vue but here it goes.

I'm getting a weird HMR  behavior on certain .vue components that get displayed by VueRouter.
I've splitted the component TS code to separate files and import it as following:

**home.vue**
```Vue
<template>
    <div class="home">
        <h2>Home container! {{Message}}</h2>
    </div>
</template>
<script>
    import index from "./index";
    export default index;
</script>
```
**home.ts**
```TypeScript
import * as Vue from "vue";
import { Component } from "vue-property-decorator";

@Component({
    name: "c-home"
})
export default class Home extends Vue {

    get Message() {
        return "Hello World...";
    }
}
```
Whenever I change either the .vue file or the .ts file, webpack does detect and pushes the changes but there is no view update.

However, if I launch the app with the <script> block commented and then uncomment it, HMR picks it up and everything starts working fine.

This is only happening for components being "managed" by VueRouter; other components work fine.

app.vue
```Vue
<template>
    <c-sidebar></c-sidebar>
    <div class="main-wrapper">
        <c-header></c-header>
        <router-view></router-view>
    </div>
</template>

<script>
    import home from "./index";
    export default home;
</script>
```

_c-sidebar_ and _c-header_ are updated just fine, but the router-view component, that is used by VueRouter to display the _c-home_ component, has the erratic behavior I described.

Here is my very typical webpack config section for handling vue+ts:

```JavaScript
{
    test: /\.ts$/,
    loader: "ts-loader",
    options: {
        appendTsSuffixTo: [/\.vue$/]
    }
}, {
    test: /\.vue$/,
    loader: "vue-loader",
    options: {
        esModule: true
    }
}
```

Am i doing something wrong? Any help is appreciated.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for using ts-loader.

Please provide a minimal reproduction repository for issue reporting. Without proper reproduction, we cannot help much here.

[Why is this important](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by HerringtonDarkholme** [comment]
Close due to no active feedback.

And, fairly, this is ts-loader repository, not vue-loader's.

**Comment by chanon** [comment]
Here is the reproduction:
https://github.com/chanon/ts-vue-hmr

See:
https://github.com/chanon/ts-vue-hmr/blob/master/src/components/Hello.vue#L25-L45

There are at least 2 issues. One is when using vue-class-component, editing of the <template > section does not get updated in browser. Second is when editing inside the <script lang="ts"> portion, the whole page will get reloaded (regardless of whether vue-class-component is used).
