### ISSUE TITLE
Webpack 2 fails on any error

### ISSUE THREAD

**Issue by IRus** [TypeStrong/ts-loader#460]
With webpack 1 ts-loader doesn't fail build, even if i had some errors, but with webpack 2 i got exit code 2 from webpack, if ts-loader produces any error. How i can disable this behavior?

**Comment by johnnyreilly** [comment]
I think this may be a change in behaviour with webpack 2 - I don't know details though.  Are you running in watch mode or build mode?  (I ask as my own watch approach still works fine.)

**Comment by IRus** [comment]
Sorry for slow response.

I reproduce my issue in sample project:

https://github.com/IRus/ts-loader/tree/issue/460/examples/webpack2-react-cdn-simple

```
npm install
npm run build
# ...error!
```

I delete `transpileOnly` in order to reporoduce issue, as you see, webpack fails (with error code = 2) and fail npm too. 

Is it possible to get errors from typescript in console, but doesn't fail build?
It really useful when you migration projects, or doesn't have yet right typings.

**Comment by miguelbermudez** [comment]
Having the same issue. Would love to know how to change this.

**Comment by johnnyreilly** [comment]
I believe WebPack 2 introduced this behaviour. There is likely some config for WebPack itself to control this. I'd investigate that if I were you
