### ISSUE TITLE
Recommended module/target options

### ISSUE THREAD

**Issue by sternbel** [TypeStrong/ts-loader#461]
Hi,

I'm creating 2 libraries `A` and `B` (written in TS) where `B` relies on `A`, and `B` will be consumed by an html file as `<script src="b.js>` by browsers like IE11 and Chrome.

Currently, I'm compiling with this:

*tsconfig.json*
```typescript
{
  "compileOnSave": false,
  "compilerOptions": {
    "strictNullChecks": false,
    "declaration": false,
    "removeComments": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "./dist/",
    "module": "commonjs",
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "resources"
  ]
}
```

*webpack.config.js*
```typescript
var webpack = require("webpack");
var LoaderOptionsPlugin = require("webpack/lib/LoaderOptionsPlugin");

module.exports = {
    entry: {
        "a": "./src/index.ts",
        "a.min": "./src/index.ts"
    },
    output: {
        path: "./dist",
        filename: "[name].js",
        library: ["a"],
        libraryTarget: "var",
        umdNamedDefine: true
    },
    devtool: "source-map",
    resolve: {
        extensions: [".ts", ".js"]
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            include: /\.min\.js$/,
            minimize: true,
            compress: {
                warnings: false
            }
        }),
        new LoaderOptionsPlugin({
            debug: false,
            options: {
                resolve: {
                    extensions: ['.ts', '.tsx', '.js']
                }
            }
        })
    ],
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                exclude: /node_modules/,
                loader: "ts-loader"
            },
            {
                test: /\.js$/,
                loader: "source-map-loader"
            }
        ]
    }
};
```

Do you see anything I'm doing wrong in my settings? 
It's currently compiling fine, but I'm wondering if `"module": "commonjs", "target": "es5"` in `tsconfig.js` are really necessary.

What's the best way to configure tsc and ts-loader when one wants to target IE11/es5 with no extra on-the-fly loader like systemjs?

**Comment by johnnyreilly** [comment]
Well we have a number of [examples you can look at](https://github.com/TypeStrong/ts-loader/tree/master/examples) but they're fairly opinionated and bring Babel into the mix for the most part.  

I'm slightly surprised by some parts of your web config: 

```
    entry: {
        "a": "./src/index.ts",
        "a.min": "./src/index.ts" // what's this for?  Shouldn't you have one entry point that you treat differently in Prod and during development?  
    },
    output: {
        path: "./dist",
        filename: "[name].js",
        // I must confess to not knowing what the following settings are for?
        library: ["a"],
        libraryTarget: "var",
        umdNamedDefine: true
    },
```

In terms of `tsconfig.json` I like having these options set:

```
        "module": "es2015",
        "moduleResolution": "node",
```

These allow using ES2016 import statements which is nice.  Also it makes node resolution work in the fashion that you would expect.

In the end there is no "one right way"; it's a question of picking what works for you.

**Comment by sternbel** [comment]
@johnnyreilly thanks for your quick reply!

I usually try to keep things as simple as possible and not include too many tools and/or libraries. I for instance got rid of gulp a while ago and use only the minimum: tsc, npm, webpack and karma/jasmine. 
I took a look at your examples but it's either gulp or babel involved. Btw what is the benefit to utilise Babel in your case, apart tree shaking?

```typescript
 entry: {
        "a": "./src/index.ts",
        "a.min": "./src/index.ts" 
    },
```
It's my old fashion way (Webpack 1) to generate a.js + minified/uglyfied a.min.js at the same time. Although I have to admit that I never looked to this Dev / Prod stuff...

```typescript
output: {
        path: "./dist",
        filename: "[name].js",
        // gives the name of the library, which will replace [name] on the line above
        library: ["a"],
        // the way the library is published: var Library = xxx 
        libraryTarget: "var",
       // give a name to the AMD part of the UMD module using 'library' property
        umdNamedDefine: true
    },
```

In case I go for `"module": "es2015"` (in this case `target` should be `es2015`), can I still load `a.js` using only `<script src="a.js>`?

**Comment by johnnyreilly** [comment]
> I for instance got rid of gulp a while ago and use only the minimum

At some point I think I'll probably do the same but I just haven't got round to it yet.  One day I'm sure.

> Btw what is the benefit to utilise Babel in your case, apart tree shaking?

I make heavy use of some of the new features of ES2015+ that aren't available in vanilla TypeScript tranpilation.  For instance: `Map`, `Set`, `Promise` `Array.prototype.includes` etc.  

> In case I go for "module": "es2015" (in this case target should be es2015), can I still load a.js using only <script src="a.js>?

Give it a try I guess :smile:
