### ISSUE TITLE
Does ts-loader add "use strict" despite tsconfig setting?

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-loader#464]
I am having this issue, mentioned you guys there: https://github.com/webpack/webpack/issues/4168

Not sure if it is because of Webpack or ts-loader.

**Comment by HerringtonDarkholme** [comment]
Please provide a reproduction for us. I cannot reproduce it in minimal configuration.

app.ts
```ts
class A {}
```

```ts
module.exports = {
  entry: './app.ts',
  output: {
      filename: 'build.js'
  },
  resolve: {
      extensions: ['.js', '.ts'],
  },
  module: {
      rules: [
          { test: /\.ts$/, use:  'ts-loader' }
      ],
  },
}
```

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity.
