### ISSUE TITLE
HMR is failed and force reloading is occur even if module.hot.accept is called in some cases

### ISSUE THREAD

**Issue by ktsn** [TypeStrong/ts-loader#466]
Hi, I'm not sure whether this is intended behavior or not, but as there is a problematic case due to this behavior, I'm reporting it. If I'm missing something, just let me know. 🙂 

The issue happens if we have `a.ts` (does not accept HMR) and `b.ts` (accepting HMR), and `a.ts` imports `b.ts`. I expect HMR is succeeded if I edit `b.ts` but it is failed and the page will be reloaded. I investigated this and noticed webpack also try to do HMR with `a.ts` in such case and this causes the force reloading. 

I've also try the same thing without ts-loader and it worked as expected. (only `b.ts` is updated without force reloading).

### Version

    "ts-loader": "2.0.0",
    "typescript": "2.1.6",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.3.0"

### Reproduction

https://github.com/ktsn/ts-loader-test

1. Clone it
2. `npm install`
3. Run `npm run js`(to check expected behavior)
    1. Access dev server on browser
    2. Edit `js/dep.js`
    3. Will be updated `dep.js` on browser and HMR is succeeded.
4. Run `npm run ts`
    1. Access dev server on browser
    2. Edit `ts/dep.ts`
    3. Will be update `dep.ts` and also `main.ts` and HMR is failed (then force reloading is happened) since `main.ts` does not accept HMR.

**Comment by HerringtonDarkholme** [comment]
Thanks, my pal! Your detailed bug report is appreciated.

Effectively, I think this is the same issue with #433 . 

The workaround is adding `transpileOnly` option. However, I suspect the effect of rebuilding dependency graph which disables HMR.

**Comment by ktsn** [comment]
Oh, I did not notice the issue, sorry.
I'm closing this in favor of #433.
