### ISSUE TITLE
Using npm lib with umd module.

### ISSUE THREAD

**Issue by idchlife** [TypeStrong/ts-loader#477]
I'm trying to use https://github.com/tunnckoCore/gibon. As you can see - default script when importing using umd module. How can I use this module? I'm getting empty Object or even undefined when I'm importing this lib.

I tried to write declarations but it won't help that bundle have module gibon with local variable that does not export anything.

**Comment by blakeembrey** [comment]
What did you try? It looks like it should work by doing `import gibon = require('gibon')`.
