### ISSUE TITLE
Weird class inheritance bug when accidentally having loader run twice

### ISSUE THREAD

**Issue by mordocai** [TypeStrong/ts-loader#487]
Not really sure if this is more on webpack than ts-loader, but if you accidentally include ts-loader twice in your loaders config like so:

```
 loaders: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader'
      },
      {
        test: /\.tsx?$/,
        loader: 'ts-loader'
      }
]
```

Then running webpack gives the error message:

```
(2,32): error TS2339: Property 'setPrototypeOf' does not exist on type 'ObjectConstructor'.
```

See https://github.com/mordocai/webpack-ts-loader-bug for a typescript 2.2.1 webpack 2.x yarn project to reproduce.

**Comment by mordocai** [comment]
The rest of my typescript compiled fine, it was only when doing class inheritance that this showed up.

**Comment by blakeembrey** [comment]
That makes sense. The code would be analysed a second time because you used the loader twice. The emitted JavaScript code probably contains `setPrototypeOf`.

**Comment by blakeembrey** [comment]
And it is, see your `dist/` - https://github.com/mordocai/webpack-ts-loader-bug/blob/494a24531e50cc1a712acbf99f4a6d6200384e03/app/dist/bundle.js#L74.

**Comment by mordocai** [comment]
@blakeembrey but the output from the first analysis is .js not .ts so shouldn't it not run on it the second time since it doesn't match the test?

**Comment by blakeembrey** [comment]
I don't believe that's how Webpack works. The file keeps it's name during the compilation, it doesn't change the extension for you along the way.

**Comment by mordocai** [comment]
Sounds to me then that this is either a webpack bug or just expected behavior (though in the latter case i'd hope there would be a way to get a better error message out of webpack). Thanks, closing!
