### ISSUE TITLE
ts-loader should not log `compilerDetailsLogMessage` when profiling

### ISSUE THREAD

**Issue by klavs** [TypeStrong/ts-loader#488]
The following line fails to create a valid JSON because `compilerDetailsLogMessage` gets logged before the json.
```sh
webpack --profile --json > stats.json
```

`compilerDetailsLogMessage` should not be logged when printing webpack stats.

**Comment by johnnyreilly** [comment]
PRs welcome!

**Comment by klavs** [comment]
@sokra, @TheLarkInn, @jhnns
It makes sense to me that `ts-loader` outputs the tsc version and tsconfig location. Is there a way to print this info the same way as webpack does with `Hash`, `Version` and `Time`?

It does not seem reasonable to create a white list of cases when a loader can print something out as webpack can add new features at any time.

**Comment by jhnns** [comment]
> Is there a way to print this info the same way as webpack does with Hash, Version and Time

No, I don't think so. We would need to expose a logger on the loader context. That would be a reasonable change.

Personally, I think the loader should only output something to the console if a debug flag is set.

**Comment by klavs** [comment]
Thanks @jhnns for your input.
@johnnyreilly, what do you think about logging only if debug flag is set?

**Comment by cletusw** [comment]
> Is there a way to print this info the same way as webpack does with Hash, Version and Time

I know that the webpack progress indicator logs to stderr and it correctly doesn't get included in the redirected output.

**Comment by simon04** [comment]
Having a 68 line [logging module](https://github.com/TypeStrong/ts-loader/blob/8cff471/src/logger.ts) plus [external colouring library](https://github.com/TypeStrong/ts-loader/blob/78316c7/package.json#L35) seems to be an overkill for a total 5 logging invocations. Any reason not to simply use `console.warn`, `console.error`?

**Comment by johnnyreilly** [comment]
For version 3 of ts-loader we'll be changing the default log level to warn.  Once that lands users will no longer be affected by this. https://github.com/TypeStrong/ts-loader/issues/631 (my own "aha" moment came when I realised I was using ts-loader in `silent` mode by choice)

**Comment by johnnyreilly** [comment]
Closed with 3.0

**Comment by jhnns** [comment]
That's a good idea 👍. [`stderr` was invented exactly for this purpose 😁](https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout)
