### ISSUE TITLE
Code Runs Before Source Maps Load

### ISSUE THREAD

**Issue by adam-beck** [TypeStrong/ts-loader#489]
I have set up a very basic project to better understand how to properly get source maps to work with `ts-loader`. The following is my `webpack.config.js`.

```
const path = require('path');
const wepback = require('webpack');

module.exports = {
    devtool: 'eval-source-map',
    entry: [
        './src/index'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'
    },
    resolve: {
        extensions: ['.ts', '.js']
    },
    module: {
        rules: [{
            test: /\.ts$/,
            exclude: /node_modules/,
            use: [{
                loader: 'ts-loader'
            }]
        }}]
    }
};
```

This set up is generating the `eval()` + `//# sourceMappingURL=data:application/json...` but I cannot set breakpoints in the source maps. They never get hit. And the reason is because the `eval` step calls the function at the same time as loading the source map. Put another way, after the `eval` line in the bundle file is run I can then see the source map in my debugger but by that point the code has already executed.

For instance, my `index.ts` is as simple as this:

```
const test = 1 + 2;
console.log(test);
```

I cannot put a breakpoint on either of those lines that will get hit. However, if I wrap that in `setTimeout()` they will break. 

Is this just the case that I cannot use `devtool: eval-source-map`? I am using `webpack@2.2.1` and of `ts-loader@2.0.1`.  Things seem to be a little better with `cheap-module-source-map` ~~but when using with HMR it doesn't load the new source maps~~ (this is a browser issue, apparently).

**Comment by johnnyreilly** [comment]
I've never used ts-loader with ts-node but otherwise I've never had problems with source maps. @blakeembrey have you ever used ts-loader with ts-node?

**Comment by adam-beck** [comment]
@johnnyreilly I have since switched it to just JavaScript to eliminate as many possible problem areas as possible. The post should have been updated as I made the edit a while ago. Thank you for taking a look at this issue.
