### ISSUE TITLE
ts-loader doesn't use filesystem provided by Webpack

### ISSUE THREAD

**Issue by sthuck** [TypeStrong/ts-loader#494]
Webpack has a nice feature where you can pass it a filesystem object with the same interface as node's builtin `fs`. This allows you to generate the build completely in memory using [memoryfs](https://github.com/webpack/memory-fs) , something that is very useful for code-generation projects. 

ts-loader doesn't use the fs object it gets from webpack, but instead uses typescript `compiler.sys` at various locations. (There are obviously ways around that, like monkey-patching `fs` module, but I prefer a cleaner fix)

I'm interested in ~writing~ trying to write  a pull request to fix this, but I would obviously like to know first if this would even be considered an issue for you guys and if it would be at least considered for merging.

**Comment by johnnyreilly** [comment]
Would need to see a PR but I reckon we'd consider it.
