### ISSUE TITLE
Slow rebuild times for ts-loader@2.0.1

### ISSUE THREAD

**Issue by pelotom** [TypeStrong/ts-loader#499]
Something appears to have changed between version 2.0.0 and 2.0.1 such that my rebuild times in `--watch` mode have ballooned from ~2s to ~20s. Time for first build has remained the same.

**Comment by johnnyreilly** [comment]
I'm not experiencing the same myself; I'm not sure why you would be.  

For what it's worth there was a breaking change in webpack that we had to cater for; code-wise the changes were pretty marginal: https://github.com/TypeStrong/ts-loader/releases/tag/v2.0.1 

(For more background on the breaking change read [this](https://blog.johnnyreilly.com/2017/02/under-duck-afternoon-in-open-source.html))

BTW are you running webpack 2?

**Comment by pelotom** [comment]
Yes, I am running webpack 2, but I've tried with both webpack 1 and 2 and the problem exists in either case.

**Comment by johnnyreilly** [comment]
Do you want to share your setup?

**Comment by pelotom** [comment]
Unfortunately this is a private company repo so I can't share it wholesale. I can see about trying to create a minimal example that reproduces it when I get some time.

**Comment by johnnyreilly** [comment]
Actually, I'm starting to wonder if this is related to the `mtimes` to `getTimes()` switch.  See discussion in #497

**Comment by mmorton** [comment]
I am seeing the same thing on a large project that I too unfortunately cannot share.  Rebuild is ~30s with 2.0.1 and only ~6s with 2.0.0.  I can switch back and forth between versions and consistently see those numbers.

**Comment by johnnyreilly** [comment]
Thanks for reporting. We've got a PR that looks like it may resolve the issue: https://github.com/TypeStrong/ts-loader/pull/500

However since i haven't experienced it myself i can't be sure. Would you be able to give this PR a test drive and confirm if it fixes things?

**Comment by johnnyreilly** [comment]
Hopefully #500 will fix this - closing for now.
