### ISSUE TITLE
On webpack run: "TypeError: Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by aight8** [TypeStrong/ts-loader#502]
If ```transpileOnly``` is true it works. However this is not a permanent solution.
Webpack builds very long time and the memory of the webpack process increases over 1.5 GB, until node.js ran out of memory. I literally build just a ts file as entry point which contains ```console.log('abc')```.

```JS
ts-loader: Using /Users/aight8/my-project/node_modules/typescript@2.2.1. This version may or may not be compatible with ts-loader.
ts-loader: Using config file at /Users/aight8/my-project/tsconfig.json

/Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25122
                error(source.valueDeclaration.name, ts.Diagnostics.Cannot_augment_module_0_with_value_exports_because_it_resolves_to_a_non_module_entity, symbolToString(target));
                                             ^
TypeError: Cannot read property 'name' of undefined
    at mergeSymbol (/Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25122:46)
    at /Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25146:21
    at Map.forEach (native)
    at mergeSymbolTable (/Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25136:20)
    at mergeSymbol (/Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25117:21)
    at /Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25146:21
    at Map.forEach (native)
    at mergeSymbolTable (/Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25136:20)
    at mergeSymbol (/Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25117:21)
    at /Users/aight8/my-project/node_modules/typescript/lib/typescript.js:25146:21
```

Ts config is currently:
```JSON
{
    "compilerOptions": {
        "noImplicitAny": false,
        "strictNullChecks": false,
        "moduleResolution": "node",
        "target": "es2017",
        "outDir": "bin",
        "sourceMap": true,
        "module": "commonjs",
        "typeRoots": [
            "node_modules/@types"
        ],
        "pretty": true
    },
    "include": [
        "src"
    ]
}
```

However I tested various other settings. The error stays the same.

Tested with typescript **2.2.1** and **2.3-nightly**

Parallel issue in awesome-typescript-loader: https://github.com/s-panferov/awesome-typescript-loader/issues/395

**Comment by johnnyreilly** [comment]
I've a feeling there are issues with `typeRoots` - though i forget the specifics...

**Comment by lbguilherme** [comment]
Looks like this was fixed by pull https://github.com/Microsoft/TypeScript/pull/15075, issue https://github.com/Microsoft/TypeScript/issues/14628. Will be released as TS 2.3.1 soon.

**Comment by lbguilherme** [comment]
2.3.1 was released and still contains the bug, you can use `typescript@next`. The fix was *NOT* released, but resides in master for 2.4.0. They really should release this.

**Comment by Opty1712** [comment]
Got same error. Any news?

**Comment by johnnyreilly** [comment]
Assuming 2.4 resolved it then hang tight for that. It'll be out soon

**Comment by johnnyreilly** [comment]
Oh and you could try making use of the fork-ts-checker-webpack-plugin (see our docs). It should be run with ts-loader in transpile mode and so might not be affected. Worth a try anyway (perf boost either way!)
