### ISSUE TITLE
Typings for CSS modules

### ISSUE THREAD

**Issue by MortenHoustonLudvigsen** [TypeStrong/ts-loader#512]
I have the beginnings of creating typings for CSS modules as created by `css-loader`.

The idea is that a virtual `.d.ts` file is created and consumed by ts-loader.

Example:

Given a file `Game.css`:
```css
.game {
    display: flex;
    flex-direction: row;
}

.game-board {
}

.game-info {
    margin-left: 20px;
}

.game-footer {
    margin-top: 20px;
}
```

A virtual `Game.css.d.ts` file is created (assuming `modules: true` and `camelCase: true` in the `css-loader` options):
```typescript
export const game: string;
export const gameBoard: string;
export const gameInfo: string;
export const gameFooter: string;

declare const __styles: {
    "game": string;
    "game-board": string;
    "gameBoard": string;
    "game-info": string;
    "gameInfo": string;
    "game-footer": string;
    "gameFooter": string;
};
export default __styles;
```

It should optionally be possible to write the virtual `.d.ts` file to disk, so that other tools can benefit from the typings.

There are existing solutions, but they suffer from the following problems:
* The local css classes are only known after `css-loader` has run. So it is not feasible to generate typings in a prebuild step.
* A loader used with `css-loader`, that generates typings and writes them to disk will not work properly, because the `.d.ts` files can be generated _*after*_ `ts-loader` tries to read the files.

So my suggestion is to incorporate CSS modules in ts-loader.

My question is whether you would be open to at PR implementing this?

**Comment by HerringtonDarkholme** [comment]
Currently the best workaround I think is https://github.com/Quramy/typed-css-modules. It generates definition file beforehand.

**Comment by MortenHoustonLudvigsen** [comment]
After discussing this with @johnnyreilly and @HerringtonDarkholme I have started implementing this as stand alone loader, to be used with ts-loader: [ts-css-loader](https://github.com/MortenHoustonLudvigsen/ts-css-loader).

It is actually working right now, but when webpack is in watch mode it runs twice every time a css file is changed. The first time ts-loader does not pick up the changed typings.

@johnnyreilly would you be amenable to a PR which can handle changed files from other loaders in the chain?

I am thinking that the loader context could be augmented with a new property:

```typescript
'ts-loader-files'?: { path: string; contents: string; }[];
```

If `ts-loader-files` exists in the loader context, ts-loader would then run `updateFileInCache` for each file, and possibly not add dependencies for them, assuming that the loader, that has supplied the file, takes care of dependencies.

For dependencies to work properly the call to `clearDependencies` in `getEmit` should be removed, unless there is a reason for the call, that I don't know about.

**Comment by amir-arad** [comment]
I have the exact same problem working with my own loader based on [typed-css-modules-loader](https://github.com/olegstepura/typed-css-modules-loader) in webpack 3: seems that ts-loader has already scanned the file system before the css-loader has a chance to add `d.ts` files. it does not respond to `enforce` configurations when it comes to loading typings.

**Comment by johnnyreilly** [comment]
Closing as https://github.com/Jimdo/typings-for-css-modules-loader seems to cover this well.
