### ISSUE TITLE
Error building generic types

### ISSUE THREAD

**Issue by ddwwcruz** [TypeStrong/ts-loader#513]
**Current Output**
```
ERROR in ../server/broadcaster.ts
Module parse failed: /home/wyn/Code/ddwwcruz/node-spyfall/src/server/broadcaster.ts Unexpected token (3:5)
You may need an appropriate loader to handle this file type.
| import AI from './library/auto-increment'
| 
| type Subscriber<T> = (args: T) => void
| 
| const broadcasterAI = new AI()
```

**Expected Output**

This should compile cleanly. I have other generic types that compiles cleanly elsewhere.

**Comment by QuantumInformation** [comment]
I'm getting the same error (awesome-ts-loader)for a different things and raised here: https://github.com/s-panferov/awesome-typescript-loader/issues/404

**Comment by elvizcacho** [comment]
the loader is not able to parse this typed generic function

```
const function2 = <I>(arg: I): I{

    return arg
}
```
I get: 
```
Module parse failed: Unexpected token (3:0)
File was processed with these loaders:
 * ./node_modules/awesome-typescript-loader/dist/entry.js
You may need an additional loader to handle the result of these loaders.
| var function2 = React.createElement(I, null,
|     "(arg: I): I",
> ,
|     "return arg } export default function2");
```

**Comment by B3zo0** [comment]
> the loader is not able to parse this typed generic function
> 
> ```
> const function2 = <I>(arg: I): I{
> 
>     return arg
> }
> ```
> 
> I get:
> 
> ```
> Module parse failed: Unexpected token (3:0)
> File was processed with these loaders:
>  * ./node_modules/awesome-typescript-loader/dist/entry.js
> You may need an additional loader to handle the result of these loaders.
> | var function2 = React.createElement(I, null,
> |     "(arg: I): I",
> > ,
> |     "return arg } export default function2");
> ```

You are using **awesome-typescript-loader**. This is ts-loader.
