### ISSUE TITLE
Importing .html get undefined in angularjs

### ISSUE THREAD

**Issue by omkadiri** [TypeStrong/ts-loader#525]
Am trying to be consistent using import across my application but all file with .ts have some kind of issue with import file that are not a module. Using babel-loader with all .js file works fine.

 eg: 
![image](https://cloud.githubusercontent.com/assets/10691627/25291696/29b24664-26a1-11e7-8b47-549f30c6f894.png)
will transpile into:
![image](https://cloud.githubusercontent.com/assets/10691627/25291917/f84194d0-26a1-11e7-8cc6-e28080ac9a94.png)
which default will always be undefined because it was never set. However same functionality with .js using babel-loader will transpile into a file with 
![image](https://cloud.githubusercontent.com/assets/10691627/25292184/1695f90c-26a3-11e7-97ec-86eecb430e35.png)
Here _interopRequireDefault takes care of setting the default.

There are other ways i can import the html file but can this issue be look at?

**Comment by blakeembrey** [comment]
This is how TypeScript is designed to work. If the export of the HTML file CommonJS you should try `import foo = require('foo')`. It should be a type error importing like that too, have you added a definition to make it not error?

**Comment by omkadiri** [comment]
Yes i added a definition for *.html
