### ISSUE TITLE
Sourcemaps are not working

### ISSUE THREAD

**Issue by artem-malko** [TypeStrong/ts-loader#534]
Hello.

I have got some problems with sourcemaps. They are switched on in tsconfig.json:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "tslib": [
        "./node_modules/tslib/tslib.d.ts"
      ],
      "*": [
        "src/*"
      ]
    },
    "target": "es5",
    "pretty": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "jsx": "react",
    "strictNullChecks": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

They are switched on in webpack config:
```js
devtool: 'inline-source-map'
```
And my config for ts-loader:
```js
module: {
    rules: [
      {
        test: /\.ts(x)?$/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true
            }
          }
        ]
      }
    ]
  },
```

But in browser (google chrome, for example) I see this code:
```js
webpackJsonp([1],{

/***/ 303:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = __webpack_require__(20);
var React = __webpack_require__(12);
var react_redux_1 = __webpack_require__(26);
var header_1 = __webpack_require__(302);
var RootPage = (function (_super) {
    tslib_1.__extends(RootPage, _super);
    function RootPage() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    RootPage.prototype.render = function () {
        var name = this.props.name;
        return (React.createElement("div", null, React.createElement("div", null, "ROOT PAGE"), React.createElement(header_1.default, { title: name })));
    };
    return RootPage;
}(React.Component));
function mapStateToProps(state) {
    return {
        name: state.appContext.page.type
    };
}
exports.default = react_redux_1.connect(mapStateToProps)(RootPage);


/***/ })

});
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicm9vdFBhZ2UuanMiLQ==
```
I striped some of sourcemaps content.

It is quite strange, cause I want to see .tsx code of my component:
```tsx
import * as React from 'react';
import { connect } from 'react-redux';
import {
  AppState
} from 'types/appState';
import {
  RootPageProps
} from './types';

import Header from 'app/components/header/header';

class RootPage extends React.Component<RootPageProps, {}> {
  public render() {
    const { name } = this.props;

    return (
      <div>
        <div>ROOT PAGE</div>
        <Header title={name} />
      </div>
    );
  }
}

function mapStateToProps(state: AppState): RootPageProps {
  return {
    name: state.appContext.page.type
  };
}

export default connect(mapStateToProps)(RootPage);
```

So I'd like to know, what I'm doing wrong?)

**Comment by johnnyreilly** [comment]
Could you put up a screenshot of your devtools? There should be a webpack item under sources which, when expanded, reveals the original source. You might need to f5 first to see it. Your config looks correct though

**Comment by johnnyreilly** [comment]
It's also possibly worth looking at some of the examples in this repo. They demo sourcemap support

**Comment by artem-malko** [comment]
@johnnyreilly Here you are =)

Sources from webpack dir (it looks strange, not like in source file):
<img width="762" alt="screenshot 2017-05-04 09 38 34" src="https://cloud.githubusercontent.com/assets/1823689/25688950/a1216ebc-30ad-11e7-8f35-b35acb929a48.png">

And this is a file from base source:
<img width="758" alt="screenshot 2017-05-04 09 38 45" src="https://cloud.githubusercontent.com/assets/1823689/25688956/b3aa1c50-30ad-11e7-9454-0435f898ba9f.png">

File from webpack dir looks much more better, but it is not source file.

**Comment by johnnyreilly** [comment]
Hmmm do you have a repo you can share?

**Comment by artem-malko** [comment]
@johnnyreilly I am sorry, but I can not) I can try to create a sample repo, but it doesn't matter, cause I reproduce it in any project.
By the way, RootPage is separate chunk, which will be loaded via require.ensure by webpack, may be it can be useful).

I will try to reproduce it by using example https://github.com/TypeStrong/ts-loader/tree/master/examples/webpack2-react-cdn-simple

**Comment by artem-malko** [comment]
@johnnyreilly it is ok with webpack2-react-cdn-simple. I do not know, what to do(

**Comment by artem-malko** [comment]
@johnnyreilly by the way, "sourceMap": true, option from tsconfig is not working, as I understand, cause if dev-tool option is disabled in webpack, there is no sourcemaps on client and it is not depends on tsconfig sourceMap option.

**Comment by johnnyreilly** [comment]
I would compare your setup with the working demo. Without seeing it I can't help too much. I think sourcemaps need to be enabled both in webpack and TypeScript

**Comment by joekrump** [comment]
@artem-malko I think I'm running into a similar issue. Were you able to resolve it on your end? Are you able to give any tips?

**Comment by artem-malko** [comment]
@johnnyreilly I just switch on sourcemaps in tsconfig and webpack config and it works =) I use ts-loader 5.3.3 and webpack 4.29.6
