### ISSUE TITLE
Faster type checking with forked process

### ISSUE THREAD

**Issue by piotr-oles** [TypeStrong/ts-loader#537]
Hi everyone!
I've created webpack plugin: [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) that plays nicely with `ts-loader`. The idea is to compile project with `transpileOnly: true` and check types on separate process (async). With this approach, webpack build is not blocked by type checker and we have semantic check with fast incremental build. More info on github repo :)
So if you like it and you think it would be good to add some info in README.md about this plugin, I would be greatful.
Thanks :)

**Comment by johnnyreilly** [comment]
Thanks for letting us know! This sounds really useful / interesting. Assuming there's no gotchas then I think adding documentation about this to ts-loader could be a good idea.

When I get some time I'd like to have a play with this and reply back to you. Thanks!

**Comment by johnnyreilly** [comment]
Would you  be interested in submitting a PR which contains:

1. An update to the readme mentioning the fork-ts-checker-webpack-plugin and
2. An example setup to live here: https://github.com/TypeStrong/ts-loader/tree/master/examples

?

I think this could be useful to people. Thanks for your work!

**Comment by piotr-oles** [comment]
Of course, I will submit it soon ;)

**Comment by johnnyreilly** [comment]
Merged.  Thanks!
