### ISSUE TITLE
Why we need babel if we can use `tsc` to convert `es6` to `es5`?

### ISSUE THREAD

**Issue by chenzhutian** [TypeStrong/ts-loader#542]
As my understanding, I can use `tsc` to convert `es6` to `es5`. The only constraint is that the file extension of the script to be converted must be `.ts` or `.tsx`.
Can `ts-loader` provide an option so that we can convert `.js` file by using `tsc`?
By doing so, I can no longer need to install too many devDependences modules of babel.

**Comment by johnnyreilly** [comment]
Babel is necessary if you want to polyfill new APIs like `Promise`, `Map` etc. If you don't use those then you don't need babel
