### ISSUE TITLE
visualStudioErrorFormat - Help integrating with Visual Studio - nothing happens

### ISSUE THREAD

**Issue by stephen-nba** [TypeStrong/ts-loader#545]
I have the following config:

```javascript
test: /\.ts?$/,
                use: [
                    {
                        loader: 'ts-loader',
                        options: {
                            sourceMap: true,
                            visualStudioErrorFormat: true
                        }
                    }]
```
And I see the following output in the task runner:

    ERROR in ./app/shared/apiService.ts
    C:\Code\js\app\shared\apiService.ts(29,25): error TS1005: ';' expected.
    ERROR in ./app/shared/apiService.ts
    C:\Code\js\app\shared\apiService.ts(29,25): error TS7027: Unreachable code detected.
    ERROR in ./app/shared/apiService.ts
    C:\Code\js\app\shared\apiService.ts(29,21): error TS2339: Property '_ht' does not exist on type 
    'ApiService'.
    ERROR in ./app/shared/apiService.ts
    C:\Code\js\app\shared\apiService.ts(29,25): error TS2304: Cannot find name 'tp'.

But nothing happens in Visual Studio.  Should I be expecting that having run webpack in the task runner that these lines in the console are clickable? Or should I expect that these lines appear in the error window automatically and I can click on them there? Neither of those things are happening.

Thanks!

**Comment by NN---** [comment]
There was an issue and a PR: #355 #356 but seems it didn't really solve the issue.
