### ISSUE TITLE
Watch tsconfig.json

### ISSUE THREAD

**Issue by jbrantly** [TypeStrong/ts-loader#55]
It would be ideal if tsconfig.json could be watched for changes. I think this would have to result in the creation of a whole new language service instance.

**Comment by basarat** [comment]
> I think this would have to result in the creation of a whole new language service instance.

That is what I do in atom-ts.

Also this is what `tsc -w` does internally as well. Callstack: 

* set cached program to undefined : https://github.com/Microsoft/TypeScript/blob/d9559d58ca4f68bf51849d067fe2e9560b2e081f/src/compiler/tsc.ts#L296

* recompile https://github.com/Microsoft/TypeScript/blob/d9559d58ca4f68bf51849d067fe2e9560b2e081f/src/compiler/tsc.ts#L307

* performCompilation 
https://github.com/Microsoft/TypeScript/blob/d9559d58ca4f68bf51849d067fe2e9560b2e081f/src/compiler/tsc.ts#L313

* no cached program https://github.com/Microsoft/TypeScript/blob/d9559d58ca4f68bf51849d067fe2e9560b2e081f/src/compiler/tsc.ts#L216 

* create an cache the new program 
https://github.com/Microsoft/TypeScript/blob/d9559d58ca4f68bf51849d067fe2e9560b2e081f/src/compiler/tsc.ts#L249

:rose:

**Comment by OliverJAsh** [comment]
I often make changes to my `tsconfig` and have to restart `webpack --watch` to pick up the changes.

**Comment by johnnyreilly** [comment]
Pull requests welcome!
