### ISSUE TITLE
Dependency bug in ts-loader?

### ISSUE THREAD

**Issue by wwoods** [TypeStrong/ts-loader#567]
I encountered a bug in the following generated code from ts-loader (this is from ts-loader, right?); specifically, `TaskLoader` is undefined:

```js
__decorate([
    __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_5__angular_core__["N" /* Input */])(),
    __metadata("design:type", TaskLoader), // <-- ReferenceError here
    __metadata("design:paramtypes", [TaskLoader])
], SStarTaskRow.prototype, "loader", null);
```

The code that generates this bug looks like the following:

A.ts
```ts
export class TaskLoader {
}
```

B.ts
```ts
import {TaskLoader} from 'A';
export class UsesTaskLoader {
  loader:TaskLoader|null = null;
}
```

main.ts
```ts
import {TaskLoader} from 'A';
import {UsesTaskLoader} from 'B';
loader = new TaskLoader();
usesLoader = new UsesTaskLoader();
usesLoader.loader = loader;
```

With this configuration of files, I get the bug.  If I change B.ts:

B-fixed.ts
```ts
import {TaskLoader} from 'A';
const _workaround = new TaskLoader();
export class UsesTaskLoader {
  loader:TaskLoader|null = null;
}
```

Then it begins working again.  I'm pretty sure ts-loader (most likely) or some other package that prepares the typescript in my ionic chain is not properly importing the `TaskLoader` class from A because it is not used, except in a definition.

Apologies for lack of a complete MWE, this is part of an ionic project and I'm unsure how to set the webpack / ts config files independently at the moment, and figured this would be enough information for the issue.

Thanks for taking a look.

**Comment by collibra** [comment]
I have similiar problem only for me, `ClassNames` used in JSX is not taken into account and missing after compilation.

```
import ClassNames = require("ClassNames");
const CloseIcon: React.StatelessComponent<IIconProps> = (props) => {
  return (
    <Icon
      {...props}
      className={ClassNames(props.className, "icon-close")}
    />
  );
};
```
-->
```
...
var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;!(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__, exports, __webpack_require__(0)], __WEBPACK_AMD_DEFINE_RESULT__ = function (require, exports, React) {
...
```
ClassNames is not there in dependencies and JS crashes when its encountered in compiled JSX.
