### ISSUE TITLE
Add warning if `files` is omitted from tsconfig.json

### ISSUE THREAD

**Issue by jbrantly** [TypeStrong/ts-loader#57]
[All files in the directory and subdirectory are included](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#details) if `files` is omitted from tsconfig.json. This typically results in some errors of some sort as all kinds of crap can get added (TypeScript lib files, for instance). I think it might be useful to detect this condition and just print a simple warning.

**Comment by OldrichDlouhy** [comment]
In TypeScript 1.6 there is an option to exclude directories when you do not specify the files property - see https://github.com/Microsoft/TypeScript/issues/3043. So if this is implemented it needs to take the exclude property into acount.

**Comment by jbrantly** [comment]
Good point. FWIW, `exclude` does already work in ts-loader, but you're definitely right that any warning message would need to take that into account.
