### ISSUE TITLE
individual js files not being generated by ts-loader

### ISSUE THREAD

**Issue by thiagolacerda** [TypeStrong/ts-loader#571]
Hi,

I'm starting a TypeScript + react + webpack project. From the ts-loader and webpack docs, seems like webpack + ts-loader do all the needed steps to compile the TypeScript files and bundle them all together in a single js file.

But, ts-loader is not generating individual js files for each ts file that I have in my project. To explain better: when I compile my project using only tsc I get both declaration files and js files for each individual ts file in my project, but when using only webapack I get only .d.ts and bundle js file. Since ts-loader also invoke tsc under the hood, my plan was to only use webpack + ts-loader for everything.

Here is an example repo with my configuration: https://github.com/thiagolacerda/reacttest

if I run ``yarn run ts`` (as stated in my package.json), the dist folder will have these files:
Hello.d.ts
Hello.js
Hello.js.map
index.d.ts
index.js
index.js.map

However, running ``yarn run bundle`` I get this in my dist folder:
Hello.d.ts
bundle.js
bundle.js.map
index.d.ts

Why the individual js files Hello.js and index.js (as well as their map files) are not being generated too? Is that by design? Am I missing some config option?

Thanks

**Comment by johnnyreilly** [comment]
That's by design and it's really a webpack thing rather than a ts-loader thing. With webpack you don't generate a single output file for each input file. I recommend having a read of the webpack docs.
