### ISSUE TITLE
generating webpack package statistics, ts-loader will prepend message into generated json

### ISSUE THREAD

**Issue by llyys** [TypeStrong/ts-loader#572]
when running a comand  
`webpack --env production --profile --json > stats.json`

stats.json will contain following message in generated stats.json
ts-loader: Using typescript@XXX and pathTo\tsconfig.json

this will be generated in config.js:11 by
`log.logInfo((compilerDetailsLogMessage + " and " + configFilePath).green);`

it is right now merely annoyance and just by removing the first line in stats.json.
But also it will break other automation pluggins, because the generated json will be invalid.

**Comment by johnnyreilly** [comment]
How about if you use the `silent` option?

**Comment by llyys** [comment]
thank you 
by adding loader: "ts-loader?silent",
now it won'nt print out this.
