### ISSUE TITLE
Cannot default export object literal with computed property name

### ISSUE THREAD

**Issue by ytkj** [TypeStrong/ts-loader#588]
Minimal reproduction code is below:

https://github.com/ytkj/ts-loader-issue-reproduction

1. `git clone https://github.com/ytkj/ts-loader-issue-reproduction`
2. `cd ts-loader-issue-reproduction`
3. `npm install`
4. `npm start`

TypeScript source files, `index.ts` and `sub.ts`, are grammatically right, but ts-loader emits error.
- index.ts
```ts
import a from './sub';

console.log(a);
```

- sub.ts
```ts
const COMPUTED_PROPERTY_NAME: string = 'message';

export default {
    [COMPUTED_PROPERTY_NAME]: 'foo'
};
```
```
ERROR in ./sub.ts
Module parse failed: D:\dev\ts-loader-issue-reproduction\node_modules\ts-loader\index.js??ref--0-0!D:\dev\ts-loader-issu
e-reproduction\sub.ts Unexpected token (2:22)
You may need an appropriate loader to handle this file type.
| var COMPUTED_PROPERTY_NAME = 'message';
| export default _a = {},
|     _a[COMPUTED_PROPERTY_NAME] = 'foo',
|     _a;
 @ ./index.ts 1:0-22
```

**Comment by johnnyreilly** [comment]
What is your tsconfig.json?

**Comment by ytkj** [comment]
https://github.com/ytkj/ts-loader-issue-reproduction/blob/master/tsconfig.json

**Comment by johnnyreilly** [comment]
And this works OK with tsc?

**Comment by ytkj** [comment]
Yes.

**Comment by johnnyreilly** [comment]
How peculiar.  Does it work ok with named exports?

**Comment by johnnyreilly** [comment]
It looks like the default export is just lacking parens.  `(` and `)` around the export.  I'm wondering if this is actually a ts-loader issue or one with TypeScript itself.  Simple test - try swapping in awesome-typescript-loader and see if it suffers the same issue.  If it does then it may be a TypeScript compiler issue.

**Comment by ytkj** [comment]
> Simple test - try swapping in awesome-typescript-loader and see if it suffers the same issue.

I tryed actually.
awesome-typescript-loader emits same error.

```
ERROR in ./sub.ts
Module parse failed: D:\dev\ts-loader-issue-reproduction\node_modules\awesome-typescript-loader\dist\entry.js!D:\dev\ts-
loader-issue-reproduction\sub.ts Unexpected token (2:22)
You may need an appropriate loader to handle this file type.
| var COMPUTED_PROPERTY_NAME = 'message';
| export default _a = {},
|     _a[COMPUTED_PROPERTY_NAME] = 'foo',
|     _a;
 @ ./index.ts 1:0-22
```

**Comment by ytkj** [comment]
> It looks like the default export is just lacking parens. ( and ) around the export. 

Just adding `(` and `)` around object literal, compilation succeeds for both ts-loader and awesome-typescript-loader.

- sub.ts
```ts
export default ({
    [COMPUTED_PROPERTY_NAME]: 'foo'
});
```

**Comment by johnnyreilly** [comment]
I think this is a tsc transpilation issue. I'd recommend opening an issue there and using your workaround in the interim

**Comment by ytkj** [comment]
Yes, I think so. I'll take your advice.
Thanks a lot!
