### ISSUE TITLE
webpack --watch ignores certain files when ts-loader with transpileOnly is used

### ISSUE THREAD

**Issue by pamelus** [TypeStrong/ts-loader#591]
When using [configuration mentioned in Faster Builds section](https://github.com/TypeStrong/ts-loader/tree/master/examples/fork-ts-checker) of [Readme.md](https://github.com/TypeStrong/ts-loader/blob/master/README.md) (with `fork-ts-checker-webpack-plugin` and `transpileOnly` set to `true`), webpack is unable to watch `.ts` files those do not produce any `.js` output (e.g. with interface definition only).

Consider following `fancy-interface.ts` file:
```
export interface FancyInterface {
	test(): void;
}
```
If you run `webpack --watch`, modifications in this file are ignored, as webpack is not triggering rebuild. With `transpileOnly: false` everything works like expected.

I've made a small repo based on "fork-ts-checker" example to isolate the problem. Steps to reproduce:

1. `git clone https://github.com/pamelus/ts-loader-transpileOnly-watch`
2. `cd ts-loader-transpileOnly-watch && npm install`
3. `npm run start`
4. Make some changes in `src/fancy-interface.ts`. Observe that webpack is not triggering rebuild.

I don't know either it is intentional or not, but I think it deserves at least small mention in Readme.md. Or a fix. 

Test case created using:
- webpack@3.4.1
- typescript@2.4.2
- ts-loader@2.3.2
- fork-ts-checker-webpack-plugin@0.2.7

**Comment by johnnyreilly** [comment]
Yes - this is an issue with the fork checker, you can track it here: https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/36

Agreed it would be good to mention it in the readme - if you'd like to submit a PR I'll take a look.

**Comment by johnnyreilly** [comment]
I've raised a docs PR for the fork checker [here](https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/37)
