### ISSUE TITLE
Extended `tsconfig` ignores parent `moduleResolution` if `module` is set

### ISSUE THREAD

**Issue by demurgos** [TypeStrong/ts-loader#592]
Hi,
I have the following directory structure:

```
├── tsconfig.json
└─┬ src
  └── browser.tsconfig.json
```

With the following config at the root:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node"
  }
}
```
And in src/browser.tsconfig.json:
```
{
  "extend": "../tsconfig.json",
  "compilerOptions": {
    "module": "es6"
  }
}
```

I can successfully run `tsc -p src/browser.tsconfig.json` but supplying this same config to `ts-loader` results in `error TS2307: Cannot find module 'my-node-module'` (fails to resolve node modules in `node_modules`).

I was about to take a deep dive into the library to understand what happened when I had the idea to simply duplicate `moduleResolution`. It solved my issue so I am just reporting it and hope that it'll help.

**Comment by johnnyreilly** [comment]
Thanks for reporting!
