### ISSUE TITLE
Module build failed: Error: Typescript emitted no output [*.d.ts] files

### ISSUE THREAD

**Issue by Foreinyel** [TypeStrong/ts-loader#596]
I write some definition files in my vue project, it goes write when packing or building.
but throws exceptions when running unit-testing.
below is the errors:

`
WARNING in ./src/public/utils/wx.d.ts
Module build failed: Error: Typescript emitted no output for /Users/shihao/Documents/Ldj/ldj_wechat_user/src/public/utils/wx.d.ts.
    at successLoader (/Users/shihao/Documents/Ldj/ldj_wechat_user/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/shihao/Documents/Ldj/ldj_wechat_user/node_modules/ts-loader/dist/index.js:21:12)
 @ ./src \.\/(?!main\.ts)(?!((\S*\.d\.ts)|(\S*\.scss))$)
 @ ./test/unit/index.js
08 08 2017 09:55:31.729:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
08 08 2017 09:55:31.730:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
08 08 2017 09:55:31.772:INFO [launcher]: Starting browser PhantomJS
08 08 2017 09:55:33.064:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket E2nThVXeM8NYRY3aAAAA with id 31493736
08 08 2017 09:55:33.339:WARN [reporter]: SourceMap position not found for trace: undefined
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Module build failed: Error: Typescript emitted no output for /Users/shihao/Documents/Ldj/ldj_wechat_user/src/components/amap/amap.d.ts.
      at successLoader (/Users/shihao/Documents/Ldj/ldj_wechat_user/node_modules/ts-loader/dist/index.js:39:15)
      at Object.loader (/Users/shihao/Documents/Ldj/ldj_wechat_user/node_modules/ts-loader/dist/index.js:21:12)
  at index.js:29910`

--karma config file
`const webpackConfig = require('../../build/webpack.test.conf');

module.exports = function (config) {
  config.set({
    // to run in additional browsers:
    // 1. install corresponding karma launcher
    //    http://karma-runner.github.io/0.13/config/browsers.html
    // 2. add it to the `browsers` array below.
    browsers: ['PhantomJS'],
    frameworks: ['mocha', 'sinon-chai', 'phantomjs-shim'],
    reporters: ['spec', 'coverage'],
    files: ['./index.js'],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap'],
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true,
    },
    'log-level': 'info',
    coverageReporter: {
      dir: './coverage',
      reporters: [
        {type: 'lcov', subdir: '.'},
        {type: 'text-summary'},
      ],
    },
  });
};`

typescript and ts-loader are latest versions.

anyone can help?

**Comment by johnnyreilly** [comment]
Sorry I'm not a Vue user. Possibly @herringtondarkholme can help?

**Comment by HerringtonDarkholme** [comment]
Can you provide a repo for reproduction?

**Comment by Foreinyel** [comment]
here is a demo I wrote, and it has the same issue. Thank you.
@HerringtonDarkholme 
https://github.com/Foreinyel/vue-typescript

**Comment by Foreinyel** [comment]
@HerringtonDarkholme ,whole exception messages:
WARNING in ./src/vue-js-modal.d.ts
Module build failed: Error: Typescript emitted no output for /Users/shihao/Documents/demo_projects/vue-demo2/src/vue-js-modal.d.ts.
    at successLoader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:21:12)
 @ ./src \.\/(?!main\.ts)(?!((\S*\.d\.ts)|(\S*\.scss))$)
 @ ./test/unit/index.js

WARNING in ./src/globals.d.ts
Module build failed: Error: Typescript emitted no output for /Users/shihao/Documents/demo_projects/vue-demo2/src/globals.d.ts.
    at successLoader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:21:12)
 @ ./src \.\/(?!main\.ts)(?!((\S*\.d\.ts)|(\S*\.scss))$)
 @ ./test/unit/index.js

WARNING in ./src/public/classComponent/globals.d.ts
Module build failed: Error: Typescript emitted no output for /Users/shihao/Documents/demo_projects/vue-demo2/src/public/classComponent/globals.d.ts.
    at successLoader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:21:12)
 @ ./src \.\/(?!main\.ts)(?!((\S*\.d\.ts)|(\S*\.scss))$)
 @ ./test/unit/index.js

WARNING in ./src/vue-shims.d.ts
Module build failed: Error: Typescript emitted no output for /Users/shihao/Documents/demo_projects/vue-demo2/src/vue-shims.d.ts.
    at successLoader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/shihao/Documents/demo_projects/vue-demo2/node_modules/ts-loader/dist/index.js:21:12)
 @ ./src \.\/(?!main\.ts)(?!((\S*\.d\.ts)|(\S*\.scss))$)
 @ ./test/unit/index.js
08 08 2017 17:51:02.651:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
08 08 2017 17:51:02.652:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
08 08 2017 17:51:02.653:ERROR [karma]: Found 1 load error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-demo2@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-demo2@1.0.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shihao/.npm/_logs/2017-08-08T09_51_02_716Z-debug.log

**Comment by juunp** [comment]
I have the same error in an angularJS project. Did you find any solution?
Using awesome-typescript-loader instead of ts-loader doesn't raise the errors FYI.

**Comment by anymost** [comment]
The same problem I have to face, somebody has the way to solve it?

**Comment by bobohuochai** [comment]
try set options 'transpileOnly' value to set ?
