### ISSUE TITLE
Documentation: webpack-fail-plugin not needed anymore

### ISSUE THREAD

**Issue by mblandfo** [TypeStrong/ts-loader#599]
The documation for ts-loader says to use webpack-fail-plugin.

webpack-fail-plugin says it's deprecated and not needed anymore https://www.npmjs.com/package/webpack-fail-plugin

**Comment by johnnyreilly** [comment]
Last time I tested it was still necessary... Maybe worth trying again - but it was pretty recent...

**Comment by mblandfo** [comment]
Hm that's weird, their doc says not needed as of webpack 2. I'm on webpack 3. I just tested by adding a random cast to boolean in my ts code and it errored out:

```
ERROR in ./src/x.ts
(21,47): error TS2352: Type '(...args: any[]) => void' cannot be converted to type 'boolean'.
Warning: exec: internal error Use --force to continue.

Aborted due to warnings.
```

**Comment by johnnyreilly** [comment]
Ok - maybe we can ditch this now
