### ISSUE TITLE
Loader option: ignoreWarnings

### ISSUE THREAD

**Issue by jbrantly** [TypeStrong/ts-loader#60]
We need to add the loader option `ignoreWarnings` like [typescript-simple-loader](https://github.com/blakeembrey/typescript-simple-loader/blob/master/src/typescript-simple-loader.ts#L223-L225)

One topic of discussion here is that ts-loader only emits TS errors as webpack errors and not warnings. Before we add this we need to decide between errors only vs errors/warnings, and if we go errors only then the option should probably be called `ignoreErrors`. Or we could sidestep the issue and come up with a more generic name.

**Comment by jbrantly** [comment]
Idea for a generic name: `ignoreDiagnostics`

Reasons why ts-loader does what it does:

1. webpack errors aren't necessarily errors in the sense that there is no output. Files with TS errors continue to be emitted.
2. I looked into making TS warnings into webpack warnings, but when I looked I found out [there are no TS warnings](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json)
3. Using errors interacts with the webpack NoErrorsPlugin which causes webpack to not emit if there are errors. I feel like this puts the user in ultimate control.

**Comment by gdi2290** [comment]
this feature is need for alpha software where the typings may produce unneeded warning.  For this reason the feature was requested in typescript-simple-loader. Since we're merging all the ts loaders I would like to replace typescript-simple-loader in my starter repo which uses alpha software (Angular 2)

https://github.com/angular-class/angular2-webpack-starter

**Comment by jbrantly** [comment]
Yup, I was actually planning on implementing this tonight for that very reason.

**Comment by gdi2290** [comment]
I need to ignore this one error
2309 -> An export assignment cannot be used in a module with other exported elements.

**Comment by jbrantly** [comment]
This was published in v0.5.6
