### ISSUE TITLE
Documentation: To generate declaration files, DeclarationBundlerPlugin is needed.

### ISSUE THREAD

**Issue by mblandfo** [TypeStrong/ts-loader#600]
I tried generating a .d.ts file without DeclarationBundlerPlugin and just got a bunch of imports to my source files. This is bad since I don't want to ship my source files.

Using DeclarationBundlerPlugin generated the correct .d.ts file.

**Comment by johnnyreilly** [comment]
If you could submit a docs PR that would be awesome!
