### ISSUE TITLE
LoaderOptions: configFileContent

### ISSUE THREAD

**Issue by hdennen** [TypeStrong/ts-loader#603]
We're specifying different tsconfig settings for different builds and I'd like to be able to just generate one and pass it in without writing anything to disk. Is anyone working on anything like this? I'm happy to take a shot at it when I get the time.

**Comment by johnnyreilly** [comment]
Not at present but we welcome contributions - go for it!

**Comment by hdennen** [comment]
Will do 👌

**Comment by Loilo** [comment]
We could extend the scope of the possible new `configFile` option to achieve this (see #607). Naming-wise, it could definitely go in there.

Currently, the option takes file names and path, so strings only. We could passing a JavaScript object interpret as "passing the config directly". What do you think, @hdennen?

**Comment by hdennen** [comment]
@Loilo Honestly I don't think it matters. My knee jerk response is to put options 1 to 1 with what they do but adding more functionality to the configFile option seems fine.
