### ISSUE TITLE
Should "configFileName" be used as filename only or with path?

### ISSUE THREAD

**Issue by mengxy** [TypeStrong/ts-loader#604]
I am using follow configuration:
```
{
  configFileName: path.join(__dirname, 'tsconfig.json'),
}
```

It works as expected in POSIX file systems. But in windows, 'ts-loader' cannot find the config file. Below function in config.js is broken in windows: https://github.com/TypeStrong/ts-loader/blob/master/src/config.ts#L76
```javascript
function findConfigFile(compiler, searchPath, configFileName) {
    while (true) {
        var fileName = path.join(searchPath, configFileName);
        if (compiler.sys.fileExists(fileName)) {
            return fileName;
        }
        var parentPath = path.dirname(searchPath);
        if (parentPath === searchPath) {
            break;
        }
        searchPath = parentPath;
    }
    return undefined;
}
```
 
I just want to discuss that should we use configFileName as simple filename or path. If we use it as filename, then it's fine. But if we can use it as path, we should fixed this bug in windows file system.

**Comment by johnnyreilly** [comment]
I'm not sure as I didn't implement this part. @jbrantly any thoughts?

I'd suggest we could fix this for Windows simply and it would be fine - would you be up for submitting a PR?

**Comment by mengxy** [comment]
Sure, I can follow it up and get it fixed.

Seems that you are using the same findConfigFile function as tsc, but there is some modifications. Maybe that is the issue.

**Comment by johnnyreilly** [comment]
Go for it! Thanks!
