### ISSUE TITLE
Code splitting with import() - webpackchunkname doesn't work

### ISSUE THREAD

**Issue by raghur** [TypeStrong/ts-loader#609]
I'm trying to use this in a vue project and would like to move multiple components to a single chunk. 
Using syntax like this (with typescript 2.4.2)

```
@Component({
    components: {
        "todo-item":  () =>import(/* webpackChunkName = "comps" */ "./todo-item.vue.html" )
    }
})
```

generates 

```
 App4 = __decorate([
        vue_property_decorator_1.Component({
            components: {
                "todo-item": function () { return Promise.resolve().then(function () { return require(/* webpackChunkName = "comps" */ "./todo-item.vue.html"); }); }
            }
        })
    ], App4);
```

which webpack doesn't see as a valid chunkname (webpack seems to support this only if you use `import` statements in ES2015.

Here's my tsconfig.json

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "types": ["webpack-env"],
    "lib": ["es2015", "dom"],
    "removeComments": false
  },
  "exclude": [
      "bin",
      "node_modules"
  ]
}
```

Can you please advise on the right way to go about this? I'd prefer to use the `import()` call as it's succinct and makes the intention clearer but if it doesn't let me target multiple components in the same chunk, it seems a little premature. 

Complete code example here: Complete example codebase here - https://github.com/raghur/vue-testdrive/tree/ts-import

**Comment by johnnyreilly** [comment]
I don't know vue and so can't help there; you might want to take a look at an example of import code splitting in action: https://github.com/TypeStrong/ts-loader/tree/master/test/execution-tests/2.4.1_babel-importCodeSplitting

**Comment by johnnyreilly** [comment]
Also: https://blog.johnnyreilly.com/2017/07/dynamic-import-ive-been-await-ing-you.html

**Comment by johnnyreilly** [comment]
I take it vue accepts Promises?

**Comment by raghur** [comment]
Yes - the promise syntax works but it's verbose.

```
@Component({
    components: {
        "todo-item":  () =>Promise.resolve(require.ensure(["./todo-item.vue.html"], 
                                                            ()=> require("./todo-item.vue.html"), 
                                                            "comps"))    
        }
})
```

**Comment by raghur** [comment]
So I looked at  https://github.com/TypeStrong/ts-loader/tree/master/test/execution-tests/2.4.1_babel-importCodeSplitting

and made similar changes to my project. Code splitting works -but specifying chunk name with /*webpackChunkName="foo"*/ does not work.

**Comment by johnnyreilly** [comment]
Are you definitely using webpack 3?  Our tests still run against webpack 2.

**Comment by raghur** [comment]
I'm using webpack 2.7.0. Note that there is no problem with using `import` for code splitting - just that without being able to specify chunk name, each and every split ends up in a different chunk which is of limited usefulness.

**Comment by johnnyreilly** [comment]
Yeah I think you need to be on webpack 3 to use specifying of chunk names

**Comment by raghur** [comment]
No - the comment syntax works with webpack  > 2.4

**Comment by johnnyreilly** [comment]
Then I'd look at the output js that ts-loader is passing to webpack. Find out what that looks like and see if there's any problem compatibility wise between what that is and what webpack expects

**Comment by raghur** [comment]
I included the generated output in the issue description - is that what you mean? The issue seems to be that import is transpiled to a require call which doesn't support the chunk name in comments. 

Not sure if that is a ts-loader issue or a TS issue.

**Comment by johnnyreilly** [comment]
I'm going to guess you're going to need to change your compile target to es2015 from `"target": "es5"`?

**Comment by raghur** [comment]
Ah - so after bringing in babel-loader and changing tsconfig.json to `"target": "es2015"`, I've got this working. 

Still new to webpack & typescript - thanks for the support

If anyone else needs the same thing, here's my [webpack config](https://github.com/raghur/vue-testdrive/blob/e8f7f0a6c65571e196de712cc173d4212196d74e/webpack.config.js)

**Comment by johnnyreilly** [comment]
Thanks for sharing!

**Comment by WanderWang** [comment]
Update : 

I have got the same problem , and I found I don't need to change ```target``` to ```es2015``` and add a ```babel-loader```  .  


here is my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5", 
    "module": "es2015",
}
```
