### ISSUE TITLE
Project structure issue?

### ISSUE THREAD

**Issue by xogeny** [TypeStrong/ts-loader#61]
I've gone through the tutorial and it does a nice job of introducing `webpack`.  But it is missing several important things.  First, I couldn't find any "example" repo that shows how you had things configured.  This could answer several important questions like: "What does the file structure look like in a project?" or "How are modules organized?".

There really isn't any documentation I could find on what this loader actually does.  Without that, it is hard to really reason about things.  For example, the tutorial implies that things somehow "work"  with the `tsconfig.json` file.

For example, I have a `tsconfig.json` file that looks like this:

```
{
    "compilerOptions": {
		"module": "commonjs",
		"sourceMap": true,
		"noImplicitAny": true,
		"moduleResolution": "node",
		"outDir": "./build",
		"jsx": "react"
    },
    "files": [
      "./src/entry.ts",
      ...
    ]
}
```

If I run `tsc`, everything works perfectly and I get a bunch of generated files in "./build".

Now, if I use **this** `webpack.config.js`:

```
var path = require('path');

module.exports = {
    context: path.join(__dirname, "build"),
    entry: "./entry.js",
    resolve: {
        modulesDirectories: ["build", "node_modules"],
        extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
    },
    output: {
        path: path.join(__dirname, './dist'),
        publicPath: "/",
        filename: "./bundle.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            { test: /\.ts$/, loader: 'ts-loader' },
            { test: /\.tsx$/, loader: 'ts-loader' }
        ]
    }
};
```

...everything works perfectly.  It creates a "dist/bundle.js" which my app loads.  But note, I'm using `build/entry.js` as my entry point, *not* `src/entry.ts`.

The problem here is that the complete pipeline isn't handled in this case since I have to already run `tsc`.  So I was hoping to use `ts-loader` to address this.  Looking at the tutorial, it seems like all I should have to do is change these two lines:

```
    context: path.join(__dirname, "src"),
    entry: "./entry.ts",
```

This definitely triggers `ts-loader` (and the `typescript@1.6.2` compiler), but then it dies with the message:

```
ERROR in ./entry.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Impact.js in /Users/mtiller/Source/impact-search/src
 @ ./entry.ts 2:13-39
```

If I run `webpack-dev-server`, I get a bit more information, it says:

```
./src/entry.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Impact.js in /Users/mtiller/Source/impact-search/src
resolve file
  /Users/mtiller/Source/impact-search/src/lib/Impact.js doesn't exist
  /Users/mtiller/Source/impact-search/src/lib/Impact.js.webpack.js doesn't exist
  /Users/mtiller/Source/impact-search/src/lib/Impact.js.web.js doesn't exist
  /Users/mtiller/Source/impact-search/src/lib/Impact.js.ts doesn't exist
  /Users/mtiller/Source/impact-search/src/lib/Impact.js.tsx doesn't exist
  /Users/mtiller/Source/impact-search/src/lib/Impact.js.js doesn't exist
resolve directory
  /Users/mtiller/Source/impact-search/src/lib/Impact.js doesn't exist (directory default file)
  /Users/mtiller/Source/impact-search/src/lib/Impact.js/package.json doesn't exist (directory description file)
[/Users/mtiller/Source/impact-search/src/lib/Impact.js]
[/Users/mtiller/Source/impact-search/src/lib/Impact.js.webpack.js]
[/Users/mtiller/Source/impact-search/src/lib/Impact.js.web.js]
[/Users/mtiller/Source/impact-search/src/lib/Impact.js.ts]
[/Users/mtiller/Source/impact-search/src/lib/Impact.js.tsx]
[/Users/mtiller/Source/impact-search/src/lib/Impact.js.js]
 @ ./src/entry.ts 2:13-39
```

But I'm scratching my head because, of course, the generated Javascript is in `./build`, not `./src`.  Why is it looking in `src`?  If I point `context` to `src`, the compiler works, but `webpack` fails with the message above.  If, on the other hand, I change `context` to `build`, then the compiler fails completely (but I imagine that perhaps `webpack` might work since that value of `context` works when the files are generated by an independent call to `tsc`).

The tutorial implies that the benefit of `ts-loader` is that it works with the `tsconfig.json` file so you don't have to specify redundant information.  But it doesn't seem like it is paying attention to the `outDir` compiler option in `tsconfig.json`.  It *seems like* it assumes that the compiler drops down the generated javascript right along side the `ts` files.  But I can't really tell since I'm not sure exactly what `ts-loader` is supposed to do here.  I assumed it would automatically run `tsc` behind the scenes and then pick up the generated `js` files to bundle.  But it doesn't seem to be doing that.

Am I misunderstanding `ts-loader`'s purpose?

If not, is there a way to tell it where to find the generated `js` files (since, as a far as I can tell, it isn't using the settings in `tsconfig.json` for this)?

Thanks.

**Comment by blakeembrey** [comment]
I'll let @jbrantly reply still, but just quickly this project is so you can use TypeScript files. If you want to use the generated JavaScript files, you wouldn't need this loader - this gets rid of the `tsc` step for you. To make this work properly, all your imports should be extension-less (so don't import `./lib/Impact.js`, import `./lib/Impact`). Using it with imports is why you end up with it trying to resolve `./lib/Impact.js.ts` and `./lib/Impact.js.js`, among others). Hope that clears up some things :smile:

**Comment by xogeny** [comment]
An additional data point.  I thought that perhaps the issue here was that `ts-loader` required the `.js` files to site side by side with the `.ts` files (something I'd like to avoid).  So I changed my `tsconfig.json` file to emit the `js` in this way (inside the `src` directory in my example above).  But when I run `webpack`, it *still* fails.  But the interesting part is that if I run `tsc` and then `webpack`, it works.  Again, I'm puzzled by exactly what `webpack` is doing here.  If it called `tsc` itself, it should have generated the files at that point.  Why didn't that happen?  It **is** running the compiler because I get this output:

```
ts-loader: Using typescript@1.6.2 and /Users/mtiller/Source/impact-search/tsconfig.json
```

That is exactly the `tsconfig.json` file I want it to use (and the correct version of the compiler).  So why isn't it actually compiling the `js` files?!?  I checked...it isn't emitting any actual Javascript code in my project anywhere.

I'm trying to make this a single step build process (ideally with a `watch` option) so I'm hoping I can get `ts-loader` to emit Javascript as part of that.

Still baffled.  What am I missing here?

P.S. - In response to the previous comments, my imports look like this:

```
import Result = require("./Result");
```

i.e., I'm **not** putting extensions on any of them.

**Comment by xogeny** [comment]
@blakeembrey To be clear, I **want** to get rid of `tsc`.  I don't want to use the generated `js` (I only used that as an example to show that the rest of the configuration seems to be fine).

I'm trying to get `ts-loader` to run `tsc` for me.  The issue is that I cannot debug what is going wrong here.  It **seems** to run `tsc` with the correct configuration file, but nothing is getting generated anywhere.

**Comment by blakeembrey** [comment]
I think I'd need a reference to the project to get more information now, but the loader will not be using the out options from `tsconfig.json`. It is providing a compilation pipeline for webpack, so it'll be compiled however you're using webpack.

**Comment by xogeny** [comment]
If anybody wants to see the issue, the source is at:

https://github.com/impact/search/tree/build_process

This is an open source project so poke around all you want.

**Comment by blakeembrey** [comment]
@xogeny https://github.com/impact/search/blob/build_process/src/entry.ts#L3 is the line I was talking about for your first error. Webpack resolves the same as node, which is by adding each available extension to the file name and checking if it exists - hence your issue with unable to find `./lib/Impact.js.ts`.

**Comment by xogeny** [comment]
Doh!  You're right.  I screwed that up when I tried (to quickly) threw that `entry.ts` file together.  :rage:

I'm not out of the woods just yet (still not quite running).  But at least I've gotten through this (self imposed) hurdle.

**Comment by jbrantly** [comment]
@xogeny Feel free to join the gitter chat for real-time help. I should be available for a little while.

**Comment by xogeny** [comment]
Closing this because it was my own dumb mistake in the end (and, despite @blakeembrey hinting at it, I still failed to see it).

In the end, I got `ts-loader` working perfectly.  I still think it would be useful for new users to have a working example.  Fortunately, anybody interested can now find a working example at:

https://github.com/impact/search/tree/v1.0.3

:smiley:
