### ISSUE TITLE
invalid interface reference with emitDecoratorMetadata/esnext module/transpileOnly

### ISSUE THREAD

**Issue by staeke** [TypeStrong/ts-loader#613]
Taken from https://github.com/Microsoft/TypeScript/issues/18008

Consider these files 

(Angular 4 style code)
```ts
// other-file.ts
export interface MyInterface { a: string }

// my-class.ts
import { Input } from '@angular/core'
import { MyInterface } from './otherFile'

class MyClass {
  @Input() myi: MyInterface;
}
```

```js
// tsconfig.json
{
  "compilerOptions": {
    ...
    "target": "es2017",
    "module": "esnext",
    "emitDecoratorMetadata": true,
    ...
  }
}
```

They work fine with ts-loader when not using transpileOnly. The problem when using transpileOnly is that this code is emitted:

```js
// ...
__decorate([
    Input(),
    __metadata("design:type", typeof (_a = typeof MyInterface !== "undefined" && MyInterface) === "function" && _a || Object)
], MyClass.prototype, "myi", void 0);
// ...
```

This yields warnings in webpack build pipeline as there is no `MyInterface` exported. It's just a compile time construct! 

What ts-loader ought to do is what the typescript compiler does and just output

```js
// ...
__decorate([
    Input(),
    __metadata("design:type", Object)
], MyClass.prototype, "myi", void 0);
```

**Comment by johnnyreilly** [comment]
Thanks but I don't think this an issue with ts-loader - we take the emit from the TypeScript compiler and feed it to webpack (roughly speaking). If there's a problem with the output then that needs to be fixed in the compiler itself.

**Comment by staeke** [comment]
Ok. Thanks. Reopened the first issue
