### ISSUE TITLE
Build hangs on ts-loader

### ISSUE THREAD

**Issue by jonathan82** [TypeStrong/ts-loader#616]
When I run webpack it seems to hang/freeze when running ts-loader.  I looked at my processes and node keeps using more and more memory.  any idea why or how I can diagnose?

`ts-loader: Using typescript@2.5.2 and D:\Projects\ELVIS\ELVIS.Web\tsconfig.json`

**Comment by johnnyreilly** [comment]
You haven't given me much to go on!  Why don't you take one of our example setups and run that on your machine. Then, assuming that works, compare that setup with your own?
