### ISSUE TITLE
Relative paths for "configFile" option are broken

### ISSUE THREAD

**Issue by Loilo** [TypeStrong/ts-loader#617]
I'm afraid I introduced a bug. That's for not being able to properly attach tests for the feature I guess.

Relative paths to `tsconfig.json` are currently resolved relative to the CWD as opposed to the entry file's directory path. I'll attach a PR fixing this ASAP.

**Comment by johnnyreilly** [comment]
Thanks for being so proactive! I'll take a look and release as soon as I can...
