### ISSUE TITLE
Logging to console breaks up webpack progress

### ISSUE THREAD

**Issue by sebastianhaeni** [TypeStrong/ts-loader#623]
When I start the webpack build with `--progress` or the `ProgressPlugin` the `ts-loader` writes to the console and breaks up the progress display in the console.

The options `silent: true` or `logLevel: 'warn'` are not respected.

Example output:

     10% building modules 0/2 modules 2 active ...epos\sample-project\src\vendor.tsts-loader: Using typescript@2.5.2 and D:\repos\sample-project\tsconfig.json         Hash: ed0b3556e568ae74e3fd

The suspected line writing it to the log is probably here:
https://github.com/TypeStrong/ts-loader/blob/3296ef7fe9d3b83103c6df79143e29a9b3e9b8bd/src/config.ts#L33

**Comment by johnnyreilly** [comment]
Are you sure you're supplying the options correctly?

I think the logger should be configured here:

https://github.com/TypeStrong/ts-loader/blob/fbd64be5bdb010e79ef0f702896c5d470f6fc619/src/instances.ts#L39

And if you've passed `silent: true` then you should be fine.  Do you want to fork, add some console log statements to debug and report back?  If there's actually an issue I'd like to resolve it.

**Comment by sebastianhaeni** [comment]
Well this is embarrassing. I did supply the options incorrectly...
So now it works as intented.

Sorry for the circumstances created.

**Comment by johnnyreilly** [comment]
No bother!

**Comment by scarlac** [comment]
A little follow-up: If you do `webpack --profile --json > stats.json` then `ts-loader` will break the output json file because it logs strait out. Shouldn't this debug statement be hid under a `--verbose` or similar?

**Comment by johnnyreilly** [comment]
Arguably yes ... it's pretty much always been this way.  Maybe we should change it.
