### ISSUE TITLE
Webpack code-splitting without babel-loader

### ISSUE THREAD

**Issue by deamme** [TypeStrong/ts-loader#624]
Is code-splitting without babel-loader possible? I wonder if you could write a custom transformer for TypeScript that deals with this problem?

**Comment by johnnyreilly** [comment]
Yes - but only if you use `require` - not the new `import` syntax that landed with TypeScript 2.4. See https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/codeSplitting for an example
