### ISSUE TITLE
`tsconfig.json` by any other name

### ISSUE THREAD

**Issue by icylace** [TypeStrong/ts-loader#635]
I have a project where I use a base `tsconfig.json` located in my project root folder and another `tsconfig.json` in a subfolder that extends it.  When I use the `configFile` option to refer to the latter everything works.  However, if I tried using a different name, say `tsconfig.client.json` it doesn't work.

I think `configFile` should be configurable enough to point to the exact config file I want.

**Comment by johnnyreilly** [comment]
Is this it? https://github.com/TypeStrong/ts-loader/blob/master/README.md#configfile-string-defaulttsconfigjson

**Comment by icylace** [comment]
@johnnyreilly Yes, `configFile` is what I'm talking about.

**Comment by johnnyreilly** [comment]
Does `tsc` support that behaviour?  ts-loader aims to be a drop in replacement for tsc where sensible.

**Comment by theironcook** [comment]
I'm trying to do the same thing.  I have 2 different TypeScript configurations.  One for client and one for server (NodeJS).

rules: [
      {
        test: /\.ts?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
        options: {
          configFile: 'tsconfig.client.json'
        }
      }

Unfortunately I get an error.  It seems like the docs state that we should be able to override the tsconfig file but it doesn't appear to work?  Or I'm setting things up wrong?
