### ISSUE TITLE
ts-loader looking at files not part of the bundle tree

### ISSUE THREAD

**Issue by ebardajiz** [TypeStrong/ts-loader#636]
I'm halfway through writing a test file, meaning that 
* I haven't yet added types for Jest, (or other libraries that may be used in test files)
* The file may or may not be syntactically correct
* Other issues contributing to a file being considered *not finished*

However, when running webpack, the ts-loader is "looking" at these test files. They're not being imported anywhere (i.e., they are not part of the bundle dependency graph), and yet, just because they're `.ts` files, they're being read.

This causes **many** errors to be thrown, errors that are not at all related with files that are part of the bundle. Development is stopped because there's no way of continuing without completing, renaming, or removing these incomplete test files.

I'm not sure if this is a feature, meaning that I'm expected to add `exclude` rules for test files. While this seems reasonable when using `tsc` from the CLI, it does not when using `ts-loader`. 

As far as I understand, loaders should be focusing on the file being provided to them and avoid dealing with other files if not necessary. In this sense, I'd call this a bug.

**Comment by vinaykukke** [comment]
@ebardajiz I am also facing this issue. Thank you for bring it up.

**Comment by johnnyreilly** [comment]
How are these files being pulled in? Ts-loader should only be pulling in things that are imported / required

**Comment by ebardajiz** [comment]
Interesting... because the test files are not being imported or required. I'll try to create a slimmed-down repo that recreates the issue.

**Comment by ebardajiz** [comment]
Here's a repo that behaves as I described above: https://github.com/ebardajiz/greedy-ts-loader

**Comment by johnnyreilly** [comment]
Actually I misinformed you when I said: 

> Ts-loader should only be pulling in things that are imported / required

It's down to how tsc behaves - see the discussion [here](https://github.com/TypeStrong/ts-loader/issues/267).  Closing as duplicate.

Feel free to continue discussion there.
