### ISSUE TITLE
Type error only through ts-loader

### ISSUE THREAD

**Issue by quicksnap** [TypeStrong/ts-loader#637]
I posted this question: https://stackoverflow.com/questions/46289856/why-does-a-heterogeneous-result-of-promise-all-cause-a-ts-error

Seems like this error only occurs through ts-loader, and is not erroneous through `tsc` on its own.

Our project Typescript version is `2.5.2`. This error is produced in `2.4.2`. Does ts-loader gather its type information from a vendored typescript?

**Comment by johnnyreilly** [comment]
No. Do you have a different version of TypeScript in your package.json?

**Comment by quicksnap** [comment]
@johnnyreilly I forked the vanilla example and replicated the issue. Steps are in the readme. Should be pretty fast to replicate. 

https://github.com/quicksnap/loader-issue

**Comment by johnnyreilly** [comment]
Hum. That's weird. I'll try  and take a look when I get a moment. Not sure when that will be which doesn't help you I know. I'm wondering if it's going to be something to do with typescript 2.4 being installed globally for you or something. Not sure

**Comment by quicksnap** [comment]
Could you replicate it? My system doesn't have typescript 2.4 on it anywhere that I can tell. When the yarn.lock also doesn't contain any ts 2.4 resolutions.

I'm at a loss as to what's causing this.

**Comment by quicksnap** [comment]
We have a workaround via type hinting in our actual code, so this isn't causing a terrible amount of trouble. But, if it is due to some kind of typescript version mismatch, that could cause other strange behavior down the line.

Thanks for taking a look whenever you get time. I'll try and dig in further when I get a chance as well.

**Comment by johnnyreilly** [comment]
Yup I can repro this. I have literally no idea what is causing it. If you can look into it I'll give you all the help I can.  I'm afraid I can't look into this myself at present

**Comment by quicksnap** [comment]
Totally understand. It's really baffling..

**Comment by ilikebits** [comment]
I'm seeing weirdness too, where `ts-loader`'s type-checking fails but `tsc`'s type-checking succeeds. For me, the definition of `RequestInit` in `lib.es6.d.ts:6569` is different between the two.

**Comment by johnnyreilly** [comment]
To be clear: ts-loader does not package up Typescript. It uses either the version of Typescript installed in your project, or failing that, if Typescript is globally installed that will be used.

**Comment by ilikebits** [comment]
I futzed around with my global TypeScript installation and got the error warnings to match. My working theory is that my `tsc` was using the global installation which was at a different version than the `typescript` installed locally as a `devDependency`.

**Comment by luke-j** [comment]
Any update on this? TypeScript is not installed anywhere else on my system and it's not particularly obvious to me what could be causing this. Currently on `webpack@4.5.0`, `typescript@2.7.2` & `ts-loader@4.2.0` with node `8.11.0`.

**Comment by johnnyreilly** [comment]
I'm afraid I don't have time to look at this myself right now. I'd hugely value someone else taking a look and reporting back.

**Comment by lednhatkhanh** [comment]
Hello, any updates on this?

**Comment by edbentley** [comment]
In case this helps anyone having this problem: I had a types conflict error because I had the same package installed in different places in a monorepo (even though they were both at the same version). `tsc` didn't give me any type errors but webpack's module resolution was.
