### ISSUE TITLE
tsc and webpack works differently

### ISSUE THREAD

**Issue by bglgwyng** [TypeStrong/ts-loader#640]
```typescript
import * as THREE from 'three';
require('three-obj-loader')(THREE);
THREE.OBJLoader;
```

ts-loader gives an error `export 'OBJLoader' (imported as 'THREE') was not found in 'three'`
But OBJLoader is declared in three's `index.d.ts`. Its implementation is injected lazily by another package `three-obj-loader`.

I compiled the same source code with `tsc`, but it worked well while `webpack` didn't.

I prepare a [repository](https://github.com/bglgwyng/ts-loader-report) to help you reproduce this behavior.
`typescript` 2.5.2  and `ts-loader` 2.3.7 are used.

**Comment by johnnyreilly** [comment]
Hi, I'm a little puzzled by `require('three-obj-loader')(THREE);` - I wouldn't expect to see that in the TypeScript source. I'm afraid I don't know three

**Comment by johnnyreilly** [comment]
I suspect this is a definitions issue or usage; closing unless we can be certain it's ts-loader at fault
