### ISSUE TITLE
Problems transpiling `.js` files both local and within `node_modules`

### ISSUE THREAD

**Issue by corsen2000** [TypeStrong/ts-loader#645]
## Local JS Files

I have a TypeScript project with `allowJs: true` and a basic Webpack configuration:

```js
      {
        test: /\.ts$/,
        use: [{
          loader: 'ts-loader',
          options: {
            configFileName: 'tsconfig.json'
          }
        }],
        exclude: /node_modules/
      }
```

When I build the project using this configuration only the `.ts` files have their ES6 transpiled down to ES5. The `.js` files are not processed.

My first though to fix this was to update the test expression to be `test: /\.(ts|js)$/,`, but this single change results in an error `ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.`.

I can resolve this by adding `include: [projectSrc],` to the webpack configuration, but I don't understand why I have to do this.

## Node Modules

I was not able to figure how to extend what I did above to also transpile `.js` files within `node_modules`. I install some dependencies that only ship ES6 code and I need that to be transpiled. I attempted to solve this by adding a separate `ts-loader` for `.js` files:

```js
      {
        test: /\.js$/,
        include: [projectSrc, projectModules],
        use: [{
          loader: 'ts-loader',
          options: {
            configFileName: 'tsconfig.json',
            transpileOnly: true
          }
        }]
      }
```

In this case I had to add `include: [projectSrc, projectModules]` to work around the empty files error from the first case. It continues to successfully allow me to import `.js` files from the local project, but files in `node_modules` do not work. I get errors that look like `Module build failed: Error: Could not find file: 'SOME_NODE_MODULE_PATH'.`

It seems that my `.js` loader causes the `.ts` loader to no longer be able to find the files.

## Using Babel

Although not complete adding Babel to handle JS files seems to be off to a much better start:

```js
      {
        test: /\.js$/,
        use: [{
          loader: 'babel-loader',
          options: {
            presets: ['es2015']
          }
        }]
      },
```

This more or less works out of the box.

## Conclusion 

I am considering just using Babel since it is working out of the box, but I had originally hoped to not have to add another tool since TypeScript has this transpilation logic built in. Additionally, I prefer TypeScript's `tslib` approach for helpers.

I can put together a reproducer repository if needed, but was first curious if others have tried this and perhaps had an example configuration that worked.

Thank you.

**Comment by johnnyreilly** [comment]
Are you using the `entryFileIsJs` option? At present this needs to be specified; this requirement will be dropped with ts-loader v3

**Comment by johnnyreilly** [comment]
See https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla-jsts

**Comment by corsen2000** [comment]
@johnnyreilly I did try that in various ways. Adding it to my basic configuration causes the build to start throwing errors related to finding declaration files for things like `tslib` and `angularjs`. I'm not sure whether or not the other error would still be present, but I was unable to figure out how to resolve the declaration file problems that the setting introduced.

**Comment by johnnyreilly** [comment]
Perhaps try adding the definition @types packages as Dev dependencies?

**Comment by corsen2000** [comment]
I already have those **@types** added and they are picked up and used correctly. It is only when I make the suggested changes that it starts to fail at finding the types.

* `test: /\.ts$/,` -> `test: /\.(ts|js)?$/,`
* `` -> `entryFileIsJs: true,`

I've tried adding `angular` as a dependency to the test project you listed, but ran could not successfully import and build for some other reason. The error was something like `kind of undefined`. I did not encounter the **@type** issue at least for Angular, but I am unable to determine what is different.

There are a few layers of abstractions to my build that was added to share code between projects. I've tried stripping these layers out to simplify, but continue to run into the same issue.

**Comment by johnnyreilly** [comment]
what does your `tsconfig.json` look like and why do you need to specify it as an option using `configFileName`?

**Comment by corsen2000** [comment]
There is no good reason why it was specified, looks like that is the default.

**tsconfig.json**

```json
{
  "extends": "./node_modules/@namespace/shared-library/tsconfig-base.json"
}
```

**tsconfig-base.json**

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "module": "es2015",
    "allowJs": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "skipLibCheck": true,
    "lib": [
      "dom",
      "es5",
      "es2015.core",
      "es2015.promise",
      "scripthost"
    ]
  }
}

```

**Comment by corsen2000** [comment]
Getting rid of `exclude: /node_modules/` seems to get me past those type errors and to the same error I reproduced from the sample repository of `Module build failed: TypeError: Cannot read property 'kind' of undefined`.

This error seems specific to one of the files in the Angular.js repository and may have [a fix coming](https://github.com/Microsoft/TypeScript/pull/18708).
