### ISSUE TITLE
Please, don't clear depencies

### ISSUE THREAD

**Issue by trikadin** [TypeStrong/ts-loader#650]
I use my own custom loader that runs before `ts-loader` and adds dependencies for some `.ts` files. `ts-loader` [clears dependencies](https://github.com/TypeStrong/ts-loader/blob/a89212d9ce6f83a50f58771582e68258a491057c/src/index.ts#L204), so webpack doesn't rebuild project when dependencies from my loader are updated.

**Comment by johnnyreilly** [comment]
I'm afraid I'm going to need some more information....

**Comment by trikadin** [comment]
@johnnyreilly, what kind of information do you need?

**Comment by trikadin** [comment]
Ok, I'll try. But why do you do it? Why do you clean dependencies?

**Comment by johnnyreilly** [comment]
So if they change they can be reconstructed - old versions aren't cached.

**Comment by johnnyreilly** [comment]
If using `transpileOnly` you might also want to use the fork-ts-checker-webpack-plugin as well

**Comment by trikadin** [comment]
Afaik, webpack doesn't cache dependencies, so you don't have to clear them manually. You can check this with `this.getDependencies()`.

**Comment by trikadin** [comment]
> If using transpileOnly you might also want to use the fork-ts-checker-webpack-plugin as well
Already read about it, ty)

**Comment by johnnyreilly** [comment]
Closing as no further action seems to be required
