### ISSUE TITLE
how can i use ts-loader and webpack3 dynamic imports to implement code-splitting

### ISSUE THREAD

**Issue by jackie19** [TypeStrong/ts-loader#652]
code: 
```
class Home{

    append() {

        this.getComponent().then((component) => {
            document.body.appendChild(component);
        })
    }

    getComponent() {

        return import(/* webpackChunkName: "lodash" */ 'lodash/join').then(join => {

            let element = document.createElement('div');
            element.innerHTML = join(['Hello', 'webpack'], ' ');
            return element;
        })
    }
}

var myHome = new Home()

myHome.append()
```

webpack code-splitting guides:  [https://webpack.js.org/guides/code-splitting/](https://webpack.js.org/guides/code-splitting/)

**Comment by johnnyreilly** [comment]
I advise taking a look at one of our execution tests that uses this approach: https://github.com/TypeStrong/ts-loader/tree/master/test/execution-tests/2.4.1_babel-importCodeSplitting

**Comment by landru29** [comment]
@johnnyreilly: the question was about using webpackChunkName in a typescriypt project

**Comment by johnnyreilly** [comment]
Oh well - that's simple.  It should just work.  Just make sure your `tsconfig.json` doesn't trim comments.

**Comment by Plmeks** [comment]
module: "esnext" and removeComments: false at tsconfig.json
