### ISSUE TITLE
3.0.0 files are missing from npm

### ISSUE THREAD

**Issue by mattlewis92** [TypeStrong/ts-loader#654]
Hi there! It looks like only `dist/index.js` is published to npm: https://unpkg.com/ts-loader@3.0.0/dist/, however if you look in the source you'll see it references other files which should be in the dist folder and aren't: https://unpkg.com/ts-loader@3.0.0/dist/index.js

**Comment by johnnyreilly** [comment]
Whoops!

**Comment by johnnyreilly** [comment]
First time using yarn to publish.  Maybe npm is safer for that...

**Comment by johnnyreilly** [comment]
Okay - now published ts-loader 3.0.0 as ts-loader 3.0.2.  No change but version.  Thanks for reporting!

**Comment by mattlewis92** [comment]
3.0.2 is working great, thanks a bunch for the quick turnaround! 😃

**Comment by johnnyreilly** [comment]
No bother - having the unpkg link was super helpful. You're credited on the 3.0 release page now :wink: https://github.com/TypeStrong/ts-loader/releases/tag/v3.0.0
