### ISSUE TITLE
@types not working with 3.0.2

### ISSUE THREAD

**Issue by ldrick** [TypeStrong/ts-loader#657]
I encountered a couple of Errors saying things like:
`ERROR in ./[...]/SimpleDateFormat.ts
[tsl] ERROR in /home/[...]/SimpleDateFormat.ts(1,52)
      TS7016: Could not find a declaration file for module 'date-fns'. '/home/[...]/node_modules/date-fns/esm/index.js' implicitly has an 'any' type.
  Try `npm install @types/date-fns` if it exists or add a new declaration (.d.ts) file containing `declare module 'date-fns';`
`
These @types are all installed and tsc is working smooth with them. Until today I used ts-loader@2.3.7 and it worked. If you need further information, please come back to me, thanks.

**Comment by johnnyreilly** [comment]
@ldrick I'm guessing this is going to be the same as https://github.com/TypeStrong/ts-loader/issues/655.  Essentially I think you can fix this by either supplying ts-loader with the option `entryFileCannotBeJs: true` **OR** setting `allowJs: false` in your `tsconfig.json`. 

I believe there is a bug in ts-loader around the `allowJs` functionality which is worked around with this flag.  Can I ask a favour?  Assuming that my suggestion does resolve your issue would you be able to supply me with a minimal repro repo that illustrates this issue?  I'd love to fix this properly in ts-loader so the workaround isn't necessary.  To do that I need a way to reliably reproduce the issue.  You can help!

**Comment by ldrick** [comment]
@johnnyreilly Thanks, allowJs is truthy needed in my project. But `entryFileCannotBeJs: true` works.
I will come back within next 2 hours having a reproducable repo. (I think of running JQuery with @types/JQuery)

**Comment by johnnyreilly** [comment]
Thanks @ldrick - I appreciate it!

**Comment by ldrick** [comment]
@johnnyreilly I got through some strange things, but could reproduce exact my error like this:
[ts-loader-test](https://github.com/ldrick/ts-loader-test)

I know types are not installed for date-fns, but they are not required.
It comes down to tsconfig --> moduleResolution: "node" I believe. Because activating this one in this new project, tsl failed.

**Comment by johnnyreilly** [comment]
Thanks @ldrick - I'll take a look!

**Comment by johnnyreilly** [comment]
Hopefully this will be fixed with https://github.com/TypeStrong/ts-loader/pull/658 (testing now)

**Comment by johnnyreilly** [comment]
Fix released with 3.0.3

**Comment by dawidzq** [comment]
Hey, 

I'm trying to download 3.0.3 via npm and I'm getting "No matching version found for ts-loader@3.0.3". Has it officially been published yet?

Thank you!

**Comment by johnnyreilly** [comment]
Yup - shipped. Other people have reported it working so downloading must be happening...

**Comment by johnnyreilly** [comment]
See https://www.npmjs.com/package/ts-loader

**Comment by dawidzq** [comment]
It appears to be a caching issue on my end.

**Comment by johnnyreilly** [comment]
Well cache invalidation is famously hard :wink:

**Comment by ldrick** [comment]
Just want to confirm, that everything works smooth on my side since 3.0.3 and I removed the `entryFileCannotBeJs: true` again.
Thanks @johnnyreilly

**Comment by johnnyreilly** [comment]
Brilliant!
