### ISSUE TITLE
Errors are sometimes not fully logged

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-loader#659]
Sometimes webpack will fail with an error but ts-loader will not log what the error is. See https://github.com/TypeStrong/ts-loader/issues/647#issuecomment-333317050.

**Comment by OliverJAsh** [comment]
I am getting this again. Do we have any ideas why the errors might not be logging?

**Comment by johnnyreilly** [comment]
Sorry - I've been tremendously busy and haven't had chance to think about it. If someone else could take a look at it that would be awesome 💓
