### ISSUE TITLE
Simple webpack configuration means that extra directories are written to my project root

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/ts-loader#665]
hey all, this is working for me, but there's a less than savory side-effect in my project

In my `node_modules` directory, I have a couple of symlinked projects (using npm link).

After using the following configuration, several of the symlinked projects are "copied" to my project's root directory, and _they all contain just the .d.ts files_.

Here is the configuration:

```js

const path = require('path');

module.exports = {

  entry: ['babel-polyfill', './lib/index.ts'],

  output: {
    path: path.resolve(__dirname + '/dist'),
    filename: 'suman.js'
  },

  module: {

    rules: [
      // all files with a `.ts` extension will be handled by `ts-loader`
      {
        test: /\.ts$/,
        loader: 'ts-loader'
      },
      {
        test: /^\.d.ts$/,
        loader: 'ignore-loader'
      },
      {
        test: new RegExp('^' + path.resolve(__dirname + '/lib/cli-commands/') + '.*'),
        loader: 'ignore-loader'
      },
      {
        test: new RegExp('^' + path.resolve(__dirname + '/suman.conf.js')),
        loader: 'ignore-loader'
      }
    ],

  },

  resolve: {
    alias: {
      fs: require.resolve('suman-browser-polyfills/modules/fs'),
      process: require.resolve('suman-browser-polyfills/modules/process'),
    },
    extensions: ['.ts', '.js']
  },
};

```

I create the build using `webpack` or `webpack -w`

And after running webpack (with the above config), I get these extra directories in my project:

<img width="615" alt="screenshot 2017-10-24 11 58 50" src="https://user-images.githubusercontent.com/11139560/31962583-cf2dab8a-b8b2-11e7-83b4-7bc909a62674.png">

I am 100% certain that ts-loader is responsible for creating those directories, and that can't be the right thing to do...! Those directories do not get written when I remove ts-loader from my webpack config.

These directories are symlinked to my node_modules directory here:

![screenshot 2017-10-23 13 28 37](https://user-images.githubusercontent.com/11139560/31911624-21cae10e-b7f6-11e7-9a84-b761d1e7b5d4.png)

anybody know what might be going on? never seen this before until I used `ts-loader`.

thanks

**Comment by ORESoftware** [comment]
@johnnyreilly any idea what this might be about? ever seen it before? It looks like ts-loader is polluting my project with directories that should only belong in node_modules, it's very strange.

**Comment by johnnyreilly** [comment]
what does your `tsconfig.json` look like?  TBH it's hard to help without seeing a minimal reproduction repo.

**Comment by ORESoftware** [comment]
you can just clone this:

git clone -b  feature_alexamil_1508459456817 git@github.com:sumanjs/suman.git

and then run

`$ webpack`

the extra dirs will be written out..make sure to take a look at the root project directories before running webpack.

The tsconfig.json file is nothing crazy:

```json
{
  "compilerOptions": {
    "declaration": true,
    "baseUrl": ".",
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/suman-types/dts"
    ],
    "allowJs": false,
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom",
      "es5",
      "es2015.promise"
    ]
  },
  "allowJs": true,
  "compileOnSave": false,
  "exclude": [
    "test",
    "node_modules"
  ]
}
```

**Comment by johnnyreilly** [comment]
I'm not near a computer right now but I'd lay money it's related to `"declaration": true`

**Comment by ORESoftware** [comment]
Yeah, maybe because those generated directories only include .d.ts files

...but what if I told you that if I run `tsc` this doesn't happen? :)

**Comment by johnnyreilly** [comment]
So what happens with tsc? Where does it place generated files?  Or does it generate a different set of files?

**Comment by ORESoftware** [comment]
tsc doesn't generate .d.ts files for projects in node_modules because node_modules is ignored

but for some reason ts-loader is not ignoring the projects in node_modules and is generated `.d.ts` files for them. And not only that, but it's writing those projects in node_modules to my project root.  One hint is that these projects are all symlinked to node_modules, not sure if that has anything to do with it.

**Comment by KnisterPeter** [comment]
@ORESoftware This may be caused by webpack. `tsc` creates just files for your source and `node_modules` are seen as third party dependencies. But `webpack` has a different look at it, since it bundles everything and the output includes your third-party dependencies.
To use your bundle as input to another compile process (for example if you bundle a library) you will need your third-party declaration files as well, otherwise you will into compiler issues.
