### ISSUE TITLE
Remove custom `lib` filename resolve

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-loader#67]
https://github.com/TypeStrong/ts-loader/blob/master/index.ts#L221-L227

Should be able to replace with `ts.getDefaultLibFilePath(compilerOptions)`.

Reference: https://github.com/blakeembrey/typescript-simple-loader/blob/master/src/typescript-simple-loader.ts#L189

**Comment by jbrantly** [comment]
Fixed in v0.8.0.
