### ISSUE TITLE
Weird issue when updating from 2.3.7 -> 3.0.5

### ISSUE THREAD

**Issue by stormpat** [TypeStrong/ts-loader#672]
When updating ts-loader (from 2.3.7 to 3.0.5) i start getting errors on console.log statements. 

### Expected Behaviour

No errors should be given.

### Actual Behaviour

    ERROR in ./....File.ts
    [tsl] ERROR in ./...File.ts(52,5)
    TS2554: Expected 0-1 arguments, but got 2.

In the code i have the following code, that emits a error:

    console.log('Some message', someVar);

EDIT

The error is not present when using ```transpileOnly: true``` as a loader param

**Comment by johnnyreilly** [comment]
Could you provide a minimal repro repo please?

**Comment by stormpat** [comment]
I tried to make a minimal repo, but have not yet succeed to pinpoint the failure point. Ill continue when i have some more time.

Interestingly, the error also disappears  when i do

     const console = window.console

**Comment by johnnyreilly** [comment]
Weird!

**Comment by johnnyreilly** [comment]
Also, do you want to check which version of chalk you have installed? Could be worth pinning to 2.2 to check if that fixes the issue?

**Comment by stormpat** [comment]
This seems to be fixed. (using latest 3.2.0)
