### ISSUE TITLE
Const enum inlining does not work in happyPackMode

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [TypeStrong/ts-loader#677]
Enums declared as `const` are not inlined when in `happyPackMode`. Example code:

```js
const enum SomeEnum {
  FIRST = 'first',
  SECOND = 'second'
}

const o = {
  first: SomeEnum.FIRST
};

console.log(o);
```

### Expected Behaviour
```js
var o = {
    first: "first" /* FIRST */
};
console.log(o);
```

### Actual Behaviour
```js
var SomeEnum;
(function (SomeEnum) {
    SomeEnum["FIRST"] = "first";
    SomeEnum["SECOND"] = "second";
})(SomeEnum || (SomeEnum = {}));
var o = {
    first: SomeEnum.FIRST
};
console.log(o);
```

**Comment by johnnyreilly** [comment]
I believe this is down to the `transpileModule` behaviour in tsc.  Could be worth checking with the TypeScript project itself; `happyPackMode` runs in using the `transpileModule` behaviour.
