### ISSUE TITLE
Replace custom error resolving with program usage

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-loader#68]
1. https://github.com/TypeStrong/ts-loader/blob/master/index.ts#L398-L422
2. https://github.com/blakeembrey/typescript-simple-loader/blob/master/src/typescript-simple-loader.ts#L218-L232

**Comment by basarat** [comment]
Nice. I use something similar to what `ts-loader` does on `atom-typescript` build and it has issues around `noEmitOnError` and `out`. For my ref : https://github.com/TypeStrong/atom-typescript/issues/603

**Comment by jbrantly** [comment]
This might also fix the error reporting part of #71. Should loop back around when we implement this to see if that's the case. If not should maybe create a new issue.
