### ISSUE TITLE
Entry point is never hit

### ISSUE THREAD

**Issue by dougajmcdonald** [TypeStrong/ts-loader#680]
I have a fairly straightforward `webpack.config.js` and I'm using `ts-loader` which appears to build everything correctly until I try to execute any code!

In my `app.ts` as the entry point I build to a `bundle.js` and then reference the `.js` file in my HTML. I've got some setup bits such as button event handlers in the `app.ts` file and have put in some `window.console.logs` in the file, but none are ever hit.

My config looks like this:

```
module.exports = {
  devtool: 'inline-source-map',
  entry: "./corewar/app.ts",
  output: {
      path: __dirname,
      filename: "bundle.js"
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
  module: {
      rules: [
        // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
        { test: /\.tsx?$/, loader: 'ts-loader' }
      ]
  }
};
```

In my `app.ts` it's basically a long list of imports, but I have some raw code in there like so:

```
// lots of imports

window.console.log('loaded');

document.getElementById('someButtonId').addEventListener('click', () => {
  window.console.log('clicked');
})

export class Start {
  constructor() {
   window.console.log('start ctor');
  }
}

new Start();

```

but none of these log anything.

Am I doing something wrong with how I hope to start things up? Any thoughts greatly appreciated

**Comment by johnnyreilly** [comment]
If I was you I'd take a look at one of the simple examples. This is a good candidate: https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla

**Comment by dougajmcdonald** [comment]
@johnnyreilly it was a stupid reference error on my part (referencing webpack output) thanks for the pointers though
