### ISSUE TITLE
Automatically "external"-ize ambient modules?

### ISSUE THREAD

**Issue by martijnthe** [TypeStrong/ts-loader#682]
I've got a `.d.ts` containing ambient module declarations, i.e.
```
declare module 'my_mod' {
   ...
}
```

If a `.ts` file contains for example...
```
import * as myMod from 'my_mod';
```
... webpack should not try to resolve the `my_mod` module, but just leave the `require('my_mod')` (or whatever module loading code got generated by the TS compiler).

I know you can solve this by adding `externals` to the webpack config, but I'm looking for a more automated solution.

It would be nice it it was possible to tell `ts-loader` which `.d.ts` files that contain ambient module declarations that should be to "auto-externalized".

Any advice?

Tangentially related webpack util: https://www.npmjs.com/package/webpack-node-externals

**Comment by christiantinauer** [comment]
I think you can use the files-section of the tsconfig.json file. Typescript will respect the .d.ts file for transpilation but it will not be bundled.

**Comment by martijnthe** [comment]
> Typescript will respect the .d.ts file for transpilation but it will not be bundled.

@christiantinauer did you mean to write *Typescript* or *ts-loader* here?

If the former: I'm not sure if I understand. Typescript doesn't bundle anything?

If the latter: I've added the package in that contains the `.d.ts` files to the `"types"` section in the `tsconfig.json` file:

```tsconfig.json
{
    "compilerOptions": {
        "types": [
            "my_mod_npm_package_name"
        ]
    },
    "include": [
        "**/*.ts"
    ]
}
```

I'd rather not use `"files"` for that because then I have to specify the `node_modules/my_mod_npm_package_name/...` path there, which is cumbersome because the package could be hoisted to a parent folder (`../node_modules/`), etc. etc.

I guess if `ts-loader` is smart about `.d.ts` files being part of the `"files"` section, I guess the "bug" is that it should also be smart about the `.d.ts` files that are included through the `"types"` section as well?

**Comment by martijnthe** [comment]
I just tried adding the path to the `.d.ts` file "manually" to `"files"`.

It doesn't seem to work:
```
ERROR in ./index.ts
Module not found: Error: Can't resolve 'my_mod' in '/Users/mthe/test'
 @ ./index.ts 4:14-30
```

`index.ts`:
```index.ts
import * as myMod from 'my_mod';

// etc
```

Only if I manually add this to the `webpack.config.js`, it works as expected:
```
  externals: {
    'my_mod': 'require("my_mod")',
  }
```

**Comment by martijnthe** [comment]
Ah, I was just digging through the code and test cases and noticed this `"externals"` config:
https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/externals/webpack.config.js#L10

I also noticed the [expected output](https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/externals/expectedOutput-2.6/bundle.js#L81) is kind of broken:

```
...
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

exports.__esModule = true;
var hello = __webpack_require__(1);
var msg = hello.sayHello('World');


/***/ }),
/* 1 */
/***/ (function(module, exports) {

module.exports = hello; 

/***/ })
...
```

I think `module.exports = hello;` is wrong. The [hello.d.ts](https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/externals/hello.d.ts) file is promising there will be a module `"hello"`, not a global variable `hello`.

**Comment by johnnyreilly** [comment]
I don't think behaviour has changed.  If you compare the output from [TypeScript 1.6](https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/externals/expectedOutput-1.6/bundle.js) to [TypeScript 2.6](https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/externals/expectedOutput-2.6/bundle.js) it's essentially the same.

If it's wrong now then it's always been wrong I guess...

**Comment by martijnthe** [comment]
> If it's wrong now then it's always been wrong - which seems unlikely

@johnnyreilly I guess it's not wrong if the `bundle.js` gets run in an environment where the global `hello` happens to point to the `"hello"` module (such as an HTML page where another script that is loaded first, takes care of setting up the global `hello`).

In my use case, I would like to be able to write against a `.d.ts` that specs built-in/ambient modules, without having to worry whether webpack's `"externals"` configuration is set up correctly and that it is in sync with whatever modules the `.d.ts` declares.

I think this can be done through a webpack plugin, but perhaps not through a loader? If not, `ts-loader` is probably not right the place try to add this functionality?

**Comment by johnnyreilly** [comment]
Can this be accomplished with the webpack ignore plugin?

**Comment by martijnthe** [comment]
@johnnyreilly it's usually accomplished using either the `"externals"` config or using the `ExternalsPlugin`. Here's an example how it's done by webpack itself for the Electron built-in modules: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L128

**Comment by johnnyreilly** [comment]
Cool - I'll close this issue as it looks like no action is required for ts-loader
