### ISSUE TITLE
Decorator TypeHint resolution seems to be broken

### ISSUE THREAD

**Issue by gitnik** [TypeStrong/ts-loader#686]
This might be the wrong place to ask, but even after looking at the code more thoroughly, I couldn't pin it down to the exact repo/project. Anyway here goes the bug description: 

When resolving the typehint for a decorator (in my case with angular)
```typescript
import { TableHeaderConfig } from 'shared/interfaces/table';

class Table {
    @Input() config: TableHeaderConfig;
}
```

the file resolution does not seem to work. The same file is found for other parts of the application where the type definition is not used on a decorator. I initially expected this to be an issue with my `tsconfig`, but running `tsc --traceResolution` and examining the output shows that typescript itself had no issue finding the correct file:
`File '<omitted>/shared/interfaces/table.d.ts' exist - use it as a name resolution result`, while for webpack I get the following error:
```
Module not found: Error: Can't resolve 'shared/interfaces/table' in '<omitted>/src/recruiter/app/util/table'
resolve 'shared/interfaces/table' in '<omitted>/src/recruiter/app/util/table'
```

The full error reads as follows:
```
ERROR in ./src/recruiter/app/util/table/table-column.component.ts
Module not found: Error: Can't resolve 'shared/interfaces/table' in '<omitted>/src/recruiter/app/util/table'
resolve 'shared/interfaces/table' in '<omitted>/src/recruiter/app/util/table'
  Parsed request is a module
  using description file: <omitted>/package.json (relative path: ./src/recruiter/app/util/table)
    aliased with mapping 'shared': '<omitted>/src/shared' to '<omitted>/src/shared/interfaces/table'
      using description file: <omitted>/package.json (relative path: ./src/recruiter/app/util/table)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: <omitted>/package.json (relative path: ./src/recruiter/app/util/table)
        using description file: <omitted>/package.json (relative path: ./src/shared/interfaces/table)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            <omitted>/src/shared/interfaces/table doesn't exist
          .ts
            Field 'browser' doesn't contain a valid alias configuration
            <omitted>/src/shared/interfaces/table.ts doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            <omitted>/src/shared/interfaces/table.js doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            <omitted>/src/shared/interfaces/table.json doesn't exist
          .css
            Field 'browser' doesn't contain a valid alias configuration
            <omitted>/src/shared/interfaces/table.css doesn't exist
          .scss
            Field 'browser' doesn't contain a valid alias configuration
            <omitted>/src/shared/interfaces/table.scss doesn't exist
          as directory
            <omitted>/src/shared/interfaces/table doesn't exist
[<omitted>/src/shared/interfaces/table]
[<omitted>/src/shared/interfaces/table.ts]
[<omitted>/src/shared/interfaces/table.js]
[<omitted>/src/shared/interfaces/table.json]
[<omitted>/src/shared/interfaces/table.css]
[<omitted>/src/shared/interfaces/table.scss]
[<omitted>/src/shared/interfaces/table]
```

I read through these error messages (e.g. `Field 'browser' doesn't contain a valid alias configuration`) but none of the answers on stackoverflow or github could solve this. And the fact that the file resolution works fine when not used on a decorator also makes me think that the webpack config cant be at fault

### Steps to Reproduce the Problem
I'm running the following packages:
```
"typescript": "^2.6.1",
"webpack": "^3.9.1"
"ts-loader": "^3.2.0",
```
Afterwards all that seems to be needed (implying your webpack config is properly set up):
TypeHint a decorator.

### Location of a Minimal Repository that Demonstrates the Issue.
I'll gladly set up a repo if needed. Is there a repo for bug reports I can fork?

**Comment by johnnyreilly** [comment]
You could try picking one of the examples and using that as a basis - the simpler the better really

**Comment by gitnik** [comment]
Alright so as I was creating a minimal repo I found out the actual cause of this bug: https://github.com/Microsoft/TypeScript/issues/18008

Doesn't really help me immediately but at least I now know the actual culprit :)
