### ISSUE TITLE
Fail to specify configFile which contains "extends" option.

### ISSUE THREAD

**Issue by zheeeng** [TypeStrong/ts-loader#689]
If the configFile is pasted from standard `tsconfig.json`, it works fine. Once the configFile using "extends" option to reuse other tsconfig files. Everything seems weird and has no solutions. 
```ts
// config/webpack.config.ts segement:

module: {
    rules: [{
      test: /\.ts$/,
      loader: require.resolve('ts-loader'),
      options: {
        configFile: '../tsconfig.json',
      },
    }],
},
```
Run webpack, I get
`Error: EACCES: permission denied, mkdir '/Users/users'` 
seems ts-loader will try to execute `mkdir`:

**Comment by gingi** [comment]
Exact same issue.

**Comment by el-fuego** [comment]
+1. This issue is related to for Mac users only: Linux is OK

**Comment by nktssh** [comment]
Have the same issue.
ts-loader@2.3.7
typescript@2.6.2
node v8.9.0
npm v5.5.1

**Comment by johnnyreilly** [comment]
If there's any Mac users out there that could take a look at this I'd greatly appreciate it. I only run Windows and Linux..

**Comment by johnnyreilly** [comment]
(hence I can't reproduce the issue)

**Comment by nktssh** [comment]
Any updates on this?
