### ISSUE TITLE
Anyone know how to use ts-loader while defining a custom @jsx pragma/compile function?

### ISSUE THREAD

**Issue by rw3iss** [TypeStrong/ts-loader#690]
I'm wondering if it's possible to parse jsx and print out custom directives (ie. 'h(...)') versus the standard React.createElement, etc. This is to support a custom virtualDom compiler or do customized rendering/tree diffing.

**Comment by jbrantly** [comment]
You should be able to use TypeScript's `preserve` option to preserve the original JSX and then chain a loader to do the custom JSX compilation.

https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by rw3iss** [comment]
Okay, will give it a shot, thanks. Haven't played with custom loaders but will try to implement my own.

**Comment by johnnyreilly** [comment]
Thanks so much for advising @jbrantly!
