### ISSUE TITLE
SourceMap - Can't debug variables declared on imports

### ISSUE THREAD

**Issue by MartinsThiago** [TypeStrong/ts-loader#696]
### Expected Behaviour
Adding these configurations should allow us to debug imported vars 
- `"sourceMap": true` on tsconfig.json 
- `"devtool": "source-map""` on webpack.config.js

### Actual Behaviour
It's possible to debug variables that I defined perfectly, but vars from imports nope
See how the scope looks like while debugging

![image](https://user-images.githubusercontent.com/8419829/34007338-8df08850-e0e8-11e7-86b0-c372247ec8b0.png)

Variables I imported are shown with **_WEBPACK_IMPORTED_MODULE** prefix... so despite of successfully logging such variables, it's not possible to do the same on console in debug time
```
//Doesn't work if I run on console
console.log(AntiShadowElement);
console.log(connectToRedux);
console.log(appState);
```

### Steps to Reproduce the Problem
Run these commands
```shell
git clone git@github.com:MartinsThiago/polymer-3-redux.git &&
cd polymer-3-redux &&
npm install && npm start
```

Then start debugging on chrome

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/MartinsThiago/polymer-3-redux

**Comment by KnisterPeter** [comment]
@MartinsThiago This is caused by webpack emulating es-modules. Export/Import in ES6+ has to export the bindings and not the values.
You should file this as an issue in the webpack repo.

**Comment by MartinsThiago** [comment]
Understood, I am going to file this issue there
