### ISSUE TITLE
Allow suppressing diagnostics for certain files

### ISSUE THREAD

**Issue by freeman** [TypeStrong/ts-loader#700]
### Expected Behaviour

I'd like to be able to ignore typescript errors/diagnostics for certain files (or only reporting errors for certain files).

This feature is available in [at-loader](https://github.com/s-panferov/awesome-typescript-loader#reportfiles-string) as `reportFiles`. This can be useful when some type definitions contain errors that do not otherwise break the application. In this case it can be useful to squelch them while waiting for upstream to fix the issue.

### Actual Behaviour

ts-loader reports all errors and we can only filter out some specific diagnostics but this is global.

**Comment by johnnyreilly** [comment]
I'd be happy to add that functionality - would you like to submit a PR?

**Comment by freeman** [comment]
I'd be happy to have a go at it.

**Comment by johnnyreilly** [comment]
Go for it! I suspect it's fairly simple to implement; don't worry about failing tests. Feel free to PR when you've got something up and running and we can iterate together on that as we need to.
