### ISSUE TITLE
Status of visualStudioErrorFormat option

### ISSUE THREAD

**Issue by corydeppen** [TypeStrong/ts-loader#703]
Would someone be able to confirm whether `visualStudioErrorFormat` is a valid ts-loader option or not? I see it's not in the list of [`LoaderOptions`](https://github.com/TypeStrong/ts-loader/blob/master/src/interfaces.ts#L262-L282) so I'm assuming it's no longer supported.

**Comment by johnnyreilly** [comment]
Hi @corydeppen,

This was dropped as an option as part of the v3 release:

> add support for a custom formatter for output - drop visual studio format (this can be added back if there's clamour for it and people can supply their own formatters in the interim) 

https://github.com/TypeStrong/ts-loader/blob/master/CHANGELOG.md#v300

There's now a more powerful `errorFormatters` option which allows anyone to provide their own formatting choice. See here for details: https://github.com/TypeStrong/ts-loader/blob/master/README.md#errorformatter-message-errorinfo-colors-boolean--string-defaultundefined

If you'd like this to have a Visual Studio formatter "in the box" then I'm open to having that still. Let me know if so and we could talk through a potential implementation

**Comment by demurgos** [comment]
Hi,
I also encountered this issue. Could it be possible to keep the visual studio formatter in this package? It allows to get clickable links to the corresponding file in WebStorm.

**Comment by johnnyreilly** [comment]
Sure - would you like to come up with a formatter that produces the visual studio output? Once we've got that we can look at getting it integrated as an "in the box" formatter. In the short term we can share it here so other people can make use of it.
