### ISSUE TITLE
How to compiled for Chrome (i.e. leave classes and async functions alone)?

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-loader#705]
How can we compile TypeScript code so that the output is minimal for a modern browser (f.e. classes and async functions are left as-is so we have best performance rather than using heavier transpiled ES5)?

**Comment by KnisterPeter** [comment]
@trusktr TypeScript is only possible to compile to targets on a js-level. Have a look at your `tsconfig.json` and the `target` property.
There is fine granular configuration of feature transpilation like with babel.

As well this issue should belong to typescript, not the ts-loader.
