### ISSUE TITLE
Unable to compile const enum in .d.ts file.

### ISSUE THREAD

**Issue by zheeeng** [TypeStrong/ts-loader#706]
I'm using .d.ts to store some enum interfaces. But it seems that ts-loader doesn't include these .d.ts files in compiling.

A work situation:

```ts
// foo.ts
const enum Direction {
    Up,
    Down,
    Left,
    Right,
}

const d: Direction = Direction.Up
```
output:
```js
var d = 0 /* Up */;
```

For reusing Direction as value and interface, I separated declaration and its applying. Unfortunately, the compiling failed.

```ts
// foo.d.ts
declare const enum Direction {
    Up,
    Down,
    Left,
    Right,
}
// foo.ts
const d: Direction = Direction.Up
```
output:
```js
var d = Direction.Up
```
This way report `ReferenceError: Direction is not defined` in webpack compliing result.

**Comment by KnisterPeter** [comment]
Couldn't you just `export` your const enum from 'foo.ts'?
Otherwise you may use a tripple-slash-directive to reference your 'foo.d.ts' which will instruct the compiler to include your file.

**Comment by zheeeng** [comment]
`const enum` is handy for number semantic. `declare` is handy for using in global. The more important, typescript allow us to use them in that way.
export means we have to import it everywhere. And the behaviour difference between native typescript compiled and the transpiled brings a little inconvenience.

**Comment by KnisterPeter** [comment]
@zheeeng Fair engouth. Does it work with plain `tsc`? I doubt this is a ts-loader issue, since ts-loader just calls `tsc` from `webpack` (but I'm not sure, could be some side-effect).

**Comment by KnisterPeter** [comment]
I think you need to add a tripple-slash somewhere in your source like this:
```js
/// <reference path="./foo.d.ts" />
```

This is a way to tell the `tsc` to include your declaration in your compilation.
As far as I know you can either use import/export or tripple-slash references to include files in your compiler context.

**Comment by zheeeng** [comment]
@KnisterPeter tsc works fine. I think it is something caused by webpack only consider files things are imported. Declaration files don't need to be imported.
Certainly, webpack won't take this issue. Maybe some improvements on ts-loader will help.

**Comment by KnisterPeter** [comment]
@zheeeng  Please add a minimal repository to test this issue. It may help to understand it a bit more.

**Comment by zheeeng** [comment]
Ok, I try build one.

**Comment by zheeeng** [comment]
@KnisterPeter very sorry for my mistakes. I just then build a minimal project for test, if the declaration file is included by 'include' option `tsconfig.json`. It indeed is transpiled right.
The issue was created when I was developing project with complicated configs, VS Code didn't report error while the `const enum` declaration is out of the `include` range that be defined by `tsconfig.json`.

**Comment by KnisterPeter** [comment]
Your welcome. I'm glad to help.

**Comment by jestarray** [comment]
Having this issue currently with the Vue CLI that uses webpack and ts-loader under the scenes. 

https://github.com/vuejs/vue-cli/issues/3376

tried flipping transpileOnly on and off, and happymodepack on and off, no luck.

**Comment by navneet-g** [comment]
Is there a way to generate a build error when we use enum instead of const enum in d.ts files?
