### ISSUE TITLE
Error in pristine project created by create-react-app

### ISSUE THREAD

**Issue by marton78** [TypeStrong/ts-loader#708]
If ts-loader is updated to the newest version in a project created with `create-react-app --scripts-version=react-scripts-ts`, a TS6059 error is thrown due to env.js not being under rootDir.

### Steps to Reproduce the Problem

```
create-react-app mockup --scripts-version=react-scripts-ts
cd mockup
yarn eject
yarn upgrade-interactive --latest
# select all packages except for ts-loader, such that it stays at version 2.3.7
yarn start
# verify that everything still works
yarn upgrade --latest
yarn start
# an error message is shown
```

### Actual Behaviour

```
ERROR
      TS6059: File '/Users/marton/workspace/mockup/config/env.js' is not under 'rootDir'
```

### Expected Behaviour

Well it should just work I guess.

**Comment by johnnyreilly** [comment]
Thanks for the repro but I'm closing as this seems to be a create-react-app or configuration problem - not a bug with ts-loader. Happy to reconsider if you can prove otherwise...

**Comment by marton78** [comment]
Well, I thought I had proven just that by showing that before updating ts-loader to v3 everything works fine. Surely it could be a configuration issue in create-react-app, but why did it work with ts-loader v2.3.7?

None of the [breaking changes in ts-loader v3](https://github.com/TypeStrong/ts-loader/releases/tag/v3.0.0) sound like they could have triggered the issue.

**Comment by johnnyreilly** [comment]
I don't know `create-react-app` so well but I know it comes with a small truckload of configuration under the bonnet. Hence I think that's probably the issue 

But as I understand, it ships with `ts-loader` 3.1.1. not 2.3.7: https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/package.json

Are you out of date?

**Comment by marton78** [comment]
You're right, they seem to have fixed the problem in the meantime. Recreating the project with the newest `react-scripts-ts` remedies the issue. Thanks!

**Comment by rifler** [comment]
> But as I understand, it ships with ts-loader 3.1.1. not 2.3.7

@johnnyreilly I open that link and see `"ts-loader": "^2.3.7",`

**Comment by johnnyreilly** [comment]
Fair point - not sure what's happened there. Feel free to investigate and report back.
