### ISSUE TITLE
webpack 4 things to do

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#709]
List of things that we need to do to make ts-loader compatible with webpack 4:

- remove: https://github.com/TypeStrong/ts-loader/blob/ba72dfc661c805dce52bdf5ba58a351ef4d08976/src/index.ts#L95

- moved to use the new enhanced-resolve: https://github.com/webpack/enhanced-resolve

**Comment by etroynov** [comment]
any news?

**Comment by Kocal** [comment]
He is actively working on it (https://github.com/TypeStrong/ts-loader/pull/710) :+1:

**Comment by johnnyreilly** [comment]
Yup - beta available: https://blog.johnnyreilly.com/2018/01/webpack-4-ts-loader-fork-ts-checker.html

**Comment by ConneXNL** [comment]
@johnnyreilly Is the new Weback 4 "sideEffects" supposed to work wtih typescript?

It seems that I can only get it to work with babel-loader, and not with ts-loader.

**Comment by johnnyreilly** [comment]
AFAIK there's nothing required for loaders to do. Let me know if you know otherwise.

**Comment by ConneXNL** [comment]
@johnnyreilly It seems you have to pipe it through babel in order for it to tree-shake. I am using the following webpack configuration for the prod env:

[{

    // We are piping trough babel to get Webpack 4 Tree Shaking support with { 'sideEffects' : false }
    loader: 'babel-loader'
}, {
    loader: 'ts-loader',
    options: ({
        transpileOnly: true,
        
        // Since we are piping trough babel we have to target es2016
        compilerOptions: {
            target: "es2016",
            module: "es2015"
        },
    })
}]

**Comment by cecilemuller** [comment]
Webpack does the tree shaking, not Babel. Babel merely doesn't interfer with the import/export statements.

**Comment by ConneXNL** [comment]
@cecilemuller I guess in the context of es5 exporting.
