### ISSUE TITLE
Compile never finishes with experimentalWatchAPI true

### ISSUE THREAD

**Issue by mikeyoon** [TypeStrong/ts-loader#718]
With TS 2.7.1 and Loader 3.4.0, if I turn on the experimentalWatchAPI flag on my project, the build never finishes, or maybe it does, but I haven't waited long enough to find out. The node process is pegged at 100%. If I run `tsc -w` that runs as expected with fast incremental compilation. Also, if I turn the flag to false it runs as before as well.

This probably isn't enough info to go on, so does there happen to be a way I can get some logs of what's happening?

**Comment by johnnyreilly** [comment]
I'd hack some logs into the `makeWatchHost` functionality to get the info you need. If you could take a look I'd be super grateful!

I'm all taken up with webpack 4 at present

**Comment by johnnyreilly** [comment]
Actually, just had a thought. Maybe you could test something for me: could you test with this build of TypeScript please?

`"^2.7.0-dev.20180120",`

This is what ts-loader watch API support was tested with. It's possible that something has changed subsequently as I haven't had time to add any tests to ts-loader for this yet. (Again webpack 4 taking up as lot of my time.)

Could you check and report back please? Perhaps something changed between that version and ts-loader 2.7.1 being released. I'd love to know

**Comment by johnnyreilly** [comment]
Also - I've only tested on Windows. Are you on Windows?

**Comment by johnnyreilly** [comment]
This worked for me: https://github.com/johnnyreilly/typescript-ts-loader-watch-api-illustration

Does it for you? Do the versions of TypeScript used make a difference?

**Comment by mikeyoon** [comment]
I'm running these builds on OSX, I'll check out your ideas.

**Comment by mikeyoon** [comment]
Using `"^2.7.0-dev.20180120"` didn't make a difference, but the illustration repo worked fine for me. Maybe needs a larger repo to reproduce.

**Comment by johnnyreilly** [comment]
If you change the `logLevel` to 'info' do you get any useful information?  This line suggests it should give us some ouput:

https://github.com/TypeStrong/ts-loader/blob/5f60800f8ec94f3b495b5028757e5f078b80ebab/src/servicesHost.ts#L190

**Comment by mikeyoon** [comment]
Unfortunately, that doesn't produce anything useful, only says what version of typescript is being used.

**Comment by johnnyreilly** [comment]
Disappointing. If you could take a look at this I'd greatly appreciate it - still very focused on webpack 4 right now. @sheetalkamat any ideas that you could share?

**Comment by sheetalkamat** [comment]
@mikeyoon  is it possible for you to share your repro code, I might be able to debug little bit of that to see if we can find something there

**Comment by mikeyoon** [comment]
@sheetalkamat It'll be in our private codebase, but we're definitely open to sharing the relevant app  with a mutual-NDA. Do you have one that you can send us? We have one we can send as well if that's easier.

**Comment by johnnyreilly** [comment]
If there's anything I can do to assist then let me know guys. Happy to help!

**Comment by sheetalkamat** [comment]
@mikeyoon can you please send it at shkamat@microsoft.com

**Comment by mikeyoon** [comment]
With Webpack 4 and TS-Loader 4.1.0, this no longer seems to be happening to me.
