### ISSUE TITLE
Lazy loaded modules not working with HappyPack and ts-loader

### ISSUE THREAD

**Issue by GenZodd** [TypeStrong/ts-loader#722]
I have converted my angular (v4) webpack (v3) over to use HappyPack and TS-loader

However, I have gotten things to build and the initial module loads up just fine but there are no lazy loaded module chunks downloaded and when I click on a link that uses a lazy loaded module I get an error about the module could not be found. Here is some of my code. Any ideas on how I set this up for lazy loaded modules?

I use to use raw-loader for the index.html file but HappyPack does not support that so I tried file loader which works at least for the root module but maybe that is causing this issue?

 const HappyPack = require('happypack');
 const happyThreadPool = HappyPack.ThreadPool({ size: 3 });

...

 new HappyPack({
    id: 'ts',
    threadPool: happyThreadPool,
    loaders: [
      {
        loader: 'ts-loader',
        query: { happyPackMode: true }
      },
      {
        loader: 'angular2-template-loader',
        query: { keepUrl: true }
      },
    ]
  }),

  new HappyPack({
    id: 'json',
    threadPool: happyThreadPool,
    loaders: [ 'json-loader' ]
  }),
  
  new HappyPack({
    id: 'styles-string',
    threadPool: happyThreadPool,
    loaders: [ 'to-string-loader', 'css-loader' ]
  }),

  new HappyPack({
    id: 'styles',
    threadPool: happyThreadPool,
    loaders: [ 'to-string-loader', 'css-loader', 'postcss-loader', 'sass-loader' ]
  }),

  new HappyPack({
    id: 'file',
    threadPool: happyThreadPool,
    loaders: [ 'file-loader' ]
  }),

...

new CommonsChunkPlugin({
    name: 'polyfills',
    chunks: ['polyfills']
  }),
  // This enables tree shaking of the vendor modules
  new CommonsChunkPlugin({
    name: 'vendor',
    chunks: ['main'],
    minChunks: module => /node_modules\//.test(module.resource)
  }),
  // Specify the correct order the scripts will be injected in
  new CommonsChunkPlugin({
    name: ['polyfills', 'vendor'].reverse()
  }),

here is a sample of my route setup. This all worked before Happypack and Ts-loader when we were using awesome-type-script-loader

   {
        path: <my path>,
        loadChildren: './my.module#MyModule',
        canActivate: [MyGuard]
    },

**Comment by shudson250** [comment]
Am experiencing same issue when upgrading from ts-loader@3.2.0 to ts-loader@4.0.1

webpack config:
`...
{
  test: /\.(ts|tsx)$/,
  include: paths.appSrc,
  use: [
    { loader: 'cache-loader' },
    {
      loader: 'thread-loader',
      options: {
        workers: require('os').cpus().length - 1,
      },
    },
    {
      loader: 'ts-loader',
      options: { happyPackMode: true }
    },
  ]
},`

**Comment by johnnyreilly** [comment]
AFAIK this is happypack related - not a ts-loader issue. it might be worth raising an issue against happypack
