### ISSUE TITLE
ts-loader ignores traceResolution in tsconfig.json and webpack config

### ISSUE THREAD

**Issue by aappddeevv** [TypeStrong/ts-loader#725]
### Expected Behaviour
traceResolution: true would output resolution traces during a webpack build.

### Actual Behaviour
No output from trace resolution

### Steps to Reproduce the Problem
Set traceResolution to true in either tsconfig and your webpack config, or either location.

**Comment by aappddeevv** [comment]
Oh, I just found the other issue around this...my search did not turn it up...this can be closed.

**Comment by JasonKleban** [comment]
@aappddeevv a reference to that other issue would be nice

**Comment by novwhisky** [comment]
#691
