### ISSUE TITLE
Storybook read config file in the .ts file extension?

### ISSUE THREAD

**Issue by gkawin** [TypeStrong/ts-loader#730]
### Expected Behaviour
- I expected the storybook to be able to read the `config.ts` and also `webpack.config.ts` in the `.storybook` folder.
### Steps to Reproduce the Problem
- I use transpile those `.ts` files to `.js` file and after that trigger the storybook process.

### Location of a Minimal Repository that Demonstrates the Issue.
- I could be required the storybook to be able to read the configuration in `.ts` directly without transpile before running the process. How can I do that? Could you please advice me? Thankyou so much.

**Comment by johnnyreilly** [comment]
Hey @gkawin

I'm afraid I've never used storybook and so can't advise. FWIW I use js files for my config; not ts.

**Comment by ConneXNL** [comment]
Also just ran into this issue. However, I think this is a problem of storybook not ts-loader.

**Comment by gkawin** [comment]
Apologize for all of you guys, I just realize this issue not involving the ts-loader. BTW, Thank you for reference this issue to storybook's repository. Cheers.
