### ISSUE TITLE
HMR only works at the first time. 

### ISSUE THREAD

**Issue by Rokt33r** [TypeStrong/ts-loader#731]
https://github.com/webpack/webpack/issues/6592

### Expected Behaviour

It should not refresh the page.

### Actual Behaviour

![webpack-hmr](https://user-images.githubusercontent.com/5865853/36713942-49af5f2e-1bd3-11e8-8419-7026b327a454.gif)

HMR only works at the first time. Later on, it keep refreshing the page on every changes.

### Steps to Reproduce the Problem

https://github.com/Rokt33r/ts-webpack-hmr

> It has been fixed after I set `transpileOnly: true` option.

**Comment by johnnyreilly** [comment]
Hey @Rokt33r,

If I was you I'd take a look at one of our examples: https://github.com/TypeStrong/ts-loader/tree/master/examples/react-hot-boilerplate

Essentially you probably want to use `transpileOnly: true` in concert with the [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin).
