### ISSUE TITLE
Still getting issue "TS18003: No inputs were found in config file 'tsconfig.json'"

### ISSUE THREAD

**Issue by apfelbox** [TypeStrong/ts-loader#732]
Hi,

I am currently building a more-or-less zero config bundler for our company's internal usage.
For this I want to add TypeScript support using `ts-loader` **without** needing any of our dozens of projects to add a `tsconfig.json`.

### Expected Behaviour
It should just work, as there is an option in the plugin to set a custom path for the `tsconfig.json`.

### Actual Behaviour
It doesn't work and errors out with

> TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.

### Steps to Reproduce the Problem
I installed your [`vanilla` example](https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla) and did the following adjustments:

* move `tsconfig.json` to `example/tsconfig.json`
* change the webpack config to point to the new config file:

	```js
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'ts-loader',
                options: {
                    configFile: __dirname + "/test/tsconfig.json" // <- this is new
                }
            }
        ]
    },
	```

**Comment by apfelbox** [comment]
Please note: moving the `tsconfig.json` back to the top level (= a parent directory of the `*.ts` files) and letting it get autodiscovered works however.

**Comment by johnnyreilly** [comment]
Does this context option help? https://github.com/TypeStrong/ts-loader/blob/master/README.md#context-string-defaultundefined

If not and you'd like to investigate this I'd appreciate that; I don't have much time to spare right now

**Comment by theironcook** [comment]
Just tried to use the context option you described like this

`{
        test: /\.ts?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
        options: {
          context: __dirname,
          configFile: 'tsconfig.client.json'
        }
      }`

Got the same error :(

Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "use": "ts-loader",
  "exclude": {},
  "options": {
    "context": "/Users/TheUser/projects/TheProject/config",
    "configFile": "tsconfig.client.json"
  }
}

The file tsconfig.client.json is in the specified directory.  It exists etc. - just not working

**Comment by johnnyreilly** [comment]
@christiantinauer do you have any inights? I seem to recall you were trying to solve a similar problem with `context`?

**Comment by apfelbox** [comment]
@johnnyreilly it actually worked using context, thank you! I was already desparate, as nothing seemed to work. Thank you very much for the fast answer!
I will send a PR though, to suggest an improvement in the docs.

@theironcook I think you have an other issue, I think you are using invalid babel loader syntax.
There are two variations (there are actually more, but two that matter):

1. with a single loader

```js
{
    test: /\.ts?$/, 
    loader: 'ts-loader', 
    exclude: /node_modules/, 
    options: { 
        context: __dirname, 
        configFile: 'tsconfig.client.json' 
    },
}
```

or 2) with a list of loaders:

```js
{
    test: /\.ts?$/, 
    use: [
        {
            loader: 'ts-loader', 
            exclude: /node_modules/, 
            options: { 
                context: __dirname, 
                configFile: 'tsconfig.client.json' 
            },
        }
    ]
}
```

You have a mix of both, but need to use `loader` as key.  That is what the error message is trying to tell you, they literally mean the object key `loader` in 

> `options` / `query` provided without `loader`

**Comment by christiantinauer** [comment]
@apfelbox happy that the option solves your problem. How can the docs be improved?

**Comment by apfelbox** [comment]
I would add a note here, that you may need to set the `context` option, if the `configFile` is outside your project (root).

![2018-02-28 at 09 31](https://user-images.githubusercontent.com/1032411/36777580-4a0b7178-1c6a-11e8-8b8b-ab9f3757ff7e.png)

What do you think?

**Comment by christiantinauer** [comment]
That is a good idea as I think there will be others who try to change the path to an outside tsconfig file and will run into the same problems.

I guess @johnnyreilly  will be happy to accept a pull request from you.

**Comment by apfelbox** [comment]
I will close this issue, as we now have an open PR to keep the discussion going in #733
