### ISSUE TITLE
How to compile in ES3? (keyword issue)

### ISSUE THREAD

**Issue by Domvel** [TypeStrong/ts-loader#735]
I've a problem with the generated bundle.js. I use this on a device with embedded linux which has a very old javascript engine. Something between ES3 and ES5. The core issue is that this engine has a problem with keywords as variables or property names. 
For exampe the expression in line 31 of bundle.js `return e.default` is not allowed. Because default is a keyword. The js engine can't parse this. A workaround is to cloth the name in quotes like `return e["default"]`. Anyway ...

How to set the target to es3? I think in es3 the keyword-issue is handled. But maybe not for the typescript compiler. 

It looks like the tsconfig.json would be ignored with webpack ts-loader. 
Is there any option to use with my issue? I would be grateful for any help. Please show complete example (e.g. webpack.config.js) Thanks! :)

**Comment by johnnyreilly** [comment]
Use `tsconfig.json` and `"target": "es3"` - should be fine!

**Comment by Domvel** [comment]
The `target` value of `tsconfig.json` does not change the output file. I tried `es3` and `es6`.The files are identically.

**Comment by johnnyreilly** [comment]
Do you want to show me your repo? Maybe that will help

**Comment by Domvel** [comment]
[Here](https://github.com/Domvel/ts-webpack-template)

**Comment by Domvel** [comment]
Of course, the `module` type in `compilerOptions` have to change. I check this out.

**Comment by pwcong** [comment]
i meet same problem too. did u fix it? could u teach me ? thk!

**Comment by pwcong** [comment]
**Add the follow code to webpack configuration it will be solved:**

```
module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          ie8: true
        },
      }),
    ],
  }
};
```
