### ISSUE TITLE
getCustomTransformers not called with happypack

### ISSUE THREAD

**Issue by alteredtastes** [TypeStrong/ts-loader#739]
### Expected Behaviour

getCustomTransformers function is called during build when used with happypack

### Actual Behaviour

getCustomTransformers is not called.

### Steps to Reproduce the Problem

https://github.com/Igorbek/typescript-plugin-styled-components/issues/6#issue-303387183

### Location of a Minimal Repository that Demonstrates the Issue.

I believe link and discussion above provide sufficient detail.

For reference,  @Igorbek points out that there is a way to do this with awesome-typescript-loader although it would be ideal for us to stick with ts-loader
https://github.com/s-panferov/awesome-typescript-loader/pull/531/commits/f37dacb9f02a76b0f05c4c0abceae75e677a6662

**Comment by johnnyreilly** [comment]
Thanks for the informative issue - that's super helpful! 

If you'd like to have a crack at implementing a similar approach as mentioned by @igorbek I'd be happy to take a look at your PR. Don't worry about tests failing etc - just get something in place and I'll gladly help you from there. 🌻

**Comment by vagusX** [comment]
same situation
