### ISSUE TITLE
how can i load .json in typescript file?

### ISSUE THREAD

**Issue by xosuperpig** [TypeStrong/ts-loader#74]
webpack config:
```
{
	module: {
		loaders: [
			{test: /\.json$/, loader: 'json'},
			{test: /\.ts$/, loader: 'ts-loader'}
		]
	},
	externals: {
		THREE: 'THREE'
	}
}
```

my directory:
- src
  - entry.ts
  - ball.json

entry.ts:
```
/// <reference path="../typings/threejs/three.d.ts" />
import ball from './ball.json';

//....
```

but when i run the webpack, it will report
ERROR in ./src/entry.ts
(5,20): error TS2307: Cannot find module './ball.json'.

**Comment by jbrantly** [comment]
Don't use `import`. See the section in the README on loading assets and https://github.com/TypeStrong/ts-loader/issues/30#issuecomment-128456710

**Comment by xosuperpig** [comment]
.json can be imported when I using babel-loader so I just simply think ts-loader will be the same.

(#30 (comment))[https://github.com/TypeStrong/ts-loader/issues/30#issuecomment-128456710] work for me.

thanks for helping.

**Comment by blakeembrey** [comment]
@xosuperpig Using `import` is specifically a TypeScript feature to import type information. When you use `const`, `let` or `var` it works just like `babel` does.
