### ISSUE TITLE
Webpack error when using declaration file string constants

### ISSUE THREAD

**Issue by westacotta** [TypeStrong/ts-loader#740]
### Expected Behaviour
in a .d.ts file to have a definition such as
declare module 'molecular/molecular' {
	export const LoggerService = "Logger";
}
(cut down for brevity)

and be able to reference the LoggerService const.
e.g.
import * as Molecular from 'molecular/molecular';
...
resolveService<Molecular.Logger>(Molecular.LoggerService)

### Actual Behaviour

I get a webpack error like so
Module not found: Error: Can't resolve 'molecular/molecular'

it works fine if i used tsc directly

### Steps to Reproduce the Problem
use the above as a template.
### Location of a Minimal Repository that Demonstrates the Issue.
n/a

**Comment by senyaak** [comment]
Just tested with webpack 3.11 it worksk, got no errors

**Comment by LosEagle** [comment]
I'm having same problems with Moleculer library.
