### ISSUE TITLE
Sourcemaps always generated inline

### ISSUE THREAD

**Issue by Legends** [TypeStrong/ts-loader#741]
**Webpack 3.1.1
ts-loader 3.5.0**

I want the sourcemaps to be generated separately in my dist folder, not inline.
Inline is bad, because when I want to to check my bundle.js under sources tab the browse starts to hang, because the file is too big I guess.

I tried different `devtool` settings but the result is always the same, sourcemaps are generated `inline`!

**webpack.config.js**
 devtool:"nosources-source-map",

**ts.config.json**
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es5",
    "diagnostics": true,
    "sourceMap": false,  // can also change it to true same result
    "moduleResolution": "node",
    "noEmitOnError": true,
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015.promise"
    ]
  },
  "include": [
    "./src/**/*"
  ]  
}

**Comment by johnnyreilly** [comment]
I think this is a webpack issue - not a ts-loader one. Closing as nothing to do I believe.

**Comment by Legends** [comment]
Yes, I was looking only at the source code, but the issue was hidden in my webpack command in package.json under scripts. There I got:

`webpack -d ....` , no matter how you configure webpack in your code, it will always generate the source-maps inline, because of the `-d` flag.

**Comment by johnnyreilly** [comment]
Cool - just I'm clear: you're saying it was a config issue?

**Comment by Legends** [comment]
Yeah, the issue was behind the screen after a very long day.... ;-)

**Comment by johnnyreilly** [comment]
> Yeah, the issue was behind the screen after a very long day.... ;-)

Yup. Been there!
