### ISSUE TITLE
TypeError: Cannot set property 'tsLoaderFileVersion' of undefined

### ISSUE THREAD

**Issue by baywet** [TypeStrong/ts-loader#748]
### Expected Behaviour
Build to work when happypackmode is not set
### Actual Behaviour
Transpilation fails with following error message
```
ERROR in ./somefile.ts
Module build failed: TypeError: Cannot set property 'tsLoaderFileVersion' of undefined
    at successLoader (C:\sources\gitttl\gsk\MeetingWorkspace\node_modules\ts-loader\dist\index.js:47:54)
    at Object.loader (C:\sources\gitttl\gsk\MeetingWorkspace\node_modules\ts-loader\dist\index.js:21:12)
```
### Steps to Reproduce the Problem
Have a project with webpack 3, ts-loader@latest, and happypackmode not set.

**Comment by hrgui** [comment]
Same here, I had to revert back to `v3.3.1` in order to get this resolved.

**Comment by johnnyreilly** [comment]
Yep - ts-loader 4 supports webpack 4. If you're on webpack 3 then run with ts-loader 3.x. I'm going to leave this open for visibility for a while, but there is no issue with ts-loader.

**Comment by baywet** [comment]
does this mean I should update this PR to also include a comprehensive error message? https://github.com/TypeStrong/ts-loader/pull/749

**Comment by baywet** [comment]
well one way would be to read the version of the package.json of the webpack module (the one installed, not the package.json of the current project)
maybe there's something like that in the webpack api, but I don't know it well enough.
If you look at my PR, anything without the property I was adding defensive programming for it webpack <4 so maybe instead of version checking only a capability checking could be implemented?

**Comment by johnnyreilly** [comment]
If there's a simple (non-hacky) way to reliably test the webpack version I'm open to adding a "your webpack version is not supported - use webpack 4 or and older version of ts-loader". Otherwise I think it's best left as is.

This was intentionally a breaking changes release and TBH people should take a look at release notes if they are hoping to make a major version bump. Not trying to be difficult. Just trying to be a good semver citizen.

**Comment by baywet** [comment]
agree 200% on the semver, I didn't do my homework properly before upgrading (lots of deps to upgrade).
I do believe however that's it's always better to have meaningful error messages.
Do you consider the "reading webpack's package.json version" option to be hacky?

**Comment by johnnyreilly** [comment]
Uh.... It should work reliably. But it slightly gives me an icky feeling. Hmmmm. Not totally sure to be honest.

**Comment by Rahulkr204** [comment]
Any fix for this ?
Running with following configuration :

"ts-loader": "^4.3.0",
"webpack": "^4.10.2",

**Comment by vankooch** [comment]
I've the same problem

    "ts-loader": "^4.4.2",
    "typescript": "^2.9.2",
    "webpack": "^4.16.1"

**Comment by johnnyreilly** [comment]
To re-iterate what was said earlier: ts-loader 4 supports webpack 4. If you're on webpack 3 then run with ts-loader 3.x. AFAIK there is no issue with ts-loader.

**Comment by vankooch** [comment]
Sorry for this, but I'm using webpack version 4.16.1 as mentioned in my first post.

```shell
% webpack --version
4.16.1
```

```json
"ts-loader": "^4.4.2",
"typescript": "^2.9.2",
"webpack": "^4.16.1"
````

I'm using nuxt, maybe this the problem. I'll check that out next week.

**Comment by VrajSolanki** [comment]
@johnnyreilly why is this issue closed? I am myself having these versions 
``` "ts-loader": "^4.3.0",
    "typescript": "^2.9.1",
 "webpack": "^4.16.0",```
 and actual versions are 
```ts-loader: 4.5.0,
typescript: 2.9.2,
webpack: 4.16.5```

and still it is not working. I guess this should be reopened and fixed or atleast be tagged as a bug ??

**Comment by vankooch** [comment]
It turns out that the bug was in somehow related to nuxt. I've switch to nuxt-edge and now it's working.
