### ISSUE TITLE
No errors logged when using thread-loader

### ISSUE THREAD

**Issue by marcofugaro** [TypeStrong/ts-loader#750]
### Expected Behaviour
<img width="534" alt="screen shot 2018-03-21 at 15 33 00" src="https://user-images.githubusercontent.com/7217420/37716210-3fe83bee-2d1e-11e8-9432-3f1962ff19cf.png">

### Actual Behaviour
<img width="349" alt="screen shot 2018-03-21 at 15 33 05" src="https://user-images.githubusercontent.com/7217420/37716234-4be607fa-2d1e-11e8-9f24-b692a866db84.png">

### Steps to Reproduce the Problem
I am using the [thread-loader](https://github.com/webpack-contrib/thread-loader) like `create-react-app` does, to parallelize multiple transpiler loaders, here is the webpack config for the .ts files:
```js
{
    test: /\.(ts|tsx)$/,
    use: [
      'thread-loader',
      {
        loader: 'babel-loader',
        options: {
          compact: process.env.NODE_ENV === 'production',
          cacheDirectory: true,
          highlightCode: true,
        },
      },
      'ts-loader',
    ],
  }
```

Or is this an issue with thread-loader?

**Comment by johnnyreilly** [comment]
Could be worth checking if this is a webpack 4 issue. Check out our example here: https://github.com/TypeStrong/ts-loader/tree/master/examples/thread-loader

It may help your config woes

**Comment by marcofugaro** [comment]
Sorry, did not fully read the readme 😄  
Turns out I had the `happyPack` mode disabled.

By the way do you suggest using the `cache-loader`? Does it really improve performances by a significant amount?

**Comment by johnnyreilly** [comment]
If the project is BIG then yes. If not then not significantly.

**Comment by marcofugaro** [comment]
That's what I was looking for, thank you!
