### ISSUE TITLE
IE 11 - Object doesn't support this property or method "includes" - example react-hot-boilerplate

### ISSUE THREAD

**Issue by skoruba** [TypeStrong/ts-loader#752]
### Steps to Reproduce the Problem

After clone of the example `react-hot-boilerplate` - I get in IE 11 error message - `Object doesn't support this property or method "includes"`.

I have tried use the babel-polyfill like this:
```
entry: [
    'babel-polyfill', <---
     ....
  ]
```

But it doesn't work.

How can I fix this error?

**Comment by gallout** [comment]
How did you fix it?
