### ISSUE TITLE
Why to use `babel-loader` with `ts-loader`?

### ISSUE THREAD

**Issue by bondom** [TypeStrong/ts-loader#755]
In your documentation you refer to this example: https://github.com/Microsoft/TypeScriptSamples/tree/master/react-flux-babel-karma

Webpack config contains `babel-loader` with `ts-loader` for `.tsx?` files.
Please explain why it is needed? 
Why `ts-loader` isn't enough?

**Comment by johnnyreilly** [comment]
It isn't needed. It is just used in that example. 

Here's an example without: https://github.com/TypeStrong/ts-loader/tree/master/examples/core-js
