### ISSUE TITLE
Building in docker container failing / extremely slow

### ISSUE THREAD

**Issue by genox** [TypeStrong/ts-loader#758]
Hi,

I'm trying to build an app with typescript in a docker container (for CI/CD) but the build (using webpack, babel, as per NextJS) never finishes and eventually exits when it hits timeout.

When I build the app (with prod env) locally, not inside the container, the build works fine and finishes after 15s. In a docker container (tried alpine and ubuntu), it hangs at 100% CPU, slowly filling memory, with low I/O.

I'm using NextJS with` @zeit/next-typescript` - already asked for guidance over there but to no avail.

I'm using webpack@3.11.0, ts-loader@3.5.0 and typescript@latest. Unfortunately I can't just upgrade to webpack 4 for the new ts-loader versions for testing - locked in by NextJS. I tried with various typescript versions, the only difference is that some of them leak memory more than others. ;-) But the result stays the same.

Anyone ever experience a similar issue, especially within a docker container?

**Comment by johnnyreilly** [comment]
As far as I can tell, this is not a ts-loader issue and so I'm closing this issue.  I hope you get your issue sorted.  Please feel free to re-open if you identify a specific ts-loader problem

**Comment by johnnyreilly** [comment]
You could up the log level to info: https://github.com/TypeStrong/ts-loader/blob/master/README.md#loglevel-string-defaultwarn

There's also a trace option you could try including

**Comment by johnnyreilly** [comment]
Thanks for reporting back! It's always good to know where things get to :smile:

**Comment by chris-vest** [comment]
@genox Thanks for the fix on that, was having the same problem!

**Comment by wchatx** [comment]
@genox same problem and your fix solved it. thanks!

**Comment by MikeShiner** [comment]
@genox same problem here - thank you! You've saved me a lot of time with this niche issue.

**Comment by OrenSchwartz** [comment]
+1

**Comment by ilteoood** [comment]
+1 for the suggestion of @genox
