### ISSUE TITLE
tsx files -- the very first example in the README seems wrong, which will frustrate new users (like me).

### ISSUE THREAD

**Issue by williamstein** [TypeStrong/ts-loader#763]
### Expected Behaviour

Copy and paste the example configuration from README.md and have it work.

### Actual Behaviour

It works on .ts files, but fails on .tsx files.

### Steps to Reproduce the Problem

Copy and paste the configuration using webpack 4.

The fix I think is just to replace

```
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: "ts-loader" }
    ]
  }
```

by

```
  module: {
    rules: [
      // all files with a `.ts` extension will be handled by `ts-loader`
      { test: /\.ts$/, loader: "ts-loader" },
      // all files with a `.tsx` extension are handled first by babel (to deal with JSX), then ts-loader:
      { test: /\.tsx$/, loader: "babel-loader!ts-loader" }
    ]
  }
```
which is basically what is later in the same README.md file.   This worked for me.   I'm not sending a PR, since this is my first day using Typescript, so maybe I'm just really confused.  If so, close this.

**Comment by johnnyreilly** [comment]
Hi @williamstein

You shouldn't actually need Babel in the mix at all.... Take a look at this example for reference:

https://github.com/TypeStrong/ts-loader/tree/master/examples/core-js

If our instructions are wrong then any docs PR improvement is welcome. Welcome to TypeScript - it's amazing!
