### ISSUE TITLE
Webpack overlay doesn't show with Async: true for ForkTsCheckerWebpackPlugin

### ISSUE THREAD

**Issue by archonsunny** [TypeStrong/ts-loader#764]
Is there anyway to get webpack overlay to show the type errors on the screen while keeping Async: true for ForkTsCheckerWebpackPlugin so that it doesn't slow down the builds?

If not, is there another alternative to showing the type errors on the screen? I've tried the notifier plugin, but that doesn't make it as apparent as the overlay for webpack.

**Comment by johnnyreilly** [comment]
AFAIK there's no other way than the ones you've tried. I use the notifier plugin (which I wrote) as it's the fastest method. `async: false` is slower but more visual. That's what create-react-app uses (TS version). You could try writing a plugin based upon the notifier codebase that hooked into the html-webpack-plugin. Not sure if that would work but it might
