### ISSUE TITLE
TS interfaces?

### ISSUE THREAD

**Issue by whitecolor** [TypeStrong/ts-loader#770]
### Expected Behaviour

I wonder why this module doesn't export any TS interfaces (LoaderOptions).

```ts
import { LoaderOptions } from 'ts-loader'
```

### Actual Behaviour

Just js code.

**Comment by johnnyreilly** [comment]
Sorry you want `.d.ts` to be emitted too? What's the use case? I'm up for including them if there's a need

**Comment by johnnyreilly** [comment]
Feel free to submit a PR

**Comment by whitecolor** [comment]
I use TS webpack config, and some wrappers to configure loaders.

**Comment by johnnyreilly** [comment]
Okay - myself I use js for my webpack config. I'm happy to support others with different flows though. Why don't you fork, have a play and submit a PR. 

I'm guessing it's just a case of adding `declaration: true` to the `tsconfig.json`. let me know your findings

**Comment by Hotell** [comment]
Heyo! I have the same problem. 
I'm using awesome latest TS 2.9 for type checking js files and with that having type safe configs for webpack, jest etc. right now I have to write my own ambient type definitions for `interface LoaderOptions`

**webpack.config.js**
```js
// @ts-check

/**
 * @type {Partial<import('ts-loader').LoaderOptions>}
 */
const tsLoaderOptionsRules = {
  configFile: tsConfig,
  transpileOnly: true
}
```

instead I would like to use definitions, which you already have in codebase, just need to be shipped as ambient types with your package. I'm definitely up to sending a PR, if you can point me in right direction. 

cheers !

**Comment by johnnyreilly** [comment]
So I think it's as simple as adding `declaration: true` to the `tsconfig.json`. Want to try and report back? If it's just that then pr with that change and we're done!

**Comment by Hotell** [comment]
I'm on it
