### ISSUE TITLE
add peerDependecies

### ISSUE THREAD

**Issue by yibuyisheng** [TypeStrong/ts-loader#775]
### Expected Behaviour

Should display some warn messages when installed with a mismatched webpack.

### Actual Behaviour

Display nothing.

### Steps to Reproduce the Problem

```
mkdir my-project
cd my-project
npm init
npm i webpack@3 -D
npm i ts-loader@4 -D
```

**Comment by yibuyisheng** [comment]
> the problem is there's no nice way to determine webpack version.

I guess you have thought about the `peerDependencies` of `package.json`. Since the `webpack@4` was put into the `package.json`'s 'devDependencies' config, it means that the test codes runs well with `webpack@4`. So I want to know what the specific problem is while using `peerDependencies`.

**Comment by johnnyreilly** [comment]
Can a package exist in `devDependencies` and `peerDependencies` at the same time?

**Comment by yibuyisheng** [comment]
Yes. This is how [babel-preset-env](https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json#L54) does.

The function and behavior of `devDependencies` can be found [here](https://docs.npmjs.com/files/package.json#peerdependencies).

**Comment by johnnyreilly** [comment]
Makes sense. Would you like to submit a PR?
