### ISSUE TITLE
Excessive stack depth compilation error compiling an app that is using yarn link to reference a module containing ImmutableJS

### ISSUE THREAD

**Issue by ryanewtaylor** [TypeStrong/ts-loader#777]
### Tested With

* Windows 10
* Node@8.5.0
* Yarn@1.6.0
* ts-loader@4.3.0
* typescript@2.8.3
* immutable@3.8.2
* webpack@4.8.1

### Expected Behaviour
No compilation errors.

### Actual Behaviour

```
ERROR in C:\Dev\excessive-stack-depth\app\tsconfig.json
[tsl] ERROR
      TS2321: Excessive stack depth comparing types 'List<Widget>' and 'List<Widget> | PromiseLike<List<Widget>> | undefined'.

ERROR in C:\Dev\excessive-stack-depth\app\index.ts
./index.ts
[tsl] ERROR in C:\Dev\excessive-stack-depth\app\index.ts(12,13)
      TS2345: Argument of type 'List<Widget>' is not assignable to parameter of type 'List<Widget> | PromiseLike<List<Widget>> | undefined'.
  Type 'List<Widget>' is not assignable to type 'PromiseLike<List<Widget>>'.
    Property 'then' is missing in type 'List<Widget>'.
error Command failed with exit code 2.
```

### Steps to Reproduce the Problem

1. Create a module (lib) exporting a function (makeWidget) returning a List<Widget>
1. yarn link the lib
1. Create an app compiled and bundled with Webpack + ts-loader
1. yarn link the previously created module
1. Import and use the makeWidget function
1. Build

Or, clone the following repro repo and follow the included instructions.

https://github.com/ryanewtaylor/repro-excessive-stack-depth-error

**Comment by johnnyreilly** [comment]
I'm not certain this is an issue with ts-loader specifically...
