### ISSUE TITLE
transpileOnly doesn't respect tsconfig.json's target and only transpiles to es5

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [TypeStrong/ts-loader#779]
### Expected Behaviour
The target JS level specified in the tsconfig.json file would be respected and the JS produced by the typescript transpiler would be es5, es6, etc.

### Actual Behaviour
The transpiler is always producing es5 level JS.

### Steps to Reproduce the Problem
1. Scaffold out a simple app and use es6 lambdas or the spread operator, etc.
2. specify es6 target in tsconfig.json
3. run webpack without specifying transpilerOnly: true.
4. Save the produced chunks.
5. update webpack.config.js to specify transpileOnly: true
6. rerun webpack and then diff the outputs of the first and second runs.
7. Notice the lambda and/or spread, etc. exist in the first but are transpiled down to closures and applys in the second.

**Comment by johnnyreilly** [comment]
So I'm pretty sure this will be a configuration error.

I suggest you take a look at your `tsconfig.json`. We have a test that protects against this: https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/es6

**Comment by ItWorksOnMyMachine** [comment]
It's definitely not a configuration issue, however, I have set up a different project and can't reproduce.  There is something else going on in my production product that is causing this.  I'm closing this issue.  Sorry for the confusion.
