### ISSUE TITLE
I experience full page refresh instead of HMR upon modification

### ISSUE THREAD

**Issue by gh67uyyghj** [TypeStrong/ts-loader#781]
Hi all, I use ts 2.8 with Webpack 4.8, I think I read the doc multiple times but I cannot get HMR working, I experience full page refresh instead of HMR upon modifying anything.

```
module: {
   rules: [
      {
        test: /\.tsx?$/,
        loader: "ts-loader",
        options: {
          transpileOnly: true
        }
      },
.....
plugins: [
    new webpack.NamedModulesPlugin(),
    // new webpack.HotModuleReplacementPlugin()
  ],
devServer: {
    hot: true,
.....
}
}
```
There is also one thing in the doc that I don't actually get:
`Inside your HMR acceptance callback function, you must re-require the module that was replaced`. What does that mean?

I appreciate any help

UPDATE: I should also mention that I tried awesome-typescript-loader and I had the same problem, always full page reload instead of HMR

**Comment by johnnyreilly** [comment]
So our example is out of date; there's been a new major version release since then. https://github.com/gaearon/react-hot-loader

Caveat: v4 of react-hot-loader requires Babel to be part of the pipeline. I'm not using it myself mainly because of that.

That said, if someone wants to update our example I'd appreciate it.

**Comment by gh67uyyghj** [comment]
Thsnks @johnnyreilly for the quick response, however I still don't understand anything from your answer :D. Do you mean that react-hot-loader (I never heard of it tbh since I am coming from vue ad HMR was pretty straightforward) is a must to get HMR working?

**Comment by johnnyreilly** [comment]
Honestly I don't know... I'm a React guy and didn't realize hmr was a thing in Vue... If anyone else knows do chime in!
