### ISSUE TITLE
Critical Server Error!

### ISSUE THREAD

**Issue by GlitterGhast** [TypeStrong/ts-loader#79]
I'm quite new to this all. Also to note, i am using a macbook air. So i downloaded pocketmine using the pocketmine code off the website (curl -sL http://get.pocketmine.net/ | bash). It was all fine until i quit without stopping my server. I couldn't figure out how to start my server again so i downloaded the same pocket mine code again (curl -sL http://get.pocketmine.net/ | bash). I filled it out like i was creating a new server, just like i did the first time. I then did ./start.sh, it came up with this:

08:04:01 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
08:04:01 [INFO] Loading pocketmine.yml...
08:04:01 [INFO] Loading server properties...
08:04:01 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
08:04:01 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
08:04:01 [INFO] PocketMine-MP is distributed under the LGPL License
08:04:01 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
08:04:01 [CRITICAL] Perhaps a server is already running on that port?
08:04:01 [EMERGENCY] [RakLib Thread #4356837376] RakLib crashed!
08:04:02 [INFO] Preparing level "world"
08:04:02 [INFO] Starting GS4 status listener
08:04:02 [INFO] Setting query port to 19132
08:04:02 [INFO] Query running on 0.0.0.0:19132
08:04:02 [INFO] Default game type: SURVIVAL
08:04:02 [INFO] Done (0.95s)! For help, type "help" or "?"
08:04:02 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [48]: Address already in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32
08:04:02 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
08:04:02 [EMERGENCY] Please submit the "/Users/Simone/CrashDump_Thu_Oct_8-08.04.02-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
08:04:03 [INFO] Unloading level "world"
Killed: 9

Please help me. i have no idea as to what all of that means. I really want my server to work but i just can't seem to get things right.

**Comment by jbrantly** [comment]
I believe you filed this in the wrong location. I would suggest maybe https://github.com/PocketMine/PocketMine-MP/issues
