### ISSUE TITLE
ts-loader moving to webpack-contrib

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#794]
Hey everybody!

I had the good fortune to meet up with @thelarkinn during his recent European travels. One of the things we discussed was the possibility of moving ts-loader from the TypeStrong organisation to the [webpack-contrib organisation](https://github.com/webpack-contrib). webpack-contrib describes itself as "community supported 3rd party packages for webpack".

I'd like to move the project there for a couple of reasons:

1. It feels like a more logical "home". TypeStrong is a cool org, but there isn't really a direct link between ts-loader and other projects that sit alongside it. If ts-loader were to sit in webpack-contrib that would make more sense as each project there is one of the bits of lego you sling together when building a project.

2. ts-loader should get more visibility if it lives in webpack-contrib. More visibility === more community involvement. That's good for the project and good for me.

3. A safer future for ts-loader. If something should happen to me, ts-loader would be in safe hands. I couldn't, hand on heart, say that with TypeStrong right now, given that it isn't a coherent organisation, more a collection of projects.

I've squared this with @jbrantly and he supports this.

Before I take action I wanted to open this up to the community. Is there anything else I ought to consider? Does anyone have any views? I'm interested; let me know!

I'll leave this open for a week or so, if there's no compelling reason to keep ts-loader in TypeStrong we'll start the process of moving the project.

Thanks everyone!

**Comment by blakeembrey** [comment]
Very cool. Please go for it! :+1:

**Comment by Themesfinity** [comment]
This is absolutely a great move.

**Comment by emilio-martinez** [comment]
I think this would be an awesome move for the project. 👏👏👏

**Comment by nycdotnet** [comment]
Great

**Comment by johnnyreilly** [comment]
Thanks everyone - it's all been positive which is very encouraging. I'll start the wheels turning!

**Comment by johnnyreilly** [comment]
I'd love for this to happen but the last I heard from @dmethvin this was still with lawyers. Given the time that's elapsed I'm not sure if this is still in process.
