### ISSUE TITLE
ts-loader can raise incomprehensible exception when typescript module was not installed

### ISSUE THREAD

**Issue by kyasbal-1994** [TypeStrong/ts-loader#795]
### Expected Behaviour

There should be more appropriate exception for developer to install typescript module.

### Actual Behaviour

It is very hard to know typescript module is missing.

```
ERROR in ./src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object]
    at runLoaders (/Users/xxxxx/Assets/Connector/node_modules/webpack/lib/NormalModule.js:300:13)
    at /Users/xxxxx/Assets/Connector/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/xxxxx/Assets/Connector/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/xxxxx/Assets/Connector/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/xxxxx/Assets/Connector/node_modules/ts-loader/dist/index.js:18:9)
 @ multi ./src/index.ts
```

### Steps to Reproduce the Problem

Just run ts-loader without typescript module installed.

**Comment by johnnyreilly** [comment]
Is this definitely related to ts-loader?

**Comment by goudarzi** [comment]
+1 - (*Please* review)

**Comment by coultonluke** [comment]
I just came across this error when using `ts-loader`.
In case anyone is confused, this error is saying:

> You need to install the 'typescript' module

You can do this by executing `npm i typescript`
