### ISSUE TITLE
Error content is empty

### ISSUE THREAD

**Issue by k-bx** [TypeStrong/ts-loader#796]
I'm running `webpack` on a project, and can't understand the errors.

### Expected Behaviour

I'd like to see the errors from the compiler, or what command should I run to omit the ts-loader but reproduce the error.

### Actual Behaviour

I see no details about the error I receive.

### Steps to Reproduce the Problem

```
$ webpack
ℹ ｢webpack｣: Starting Build                                              
ts-loader: Using typescript@2.9.2 and /proj/tsconfig.json
ℹ ｢webpack｣: Build Finished
                                                                         
webpack v4.12.0                    
                                   
...

/proj/src/utils/error-logger.ts
  0:0  error  ./src/utils/error-logger.ts
  0:0  error  ./src/utils/error-logger.ts
  0:0  error  ./src/utils/error-logger.ts
...
```

Thank you!

**Comment by johnnyreilly** [comment]
I'd say there's probably something wrong with your setup.

Take a look at an example setup and contrast it with your own. Good luck!
