### ISSUE TITLE
NotYetImplemented Error for lots of original packages

### ISSUE THREAD

**Issue by samialmorshedi** [TypeStrong/ts-loader#797]
In the screenshot I have added, You can see lots of `NotYetImplemented ` error which I have no idea what to do with and how to fix them!!!
There is no documentation for it, please help me to fix it.
I'm using Angular Universal 6

![capture](https://user-images.githubusercontent.com/30777032/41505467-2544d3f6-721f-11e8-891c-6d6858f768eb.PNG)

**Comment by johnnyreilly** [comment]
Closing as not clear this is an issue with ts-loader

**Comment by blakeembrey** [comment]
@samialmorshedi If you look at your stack trace you can see it's coming from a library called `domino` and triggered by `ngx-cookie-service`. I looked into it more and it's coming from https://github.com/fgnass/domino/blob/784a210c6454dbdfd90ca104bd34bc33c59e090b/lib/Document.js#L308 and triggered by https://github.com/7leads/ngx-cookie-service/blob/1886b06af5b9cfcd20376918337ef937efa23bea/lib/cookie-service/cookie.service.ts#L35. Looks like your trying to do server side rendering but cookies aren't supported, definitely not an issue with `ts-loader`.
