### ISSUE TITLE
TS errors do not cause failure with --watch

### ISSUE THREAD

**Issue by jakelauer** [TypeStrong/ts-loader#800]
In other words, no errors are logged in this case even when errors are present in the code.

### Expected Behaviour
TS errors cause failure when webpack is built with --watch or without

### Actual Behaviour
TS errors only cause failure when webpack is built without --watch. When --watch is used, files are compiled and emitted without showing errors in webpack's log.

### Steps to Reproduce the Problem
- Use webpack 4
- Run webpack with --watch, with all valid TS files.  
- Modify a TS file to have an error that would normally cause compilation failure  
- Save the file  
- Observe

**Comment by johnnyreilly** [comment]
Please could you take this example setup: https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla and test if you face the issue.

**Comment by jakelauer** [comment]
I ended up circumventing the issue by using awesome-typescript-loader
