### ISSUE TITLE
ts-loader build does not produce correct output with chalk

### ISSUE THREAD

**Issue by mikeerickson** [TypeStrong/ts-loader#802]
### Expected Behaviour

When running built script using node, the chalk output is not correct when using ts-loader.  If I instead build using `tsc` (and not webpack) then the output is correct

### Actual Behaviour

I expect to see proper chalk output

### Steps to Reproduce the Problem

Please following instructions in README attached the repo referenced below

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/mikeerickson/ts-loader-chalk-issue.git

**Comment by johnnyreilly** [comment]
> I expect to see proper chalk output

Could you be a little clearer please? Is the problem the lack of colour?

**Comment by mfour-merickson** [comment]
In short, yes.   But the code works when compiling the file using `tsc` but does not work when bundling using `webpack` and `ts-loader`

The repo supplied shows bare bones as to what is happening.

I tried as you suggested to flip `allowSyntheticDefaultImports` to `true` and still not providing color output

**Comment by mfour-merickson** [comment]
@johnnyreilly re `Failing that I'm not sure this is an issue with ts-loader specifically.`

I am not sure where else to look for assistance, only two different methods of bundling typescript as far as I am aware (either `tsc` or `ts-loader` with webpack)
