### ISSUE TITLE
ts-loader doesn't resolve dependencies if file-loaders follows

### ISSUE THREAD

**Issue by Deathangel908** [TypeStrong/ts-loader#804]
### Expected Behaviour
 ts-loader should resolve imports
### Actual Behaviour
 generated file contains `import a from a`
### Steps to Reproduce the Problem
[ Check out my stackoverflow question](https://stackoverflow.com/questions/51227698/ts-loader-file-loader-doesnt-resolve-require-dependencies) 

**main.ts**:
```
import 'sw.ts';
```
**sw.ts**
```
import any-module from 'any-module`
```

**webpack-config.js**:

```
module.exports = {
  entry: ['./src/main.ts'],
  plugins: [
    new HtmlWebpackPlugin({hash: true, template: 'src/index.html'}),
  ],
  devtool: '#source-map',
  module: {
    rules: [
      {
        test: /sw\.ts$/,
        exclude: /node_modules/,
        loader: 'file-loader',
        options: {
          outputPath: '',
          name: 'sw.js?[sha512:hash:base64:6]',
        }
      },
      {
        test: /\.ts$/,
        loader: 'ts-loader',
      },
    ],
  },
};
```

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/Deathangel908/sw-ts

- yarn install
- yarn run prod
- check output of `sw.js`

**Comment by johnnyreilly** [comment]
My advice (you're not going to like it) is that service workers have some complexity involved. I recommend using a project like WorkBox to make your life easier:

 https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack 

I've blogged about this in the past in case it helps: https://blog.johnnyreilly.com/2017/11/the-typescript-webpack-pwa.html

Apologies, I know this isn't exactly what you're looking for.

**Comment by Deathangel908** [comment]
How does it solve the problem? I don't need caching in service worker at all. It's even not about service worker. I want to generate separate entry in webpack that webpack-dev-server wouldn't add additional functionality into. Furthermore in the [link] you provided:(https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) you provided

![image](https://user-images.githubusercontent.com/1336703/42445903-3298294e-837d-11e8-9a78-fdf298133df4.png)

I can't even solve my issue, I also searched for plugins that just generate the output files, but I wasn't able to find one.

**Comment by johnnyreilly** [comment]
Hey @Deathangel908, 

I'm sorry I wasn't able to solve your problem for you.  I wanted to let you know about the service worker possibilities since I've found them helpful in the past.

I'm closing this issue as it's not a specific issue with ts-loader.  However, if you do manage to solve your problem in a way that makes you happy, I'd encourage you to post back here to help others.  

Many thanks and best of luck!

**Comment by Deathangel908** [comment]
Could you please guide me which part of build system is responsible for resolving `import` dependencies ? So I could investigate it further.
 - webpack
 - typescript
 - ts-loader

I thought ts-loader should feed files to `typescript` so it can assemble them together.

**Comment by akoidan** [comment]
@gpoitch using sw-loader: 

 ```
  rules: [
        {
          test: /sw\.ts$/,
          exclude: /node_modules/,
          loader: 'sw-loader',
        },
```

in entry:
`    import './sw';`
