### ISSUE TITLE
Different output when using `transpileOnly: true`

### ISSUE THREAD

**Issue by cowchimp** [TypeStrong/ts-loader#805]
### Expected Behaviour

Given the same input, the resulting bundle created when using 'happypack' is should contain the same transpiled javascript as that in the bundle created using the 'vanilla' approach. 

### Actual Behaviour

The bundles are different in a way that produces javascript that results in a runtime exception. What was an object property in the "vanilla" bundle is suddenly a standalone variable in the "happypack" bundle.

### Steps to Reproduce the Problem

1. Clone the forked repo https://github.com/cowchimp/ts-loader
2. Run the `vanilla` example
   1. `cd examples/vanilla`
   2. `npm i && npm run build`
   3. Check the output in the `dist` folder
3. Compare to the `happypack` example
   1. `cd examples/happypack`
   2. `npm i && npm run build`
   3. Check the output in the `dist` folder

Notice the following difference with\without happypack:

```diff
  SomeClass.prototype.someFunc = function () {
-    return foo.someEnum.a;
+    return someEnum.a;
  };
```

### Location of a Minimal Repository that Demonstrates the Issue.

compare
https://github.com/cowchimp/ts-loader/tree/master/examples/happypack
to
https://github.com/cowchimp/ts-loader/tree/master/examples/vanilla

Some context:
This came up when upgrading from a build tool that was using vanilla ts-loader behind-the-scenes to a newer version that is using ts-loader+happypack.
I tracked the issue upstream and saw that it manifests itself in the "example projects" provided by ts-loader as well.

The source files provided in the forked repo are quite contrived, but they illustrate the issue.

I'm new to 'happypack' but from all I've read about it today I understand it's only suppose to be a performance optimisation, so it feels weird to me that it can introduce a change like this (which is a roundabout way of saying I'm aware that I might have made some wrong assumption along the way).

**Comment by johnnyreilly** [comment]
Thanks for the detail! Question: do you have the same problem if you use cache-loader / thread-loader in place of happypack? I ask as the happypack example was written pre-webpack 4 and I'm not clear how well happypack plays with webpack 4. It's worth saying that thread-loader / cache-loader should fulfill the same purpose.

Here's an example to test with: https://github.com/TypeStrong/ts-loader/tree/master/examples/thread-loader

**Comment by cowchimp** [comment]
Thanks for the reply.
The bug manifests in the `thread-loader` example as well.
In fact, this illustrates the difference between the two outputs really well, because now the only difference between the `vanilla` and the `thread-loader` bundles is in that specific line with the missing `foo` object (and all the other webpack boilerplate is the same).

I updated my fork so that the `thread-loader` directory includes the same input source as well
https://github.com/cowchimp/ts-loader/tree/master/examples/thread-loader

**Comment by johnnyreilly** [comment]
Interesting. Out of curiosity, what purpose do the `namespace`s in the code have? If you drop them (in a modular codebase they shouldn't be necessary anyway) does the difference remain?

Something else to try: if you take your `vanilla` example and supply the `transpileOnly: true` option to ts-loader, does the issue present?

**Comment by johnnyreilly** [comment]
BTW it might be worth reading the "Needless Namespacing" section of the Typescript handbook:

https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

The TL; DR is: you probably don't want to use namespaces if you're using modules

**Comment by cowchimp** [comment]
You're right, when supplying `transpileOnly: true` to the `vanilla` example, the `foo` variable disappears as well.
We're slowly migrating a large legacy codebase that used namespaces (back when it was the standard) to use modules. For the time being we need namespaces to keep working side-by-side with proper modules as we refactor.
But does the bug have to do specifically with namespaces? Can it manifest itself in other ways?

**Comment by johnnyreilly** [comment]
> But does the bug have to do specifically with namespaces? Can it manifest itself in other ways?

I'm honestly not sure. What I can tell you is that the 2 mechanisms use 2 different APIs in the Typescript compiler; hence the different behaviour.

I feel like I used to know the reason why and I've now forgotten. Sorry!

I'd be tempted to suggest you port your codebase without happypack and then do it in one fell swoop when done. It's the sort of change you could automate; it's essentially a regex all the files and you're done.
