### ISSUE TITLE
`transpileOnly: true` prevent from outputting declaration files

### ISSUE THREAD

**Issue by stoneChen** [TypeStrong/ts-loader#806]
It is not a bug, I just suggest documenting it in the README.
I am writing a Vue components lib, using `fork-ts-checker-webpack-plugin` and setting `transpileOnly: true`. Everything is wonderful but when building the source(`"declaration": true` in `tsconfig.json`), the declaration files do not appear in the dist! I google the problem for a long time, but no answer.

At last, I try setting `transpileOnly: false`(and `"declarationDir": "."`), the declaration files appears!

As this result, the reason is obvious. Because `transpileOnly: true` skip type checking, so the type info shoud not be outputed.

But I still strongly suggest  documenting it in the README especially for new ts user(like me).
Thank you!

**Comment by stoneChen** [comment]
Sorry for making this PR so late. https://github.com/TypeStrong/ts-loader/pull/813

**Comment by johnnyreilly** [comment]
Thanks for the PR!
