### ISSUE TITLE
Webpack does not recompile non-.d.ts type definitions

### ISSUE THREAD

**Issue by liangchunn** [TypeStrong/ts-loader#808]
Webpack does not detect changes made to a pure types file in `--watch` mode on incremental builds.
I have been struggling with this issue; it's somehow related to #697, but with non-`.d.ts` files.

```ts
// types.ts
export interface AmbientType {
    a: number,
    b: string
}
```

```ts
// index.ts
import { AmbientType } from './types'

const test: AmbientType = {
    a: 2,
    b: ''
}

// tslint:disable-next-line
console.log(test)
```

After starting webpack in watch mode, removing `b: string` from `types.ts` and saving, no errors are emitted. 

### Expected Behaviour
Webpack recompiles non- `.d.ts` type definitions

### Actual Behaviour
Webpack does not detect changes in `types.ts` on incremental builds, but fails on a cold build.

### Steps to Reproduce the Problem
1. `git clone https://github.com/liangchunn/not-recompiling-ts.git`
2. `cd not-recompiling-ts`
3. `yarn install`
4. `yarn start`
5. Remove `b: string` in src/types.ts and save
6. No type errors are reported

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/liangchunn/not-recompiling-ts

### Dependency versions
- `webpack@4.12.0`
- `ts-loader@4.4.1`
- `typescript@2.9.2`

### webpack.config.json
https://github.com/liangchunn/typescript-node-scripts/blob/master/lib/webpack.config.dev.js

**Comment by liangchunn** [comment]
I've found a workaround to this issue by using `transpileOnly: true` for `ts-loader` and leveraging `fork-ts-checker-webpack-plugin` to do the type checking.

Ambient type definitions are still not reloading on save ( issue being tracked here https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/36 ), but it does not 'persist' across incremental builds anymore.

**Comment by ZSkycat** [comment]
I have encountered the same problem. The reason for this problem is not just a  pure types file, but a ts file that is not actually used. That is, only `type` or `interface` is imported.

This problem can be solved by `import './type';`

Don't worry. The webpack production mode can removes empty modules and tree shaking. This won't have extra code being packaged. 😄 

## my case

type.ts
```ts
export interface InterfaceA {
    a1: number;
    a2: string;
}

export function test() {
    console.log('test');
}
```

index.ts
```ts
import { InterfaceA } from './type';
// import './type';

export function app(value: InterfaceA) {
    console.log(value.a1.toFixed(0));
    console.log(value.a2.trim());
}
```

**Comment by jlost** [comment]
Shouldn't there be a solution to this problem that isn't just a workaround? Is it even possible?
