### ISSUE TITLE
Different type checking output when using transpileOnly

### ISSUE THREAD

**Issue by subvertallchris** [TypeStrong/ts-loader#810]
### Expected Behaviour
Type checking output with `transpileOnly` enabled will match disabled.

### Actual Behaviour
After many many months with this enabled, my webpack builds started failing due to type errors that do not appear when running `transpileOnly`. Neither webpack nor VS Code's language service sees anything wrong, but the type error being reported isn't complete nonsense. It's almost as if different versions of type definitions are being used in the two modes.

https://github.com/TypeStrong/ts-loader/issues/805 sounds on the surface like it might be related, but it's manifesting differently.

### Steps to Reproduce the Problem
I would need to create a repo for you, I think.

### Location of a Minimal Repository that Demonstrates the Issue.
I've been toubleshooting for hours and need to go home, so please excuse the absese of this. I am hoping that this is a known issue or rings a bell. If not, I'm happy to throw something together for you tomorrow.

I'm running ts-loader 4.4.1, also tried 4.4.2, as well as fork-ts-checker-webpack-plugin 0.4.2 and 0.4.3. Like I said, this has been working perfectly for months, so I'm quite confused.

**Comment by subvertallchris** [comment]
I've managed to suss out some more details about this but I'm still unsure of how to troubleshoot further.

The root of my problem seems to be the types for React, `@types/react`.

When my version is locked to exactly 16.3.8, VS Code (and I think we could say the TS Language Service?) reports no errors, ts-loader with `transpileOnly` and `ForkTsCheckerWebpackPlugin` report no errors, ts-loader without the aforementioned options _does_ report type errors.

When my version is locked to exactly 16.4.3, the type errors previously only seen by vanilla ts-loader are revealed in VS Code and ts-loader with transpileOnly/ForkTsChecker enabled. In all contexts, I now see some _new_ type errors, consistent with the wildly breaking changes that were introduced in 16.4.3.

When I lock my version to 16.4.6, all type errors are resolved, consistent with the changes introduced in those types to resolve the problems introduced 16.4.3.

What I feel like I'm seeing, then, is that vanilla ts-loader is at times (??????) using a different version of types from what I have defined in my `package.json`. Explicitly locking to the latest version of the type seems to resolve all problems.

I'm going to try putting together a sample repo in the next couple of hours, but maybe someone will recognize what's going on before then.

**Comment by johnnyreilly** [comment]
The only thing I can think of (and you've probably done this already) is to delete your `node_modules` / `cacheloader` etc folders, reinstall with `yarn install`, reboot vscode and restart webpack. That should give you a clean consistent setup. If it doesn't I'd be super surprised.

**Comment by johnnyreilly** [comment]
Can you take one of the ts-loader examples and get this to reliably happen there?

**Comment by subvertallchris** [comment]
I'm gone as far as to delete my local repo, reclone, kill yarn.lock,
rebuild, same issue. I'm working on a sample repo now but I like the idea
of trying to recreate it with your examples, I'll try that instead.

Chris

On July 19, 2018 at 3:03:23 PM, John Reilly (notifications@github.com)
wrote:

Can you take one of the ts-loader examples and get this to reliably happen
there?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TypeStrong/ts-loader/issues/810#issuecomment-406381568>,
or mute the thread

**Comment by subvertallchris** [comment]
I keep striking out on this. I'm adding more and more code to make the example app look like mine and it's just not happening. We tested this on two systems with our project and saw the same behavior, so if it is something screwed up on our end (which seems likely) then it made it into git.

Are there any caches that `ts-loader` could be using without `transpileOnly`? Any different source of type defs that might get left behind?

This might also be more of a question for someone affiliated with yarn, but my `yarn.lock` does list `@types/react` twice.

```
"@types/react@*":
  version "16.4.6"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.4.6.tgz#5024957c6bcef4f02823accf5974faba2e54fada"
  dependencies:
    csstype "^2.2.0"

"@types/react@16.3.18":
  version "16.3.18"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.3.18.tgz#bf195aed4d77dc86f06e4c9bb760214a3b822b8d"
  dependencies:
    csstype "^2.2.0"
```

That's the most recent release first, then the one that my package.json has specified. Is there any known behavior where these two will be combined in some weird way? I see 16.3.18 in my node_modules, perhaps 16.4.6 is lurking somewhere and... something-something wrong types get loaded?

**Comment by johnnyreilly** [comment]
So that's interesting; you may have a dependency which is depending on a different version of react perhaps? Make sure all your dependencies are up to date perhaps? `yarn outdated` and check all your types deps are up to date?

**Comment by subvertallchris** [comment]
I've checked for that and nothing jumps out. Looking in yarn.lock, the dependencies on `@types/react` all look like this:

```
  dependencies:
    "@types/react" "*"
```

My interpretation of the yarn.lock file is that it's resolving the above to 16.4.6 (latest) and then my explicit request of 16.3.18 is also resolved. In node_modules/@types/react, I see 16.3.18; however, those types that depend on react all have 16.4.6 in _their_ node_modules. In other words...

```
my_project/
  node_modules/
    @types/
      react/
        16.3.18
      react-dom/
        node_modules/
          16.4.6
```

Is there any chance that ts-loader without transpileOnly is using some weird combination of these different versions instead of the one I have requested?

**Comment by johnnyreilly** [comment]
Shouldn't be, no. ts-loader just gets the Typescript compiler to handle all that. FWIW why don't you blow away your lock file and create anew to see if it helps?

**Comment by subvertallchris** [comment]
Tried it a few times, no go. I don't know enough about how TypeScript works, at a low level, but offhand, are there any significant differences between how ts-loader calls upon TypeScript and how VS Code and/or the ForkTsChecker do it? My understanding is that VS Code uses the language service, does vanilla ts-loader use the language service through the same public API?

**Comment by subvertallchris** [comment]
Sorry if I keep asking dumb questions, I'm just trying to come at it from different angles to fill gaps in my understanding since I can't really troubleshoot it on my own.

**Comment by subvertallchris** [comment]
I think this has something to do with the way yarn is handling multiple versions of the same types package, in this case `@types/react`. Using the same `package.json` file where I have my version locked to 16.3.18 and with `node_modules` blown out before each run, I encounter this consistently when using yarn to compile but never when using npm. Looking at npm's `package-lock.json`, I do not see any references to 16.4.6. Those dependencies which require React's types (`react-dom` and others) all resolved to the same version I requested.

```
// yarn.lock
"@types/react-dom@^16.0.6":
  version "16.0.6"
  resolved "https://registry.yarnpkg.com/@types/react-dom/-/react-dom-16.0.6.tgz#f1a65a4e7be8ed5d123f8b3b9eacc913e35a1a3c"
  dependencies:
    "@types/node" "*"
    "@types/react" "*"
```

```
// package-json.lock
    "@types/react-dom": {
      "version": "16.0.6",
      "resolved": "https://registry.npmjs.org/@types/react-dom/-/react-dom-16.0.6.tgz",
      "integrity": "sha512-M+1zmwa5KxUpkCuxA4whlDJKYTGNvNQW4pIoCLH16xGbClicD9CzPry4y94kTjCCk/bJZCZ/GVqUsP7eKcO/mQ==",
      "dev": true,
      "requires": {
        "@types/node": "8.10.21",
        "@types/react": "16.3.18"
      }
    },
```

I'm somewhat inclined to say this might be yarn's problem, but the fact that both VS Code and ForkTsChecker seem to handle this without difficulty really does seem to put the ball back in ts-loader's court. The fact that I can't reproduce this in another repo sure as hell seems to push this further back into _my_ court, but neither reverts to previously working commits nor any of the typical troubleshooting steps seem to clear it up, so idk.

(╯°□°）╯︵ ┻━┻ 

Totally confused but glad to know I should just use npm. Close this issue? Wdyt?

**Comment by johnnyreilly** [comment]
Without a reliable reproduction I think this should be closed.

Fork-ts-checker-webpack-plugin and ts-loader use the same services. There's a difference in how fork-ts-checker-webpack-plugin resolves files but that's it really.

**Comment by subvertallchris** [comment]
Alright, let's close it. Maybe it'll be helpful to someone in the future. Thanks for your time with it.

**Comment by johnnyreilly** [comment]
No worries. Sorry I couldn't be of more help
