### ISSUE TITLE
TS18002 Error thrown when building prod package

### ISSUE THREAD

**Issue by chrumck** [TypeStrong/ts-loader#811]
### Expected Behaviour
Should compile without errors

### Actual Behaviour
Returns this error below. The interesting thing is that it is transient. The build sometimes succeeds with the success rate of ~50%
```
ERROR in [tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.
 @ multi babel-polyfill whatwg-fetch ./infrastructure/webpackSetup.ts ./index.tsx main[2]

ERROR in ./infrastructure/webpackSetup.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json

```
### Steps to Reproduce the Problem
This is the config I use:

#### webpack.common.js:
```
const webpack = require("webpack");
const path = require("path");

const urlLoaderFileSizeLimit = 50000;
const svgOutputName = "svg/[name].[ext]";
const fontOutputName = "fonts/[name].[ext]";
const imageOutputName = "images/[name].[ext]";

process.traceDeprecation = true;

module.exports = {

    entry: [
        "babel-polyfill",
        "whatwg-fetch",
        path.join(__dirname, "infrastructure/webpackSetup.ts"),
        path.join(__dirname, "index.tsx"),
    ],

    output: {
        filename: "app.js",
        chunkFilename: "[name].[chunkhash].js",
        path: path.join(__dirname, "__dist__"),
    },

    resolve: {
        extensions: [".ts", ".tsx", ".js", ".jsx", ".json", ".css", ".scss", ".svg", ".woff", "woff2", ".ttf"]
    },

    module: {
        rules: [
            {
                test: /\.svg$/,
                loader: "svg-url-loader",
                options: {
                    limit: urlLoaderFileSizeLimit,
                    iesafe: true,
                    stripdeclarations: true,
                    name: svgOutputName,
                }
            },
            {
                test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+|\?\w+)?$/,
                loader: "url-loader",
                options: {
                    limit: urlLoaderFileSizeLimit,
                    mimetype: "application/font-woff",
                    name: fontOutputName,
                }
            },
            {
                test: /\.[ot]tf$/,
                loader: "url-loader",
                options: {
                    limit: urlLoaderFileSizeLimit,
                    mimetype: "application/octet-stream",
                    name: fontOutputName,
                }
            },
            {
                test: /\.eot$/,
                loader: "url-loader",
                options: {
                    limit: urlLoaderFileSizeLimit,
                    mimetype: "application/vnd.ms-fontobject",
                    name: fontOutputName,
                }
            },
            {
                test: /\.png$/,
                loader: "url-loader",
                options: {
                    limit: urlLoaderFileSizeLimit,
                    mimetype: "image/png",
                    name: imageOutputName,
                }
            },
            {
                test: /\.gif$/,
                loader: "url-loader",
                options: {
                    limit: urlLoaderFileSizeLimit,
                    mimetype: "image/gif",
                    name: imageOutputName,
                }
            },
        ]
    },

    plugins: [
        new webpack.NoEmitOnErrorsPlugin(),
    ],
};
```
#### webpack.prod.js:
```
const merge = require("webpack-merge");
const common = require("./webpack.common.js");
const webpack = require("webpack");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const BundleAnalyzerPlugin = require("webpack-bundle-analyzer").BundleAnalyzerPlugin;

module.exports = merge.strategy({
    entry: "replace",
}
)(common, {

    mode: "production",

    optimization: {
        splitChunks: {
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "vendors",
                    chunks: "initial"
                },
            }
        }
    },

    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: "ts-loader",
                options: { transpileOnly: true, configFile: "./tsconfig.prod.json" },
                exclude: /node_modules/,
            },
            {
                test: /\.s?css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: ["css-loader", "sass-loader"],
                })
            }
        ]
    },

    plugins: [
        new ForkTsCheckerWebpackPlugin(),

        new ExtractTextPlugin("bundle.css"),

        new webpack.HashedModuleIdsPlugin(),

        // Ignore all locale files of moment.js
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),

        // Un-comment to run bundle analyzer
        // new BundleAnalyzerPlugin(),
    ],

    stats: {
        warningsFilter: /export .* was not found in/,
    },
});
```

**Comment by johnnyreilly** [comment]
Weird. This should consistently error if this error is true:

> The 'files' list in config file 'tsconfig.json' is empty.

**Comment by chrumck** [comment]
> Weird. This should consistently error if this error is true

Yes, I find it weird too, an frustrating to debug, because it looks like a race condition or something

But anyway, if anybody needs a working repro, I can try and extract enough code for that, without copying the whole frigging codebase of the project I work on.

**Comment by johnnyreilly** [comment]
Yeah - give it a go. If you have a reproduction then someone may be able to help. Also, I often find that the act of producing a repro reveals the problem!

**Comment by chrumck** [comment]
Ok, [here is the repo reproducing the bug](https://github.com/chrumck/ts-loader-issue-811). I got the bug to reproduce on two different machines, but it seems the probability of it was different (lower) on the other computer. Just for the record, the machines were both Windows 10.

The funny thing though is that the repro does not build at all. If you don't get the error as reported with this issue, you get another one, which in turn does not happen in the original project the repro was created from. Weird!

**Comment by johnnyreilly** [comment]
Well done for putting together a repro repo! It could be more minimal so let's see if we can pare it back further and hence reveal the issue.

I've been reading the code of your repo and I've got a few things you could try. 

In the `tsconfig.json`:

- do you want to drop the `exclude` property? I doubt it's the problem but I also doubt you need it.

- `outDir` - you don't need this if you're using webpack. Try dropping it.

- `noEmitOnError` I don't think you need this and you almost certainly don't want this given I believe it's super expensive build time wise. The `noEmitOnErrors` plugin should be doing this job for you on the webpack side anyway

Out of curiosity, why do you import the `babel-polyfill` given you're not using Babel? I'd switch to importing `core-js` (what the Babel polyfill uses under the covers anyway) and strip out Babel entirely. Your build will be faster.

Why do you import some TypeScript via your webpack build file. I don't quite follow how that gets built and hence consumed

**Comment by chrumck** [comment]
Thanks for you input on my setup!

Here are replies to your suggestions:
>do you want to drop the exclude property? I doubt it's the problem but I also doubt you need it.
>outDir - you don't need this if you're using webpack. Try dropping it.

The project the repro was derived from is using `arcgis-js-api` which is stuck deep in the JS past. Among other things, it uses DOJO loader and build process. Suffice to say, it's a major headache and adding `outdir` and `exclude` is a part of the scheme to keep my head from exploding.
Also, I run 'tsc' as a VS Code task to check the project for errors and I prefer to have the transpiled files dumped somewhere else than the source folders, but I guess I could switch to webpack watch mode or something for that (maybe you have a hint on how to do it?)

> noEmitOnError I don't think you need this and you almost certainly don't want this given I believe it's super expensive build time wise. The noEmitOnErrors plugin should be doing this job for you on the webpack side anyway

Good point, will do!

> Out of curiosity, why do you import the babel-polyfill given you're not using Babel? I'd switch to importing core-js (what the Babel polyfill uses under the covers anyway) and strip out Babel entirely. 

Will do again!

> Why do you import some TypeScript via your webpack build file. I don't quite follow how that gets built and hence consumed

I understand you ask why I have two typescript files in the webpack `entry` , right? I ended up doing that because I needed to set the `__webpack_public_path__` before any subsequent bundles are requested from the server. I was having problems with webpack loader calling the server before that variable was set by my code, so I split out code setting that variable to a separate module which gets loaded first. Is there a better way to do that? 
But anyway, I feel that the error I reported might have something to do with the fact that there are two typescript files in `entry`.

**Comment by johnnyreilly** [comment]
> guess I could switch to webpack watch mode or something for that (maybe you have a hint on how to do it?)

Of course! I'd recommend taking a look at this setup here:

https://github.com/TypeStrong/ts-loader/tree/master/examples/core-js

It's not perfect, but it offers 2 tasks that are interesting to you:

```
# Compile the code and serve it up in watch mode at http://localhost:8080 
yarn start

# Compile the code for your Production build
yarn build
```

> . I was having problems with webpack loader calling the server before that variable was set by my code, so I split out code setting that variable to a separate module which gets loaded first. Is there a better way to do that?

I think I can possibly help you here. But first I need to better understand what you're trying to do. Would you like to give me the most basic explanation of what you're trying to achieve here and why? (be explicit and feel free to state the obvious)

I've a feeling I've slain this particular dragon before; but I need first to better understand what you're trying to achieve.

**Comment by chrumck** [comment]
> I think I can possibly help you here. But first I need to better understand what you're trying to do. Would you like to give me the most basic explanation of what you're trying to achieve here and why? (be explicit and feel free to state the obvious)

Thank you again for looking at it for me!

It all starts with the fact that the app is part of a .NET WebApi project which gets deployed to several environments. The problem is that each environment has a different host url and that url does not match the `window.location.hostname` browser variable. That means that I have to dynamically set the `__webpack_public_path__` based on some HTML data attributes passed by the server, so webpack runtime knows where to ask for other chunks. I started with setting that variable in the main entry module, but I ran into a problem of webpack trying to load some chunks before executing the code which sets the `__webpack_public_path__`. To solve that, I've split out the the part setting the variable to a separate entry module and added it to the `entry` before the main module to make sure that the variable is set before anything else is executed. After I've added that extra entry point, I started seeing the issue I've reported here.

Does that make sense?

**Comment by johnnyreilly** [comment]
I *think* so.  Let me play it back to you:

- You want to do a build
- You want the application to start up and serve up an HTML page which contains the base URL of your web API endpoints
- You want the base URL of future HTTP requests to be populated by this

Is that correct?

**Comment by johnnyreilly** [comment]
If this is correct, this is a common scenario.  The system I'm working on right now does this very thing. We tackle it differently.  Our (single) entry script essentially does the following:

- reads HTML attributes from the DOM (including base URLs)
- initialises a "server data" object in the application and passes it into the application.
- the base URL in the server data object is used to prefix all future HTTP requests

Does this solve your scenario or have I misunderstood what you're trying to achieve?

**Comment by chrumck** [comment]
> If this is correct, this is a common scenario. The system I'm working on right now does this very thing. We tackle it differently. Our (single) entry script essentially does the following:
 -reads HTML attributes from the DOM (including base URLs)
 -initialises a "server data" object in the application and passes it into the application.
 -the base URL in the server data object is used to prefix all future HTTP requests
Does this solve your scenario or have I misunderstood what you're trying to achieve?

That is happening in my app too, but that's not exactly the problem I'm addressing with two entry points. The point is to let the webpack runtime know where the non-entry chunks are located, before the actual app is run. It is about setting the `__webpack_public_path__` global browser variable, which the actual app does not care about and does not use to call API endpoints.

**Comment by johnnyreilly** [comment]
> The point is to let the webpack runtime know where the non-entry chunks are located, before the actual app is run. 

So this is super confusing to me.  I don't think I actually understand what your setup is designed to do.  Why would `webpackPublicPath` be necessary?  Doesn't the very nature of using webpack mean that chunks are available in the same context as when you're running?  

Better question: if you took away `webpackPublicPath` why would it not work just fine?  `require` statements / `imports` should be resolved at build time.  All chunks should be located on the same server, in the same directory.

I think I've likely got the wrong end of the stick here.  If you can help me understand what it is you're trying to do, maybe I can help?

**Comment by chrumck** [comment]
>Better question: if you took away webpackPublicPath why would it not work just fine? require statements / imports should be resolved at build time. All chunks should be located on the same server, in the same directory.

I'm sorry that it is confusing to you. Maybe I'm doing something wrong here, but the chunks end up being under different directories for different environments. 

The whole .NET app gets exposed under different virtual directory depending on the environment. For example, its going to be under `foo.com`  on one server and `bar.com/app` on another. If I statically set the webpack's `output.publicPath`  to `/dist`, webpack runtime is going to request a chunk from `foo.com/dist` in the first case and `bar.com/dist` in the second. The second one will be wrong, because it needs to be `bar.com/app/dist`.  I have to assume that I do not know at compile time what the final virtual directory is going to be. That is why I'm dynamically setting the `__webpack_public_path__` variable client side once the page is requested. 

But, it looks like there might be another solution for this, by having the server set the `<base>` tag in the generated HTML. I need to check if that solves the problem.

**Comment by johnnyreilly** [comment]
> the chunks end up being under different directories for different environments

Okay that's cool. The surprising bit to me is that all the chunks aren't together. Like all the files in a single directory. How does that come to pass?

**Comment by chrumck** [comment]
>Okay that's cool. The surprising bit to me is that all the chunks aren't together. Like all the files in a single directory. How does that come to pass?
The chunks *are* together, but the relative path differs from server to server for all of them.

**Comment by chrumck** [comment]
> Where does that come into play? Where does this live? What contains the relative path? Is this within the webpack bundle or external. Gimme details!

Sure! I hope this convolution is no too annoying to you :)

The .NET app I'm working on gets deployed to several servers. The trick which is happening here is the relative path is set differently for each of these instances. To bring up the example from above, you would navigate to `foo.com` for one and `bar.com/app` for another to open the app. When the page is requested, the Razor engine generates the HTML based on a template and renders a script tag for the entry bundle with the proper `src` in each case. So, it's `foo.com/dist/entry.js` for the first and and `bar.com/app/dist/entry.js` for the second. In the first case, the webpack runtime contained in the `entry.js` requests for other chunks like this: `foo.com/dist/chunk1.js`, and that works. In the second instance, webpack has no knowledge that the whole app is not at the server's root, and requests `bar.com/dist/chunk1.js` instead of `bar.com/app/dist/chunk1.js`.

So, the solution I went with is to dynamically set `__webpack_public_path__` *before* any chunks are requested. The relative path of the server app is added to that variable. The two entry modules are there because the first one just sets that variable without triggering any chunk loads, and the other is the actual app triggering them.

But as mentioned above, I just realized that the other way to solve the problem is to set the `<base>` tag which webpack runtime takes into consideration when requesting chunks. That would make having two entry modules and setting the `__webpack_public_path__` unnecessary.

**Comment by johnnyreilly** [comment]
Ah cool - I follow (I think!)

>  I just realized that the other way to solve the problem is to set the <base> tag which webpack runtime takes into consideration when requesting chunks

Great so that worked? Is the problem still remaining without the extra entry point?

**Comment by chrumck** [comment]
> Great so that worked? Is the problem still remaining without the extra entry point?

Yes, it did! 

You need to be careful with slashes when setting the `href` attribute in `<base>` and then use a relative path in `output.publicPath`, something like `dist/` and it all works with out-of-the-box webpack runtime settings. 

The added benefit is that I was able to take advantage of this setup when calling api endpoints from within the app itself, so the app can be oblivious to the server app relative path as well.

But, I guess the ts-loader bug is still there, the question is whether it's worth fixing.

**Comment by johnnyreilly** [comment]
I'm glad you're sorted! There may still be a problem with ts-loader but until a more targeted repro is available I think I'd like to close this.
