### ISSUE TITLE
Support for TypeScript 3 Declaration map 

### ISSUE THREAD

**Issue by JonWallsten** [TypeStrong/ts-loader#820]
I'm going to be honest, I don't fully comprehend how ts-loader interacts with the typescript compiler (API?) so I'm not sure when/where in the chain this has to be corrected. But when enabling declarationMap: true in tsconfig and building with Webpack/ts-loader I don't get any map files. 
When running the typescript compiler, tsc, I get those files. 
I'm not sure if ts-loader isn't submitting the files or if I have to collect them somehow in my Webpack config. Maybe someone can enlighten me?

### Expected Behaviour
When setting declarationMap: true in tsconfig I expect the d.ts.map file to be in my dist folder
### Actual Behaviour
Only the d.ts files are ends up in the dist folder
### Steps to Reproduce the Problem
Use latest webpack and ts-loader and enable declaration and declarationMap
### Location of a Minimal Repository that Demonstrates the Issue.
Should be reproduces with any Webpack 4/Typescript@3.0.x starter repo.

**Comment by johnnyreilly** [comment]
Do you have `sourcemap: true` in your `tsconfig.json`

**Comment by JonWallsten** [comment]
@johnnyreilly Yeah! I get the maps when I run "tsc", I just don't get them when I run webpack/ts-loader.

**Comment by JonWallsten** [comment]
Fixed by https://github.com/TypeStrong/ts-loader/pull/821
