### ISSUE TITLE
DeclarationBundlerPlugin and Webpack 4.0

### ISSUE THREAD

**Issue by ChrisTalman** [TypeStrong/ts-loader#823]
Is `DeclarationBundlerPlugin` known to work with Webpack 4.0?

I attempted to use it, but it seems to throw an exception of the kind which gets thrown when a plugin isn't compatible with Webpack 4.0. The specific exception [can be read here](https://gist.github.com/ChrisTalman/51e9caa333c8482e32a9608d7f1db194).

**Comment by johnnyreilly** [comment]
Heya, I don't know I'm afraid. It might be worth asking the author of the plugin.

**Comment by ChrisTalman** [comment]
Hey @flyon, if you have a moment, any help would be appreciated.

**Comment by flyon** [comment]
hi @ChrisTalman , havn't been maintaining this library, I'll try to find some time to have a look at it.
in the meanwhile: the deprecation warning is due to the new hooks API, so it should be 
		compiler.hooks.emit.tapAsync('DeclarationBundlerPlugin', (compilation,callback) =>
but the error for `.split()` I'd have to look into it better.
