### ISSUE TITLE
vscode language service type check succeeded. But the webpack build showed error and emitted file worked fine.

### ISSUE THREAD

**Issue by ZSkycat** [TypeStrong/ts-loader#826]
### Environment
```
Window 10
"ts-loader": "^4.5.0",
"typescript": "^3.0.1",
"webpack": "^4.17.1",
```

### What am I doing
I wrote the script part of the `.vue` file in a separate `.ts` file. (Because vue's language service is not perfect)
I am trying to make the `.vue` component have the correct type. I came up with the following two methods:

#### Method A
By tricking the `vscode` language service, the imported file for `vscode` is `*.ts`, but the imported file for `webpack` is `*.vue`. For example:
```
// webpack config. Allow vue extensions to be omitted
resolve: {
    extensions: ['.vue', '.js', '.jsx', '.mjs', '.ts', '.tsx'],
}

// file list
Hello.vue
Hello.ts

// use Hello.vue
import Hello from './Hello';
```

#### Method B
Define a type for a .vue file using a .d.ts file. For example
```
// file list
World.ts
World.vue
World.vue.d.ts

// .d.ts content
export { default } from './World';
```

### Expected Behaviour
Webpack builds successfully and does not output errors.

#### Method A
```
ERROR in D:\issue-ts-loader-20180829\src\component\App.ts
[tsl] ERROR in D:\issue-ts-loader-20180829\src\component\App.ts(4,19)
      TS2307: Cannot find module './Hello'.
```

#### Method B
```
ERROR in D:\issue-ts-loader-20180829\src\component\App.ts
[tsl] ERROR in D:\issue-ts-loader-20180829\src\component\App.ts(17,23)
      TS2339: Property 'world' does not exist on type 'Vue'.
```
#### Method A
In App.ts, comment line 2 and uncomment line 3.
https://github.com/ZSkycat/issue-ts-loader-20180829/blob/master/src/component/App.ts#L2-L3

#### Method B
In App.ts, uncomment line 15.
https://github.com/ZSkycat/issue-ts-loader-20180829/blob/master/src/component/App.ts#L15

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/ZSkycat/issue-ts-loader-20180829
available commands:
```
npm start
npm run build
```

---

I have debugged `enhanced-resolve`, `webpackConfig.resolve.extensions` works fine.
I also tried to debug ts-loader, but I don't know about typescript api, so I can't find the reason.
Sorry, I am not good at English. And I want to get help.

**Comment by johnnyreilly** [comment]
I'm afraid I'm not a Vue user and so I'm not the best person to advise. Could be worth taking the Vue cli for a spin (for TypeScript it uses ts-loader I believe) and see where that lands you.

I'm going to close this issue as (AFAIK) there is no issue with ts-loader.

@herringtondarkholme would you be able to point @ZSkycat to a good resource? You seem to know all things Vue 😉

**Comment by ZSkycat** [comment]
@johnnyreilly vue-cli support for typescript is very bad. I have used it.
This is not a problem with vue, but a problem with typescript type checking.
Especially for `Method B`, ts-loader seems to ignore the type description of `.d.ts`. Maybe related to `appendTsSuffixTo, appendTsxSuffixTo`.
I am very sad to close the issue.

**Comment by ZSkycat** [comment]
@johnnyreilly 
If I want to debug the ts-loader. Can you tell me what documents I should go to first?

**Comment by johnnyreilly** [comment]
If you want to debug ts-loader I think you could probably start by adding `console.log` statements to the code in your `node_modules/ts-loader`; that should probably be enough to give you the information you seek.

**Comment by ZSkycat** [comment]
I want to know the workflow and principle of ts-loader.Or where should I start?
I have tried to perform breakpoint debugging on ts-loader. But I can't understand that ts-loader gives the same file name and text content to typescript, but it has different results.

**Comment by johnnyreilly** [comment]
Very roughly: webpack asks ts-loader to compile a TypeScript module (a file). It does, using the TypeScript compiler, and it hands back webpack the compiled code.

**Comment by HerringtonDarkholme** [comment]
Another solution I found is to use fork-ts-checker-webpack-plugin. It has special logic to handle vue file.

https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/src/VueProgram.ts#L225-L241

@johnnyreilly What's your opinion, would you like to integrate specific frameworks' resolution logic to ts-loader?

**Comment by HerringtonDarkholme** [comment]
I think this might be solved in vue-loader. If the script block is a relative import, vue-loader won't generate a `component.vue.ts` entry in webpack, for which ts-loader is seeking. Instead, it just issues a script import request to that relative src.

If vue-loader can always generate that bridging file, ts-loader can handle relative import as well!

@ZSkycat can you help me open an issue in vue-loader so I won't forget it... (Really busy with work I'm afraid I cannot pick it up)

**Comment by ZSkycat** [comment]
@HerringtonDarkholme 
Vetur provides the correct type export for `.vue`, but Vetur does not support the refactoring of typescript, so I don't use this method.
My other way. https://github.com/vuejs/vue-loader/issues/1281#issuecomment-416712907

---

> Sadly this isn't something we can support. ts-loader's support for SFC is general: that is, it will search for a file only if its name ends with specific pattern. If you omit the vue extension there is no way for ts-loader to distinguish special file.

Sorry, I don't understand very well.
I understand that the omitted extension will be resolved by webpack. 
```
resolve: {
    extensions: ['.vue', '.js', '.jsx', '.mjs', '.ts', '.tsx'],
}
```
When I debug ts-loader, I can see that the file name is with a .vue extension.

When I configure the ts and tsx of module.rules separately, it perfectly supports both cases. (but I don't want to use it).
```
<script lang="ts">
...
</script>
<script lang="tsx">
...
</script>
```
```
{
                    test: /\.ts$/,
                    use: [
                        { loader: 'babel-loader', options: createTsBabelLoaderOptions() },
                        {
                            loader: 'ts-loader',
                            options: { appendTsSuffixTo: [/(\.vue)$/] },
                        },
                    ],
                },
                {
                    test: /\.tsx$/,
                    use: [
                        { loader: 'babel-loader', options: createTsBabelLoaderOptions() },
                        {
                            loader: 'ts-loader',
                            options: { appendTsxSuffixTo: [/\.vue$/] },
                        },
                    ],
                },
```
Files created by vue-loader can be parsed correctly by ts-loader.
https://vue-loader.vuejs.org/guide/custom-blocks.html

---

I don't quite understand this practice.
Vue-loader has generated many new files
- script file block
- script import and export package
- Rendering function
- Assemble rendering functions and scripts, and hot updates
You can see it in sourcemap

**Comment by ZSkycat** [comment]
> I think this might be solved in vue-loader. If the script block is a relative import, vue-loader won't generate a component.vue.ts entry in webpack, for which ts-loader is seeking. Instead, it just issues a script import request to that relative src.

```
ERROR in D:\issue-ts-loader-20180829\src\component\App.ts
[tsl] ERROR in D:\issue-ts-loader-20180829\src\component\App.ts(4,19)
      TS2307: Cannot find module './Hello'.
```

If it is not found because it is looking for './Hello.vue.ts'. Can we change this behavior?
When the type is checked, let it look for './Hello.ts'. But webpack is compiled the way it was.

**Comment by ZSkycat** [comment]
@HerringtonDarkholme You are right!
When I add this file, the compilation no longer outputs an error.

Hello.vue.ts
```
import vue from 'vue';
export default vue;
```

I want to output the type of Hello, but it triggered an error.

```
ERROR in D:\WorkspaceTemp\issue-ts-loader-20180829\src\component\App.ts
[tsl] ERROR in D:\WorkspaceTemp\issue-ts-loader-20180829\src\component\App.ts(6,12)
      TS2344: Type 'App' does not satisfy the constraint '(new (...args: any[]) => Vue) & VueConstructor<Vue>'.
  Type 'App' is not assignable to type 'new (...args: any[]) => Vue'.
    Type 'App' provides no match for the signature 'new (...args: any[]): Vue'.

ERROR in D:\WorkspaceTemp\issue-ts-loader-20180829\src\component\App.ts
[tsl] ERROR in D:\WorkspaceTemp\issue-ts-loader-20180829\src\component\App.ts(19,5)
      TS2416: Property '$refs' in type 'App' is not assignable to the same property in base type 'object & Record<never, any> & Vue'.
  Type '{ c1: Magic; c2: Vue; }' is not assignable to type '{ [key: string]: Vue | Element | Vue[] | Element[]; }'.
    Property 'c1' is incompatible with index signature.
      Type 'Magic' is not assignable to type 'Vue | Element | Vue[] | Element[]'.
        Type 'Magic' is not assignable to type 'Element[]'.
          Property 'length' is missing in type 'Magic'.

ERROR in D:\WorkspaceTemp\issue-ts-loader-20180829\src\component\Hello.vue.ts
[tsl] ERROR in D:\WorkspaceTemp\issue-ts-loader-20180829\src\component\Hello.vue.ts(2,15)
      TS2506: 'Magic' is referenced directly or indirectly in its own base expression.
```

**Comment by ZSkycat** [comment]
Maybe we have a chance to fool the type check. Do you have any opinion? @johnnyreilly

**Comment by ZSkycat** [comment]
@HerringtonDarkholme 
I found a more appropriate method, thank you for reminding me.

We only need to spoof the IDE's language service to achieve the goal. For example:

Demonstrates Repository: https://github.com/ZSkycat/issue-ts-loader-20180829/tree/better

Hello.vue
```
<template>
    <div><h1>Hello</h1></div>
</template>

<script src="./Hello.vue.ts"></script>
```

Hello.vue.ts
```
import { Component, Vue } from 'vue-property-decorator';

@Component<Hello>({
    name: 'Hello',
})
export default class Hello extends Vue {
    hello() {
        console.log('hello!');
    }
}
```

Used in ts file
```
import Hello from './Hello.vue';
```

The most important thing is the naming of the ts file.
- For vscode, './Hello.vue' points to './Hello.vue.ts'
- For webpack, './Hello.vue' points to './Hello.vue' and does not trigger type checking errors

**Comment by johnnyreilly** [comment]
> @johnnyreilly What's your opinion, would you like to integrate specific frameworks' module resolution logic to ts-loader?

I'm not that keen on doing this as it doesn't feel like it "fits" as a responsibility for ts-loader. More relevantly, I'm hesitant about making ts-loader need to evolve as Vue does.

That said, if the change isn't too invasive then I'd consider it. Though the vue-loader solution sounds more promising. I'm also open to having a hook in ts-loader which allows people to add their own custom resolution logic, this could be used to support Vue and anyone else who wanted to play.

As with most things I think it's good if someone wants to submit a PR and we can use that as a basis for discussion / collaboration. 

Don't worry about tests initially; I can help with that.

**Comment by HerringtonDarkholme** [comment]
>  I'm also open to having a hook in ts-loader which allows people to add their own custom resolution logic, this could be used to support Vue and anyone else who wanted to play.

That's definitely a better solution. I would like to see ts-loader's support for ts-plugin.

**Comment by johnnyreilly** [comment]
Go for it!
