### ISSUE TITLE
not emitting declaration files for `.d.ts` files

### ISSUE THREAD

**Issue by veeramarni** [TypeStrong/ts-loader#833]
### Expected Behaviour
Emit declaration file for simple interface ts file.
### Actual Behaviour
No `index.d.ts` file generated
### Steps to Reproduce the Problem
Try to run in on a package with just in Interface in it.
### Location of a Minimal Repository that Demonstrates the Issue.

This issue happens in `5.0.0` only, I don't see this issue in `4.0.0`

**Comment by johnnyreilly** [comment]
@jonwallsten - could this be a side effect of the changes that shipped with 5.0.0 do you think?

**Comment by JonWallsten** [comment]
@johnnyreilly No. And I couldn't reproduce. @veeramarni Have you adjusted the path so it's relative to the root and not the webpack outdir? I got an index.d.ts file, but in a different place.

**Comment by shadygrove** [comment]
I was experiencing the same with ts-loader 5.1.1

Eventually, I removed the outDir from my tsconfig file and set it in my webpack ts-loader config...

const dist = path.resolve(process.cwd(), '_dist');

{
    loader: 'ts-loader',
    options: {
        configFile: TS_CONFIG_PATH,
        compilerOptions: {
            outDir: path.join(dist, 'typings')
        }
    }
}

End result was typings in my _dist
_dist
----/typings

**Comment by JonWallsten** [comment]
@shadygrove That's weird. The code is really straight forward. It should end up at the path TypeScript has generated. The only thing the loader does is calculate a relative path from the Webpack outdir instead of using the absolute path that TS provides. You would have to add some log statements and log the output for us to figure this out. It should work out of the box, so there seems to be a version/environment issue.

**Comment by shadygrove** [comment]
@JonWallsten yes you may very well be right.  I got it working with the above and thought it might help others who may have a unique setup and struggling to get the output path correct.  

So to clarify, our compilation is likely "outside-the-box" as we are running grunt-webpack to integrate webpack with existing build processes, and using webpack-merge to separate dev/prod/test configs, and various plugins.  

some of those versions are...
    "webpack": "^4.6.0",
    "webpack-dev-server": "3.1.6",
    "webpack-merge": "^4.1.2",
    "grunt": "1.0.3",
    "grunt-webpack": "^3.1.1"

**Comment by JonWallsten** [comment]
@shadygrove I see. Let's find out. Please make the following change to `node_modules/ts-loader/dist/after-compile.js:142` and send back a part of the log. 
Should be easy to figure out whats happening.
```js
function provideDeclarationFilesToWebpack(filesToCheckForErrors, instance, compilation) {
    for (const filePath of filesToCheckForErrors.keys()) {
        if (!filePath.match(constants.tsTsxRegex)) {
            continue;
        }
        const outputFiles = instances_1.getEmitOutput(instance, filePath);
        const declarationFiles = outputFiles.filter(outputFile => outputFile.name.match(constants.dtsDtsxOrDtsDtsxMapRegex));
        declarationFiles.forEach(declarationFile => {
            console.log('Declaration file: ', declarationFile);
            console.log('Output path: ', compilation.compiler.outputPath);
            const assetPath = path.relative(compilation.compiler.outputPath, declarationFile.name);
            console.log('Assets path: ', assetPath);
            console.log('-----------------');
            compilation.assets[assetPath] = {
                source: () => declarationFile.text,
                size: () => declarationFile.text.length
            };
        });
    }
}
```

**Comment by veeramarni** [comment]
I still have the issue, `.d.ts` are generated on a different directory.

@JonWallsten here is the output

```
Declaration filename:  /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/lib/index.d.ts
Output context:  /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/browser
Output path:  /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/browser/lib
Assets path:  ../../lib/index.d.ts
-----------------
```

**Comment by veeramarni** [comment]
seems like the below configuration working.

```
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "declarationDir": "lib",
    "rootDir": "./src",
    "outDir": "../lib",
  },
```

**Comment by JonWallsten** [comment]
> I still have the issue, `.d.ts` are generated in a different directory.
> 
> @JonWallsten here is the output
> 
> ```
> Declaration filename:  /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/lib/index.d.ts
> Output context:  /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/browser
> Output path:  /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/browser/lib
> Assets path:  ../../lib/index.d.ts
> -----------------
> ```

Sorry, I'm a bit out of context since this happened a long time ago. But it seems like your path settings are a bit of. The output path contains 'browser' but the declaration doesn't.

The relative path for to the declaration file from this directory `/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/packages-modules/counter/browser/lib` is `../../lib/index.d.ts`. So the output seems correct.
