### ISSUE TITLE
module resolution in ts-loader 

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#84]
Hello!

I've just been in the process of porting [globalize-so-what-cha-want](https://github.com/johnnyreilly/globalize-so-what-cha-want/) across to use webpack and ts-loader (previously they used browserify and tsify).  

Some background, this repo contains 2 things:

1. A small npm package which exposes a utility written in TypeScript. The unit tests are set up to run using Karma combined with Browserify / TSIFY
2. A front end that demos the utility written in ES6 (combined with Babel) using React.

I haven't started on the main job yet which is porting the ES6 / React code across to use TypeScript (2.) combined with Webpack / ts-loader.  For now I've restricted myself to moving the unit testing across to using Karma combined with Webpack / ts-loader.

I stumbled upon a peculiarity.  The first line in my test file looks like this:

```
import { determineRequiredCldrData, determineRequiredCldrGlobalizeFiles } from '../../src/lib/index';
```

This points to the source of the main utility (1.).  Using Browserify / tsify this was picked up without problem.  However with Webpack / ts-loader I get this:

```
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  Error: Cannot find module "../../src/lib/index"
  at C:/source/globalize-so-what-cha-want/test/lib/index.tests.ts:49
```

This is peculiar. If I run tsc on `index.tests.ts` itself it compiles without issue.

Is there any reason you can think of why ts loader would have different behaviour around module resolution?  I have managed to work around the issue for now by amending the import as follows:

```
import { determineRequiredCldrData, determineRequiredCldrGlobalizeFiles } from '../../';
```

The root of the repo contains the compiled output of `../../src/lib/index` (complete with `index.d.ts` file).  And so I've managed to run the unit tests with Webpack / ts loader successfully this way. 

But I remain mystified as to why ts-loader would not resolve something that tsify / tsc would.  Or why ts loader could resolve to the root of the repo but not to `src/lib/index`. Do you have any idea?  

BTW the source of this code is still on my machine but I can share it if that would help.  (I'm likely going to move the whole repo across from using Browserify to using Webpack anyway)

**Comment by johnnyreilly** [comment]
I'm impatient.  That's me.  I've switched the repo to use ts-loader and it's been uploaded.  To see how it was with tsify look [here](https://github.com/johnnyreilly/globalize-so-what-cha-want/tree/v0.9.2), to see how it looks with ts-loader look [here](https://github.com/johnnyreilly/globalize-so-what-cha-want/)

**Comment by jbrantly** [comment]
Hey John,

The issue is with your karma config; specifically, your [webpack config is not being fully brought over from `webpack.config.js`](https://github.com/johnnyreilly/globalize-so-what-cha-want/blob/master/karma.conf.js#L30-L34) which means that webpack is not configured to resolve `.ts` which means it doesn't find the module.

**Comment by johnnyreilly** [comment]
Aha!  Thanks @jbrantly - will amend and report back

**Comment by johnnyreilly** [comment]
Yes - that's it.  I needed `resolve` as well as module in my `webpack` section of `karma.conf.js`.  Interestingly (frustratingly) bringing across everything from `webpack.config.js` actually kills Karma stone dead.  My happy `webpack.config.js` looks like this:

```js
/* eslint-disable no-var, strict */
'use strict';

var webpackConfig = require('./webpack.config.js');

module.exports = function(config) {
  // Documentation: https://karma-runner.github.io/0.13/config/configuration-file.html
  config.set({
    browsers: [ 'PhantomJS' ],

    files: [
      'src/demo/dependencies.js', // This ensures we have the es6 shims in place from babel
      'test/**/*.tests.ts'
    ],

    port: 9876,

    frameworks: [ 'jasmine', 'phantomjs-shim' ],

    logLevel: config.LOG_INFO, //config.LOG_DEBUG

    preprocessors: {
      'src/**/*.{js,ts,tsx}': [ 'webpack', 'sourcemap' ],
      'test/**/*.tests.ts': [ 'webpack', 'sourcemap' ]
    },

    webpack: {
      devtool: 'inline-source-map',
      debug: true,
      module: webpackConfig.module,
      resolve: webpackConfig.resolve
    },

    webpackMiddleware: {
      quiet: true,
      stats: {
        colors: true
      }
    },

    // reporter options
    mochaReporter: {
      colors: {
        success: 'bgGreen',
        info: 'cyan',
        warning: 'bgBlue',
        error: 'bgRed'
      }
    },

    // the default configuration
    junitReporter: {
      outputDir: 'test-results', // results will be saved as $outputDir/$browserName.xml
      outputFile: undefined, // if included, results will be saved as $outputDir/$browserName/$outputFile
      suite: ''
    },
  });
};
```

**Comment by johnnyreilly** [comment]
PS I'll try and blog about this at some point to spread the knowledge.

**Comment by johnnyreilly** [comment]
Resolved by https://github.com/johnnyreilly/globalize-so-what-cha-want/commit/f9325ae882c09382365db0cad3ec3f8e3fa3190f
