### ISSUE TITLE
Cannot find module .vue single 

### ISSUE THREAD

**Issue by LY1993** [TypeStrong/ts-loader#845]
webpack:

```
{
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        ts: 'babel-loader!ts-loader',
                        tsx: 'babel-loader!ts-loader'
                    }
                }
            }
```
test.vue: 

```
<template>
    <div>hhhh</div>
</template>
<script>
export default {
    name: 'ttt'
}
</script>

```
app.vue:

```
import ttt from '../components/test.vue';
```
Cannot find module '../components/test.vue'.

if i add `lang='ts'` that is ok
### Actual Behaviour

Cannot find module '../components/test.vue'.

**Comment by johnnyreilly** [comment]
I don't believe this is an issue with ts-loader. However I'm not a Vue user and so can't advise. I recommend checking out the vue-cli which uses ts-loader under the covers
