### ISSUE TITLE
Clarification on Project references with webpack watch

### ISSUE THREAD

**Issue by jordond** [TypeStrong/ts-loader#846]
I'm looking for clarification on how to run webpack --watch with TS project references.

I followed the instructions in the [README](https://github.com/TypeStrong/ts-loader#projectreferences-boolean-defaultfalse), and added `WatchIgnorePlugin` targeting `.js` and `.d.ts` files.

Now when I run `webpack --watch` and in a seperate terminal run `tsc --build --watch`, and make a change to one of the dependents, webpack never rebuilds because it's ignoring the compiled outputs.

So I'm just wondering the proper way to watch the referenced projects, and have webpack rebuild.

If I remove the WatchIgnore plugin, then webpack will rebuild multiple times, only stopping when `tsc` has finished building the changes.  I have tried offseting this by adding

```
watchOptions: {
  aggregateTimeout: 5000
}
```

and adjusting the timeout, but it's more of a hack and isn't guarenteed to only reload once.

**Comment by johnnyreilly** [comment]
@andrewbranch what's your view on this scenario?

**Comment by jordond** [comment]
I have done some further testing, and found that my problem is I'm using path aliases in my root `tsconfig.json`:


```json
./tsconfig.json
...
"baseUrl": ".",
"paths": {
  "@lib/*": ["lib/*"]
}
...
```

inside `./lib` I have all of the shared projects (all composite projects).

Then I have a folder `./packages` which contains the projects that consume the `lib`.  They are the ones using webpack to build.

Now in one of the `./packages` projects I changed the import from `@lib/core` to `../../../lib/core`.  I enabled the WatchIgnorePlugin, then ran (in seperate terminals) `tsc --build --watch` and `webpack --watch`, and everything reloaded fine.

So the problem seems to be with using aliased imports.  The problem is, I'd really rather not change everything over to relative imports, because with the folder structure I can see it becoming a bit rediuclous.

**Comment by andrewbranch** [comment]
Hm, interesting... this sounds like good justification for building the ability to recompile upstream projects into ts-loader, where we’ll have pretty tight control over which files are getting watched. I  think the `aggregateTimeout` sounds like a good workaround in the meantime. I don’t think there’s anything ts-loader can do about it until ts-loader can rebuild projects, but this is a great thing to look out for if/when we implement that. @johnnyreilly sound reasonable to you?

**Comment by johnnyreilly** [comment]
Yeah sounds completely reasonable @andrewbranch!

Actually @jordond if you wanted submit a docs PR suggesting this as an interim solution that might be a good idea. Doubtless other people are attempting similar and so sharing your workaround seems like it could be beneficial.

Thanks for posting it!

**Comment by johnnyreilly** [comment]
See https://github.com/TypeStrong/ts-loader/issues/851

**Comment by Bnaya** [comment]
TypeScript 3.3 supports incremental build with composite projects
https://github.com/Microsoft/TypeScript/wiki/Roadmap#33-january-2019

**Comment by seawatts** [comment]
@jordond Was there any resolution to this?
