### ISSUE TITLE
Documentation on how to use output of customTransformers

### ISSUE THREAD

**Issue by martinmckenna** [TypeStrong/ts-loader#849]
### Expected Behaviour

It would be great if there was some documentation on how to get the output of what is returned from a custom transformer, so that it could be outputted to a newly created file.

My use-case for this is that I am using a custom transformer to aggregate data into a large object, which then I would then like to output into a JSON file. My only issue is that I'm not really sure how to get the results of the data from this transformer (or any for that matter)

Also, what does the syntax look like for passing a file string to the customTransformer?

**Comment by johnnyreilly** [comment]
Feel free to write some docs for us!

For reference you may want to consult our test pack:

https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/customTransformer

https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/customTransformerUsingPathString
