### ISSUE TITLE
Warn if webpack is not configured with correct file extension resolutions

### ISSUE THREAD

**Issue by jbrantly** [TypeStrong/ts-loader#85]
Inspired by #84, it might make sense to check the webpack `resolve.extensions` and make sure all supported **& loaded** extensions are configured. If not, emit a webpack warning.

For example, if webpack is configured to resolve `.ts` and only `.ts` is ever loaded into the language service then no warning should be emitted. However, if webpack is only configured to resolve `.ts` and a `.tsx` file is loaded into the language service we should emit a warning.

**Comment by johnnyreilly** [comment]
Excellent idea!

**Comment by johnnyreilly** [comment]
Hey @jbrantly,

I'm happy to say that I've now completely ported [globalize-so-what-cha-want](https://github.com/johnnyreilly/globalize-so-what-cha-want) to TypeScript using ts-loader for the build with Webpack.  

And so I wanted to say "THANKYOU!!!!" for your work on ts-loader.

Although globalize-so-watcha-want is really just a small side project I've been deliberately using it as a testing bed for having a set up which allows me to:

- write TypeScript code in Atom using Atom-TypeScript (crucially without Atom actually performing the transpilation)
- write React with JSX using TypeScript
- write Jasmine tests in TypeScript
- write unit tests featuring JSX using TypeScript
- have my code type checked by TypeScript, emitted as ES6 and transpiled by Babel
- have Karma run my unit tests continually (watching files)

All this is now done, all this now works.  YAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This might seem like extreme excitement but I completely failed to get this up and running with Browserify / TSIFY and so I am very pleased indeed!

I intend to blog about this and share the knowledge.  But for now, thank you very very much indeed.

All the best,
John

PS @basarat you might be interested to know about this.  I am now team webpack :smile:

**Comment by basarat** [comment]
> PS @basarat you might be interested to know about this. I am now team webpack

Sweet as. PS my work on an ultra portable TypeScript only IDE that can work anywhere (where node is present) is coming along nicely :) 

![image](https://cloud.githubusercontent.com/assets/874898/10714606/96e33f6c-7b4a-11e5-8509-6f4c63ed1301.png)

I'll be sure to add everyone once I can use it as my main day to day tool ... fingers crossed ... it might be a few months away still :rose:

**Comment by johnnyreilly** [comment]
Niiiiiiiiiceee!!!!  Given the portability of atom / vscode what made you build another?  Does it do something the others don't? 

Question: the `compileOnSize` flag that atom-typescript relies upon.  Did that ever get standardized? Or is it atom-typescript specific?

```
{
    "compileOnSave": false,
}
```

**Comment by jbrantly** [comment]
@johnnyreilly Awesome to hear! Thanks for the feedback.

**Comment by basarat** [comment]
@johnnyreilly glad you asked :)

> Given the portability of atom / vscode what made you build another? Does it do something the others don't

*Big one*: I wanted an IDE that was *focused* on typescript development like nothing out there .... a playing field where TypeScript is king (you have to respect the desires of other language developers when making an atom plugin) 

*Key difference in design* (why not extend vscode or atom further) : This IDE is easy to install `npm install tsb -g`. So you can use dable in it easily with zero commitment (unlike atom / vscode). And use it on your build / deploy server as well.

There are just soo many reasons : https://github.com/TypeScriptBuilder/tsb/tree/master#why and https://github.com/TypeScriptBuilder/tsb/blob/master/docs/contributing/why.md

But in the end .... its because I wanted more control ... atom keeps changing things under me (and I completely understand and respect that ... but still wanted something stable :rose: :)

**Comment by basarat** [comment]
> Question: the compileOnSize flag that atom-typescript relies upon. Did that ever get standardized? Or is it atom-typescript specific?

Still atom-typescript specific. Don't see it getting standardized :-/

**Comment by basarat** [comment]
@johnnyreilly I've moved the reasons around so now they are up front : https://github.com/TypeScriptBuilder/tsb/blob/master/README.md and categorized in the `why` section : https://github.com/TypeScriptBuilder/tsb/blob/master/docs/contributing/why.md
