### ISSUE TITLE
ts-loader project references "build" support

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#851]
[`ts-loader` has partial support for project references](https://blog.johnnyreilly.com/2018/09/ts-loader-project-references-first-blood.html) in that it will load dependent composite projects that are already built, but will not currently build/rebuild those upstream projects. We don’t want to keep it that way; this issue has been opened to track ts-loader triggering the building/rebuilding of upstream projects.

Copied from https://github.com/TypeStrong/ts-loader/issues/815#issuecomment-427608220 by @andrewbranch:

Small status update: I spent an hour or so this morning exploring the current state of the tsbuild API to see if it contains what we need for ts-loader to build/watch upstream projects. It mostly does, but currently the API isn't finalized and the whole thing is marked internal: https://github.com/Microsoft/TypeScript/blob/85a3475df87b9c10240570f32090970262c99b54/src/compiler/tsbuild.ts#L1-L2

I think ts-loader’s full support for project references will have to wait until that’s finalized, lest we get broken by minor or patch TypeScript releases.

@sheetalkamat, two things:

1. Would you be able to share with us whether that API is imminent, or more of a longer term goal?
2. The thing that ts-loader needs to be able to do, eventually, is build every dependency of a project, but not that project itself. After a little exploring this morning, it looks like the way to do that (in the hypothetical world where today’s internal APIs are final) is currently something like:

```js
const project = path.resolve('./tsconfig.json'); // “Root” project, has dependencies
const builder = ts.createSolutionBuilder(host, [project], {});
const { buildQueue } = builder.getBuildGraph([project]);

// buildQueue is an array of paths to tsconfig files, in the order that they need to be built.
// That means our “root” project is the last element in the array. We want to build every
// project _except_ that one.
const projectsIWantToBuild = buildQueue.slice(0, buildQueue.length - 1);
const dependencyBuilder = ts.createSolutionBuilder(host, projectsIWantToBuild, {});
dependencyBuilder.buildAllProjects();
```

I realize all this is still in flux, so I just wanted to give you an idea of the functionality we’ll need here, since it’s not the typical case of running a solution build programmatically. At the moment, it feels a little kludgy to have to create two SolutionBuilders. Might there be a way in the future to build all projects with a filter, or simply to build all dependencies of a project? Thanks for all your work on this!

cc @RyanCavanaugh @rbuckton

**Comment by johnnyreilly** [comment]
Thanks so much for that @sheetalkamat!

cc @andrewbranch

**Comment by andrewbranch** [comment]
Hey @sheetalkamat, any update on this? I realize you probably can't promise a timeline, but I just wanted to make sure we still have hope to keep this issue alive. 🙂 Thanks!

**Comment by sheetalkamat** [comment]
Microsoft/TypeScript#28640 tracks this and it would be a while before API is public as we work through the perf issues and shape it accordingly.

**Comment by Bnaya** [comment]
TypeScript 3.3 supports incremental build with composite projects
https://github.com/Microsoft/TypeScript/wiki/Roadmap#33-january-2019

**Comment by kirillonufreinko** [comment]
Is there any work in progress on this or the issue was put on hold?

**Comment by johnnyreilly** [comment]
I'm not working on it... It's possible @andrewbranch may be but I don't know

**Comment by andrewbranch** [comment]
This is still the current status: https://github.com/TypeStrong/ts-loader/issues/851#issuecomment-443778966

It should be something that's possible in the future, just not quite yet. Thanks for your patience, everyone 🌟

**Comment by styfle** [comment]
It looks like TS just added support

- Issue: https://github.com/microsoft/TypeScript/issues/28640
- PR: https://github.com/microsoft/TypeScript/pull/31432

**Comment by kukjevov** [comment]
Anything new here ?

**Comment by kirill-konshin** [comment]
TypeScript 2.6 has API support for this: https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#apis-to-support-build-and-incremental

https://github.com/TypeStrong/ts-loader/issues/913 this is a similar issue

**Comment by andrewbranch** [comment]
#935 should fix this.
