### ISSUE TITLE
ng-packagr -p ng-packag.json through error

### ISSUE THREAD

**Issue by Amaf-Consultants** [TypeStrong/ts-loader#852]
tsconfig.ts file

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017", 
			"dom"
    ]
  }
}
-------------------
Angular version 
 "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",

----------------- 

npm run packagr

> new-component-library@1.0.0 packagr /Users/ali/Ali-WorkSpace/Angular_Library/new-component-library
> ng-packagr -p ng-package.json

Building Angular Package
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'esnext.asynciterable'.

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! new-component-library@1.0.0 packagr: `ng-packagr -p ng-package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the new-component-library@1.0.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ali/.npm/_logs/2018-10-07T16_02_48_056Z-debug.log
-------------------

Log File

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'packagr' ]
2 info using npm@5.6.0
3 info using node@v9.9.0
4 verbose run-script [ 'prepackagr', 'packagr', 'postpackagr' ]
5 info lifecycle new-component-library@1.0.0~prepackagr: new-component-library@1.0.0
6 info lifecycle new-component-library@1.0.0~packagr: new-component-library@1.0.0
7 verbose lifecycle new-component-library@1.0.0~packagr: unsafe-perm in lifecycle true
8 verbose lifecycle new-component-library@1.0.0~packagr: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ali/Ali-WorkSpace/Angular_Library/new-component-library/node_modules/.bin:/Users/ali/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/ali/.cargo/bin
9 verbose lifecycle new-component-library@1.0.0~packagr: CWD: /Users/ali/Ali-WorkSpace/Angular_Library/new-component-library
10 silly lifecycle new-component-library@1.0.0~packagr: Args: [ '-c', 'ng-packagr -p ng-package.json' ]
11 silly lifecycle new-component-library@1.0.0~packagr: Returned: code: 111  signal: null
12 info lifecycle new-component-library@1.0.0~packagr: Failed to exec packagr script
13 verbose stack Error: new-component-library@1.0.0 packagr: `ng-packagr -p ng-package.json`
13 verbose stack Exit status 111
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid new-component-library@1.0.0
15 verbose cwd /Users/ali/Ali-WorkSpace/Angular_Library/new-component-library
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/9.9.0/bin/node" "/usr/local/bin/npm" "run" "packagr"
18 verbose node v9.9.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 111
22 error new-component-library@1.0.0 packagr: `ng-packagr -p ng-package.json`
22 error Exit status 111
23 error Failed at the new-component-library@1.0.0 packagr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 111, true ]

-----------------

Any Idea why I am having this issue

**Comment by johnnyreilly** [comment]
It should be `tsconfig.json` not `tsconfig.ts`

**Comment by Amaf-Consultants** [comment]
Thanks for the  quick ans.  I don't have tsconfig.ts except tsconfig.json. Do I need to create one ?
I created ng new project and and now creating lib. I m little new to this.  I am following this 
https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e

**Comment by johnnyreilly** [comment]
Sorry I'm afraid I'm no expert on the angular cli
