### ISSUE TITLE
importHelpers not working

### ISSUE THREAD

**Issue by canemacchina** [TypeStrong/ts-loader#859]
I'm unable to use` importHelpers` feature from typescript.
I'm using:

- tslib: 1.9.3
- webpack: 4.20.2
- ts-loader: 5.2.2

What I've done is:
- install tslib
- add `"importHelpers": true,` into `compilerOptions` section of my `tsconfig.json`

Simply running tsc show that function llike `__extends` are required from tslib.
Compiling with webpack using ts-loader seems not.
This is my ts-node configuration:
```
test: /\.ts$/,
exclude: /node_modules/,
use: [
    { loader: 'cache-loader' },
    {
        loader: 'ts-loader',
        options: {
            reportFiles: ['src/**/*.ts']
        }
    }
]

```

What I've missing?

Thanks

**Comment by canemacchina** [comment]
No sorry, my mistake.
`importHelpers` is currently working, the strange behaviour is that is working even if `importHelpers` is `true` or `false` on tsconfig.json...
Why?

**Comment by awk** [comment]
I have a similar problem (importHelpers: "true" in tsconfig.json) - the same code (same git SHA) and versions of tools (webpack 4.27.1 ts-loader 5.4.5) produces two different versions of the commons chunk. 

In one case all the helpers are resolved using an imported tslib, in the other case tslib is never imported and all the helpers are directly placed into the output code. There are no other differences in the commons.js chunk. One has 
```
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = __webpack_require__(0);
…
var ConnectionAppender = /** @class */ (function (_super) {
    tslib_1.__extends(ConnectionAppender, _super);
```

the other has 

```
/***/ (function(module, exports, __webpack_require__) {

"use strict";

var __extends = (this && this.__extends) || (function () {
…
})();
Object.defineProperty(exports, "__esModule", { value: true });
…
/**
 * A log4javascript appender that sends its messages down the websocket
 */
var ConnectionAppender = /** @class */ (function (_super) {
    __extends(ConnectionAppender, _super);
```

And so on throughout the commons.js chunk.

I'm not using thread-loader, cache-loader or the happyPack option (or an minification)

**Comment by awk** [comment]
You can leave this closed (I think).

I believe my problem was actually with thread-loader and multiple tsconfig.json files in my tree. thread-loader started a ts-loader instance where the resourcePath was pointing at a folder with a different (no importHelpers option) tsconfig.json . It looks like all the compilation in that thread was using that (inappropriate) tsconfig.json and leading to seeing a lack of importHelpers taking effect.

I'm pretty sure I saw one instance of importHelpers not taking effect when thread-loader was disabled - but I can't reproduce it now and examining the ts-loader code for finding the config file I can see no way other than the above explanation as to how it either missed the tsconfig file or got the wrong one.
