### ISSUE TITLE
Need ts.Program or Language Service to create CustomTransformers

### ISSUE THREAD

**Issue by xiaoxiangmoe** [TypeStrong/ts-loader#860]
### Expected Behaviour

```getCustomTransformers ( (service.LanguageService) => { before?: TransformerFactory[]; after?: TransformerFactory[]; } )```
### Actual Behaviour
```getCustomTransformers ( () => { before?: TransformerFactory[]; after?: TransformerFactory[]; } )```

### Steps to Reproduce the Problem
none
### Location of a Minimal Repository that Demonstrates the Issue.
none

----

see [awesome-typescript-loader](https://github.com/kimamula/ts-transformer-keys#webpack-with-awesome-typescript-loader) or [rollup](https://github.com/kimamula/ts-transformer-keys#rollup-with-rollup-plugin-typescript2)

**Comment by johnnyreilly** [comment]
Hi, I'm not completely clear what the change you're after is? Would you like to submit a PR and we can discuss it further?

**Comment by johnnyreilly** [comment]
Cool - do you want to submit a PR?

**Comment by xiaoxiangmoe** [comment]
Ok, I'll do it latter.

**Comment by nohira** [comment]
Looking forward to this as I want to use ts-transformer-keys.
