### ISSUE TITLE
TypeError: Cannot read property '<any property>' of undefined when transpileOnly is true

### ISSUE THREAD

**Issue by GalmWing** [TypeStrong/ts-loader#863]
I'm trying to speed up my build, and ts-loader seems to be the biggest offender by far, the docs recommend trying `transpileOnly: true, happyPackMode: true` + happyPack or thread-loader.
But every time I do that my code will fail immediately with the error on the title `TypeError: Cannot read property <x> of undefined`.
I'm thinking some part of the code needs the definition files, which would be the part that transpileOnly is omitting. So right now I'm stuck with super slow ts-loader builds and no way of using parallelization.

**Comment by johnnyreilly** [comment]
I recommend checking out an example repo like this: https://github.com/TypeStrong/ts-loader/tree/master/examples/thread-loader

And applying the pattern to your build.  This uses `thread-loader` and `fork-ts-checker-webpack-plugin` and should be pretty fast.

Do try that out and report back!  I'm going to close this as it's not an issue with ts-loader by the sounds of it.

**Comment by GalmWing** [comment]
I did try doing it the exact same way. But I now realized what actually triggers the errors. There is an option in thread-loader to preload the workers `threadLoader.warmup()` removing that gets rid of the `TypeError: Cannot read property`. I'm really not sure why but I get consistent repro by adding or removing that warmup, if I use them in tandem with ts-loader + babel-loader.

**Comment by johnnyreilly** [comment]
Interesting - I've never tried to use `warmup` - presumably that's not compatible with ts-loader. I don't know why.
