### ISSUE TITLE
How to use current directory tsconfig.json?

### ISSUE THREAD

**Issue by VictorQueiroz** [TypeStrong/ts-loader#865]
I currently have two folders `src` and `sw` (which would be a different environment, in this case a service worker) and I want to use different tsconfig.json files for each folder. Although ts-loader picks one tsconfig.json file, ignore the other and then use the picked one to compile all files of both directories. How can I fix that behavior? I have a different tsconfig.json file inside each of these projects.

Sorry if this is a duplicate, I already searched a few issues in this repository but none of them fixed my problem.

**Comment by johnnyreilly** [comment]
I suspect you want to run 2 different instances of ts-loader. Use this: https://github.com/TypeStrong/ts-loader/blob/master/README.md#instance-string

Usage looks something like this: https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/instance/webpack.config.js

(Above file is a test file and so has some differences from a typical config)

**Comment by AlexLeung** [comment]
Related to #926. @johnnyreilly you pointed out that @VictorQueiroz should use 2 different instances, but he also asked how we can use a **different tsconfig for each instance**.

**Comment by johnnyreilly** [comment]
Does this help? https://github.com/TypeStrong/ts-loader/blob/master/README.md#configfile-string-defaulttsconfigjson

**Comment by AlexLeung** [comment]
Yes thanks.
I guess I had a misunderstanding about webpack. It seems like this only allows me to provide rules for the various entry files. How would I use different tsconfigs for the transitive dependency files?
