### ISSUE TITLE
"Module parse failed: Unexpected token" when added the class field

### ISSUE THREAD

**Issue by TokugawaTakesi** [TypeStrong/ts-loader#867]
Works: 

```
export default class ConfigRepresentative {
  constructor() {
    console.log('ok');
  }
}
```

Fails (same if to remove `private` and `static`): 

```
export default class ConfigRepresentative {

  private static ownInstanceHasBeenCreated: boolean = false;

  constructor() {
    console.log('ok');
  }
}
```

Error:

```
ERROR in ./TypeScriptSource/index.ts 7:10
Module parse failed: Unexpected token (7:10)
You may need an appropriate loader to handle this file type.
| export default class ConfigRepresentative {
| 
>   private static ownInstanceHasBeenCreated: boolean = false;
| 
|   constructor() {

```

webpack.config.js

```
module.exports = {

  entry: './TypeScriptSource/index.ts',
  output: {
    filename: 'index.js',
    path: __dirname,
    libraryTarget: 'umd'
  },

  target: 'node',
  mode: 'production',
  watch: true,

  module: {
    rules: [
      {
        test: /\.ts?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js']
  }
};
```

For saving your time on reproducing this problem, I attached the souse files.
[error.zip](https://github.com/TypeStrong/ts-loader/files/2567961/error.zip)

**Comment by TokugawaTakesi** [comment]
Found the reason.
[“Module parse failed: Unexpected token” when added the class field.](https://stackoverflow.com/questions/53313863/module-parse-failed-unexpected-token-when-added-the-class-field/53314090#53314090)

**Comment by kuangshp** [comment]
Finally, how do you solve it, I also encountered the same problem.

**Comment by TokugawaTakesi** [comment]
I solve it by stopping to develop sublibraries directly in `node_modules`...

**Comment by surferwat** [comment]
@TokugawaTakesi I got the same error. I wrote a node module in typescript and installed into my nextjs app, but when I went to run the app, it triggered the "module parse failed" error. Were you able to find a solution other than avoiding writing in node_modules sublibraries?

[why-does-my-typescript-node-module](https://stackoverflow.com/questions/66556602/why-does-my-typescript-node-module-when-installed-into-my-nextjs-app-trigger-a)

**Comment by TokugawaTakesi** [comment]
@surferwat [Lerna](https://github.com/lerna/lerna), for example. Not ideal solution, but at least it solves above problem.

Other developers using Yarn workspaces, but I has not tried it.

**Comment by surferwat** [comment]
Thanks. I'm developing in Next.js. I was able to resolve the issue by changing the webpack configuration in my `next.config.js` file, as follows: 

```
webpack(config, options) {
    config.module.rules.push({
        test: /\.(ts)x?$/, // Just `tsx?` file only
        use: [
            {
                loader: "ts-loader",
            },
        ],
    });
    return config;
}
```

Reference: [How to load libraries which export Typescript in next.js](https://stackoverflow.com/questions/64989575/how-to-load-libraries-which-export-typescript-in-next-js)

**Comment by TokugawaTakesi** [comment]
I am glad about you solved this problem for you case.

Just let me to share my experience.
I understood that the development inside `node_modules` is unnatural from the viewpoint of NodeJS.
It's easy too lose it and hard to manage.

Current working alternatives are Lerna and Yarn workspaces. 
Maybe it's possible to refer the dependence in `package.json` to local repository, but I don't sure that we can keep the dependence up-date by this way.
