### ISSUE TITLE
[Question] Build webpack with module in node_modules still typescript

### ISSUE THREAD

**Issue by kimthangatm** [TypeStrong/ts-loader#870]
I build fail when I updated to use ts-loader@5 with webpack4 (ts-loader@3 with webpack3 build success)

I use rushjs.io, it will helps us to to link library in local,
I write library in ts and not build its to js. In main app, I import ts library to use and webpack cannot build link module.

Eg:

libraries: my-utilities and package.json/main => "src/index.`ts`"
app/: import { functionA } from 'my-utilities';

```
ERROR in /Users/abc/Desktop/project/libraries/my-utilities/src/index.ts
Module build failed (from /Users/abc/Desktop/project/common/temp/node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/abc/Desktop/project/libraries/my-utilities/src/index.ts.
```

**Comment by JonWallsten** [comment]
@kimthangatm I guess you'd probably figured it out by now, since it's in the documentation. But for people in the future finding this issue:
**In you webpack config:**
```
  {
    test: /\.ts$/,
    loader: 'ts-loader',
    options: { allowTsInNodeModules: true }
  }
```
**And in you tsconfig file:**
```
 {
    "include": [
      "node_modules/whitelisted_module.ts"
    ],
    "files": [
      "node_modules/my_module/whitelisted_file.ts"
    ]
  }
```
