### ISSUE TITLE
Better way to put in a single file all the declarations?

### ISSUE THREAD

**Issue by marcofugaro** [TypeStrong/ts-loader#879]
From the readme:

> **Declarations (.d.ts)**
> To output a built .d.ts file, you can set "declaration": true in your tsconfig, and use the [DeclarationBundlerPlugin](https://github.com/smol/declaration-bundler-webpack-plugin) in your webpack config.

However when trying to use that plugin, it generates an invalid `.d.ts` file, since it just takes all the files and puts them together, leaving multiple imports and multiple export defaults, here it is:

```ts
export { default as Button } from './components/Button';
export { default as Checkbox } from './components/Checkbox';
export { default as FlexView } from './components/FlexView';
export { default as Radio } from './components/Radio';
export { default as Select } from './components/Select';
export { default as TextInput } from './components/TextInput';
export { default as Toggle } from './components/Toggle';

/// <reference types="react" />
export interface InputPropsTypes {
    children?: React.ReactNode;
    className?: string;
    inputClassName?: string;
    style?: object;
    disabled?: boolean;
    checked?: boolean;
    onChange?: (event: boolean) => void;
    reset?: boolean;
}
export const InputDefaultProps: object;

import * as React from 'react';
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    children?: React.ReactNode;
    disabled?: boolean;
    transparent?: boolean;
    reset?: boolean;
    onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
    className?: string;
    style?: object;
    type?: string;
}
export default function Button({ children, disabled, transparent, reset, className, style, onClick, type, ...props }: ButtonProps): JSX.Element;

export interface SvgParams {
    className: string;
    style: object;
}
export interface CheckBoxArguments extends InputPropsTypes {
    svg: JSX.Element;
}
export default function Checkbox({ children, svg, className, inputClassName, style, disabled, checked, onChange, reset, ...props }: CheckBoxArguments): JSX.Element;

import * as React from 'react';
export interface FlexViewProps {
    children?: React.ReactNode;
    column?: boolean;
    vAlign?: 'top' | 'center' | 'bottom' | 'between' | 'around' | 'baseline' | 'stretch';
    hAlign?: 'left' | 'center' | 'right' | 'between' | 'around' | 'baseline' | 'stretch';
    grow?: boolean | number;
    shrink?: boolean | number;
    basis?: string | number;
    wrap?: boolean;
    className?: string;
    style?: object;
}
export default function FlexView({ children, column, vAlign, hAlign, grow, shrink, basis, wrap, className, style, ...props }: FlexViewProps): JSX.Element;

export default function Radio({ children, className, inputClassName, style, disabled, checked, onChange, reset, ...props }: InputPropsTypes): JSX.Element;

import * as React from 'react';
export interface DropDownParams {
    style: object;
}
export interface SelectProps {
    children?: React.ReactNode;
    className?: string;
    childrenClassName?: string;
    style?: object;
    label?: string;
    scrollable?: boolean;
    dark?: boolean;
    open?: boolean;
    disabled?: boolean;
    autoclose?: boolean;
    onClick?: (e: React.MouseEvent<HTMLDivElement>) => void;
    reset?: boolean;
}
export default class Select extends React.Component<SelectProps> {
    componentDidMount(): void;
    componentWillUnmount(): void;
    static defaultProps: {
        autoclose: boolean;
    };
    state: {
        open: boolean;
    };
    container: HTMLDivElement;
    setClose: () => void;
    setOpen: () => void;
    toogleOpen: () => void;
    handleClick: (event: React.MouseEvent<HTMLDivElement>) => void;
    handleOutsideClick: (event: MouseEvent) => void;
    render(): JSX.Element;
}

import * as React from 'react';
export interface TextInputpropsType {
    className?: string;
    style?: object;
    type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'time' | 'date' | 'datetime-local';
    value?: string | number;
    defaultValue?: string;
    disabled?: boolean;
    onChange?: (event?: React.ChangeEvent<HTMLInputElement>) => void;
    checkValidity?: (cond: boolean) => void;
    reset?: boolean;
}
export default function TextInput({ value, defaultValue, className, style, type, onChange, checkValidity, reset, disabled, ...props }: TextInputpropsType): JSX.Element;

export default function Toogle({ children, className, inputClassName, style, disabled, checked, onChange, reset, }: InputPropsTypes): JSX.Element;
```

Is there a better way to put in a file all the declarations? I can't just with typescript because i'm using `"module": "esnext",`. Here is my tsconfig

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": ".",
    "outDir": "lib",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "es7", "es2017", "esnext", "dom"],
    "declaration": true,
    "jsx": "react",
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "experimentalDecorators": true,
    "skipLibCheck": true
  },
  "exclude": ["node_modules", "webpack.config.js", "lib", "styleguide.config.js", "docs"]
}
```

**Comment by kobatakuJP** [comment]
I face same issue.
How do you create bundled `*.d.ts` file always? I cannot.
DeclarationBundlerPlugin has not been maintained recently, isn't it?

**Comment by marcofugaro** [comment]
@kobatakuJP DeclarationBundlerPlugin doesn't work, it just mangles the .d.ts together, without taking into consideration their imports

**Comment by AlexLeung** [comment]
I'm using a custom script which reads the tsconfig and webpack config to determine the location of the entry's output declaration file, then I read the file, extract the import paths via regex, then recursively go through each file, each import into a nested namespace, generating a bundled declaration file. There are some problems with this approach, but it sort of works.

**Comment by JasonKleban** [comment]
`declaration-bundler-webpack-plugin` is unmaintained and the repo is archived (I think?).  Webpack 5 has some problems with the published version and I adapted this from the latest I found on that repo.

https://gist.github.com/JasonKleban/bc8446f3f33c7e3c8a8103a770db442e

Unfortunately, I'm getting behavior that I don't fully understand.

1) The bundle is created but is blank because the assets object never contains the generated .d.ts or .d.ts.map files.
2) I have `outDir: "out", noEmit: true` in my tsconfig.json, overridden with `noEmit: false` in the ts-loader options.  While the .js files are missing as expected, the `/out/index.d.ts` and `/out/index.d.ts.map` are emitted (fully populated) but NOT expected (they should be in the bundle.d.ts ... _instead_.

**Comment by AlexLeung** [comment]
Lately I've just been using tsc to compile then putting the output js through webpack.

**Comment by JasonKleban** [comment]
@AlexLeung that's interesting.  How are you getting the bundle.d.ts prepared in that situation?

When I split it up like you suggest, my webpack setup still seems to ignore the tsc outputted .d.ts files just the same whether or not I reintroduce the DeclarationBundlerPlugin - which I should not expect to work since it's an input file rather than an asset - but still something needs to know how to process them.  If I add `resolve: [ ..., '.d.ts' ]` it gives errors about syntax (as I should expect).

**Comment by JasonKleban** [comment]
And @AlexLeung, how are you dealing with the non-ts source assets that webpack should process?  Are you copying them before the webpacking?  Are you modifying the loader module resolution strategy?  Or do you just not have any?
