### ISSUE TITLE
tsconfig compilerOptions.paths are not applied to declaration files generated by webpack

### ISSUE THREAD

**Issue by rgripper** [TypeStrong/ts-loader#897]
### Expected Behaviour
Generate .d.ts declaration files with resolved imports, using tsconfig-paths-webpack-plugin
### Actual Behaviour
Declaration file imports still use path alias (though generated .js files have paths resolved correctly)

**Comment by johnnyreilly** [comment]
I don't know what this means

**Comment by rgripper** [comment]
tsconfig `compilerOptions.paths` are not applied to declaration files generated by webpack, but only to .js.

**Comment by johnnyreilly** [comment]
If you'd like to submit a PR that handles this I'll gladly take a look.

**Comment by rgripper** [comment]
So this is a missing feature, not a bug, right? Just couldn't find an existing issue. How hard do you think it would be?

**Comment by johnnyreilly** [comment]
Noone has asked for it before so missing feature I guess. How hard? I don't know I'm afraid. I recommend forking and having an experiment. If you get somewhere then start a PR and we can collaborate. Don't worry about tests initially; I can help with that when the time comes.

**Comment by rgripper** [comment]
@johnnyreilly Do I get it right that:
- actual import rewriting of `.ts` `import` statements is done by `webpack` according to a resolver provided through `tsconfig-paths-webpack-plugin`
- ts-loader should not be resolving or rewriting imports
- there should be a separate plugin doing this resolution for `.d.ts` files
?

**Comment by johnnyreilly** [comment]
I don't exactly know what you mean by:

> rewriting of .ts import statements

**Comment by rgripper** [comment]
Rewriting of something like
`import UserService from 'app/api/UserService'` 
into 
`import UserService from '../../api/UserService'`

**Comment by johnnyreilly** [comment]
Yeah - I haven't double checked but I believe ts-loader should not be rewriting paths. Feel free to test and correct me if that's not the case.

**Comment by hinell** [comment]
I think  `compilerOptions` isn't working at all.
Just found out that any options from `compilerOptions` aren't applied to the running compiler.
I've used the following in order to use `ESNext` features but it failed: 
```
compilerOptions: {
    target: `esnext`,
    moduleResolution: `node`
}
```

Using the `configFile` instead of `compilerOptions` just worked fine for me.

**Comment by rgripper** [comment]
@hinell This looks like a separate issue, feel free to open another ticket.

For everyone else - there are several rewriting transformers available for the `ttypescript` package, use them to rewrite import declarations.

**Comment by hezhuojie** [comment]
> ts-loader should not be rewriting paths

@johnnyreilly I am curious why. ts-loader now can rewrite alias paths in emitted js to avoid problem in [https://github.com/Microsoft/TypeScript/issues/10866](https://github.com/Microsoft/TypeScript/issues/10866). 

Why not go further and rewrite paths in d.ts to fix [this problem](https://github.com/Microsoft/TypeScript/issues/18972)?

**Comment by johnnyreilly** [comment]
@hezhuojie feel free to submit a PR and I'll take a look
