### ISSUE TITLE
Generate build errors when d.ts file contains enum and not const num

### ISSUE THREAD

**Issue by navneet-g** [TypeStrong/ts-loader#906]
enum in .d.ts files don't work (amd modules) and we get runtime errors, instead if we define as const enum they work.
Is there a compiler option we can use to generate a build error when enum is defined instead of const enum in d.ts files.

```
// foo.d.ts
enum Foo {
   Option1,
  Optino2
}
```
does not work and gives runtime error about missing module foo
```
// foo.d.ts
const enum Foo {
   Option1 = 0,
   Option2 = 1
}
```
works.

**Comment by johnnyreilly** [comment]
I don't think this is supported in tsc - so there's nothing useful that ts-loader can do here I'm afraid. Suggest reposting this against the TypeScript repo instead
