### ISSUE TITLE
No difference for webpack output if target=ES3 or ES5?? Am I doing something wrong? 

### ISSUE THREAD

**Issue by frevds** [TypeStrong/ts-loader#907]
No matter what I enter for the target or module (also tried leaving the defaults) in the tsconfig.json it does not make any difference in the bundle.js generated by webpack for my .ts files using the ts-loader. What am I doing wrong here? How could I compile my project for some older browser? 

devDependencies: 
    "ts-loader": "^5.3.3",
    "typescript": "^3.3.3333",
    "webpack": "^4.29.5",
    "webpack-cli": "^3.2.3"

**Comment by frevds** [comment]
Hell yeah, I was using webpack --watch during those changes. 
Changes to the tsconfig.json seem to be ignore, apparently old version from startup time is cached and used.

**Comment by johnnyreilly** [comment]
This test demos outputting es3: https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/es3

Hope it helps!
