### ISSUE TITLE
Allow ts-loader to be used more than once

### ISSUE THREAD

**Issue by nicojs** [TypeStrong/ts-loader#909]
### Expected Behaviour

Given this webpack config:

```js
const path = require('path');
module.exports = {
    mode: 'development',
    entry: [
        './src/index.ts',
        './test/index.spec.ts'
    ],
    module: {
        rules: [
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                options: { configFile: 'src/tsconfig.json' },
                include: path.resolve(__dirname, 'src')
            },
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                options: { configFile: 'test/tsconfig.json' },
                include: path.resolve(__dirname, 'test')
            }
        ]
    }
}
```
I would expect files in the `test` directory to be transpiled with `test/tsconfig.json`, while files in the `src` directory are transpiled using `src/tsconfig.json`

### Actual Behaviour

Both test and src files seems to be transpiled using the `src/tsconfig.json` file, which results in errors. In my demo application:

```
ERROR in C:\z\github\nicojs\ts-loader-issue\test\index.spec.ts
./test/index.spec.ts
[tsl] ERROR in C:\z\github\nicojs\ts-loader-issue\test\index.spec.ts(1,1)
      TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`  and then add `jest` or `mocha` to the types field in your tsconfig.
```

### Steps to Reproduce the Problem

1. Create a src/tsconfig.json file and a test/tsconfig.json file.
2. Add the config above in your webpack.conf.js file
3. Install `@types/mocha` (for example)
4. Add `types: []` in src/tsconfig.json, `types: ['mocha']` in test/tsconfig.json.
5. Create a file: test/index.spec.ts. Add a call to `describe`: `describe('foo');`
6. Run webpack

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/nicojs/ts-loader-issue

*Note:* Tried to do this as a workaround for #851

**Comment by johnnyreilly** [comment]
Does the instance option help at all? https://github.com/TypeStrong/ts-loader/blob/master/README.md#instance-string

**Comment by nicojs** [comment]
@johnnyreilly thanks for the workaround. It works like a charm:

```js
const path = require('path');
module.exports = {
    mode: 'development',
    entry: [
        './src/index.ts',
        './test/index.spec.ts'
    ],
    module: {
        rules: [
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                options: { configFile: 'src/tsconfig.json' },
                instance: 'src',
                include: path.resolve(__dirname, 'src')
            },
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                options: { configFile: 'test/tsconfig.json' },
                instance: 'test',
                include: path.resolve(__dirname, 'test')
            }
        ]
    }
}
```
