### ISSUE TITLE
Compiler Option: noEmitOnError

### ISSUE THREAD

**Issue by use-strict** [TypeStrong/ts-loader#91]
I'm using the `noEmitOnError` option in `tsconfig.json` and I get a bunch of `Typescript emitted no output for ...` errors each time there is an error in one of my TypeScript files. It propagates to dependent files and it's getting really annoying, considering TypeScript errors are already properly reported. Can we remove this error or maybe suppress it if `noEmitOnError` is true?

**Comment by jbrantly** [comment]
I agree this needs to be looked at. If you don't mind I'm going to hijack your issue a little bit to make it part of the effort to evaluate all compiler options in detail. 

Another part of this, I believe, is being able to fail a build. For example, if webpack is being run as part of a larger build process, people want to be able to get an error code out of webpack if there is a TS error so that the build fails. I *think* that the right way to handle that is using `noEmitOnError`.

**Comment by use-strict** [comment]
I'm probably going to work around this at the moment by removing the `noEmitOnError` option which is not really crucial, or I could do a regex and remove those errors from my side. I already have to process and format them in a way the IDE can understand.

**Comment by jbrantly** [comment]
Out of curiosity, when you process the errors are you making use of the [undocumented error information](https://github.com/TypeStrong/ts-loader/blob/master/index.ts#L106-L107) that's provided? I threw that stuff on there to help people who are processing the raw errors but I have no clue if people actually use it.

**Comment by use-strict** [comment]
I will have to double-check from work, tomorrow, but most likely I am using those properties. I'm formatting all errors to match the output pattern of tsc. I also have a modified pattern configured in VSCode, which allows WEBPACK|TSLINT in place of TS#### error codes. This way the IDE maps errors/warnings coming from ts/ts-loader, tslint or webpack itself (there are also some legacy JS files in the project). 

I'm also relying on some undocumented properties on the webpack error objects too, and that isn't really production quality, but it worked so far. Being able to include the `tasks.json` setup in the project itself also allows for a seamless build from VSCode.

**Comment by basarat** [comment]
Note : `noEmitOnError` can slow down builds as TypeScript will validate the *entire* project even if emitting a *single file*.

**Comment by use-strict** [comment]
@basarat , I didn't know that. Thanks!

@jbrantly , looks like I'm using both `rawMessage` and `location`.
