### ISSUE TITLE
warning while using ttypescript@3.3333

### ISSUE THREAD

**Issue by andykais** [TypeStrong/ts-loader#918]
No issues with actual functionality, just a warning that I cannot find a purpose for.

### Expected Behaviour
loader does not give a warning

### Actual Behaviour
```
ts-loader: Using ttypescript@3.3.3333. This version may or may not be compatible with ts-loader.
```

### Steps to Reproduce the Problem
package.json
```json
  "devDependencies": {
    "ts-loader": "^5.3.3",
    "ttypescript": "^1.5.6",
    "typescript": "^3.3.3333",
    "webpack": "^4.28.3",
    "webpack-cli": "^3.0.6"
  }
```
webpack.config.js
```js
  module: {
    rules: [
      {
        test: /\.ts/,
        exclude: /node_modules/,
        loader: 'ts-loader',
        options: { compiler: 'ttypescript' }
      }
    ]
  }
```
### Location of a Minimal Repository that Demonstrates the Issue.
apologies, this is my full repo that contains the warning https://github.com/andykais/scrape-pages.

**Comment by crazyx13th** [comment]
I got the same
`ts-loader: Using ttypescript@3.4.1. This version may or may not be compatible with ts-loader.`

thx!

Greetings
crazyx13th

**Comment by andrewbranch** [comment]
This isn't a bug, it's a feature 😄 

ts-loader is only tested with `typescript` itself. This warning is just letting you know that if you're bringing your own alternative compiler, you're on your own and shouldn't be too surprised if something doesn't work.

**Comment by halfnibble** [comment]
Can we please add a way to suppress this warning? Thanks.

**Comment by johnnyreilly** [comment]
You can probably turn the warning off by silencing logging from ts-loader; check the options for details

**Comment by leviwheatcroft** [comment]
The warning says something like:

> ts-loader: Using ttypescript@3.7.4. This version may or may not be compatible with ts-loader.

I lazily read this as "this version is not compatible", and after trying a bunch of different versions eventually came here to realise that it's not necessarily a problem.

Maybe a warning like "ttypescript may work, but is not officially supported" might be more apt?

**Comment by johnnyreilly** [comment]
Good idea; if you'd like to submit a PR I'll take a look!

**Comment by loktar00** [comment]
Running into a small issue with this, when I attempt to profile (` webpack --profile --json > stats.json`) the warning is placed right at the top of my `stats.json` file which doesn't allow `webpack-analyze` to run since it's not valid JSON.

Tried suppressing warnings within webpack with `stats: {warnings:false},` but it's still showing up. Did anyone find a way to suppress this warning, would be nice to do especially in a production build.
