### ISSUE TITLE
[Question/Feature Request] Specify different tsconfigs for different instances.

### ISSUE THREAD

**Issue by AlexLeung** [TypeStrong/ts-loader#926]
We can specify different instances of `ts-loader` like this:

```
module: {
        rules: [
            // this will fail if both files are passed through the same instance
            { test: /a\.ts$/, loader: '../../index.js' },
            { test: /b\.ts$/, loader: '../../index.js', options: { instance: 'different' } }
        ]
}
```

but is there a way that I can have each of these instances use a different tsconfig? Perhaps one set of files is allowed to have `dom` related types and another set of files is meant to be universal and so should not have any `dom` types.

In my use case files from both sets need to end up in the final 1 bundle.

**Comment by andrewbranch** [comment]
You can use the `configFile` option: https://github.com/TypeStrong/ts-loader/blob/master/README.md#configfile-string-defaulttsconfigjson

> Perhaps one set of files is allowed to have dom related types and another set of files is meant to be universal and so should not have any dom types.

But you actually don't want two different ts-loader instances. You really want [project references](https://github.com/TypeStrong/ts-loader#projectreferences-boolean-defaultfalse). Project references don't work great with ts-loader, but they [will soon](https://github.com/TypeStrong/ts-loader/pull/935).

**Comment by AlexLeung** [comment]
Extending my example such that there is a universal set of files, a web set, and a node set, will project reference support (once it's done), bundle the built universal js into both the node and web bundles?

**Comment by andrewbranch** [comment]
Project references itself doesn't _bundle_ anything—that's webpack's job. You'd have two root projects: node and web, each of which reference a third project: the shared code. Running `tsc -b` on the node project will build both the node project and the shared code. Where the output goes depends on the `outDir` of each of those projects. Running webpack on the web project will also build the shared code, emitting output to its `outDir` but then _also_ piping that JS into the rest of webpack's build system, meaning you'll get a bundle with the web code and the shared code that can be shipped to a browser.

**Comment by AlexLeung** [comment]
Makes sense. So then if I use webpack for both the node and web sets, I would get 2 bundles, both containing copies of the transpiled shared code.

**Comment by andrewbranch** [comment]
Yeah, I guess so. I wasn’t thinking about using Webpack for node, but yeah, that would work.
