### ISSUE TITLE
Breaking change in micromatch 4 in ts-loader 5.4.6

### ISSUE THREAD

**Issue by pvtri96** [TypeStrong/ts-loader#929]
### Expected Behaviour

Everything should work fine because it is just a patch, not a breaking release.

### Actual Behaviour

I am having this log when trying to upgrade to version 5.4.6

```
[root]\node_modules\ts-loader\node_modules\micromatch\index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^

SyntaxError: Unexpected token ...
```

### Steps to Reproduce the Problem

Here is my `webpack.config.js`

```js
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  resolve: {
    extensions: ['.ts', '.js'],
    plugins: [new TsconfigPathsPlugin({})],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'ts-loader',
          },
        ],
      },
    ],
  },
};

```

### Location of a Minimal Repository that Demonstrates the Issue.

Refer to this PR: https://github.com/penta-jelly/re-radio/pull/167

Follow these steps will produce this error
- Checkout branch.
- Run `cd e2e`
- Run `npm ci`
- Run `npm run cypress:open`
- Open any test showing up in Cypress panel.
- Then you can see the error log described above.

CI build result: https://circleci.com/gh/penta-jelly/re-radio/802

**Comment by johnnyreilly** [comment]
what version of node are you running?

**Comment by johnnyreilly** [comment]
See https://github.com/TypeStrong/ts-loader/pull/930 for progress

**Comment by pvtri96** [comment]
@johnnyreilly I am using node 10. Release this dependencies upgrade on version on 6.0 is fine for me, I will figure a way to solve it on my project.

**Comment by johnnyreilly** [comment]
Okay that's somewhat unexpected - according to micromatch the minimum is node 8. So I'm not clear why it's failing on your project.... The error message suggests that it's the `{ ...options` that's problematic. Can you think why that would be an issue for you?

**Comment by pvtri96** [comment]
I am thinking the reason it is failed because ts-loader was ran directly on Browser (Cypress mechanism) but not on NodeJS environment. Do you have any idea about how to solve it?

**Comment by johnnyreilly** [comment]
> I am thinking the reason it is failed because ts-loader was ran directly on Browser

I'm not sure I understand how that would work... Either way, I'd still expect object spread to be just fine since chrome has had it for a very long time indeed!  

Puzzling...

**Comment by B3zo0** [comment]
@pvtri96  It is a problem in cypress not in ts-loader. Cypress comes with electron builtin with chorme 63 that does not support object spread. You should be fine after this https://github.com/cypress-io/cypress/pull/4001 gets released. What you can do is to not run your code in electron but the browser instead. You can do it like this https://docs.cypress.io/guides/guides/command-line.html#cypress-run

**Comment by pvtri96** [comment]
@B3zo0 thanks for your in-depth answer. Instead of trying to find a workaround for this, I am better stick with ts-loader@5.4.5 while waiting for Cypress to release the new version with a newer version of Chrome.

**Comment by johnnyreilly** [comment]
Re-released as 6.0.0 https://github.com/TypeStrong/ts-loader/releases/tag/v6.0.0

**Comment by vytautas-pranskunas-** [comment]
any updates on this?

**Comment by johnnyreilly** [comment]
Without knowing your problem I can't advise in detail. Micromatch 4 is a breaking changes release and so (accordingly) ts-loader 6 is too. My advice is stick with 5.x until you're able to upgrade. That may mean waiting for a cypress release if that's what is impacting you.

**Comment by pvtri96** [comment]
This issue should not be a problem since Cypress [3.3.0](https://github.com/cypress-io/cypress/releases/v3.3.0).

**Comment by anvlkv** [comment]
Hi, i have this issue @6.0.3
