### ISSUE TITLE
Yarn PnP support - resolveTypeReferenceDirective - "I'm calling for a resolution..."

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#934]
It all started when @arcanis raised a PR which added Yarn PnP support to ts-loader. To quote the PR:

> This PR adds a new `resolveModuleName` option that can be used to help TypeScript figure out the location of the files on the disk. It mimics the TypeScript API.

https://github.com/TypeStrong/ts-loader/pull/862

Time passed and it was all good. Then the wonderful @arcanis submitted a very similar PR to the `fork-ts-checker-webpack-plugin`:

https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/250

This PR was very similar to the ts-loader one. However, as I was reviewing it I noticed something. https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/250#issuecomment-485061143

To quote myself: 

> Thanks! I was just looking at the work you did on ts-loader: https://github.com/TypeStrong/ts-loader/pull/862
>
> You only added `resolveModuleName` there. 
>
> This adds 2 options: `resolveModuleNameModule` and `resolveTypeReferenceDirectiveModule`
>
> Does ts-loader need  a `resolveTypeReferenceDirective` to work with pnp as well? Or is it not necessary?

And @arcanis response:

> I think that might be useful yep. When I initially made the PR for ts-loader I wasn't aware of what `resolveTypeReferenceDirective` was used for (`/// <reference types="...">`) - I just discovered it when implementing the feature for fork-ts-checker-webpack-plugin and only because `create-react-app` uses it to automatically define the `*.svg` typings.

So I decided to add the corresponding functionality to ts-loader; I gave it its own `resolveTypeReferenceDirective`:

https://github.com/TypeStrong/ts-loader/pull/921

Now up until this point, when we created a `ServicesHost` in ts-loader we didn't actually supply `resolveTypeReferenceDirective` at all - in fact it was commented out in the codebase as you can (slightly embarrassingly) see here:

https://github.com/TypeStrong/ts-loader/pull/921/files#diff-70b0dbb6219cb6164e67ffb54a8f23c0L140

And it turned out that introducing it at all has had a breaking side effect for jest users:

https://github.com/TypeStrong/ts-loader/issues/919#issuecomment-486653154

Clearly this issue could be "fixed" by just dropping the `resolveTypeReferenceDirectives` from ts-loader. But if we do that, then I'm assuming we break Yarn PnP support too (only for type reference directives that is).

Where I am is here: I can no longer remember the reason I commented out supplying `resolveTypeReferenceDirectives`. Flat out, I just don't remember. And so we finally get to the question:

Is ts-loader using this API correctly? Should we be using differently? Or is it actually not to be used? I'm after guidance. Please educate me!

cc @andrewbranch

**Comment by johnnyreilly** [comment]
Additional info; the new option being used by ts-loader adds further issues when plugged into `yarn-pnp-plugin` - using my PR here: https://github.com/arcanis/pnp-webpack-plugin/pull/10

The errors look like this:

```
ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'anymatch'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'braces'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'micromatch'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'node'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'normalize-package-data'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'semver'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'tapable'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'uglify-js'.

ERROR in C:\source\ts-loader\examples\yarn-pnp\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'webpack'.
``` 

Which are similar to the errors mentioned in this issue: https://github.com/Microsoft/TypeScript/issues/27956

You can take the (broken) example for a test drive here: https://github.com/TypeStrong/ts-loader/tree/yarn-pnp-broken-example/examples/yarn-pnp

**Comment by johnnyreilly** [comment]
Hey @andrewbranch

Thanks for all your work on this - it's been *amazing*. I think there's still an issue which remains. Unfortunately my laptop is dying on me right now which is making it difficult for me to share the details... Do bear with me!

**Comment by andrewbranch** [comment]
Welp, I would love to debug and see what's happening, but the first thing I notice about PnP is—how are you supposed to debug anything? Debugging build and test tools like `webpack` is dependent upon being able to write something like `node --inspect-brk node_modules/webpack/bin/webpack.js`. In this universe, even if I go through the manual work of figuring out where webpack _is_, running node at that path can't figure out where all _its_ dependencies are since you didn't start node with the custom resolver. 

```
node --inspect-brk `which yarn` build
```

doesn't work either, presumably because `yarn` spins up a child process to actually run the npm script, so you're attaching to the wrong thing.

The other thing debugging packages relies on is linking to local—`npm link` or `yarn link`. I ran `yarn link ts-loader` and it gave me a success message, but `.pnp.js` still says it should pull ts-loader from some library cache. Does PnP just not work with `yarn link`?

Without an active debug session, there’s not much I can do—punting to @arcanis

**Comment by arcanis** [comment]
Hey! I'll give a better look at this issue soon but I figured I should first quickly answer your question, @andrewbranch 😃

> how are you supposed to debug anything?

A few things:

- The PnP hook can be manually injected with `--require <path/to/.pnp.js>`.
- But it also can be automatically injected via `yarn node`
- You can instruct Yarn to materialize any package with `yarn unplug <name>`

So in your case it would be something like this:

```
$> yarn unplug webpack
$> yarn node --inspect-brk $(yarn -s bin webpack)
```

The first line can be skipped if you don't intend to edit webpack's source code (you don't need to materialize the package).

**Comment by arcanis** [comment]
I'm trying to run the example locally but it seems to succeed - what did I do wrong? I did the following:

- `git clone git@github.com:TypeStrong/ts-loader`
- `git checkout yarn-pnp-broken-example`
- `cd examples/yarn-pnp-resolveTypeReferenceDirectives-broken`
- `yarn install`
- `yarn build`

I'm using Yarn 1.16 and got the following output:

```
yarn run v1.16.0
warning package.json: No license field
$ webpack --mode production
Hash: 73451fa1973643a857c1
Version: webpack 4.20.2
Time: 1157ms
Built at: 05/19/2019 6:59:57 PM
  Asset      Size  Chunks             Chunk Names
main.js  7.44 KiB       0  [emitted]  main
Entrypoint main = main.js
[0] ./src/index.ts 85 bytes {0} [built]
[1] ./src/render.ts 138 bytes {0} [built]
Done in 3.33s.
```

**Comment by johnnyreilly** [comment]
Weird - that's not what I get / got.... Let me retest now

**Comment by johnnyreilly** [comment]
Okay this is super weird.... If I do this I'm golden:

```
git clone https://github.com/TypeStrong/ts-loader.git
cd ts-loader
git checkout yarn-pnp-broken-example
cd examples/yarn-pnp-resolveTypeReferenceDirectives-broken
yarn install
yarn build
```

My local copy is theoretically identical and yet it doesn't work....  Not sure why that would be?

**Comment by johnnyreilly** [comment]
So the only difference appears to be in the `.pnp.js` files.  There's subtle differences....

**Comment by johnnyreilly** [comment]
Okay so I think there isn't actually a problem with ts-loader or with the PR to `pnp-webpack-plugin` either.  I'm going to close this issue.  Thanks @arcanis / @andrewbranch for looking into this.  I super appreciate it.

@arcanis in case you're curious, I ran BeyondCompare over the working / broken versions and got this:

![Screenshot 2019-05-19 20 02 04](https://user-images.githubusercontent.com/1010525/57986768-0416b180-7a71-11e9-9828-c9e74e462c34.png)

**Comment by arcanis** [comment]
Hmm I really don't know 🤔 I know that `node_modules/.cache` is typically used by Babel, but since it's not used in this example ... maybe TS also uses it and didn't see some file had changed?

**Comment by johnnyreilly** [comment]
It's weird... I blew away `.pnp.js` and `node_modules`, `yarn` and `yarn build`.  `node_modules` reappears in the `yarn build`.... Dunno

**Comment by andrewbranch** [comment]
> - The PnP hook can be manually injected with --require <path/to/.pnp.js>.
> - But it also can be automatically injected via yarn node
> - You can instruct Yarn to materialize any package with yarn unplug <name>

Amazing, I was hoping there would be some magic I was unaware of like that. Thanks @arcanis!
