### ISSUE TITLE
Info string on stdout causes problem to --json webpack output

### ISSUE THREAD

**Issue by alexdrel** [TypeStrong/ts-loader#95]
Hi, 
The ts-loader writes info string to stdout:
>ts-loader: Using typescript@1.6.2 and /[skipped]/src/tsconfig.json

When building JSON module statistics it goes to the json file and has to be removed manually.
>webpack  --progress -j > m.json   

Of course it is a minor nuisance but it would be nice if it will be written to stderr instead of stdout.

Thanks

**Comment by jbrantly** [comment]
If you use the [silent flag](https://github.com/TypeStrong/ts-loader#silent-boolean-defaultfalse) that info won't be written. I'm not sure using stderr would be correct since it's not an error.

**Comment by blakeembrey** [comment]
@jbrantly It's not uncommon to use `stderr`. I just realised today that NPM logs to output to stderr and not stdout.

**Comment by jbrantly** [comment]
@blakeembrey Interesting. Maybe something to look at then.

@alexdrel For the time being does the `silent` flag solve your need?

**Comment by alexdrel** [comment]
`silent` flag works fine but it is actually simpler to remove the first line from json than to change `webpack.config.js` back and forth. 
It is not a big deal, but I consider `stderr` as suitable for anything which is not primary output - the `progress` flag for example writes to `stderr`.

**Comment by jbrantly** [comment]
Why do you have to change the webpack config back and forth? Just leave the silent flag on. All it affects is that one message which you probably don't care much about once things are "set up".

Re: stderr, I'm open to that.

**Comment by alexdrel** [comment]
@jbrantly - I kinda like it :) - it shows ts version and I use to jump between nightly,1.6.2 and 1.7.2 (which I don't quite understand - is it official and how it made its way into sublime plugin).

**Comment by jbrantly** [comment]
> I kinda like it :)

That's... actually a really good reason :grin:

**Comment by jbrantly** [comment]
Fixed in v0.7.0. Thanks for reporting!
