### ISSUE TITLE
Can't set both declarationMap, transpileOnly to true

### ISSUE THREAD

**Issue by stavalfi** [TypeStrong/ts-loader#957]
`declarationMap=true` (in tsconfig.json) + `transpileOnly=true` (in webpack.config.js) don't get along. 

### Expected Behaviour

no errors 

### Actual Behaviour

> TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.

(I already have set `declaration` & `composite` to true). The error only occurs when I set `transpileOnly` to true.

### Steps to Reproduce the Problem

Super minimal repo to reproduce the bug: https://github.com/stavalfi/ts-bug-repo

Run: `yarn && yarn start`

#### Usecase

I'm using https://github.com/Realytics/fork-ts-checker-webpack-plugin so I want to speed up my build by setting `transpileOnly=true`

**Comment by johnnyreilly** [comment]
I think you're stuggle may be with the TypeScript compiler rather than ts-loader.... Have you tried making the changes the error message suggests?

**Comment by stavalfi** [comment]
yes. i already set everything to true. this is why i see this as a bug and not a feature =[

the reason i post it here is because the error occur only when setting `transpileOnly` to true.

**Comment by johnnyreilly** [comment]
I see what you mean. Yes - I'm afraid it's not a bug but part of the behaviour of `transpileOnly` - declaration files are not output in this mode and consequently map files of them too. 

see here: https://github.com/TypeStrong/ts-loader/blob/master/README.md#faster-builds

**Comment by stavalfi** [comment]
ho.. damn.. How could I miss it..

In a different topic, why there is a limitation such as: no decleration maps in this mode?

**Comment by johnnyreilly** [comment]
We use a different API for this mode: https://github.com/TypeStrong/ts-loader/blob/985406808063a47cb24c6b3706a14f49b752e88d/src/index.ts#L485

this API does not support declaration files - you'd have to check with the TypeScript team for the reasons but I imagine it's that this API is just about transpilation ie making JS and so it would not do anything but that
