### ISSUE TITLE
vue-loader example in Readme is not working

### ISSUE THREAD

**Issue by happycoder97** [TypeStrong/ts-loader#958]
## Steps to Reproduce the Problem

Install `webpack`, `webpack-cli`, `ts-loader`,`typescript`,`vue`,`vue-loader`,`vue-template-compiler` using `yarn`.
Copy the example `webpack.config.js` and `index.vue` from the Readme.
Import and register `VueLoaderPlugin` in `webpack.config.js` so that `vue` compiler doesn't complain.
Create `index.html` and add a script tag to load `./dist/bundle.js`
Create an empty file `empty.ts` so that typescript compiler doesn't complain about having no input files.
Run `yarn webpack`
Open `index.html` in browser

## Expected behavior
The `index.vue` file gets compiled and loaded into browser

## Actual behavior
Vue is not being loaded

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/happycoder97/ts-loader-vue-repro

**Comment by johnnyreilly** [comment]
Thanks for reporting! I'm not a Vue user and would greatly appreciate someone who is submitting a PR to update our docs. I'm aware that people are happily using Vue with ts-loader so it can be done!
