### ISSUE TITLE
error "... has no exported member ..." after rename type, with webpack running in hmr or watch mode

### ISSUE THREAD

**Issue by SvyatoslavPozhydaev** [TypeStrong/ts-loader#959]
### Expected Behaviour
new name interface can be imported

### Actual Behaviour
```
ERROR in ...src\MessagesCard.tsx ./MessagesCard.tsx
[tsl] ERROR in ...src\MessagesCard.tsx(2,10)
      TS2305: Module '".../src/types"' has no exported member 'IMessagesCard'.
```

### Steps to Reproduce the Problem
1. clone project
2. `yarn install`
3. `yarn start`
4. rename `MessagesItem` in `src/MessagesCard.tsx` and `src/types.ts` to `IMessagesCard`

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/SvyatoslavPozhydaev/demo-ts-loader-error

**Comment by akoidan** [comment]
Oh come on, this is not solved!

**Comment by johnnyreilly** [comment]
Important news! @akoidan has volunteered his time to fix this issue 🥰
