### ISSUE TITLE
LoaderOptions.compilerOptions typed incorrectly

### ISSUE THREAD

**Issue by slavafomin** [TypeStrong/ts-loader#962]
Hello!

Thank you for this great loader.

However, it looks like the `LoaderOptions.compilerOptions` property is typed incorrectly. The `target` property is typed as `ScriptTarget`, which is:

```typescript
enum ScriptTarget {
    ES3 = 0,
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ESNext = 8,
    JSON = 100,
    Latest = 8
}
```

So, it requires the number value. However, in runtime it's actually expecting a string value, like `'ES2015'`. This leads to an error: `TS5024: Compiler option 'target' requires a value of type string.`

Please, see my issue in TypeScript project:
https://github.com/microsoft/TypeScript/issues/32317

**Comment by johnnyreilly** [comment]
Do you want to submit a PR to fix this?

**Comment by ark120202** [comment]
It's actually not just `target`, it also affects all other enums and `lib` option (during tsconfig parsing raw names like `es2015` are changed to file names, like `lib.es2015.d.ts`), so `compilerOptions` section of tsconfig isn't the same thing as `ts.CompilerOptions`. TypeScript doesn't have a type that reflects tsconfig structure (see https://github.com/microsoft/TypeScript/pull/32501), so I see 3 options:
- Manually maintain a config type
- Generate it from `ts.optionDeclarations` internal value
- Actually use `LoaderOptions.compilerOptions` as `ts.CompilerOptions`: merge it with options from config file after parsing (which would be a breaking change)

**Comment by slavafomin** [comment]
I've released [a package](https://github.com/moebius-mlm/ts-compiler-options) with proper compiler options types. Please, review [the PR](https://github.com/TypeStrong/ts-loader/pull/1033).
