### ISSUE TITLE
TypeScript 3.6 transpileOnly:true incompatible with tsconfig incremental:true

### ISSUE THREAD

**Issue by shelakel** [TypeStrong/ts-loader#995]
Note using both transpileOnly: true and incremental: true works with TypeScript 3.5

### Expected Behaviour
Webpack build succeeds.

### Actual Behaviour
Webpack fails with `... === undefined. Unexpected multiple outputs`

### Steps to Reproduce the Problem
Set webpack ts-loader options - transpileOnly: true and tsconfig compilerOptions - incremental: true.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/shelakel/ts-loader-ts3_6_issue_repro

**Comment by johnnyreilly** [comment]
Thanks for reporting! I'm kind of snowed and so I'm unlikely to look at this anytime soon. But if you'd like to have a go please do feel free. 

My recommendation is hack away, make a start and then raise a PR. Don't worry about getting tests passing initially; just start the process and I'll help you as I can.

**Comment by shelakel** [comment]
All good @johnnyreilly . I think for now adding a recommendation/caveat to the README should be sufficient. You must use either incremental: true or transpileOnly: true, but not both, when using TypeScript 3.6.

I'm sceptical of making changes to ts-loader since this issue wasn't present in TypeScript 3.5 and such changes are likely to not be compatible with TypeScript < 3.6 which could benefit performance wise from using incremental: true.

**Comment by johnnyreilly** [comment]
Cool - if you'd like to raise a docs PR @shelakel I'll take a look

**Comment by plievone** [comment]
Just ran into this -- will be fixed in TS 3.6.3 soon https://github.com/microsoft/TypeScript/pull/33216

**Comment by johnnyreilly** [comment]
Thanks @plievone!

**Comment by johnnyreilly** [comment]
Closing as a TypeScript issue
