### ISSUE TITLE
projectReferences: true causes node to not exit (webpack host)

### ISSUE THREAD

**Issue by sublimator** [TypeStrong/ts-loader#998]
### Expected Behaviour
Node to exit once webpack finished

### Actual Behaviour
Node just hangs and doesn't exit.
Have tried node 10 and 12. 
Both hang

### Steps to Reproduce the Problem
1. clone this repository
2. yarn install
3. yarn build.
4. cd test/execution-tests/3.6.0_projectReferencesToBeBuilt
5. yarn install
6. ../../../node_modules/.bin/webpack-cli --config webpack.config.js

![image](https://user-images.githubusercontent.com/525211/64684442-56ac2b80-d4af-11e9-9264-649c57c16101.png)

### Location of a Minimal Repository that Demonstrates the Issue.
This repo

**Comment by sublimator** [comment]
Referring to: 
https://github.com/TypeStrong/ts-loader/pull/935#issuecomment-530220965

**Comment by sublimator** [comment]
Using this commit:
```
commit bfa48c75adc424a33bbc1f0ec3eeddb8ea1c2722 (HEAD -> master, tag: v6.1.0, origin/master, origin/HEAD)
Merge: ab3ba29 a47f244
Author: Andrew Branch <andrewbranch@users.noreply.github.com>
Date:   Tue Sep 10 14:38:23 2019 -0700

    Merge pull request #935 from sheetalkamat/solutionBuilder
    
    Using Solution builder to build project references
```

**Comment by sublimator** [comment]
Running the webpack command with `node --inspect` and running process._getActiveHandles() one can see that there are some typescript.js:5055 StatWatcher things open ... 

![image](https://user-images.githubusercontent.com/525211/64685559-67f63780-d4b1-11e9-9bb6-c331a82523b0.png)

**Comment by sublimator** [comment]
![image](https://user-images.githubusercontent.com/525211/64687909-8b22e600-d4b5-11e9-85d1-0fcef85ee53d.png)

Seems like due to above in instances.ts ^^^ 

Need to pick up kid from school, will investigate further later, but it doesn't seem like it's honoring the webpack --watch mode ... 

Not very familiar with other contexts/use cases for ts-loader  ...

**Comment by sublimator** [comment]
Ok, so it seems the code is using the `compiler.createSolution*Watch`apis ...
See here for a quick hack that gets it to exit cleanly: 
https://github.com/sublimator/ts-loader/commit/095e046beafd59713119895a65b5ef83003efbc5

Not sure how you guys want to solve this or why watch apis were chosen?

**Comment by sublimator** [comment]
@sheetalkamat  
Any ideas ?

**Comment by johnnyreilly** [comment]
cc @andrewbranch

**Comment by sheetalkamat** [comment]
I think https://github.com/microsoft/TypeScript/pull/33145 should fix that.

**Comment by sheetalkamat** [comment]
@sublimator you are right.. I didn't realize that I forgot to do something with watch similar to what we do with the `WatchHost`, I believe we need watch functionality for `--watch` scenarios

**Comment by sublimator** [comment]
Thanks for looking into it :)
